### PR TITLE
Update indexing.md

### PR DESCRIPTION
**Pull request by ryantfowler**
## This PR is a:
[ ] New topic
[ ] Content fix or rewrite
[ X] Bug fix or improvement
 
## Summary
This PR includes two additional indexers in the list of indexers.
 
When this pull request is merged, it will... complete the list of major indexers the someone would see when running `php bin/magento indexer:info`
 
## Additional information
I have listed `Magento\Framework\Indexer\Action\Entity` as the `customer_grid` Indexer class, as there was no concrete Customer Indexer class that I could find, so this may need to be revised.

### CODE REVIEW

**Comment by shrielenee** [comment]
@buskamuza Can you please review the addition of two indexers in this PR and the technical details provided?

**Comment by shrielenee** [comment]
@ryantfowler We use liquid tags for the `baseurl` formatting you changed - the spaces belong there as this is our style specification. See our [Basic template page](https://devdocs.magento.com/guides/v2.2/contributor-guide/templates/basic_template.html) and the [Liquid variables reference](http://shopify.github.io/liquid/tags/variable/).

Can you please re-push up the PR with those changes reverted (the `</tbody>` one can stay) while we wait for a technical review on your other proposed changes?

**Comment by ryantfowler** [comment]
@shrielenee yes, of course. My apologies on that.

**Comment by ryantfowler** [comment]
@shrielenee can you verify that I have corrected the PR for liquid tag compliance correctly? Thank you

**Comment by shrielenee** [comment]
@ryantfowler It looks like you did that correctly, thanks! I'm implementing your changes, along with doing a copyedit of the page (I try to edit each page I touch to smartly maintain as I go). This change will be in a separate PR that I'll link to this one.

One thing I wanted to mention is that we use markdown as much as we can in the place of HTML. So in this case I'd leave the HTML table but convert things like links and headings to markdown.

**Comment by shrielenee** [comment]
Closing this because I implemented your changes in PR #2009. Thanks!!!

**Pull request closed without merging**
