### PR TITLE
Corrected typos on InsertForm component page

### LINKED ISSUE #8824: Feedback on page: /guides/v2.4/ui_comp_guide/components/ui-insertform.html
# General issue

## Description:

Under "**Configuration Options**", the option "**autoRender**" is described as
> When set to true, the Form component is automatically rendered during InsertForm initialization. Otherwise, insertListing’s render method should be called to render the Form.

*InsertListing** should be corrected to  **InsertForm**. 

## Possible solutions:

**InsertListing** should be corrected to  **InsertForm**.

### PR DESCRIPTION
**Pull request by Viper9x**
## Purpose of this pull request

This pull request (PR) Corrected typos on **InsertForm component** page
Fixes #8824

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-insertform.html
- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-insertform.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Not sure why linting is failing but other PR has the same issue with GITHUB_TOKEN

Will pass this PR

**Review by dobooth — APPROVED** [review]

**Comment by dshevtsov** [comment]
The GitHub token error is expected and it is not relevant to this failure. Investigating.
There is some issue with git history or some bug in the tool. Investigating.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8827`.

**Pull request merged**
