### PR TITLE
Issue-8608- Added a disclaimer regarding custom domains of Starter Projects

### PR DESCRIPTION
**Pull request by dineshvb**
## Purpose of this pull request

This pull request (PR) covers #8608 

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/cdn/configure-fastly.html#update-dns-configuration-with-development-settings

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Comment by dineshvb** [comment]
Hi @bdenham is this good to be approved?

**Comment by bdenham** [comment]
@dineshvb, Not yet. I've been investigating whether we can make a blanket statement like that and I haven't gotten a solid answer yet. I've had one cloud dev say that this was true a year ago, but not certain now. I've seen another recent Starter merchant ticket that would suggest it isn't true because this particular merchant was assigned multiple custom domains on their Starter staging branch. 

I've asked Platform.sh for clarification on this and am waiting to hear back from them. I'll update this PR again when I hear back definitively.

**Comment by bdenham** [comment]
Hey @dineshvb, sorry for the delays, but I'm still waiting on others to give me a definitive answer on the essential question here: _Can merchants with Starter projects specify custom domains for their staging environments?_

This has been a surprisingly difficult question to answer definitively. I've asked many people. But none were certain. Stay tuned.

**Comment by dineshvb** [comment]
> Hey @dineshvb, sorry for the delays, but I'm still waiting on others to give me a definitive answer on the essential question here: _Can merchants with Starter projects specify custom domains for their staging environments?_
> 
> This has been a surprisingly difficult question to answer definitively. I've asked many people. But none were certain. Stay tuned.

No issues @bdenham

**Comment by dobooth** [comment]
From Oleh P.: The overall phrase is not correct.
There is no Staging on Starter. Each non-master branch can be considered  as Staging depending on workflow.
It should be something like:
"You cannot specify a custom domain for a non-production environment in Starter."

**Review by bdenham — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
