### PR TITLE
Add ES 5.2 as supported Cloud service

### PR DESCRIPTION
**Pull request by robbie-thompson**
## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will add ES 5.2 as a supported service in Cloud's services.yaml file.

ES 5.2 is listed as a supported version in other parts of the devdocs/support: https://devdocs.magento.com/guides/v2.3/cloud/project/project-conf-files_services-elastic.html
https://support.magento.com/hc/en-us/articles/115004905874-Enable-Elasticsearch-on-Cloud

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/cloud/project/project-conf-files_services.html#cloud-yaml-services-type

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
This looks like something @hguthrie or @meker12 can investigate.

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Pull request merged**
