### PR TITLE
MC-17576: Technical Question and possible documentation updates

### PR DESCRIPTION
**Pull request by dyushkin**
## Purpose of this pull request

This pull request (PR) added description for new required attribute for Signifyd xml configuration node.
Pull request to magento repository with code changes is https://github.com/magento/magento2ce/pull/4465

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/payments-integrations/signifyd/signifyd.html
- https://devdocs.magento.com/guides/v2.3/payments-integrations/signifyd/signifyd.html

## Links to Magento source code

- https://github.com/magento/magento2ce/pull/4465

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5092) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5092) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@dyushkin thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
