### PR TITLE
Add line break to nginx topic

### PR DESCRIPTION
**Pull request by markoshust**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix a missing line break which causes a readability error.

## Affected URLs

- https://devdocs.magento.com/guides/v2.1/config-guide/multi-site/ms_nginx.html
- https://devdocs.magento.com/guides/v2.2/config-guide/multi-site/ms_nginx.html
- https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_nginx.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by lorikrell** [comment]
running tests

**Comment by lorikrell** [comment]
running tests

**Comment by lorikrell** [comment]
@markoshust  thanks for the contribution! All set and merged. It will be published soon!

**Pull request merged**
