### PR TITLE
magento/devdocs#: Extend commands list

### PR DESCRIPTION
**Pull request by atwixfirster**
https://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands.html
https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands.html
https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands.html

## Purpose of this pull request

This pull request (PR) adds the next commands

- `bin/magento admin:user:{create/unlock}`
- `bin/magento dev:template-hints:{enable/disable`}

into "Command summary" list.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands.html
- https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands.html
- https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
References from the codebase:
https://github.com/magento/magento2/blob/36097739bbb0b8939ad9a2a0dadee64318153dca/setup/src/Magento/Setup/Console/Command/AdminUserCreateCommand.php#L51
https://github.com/magento/magento2/blob/e60d3a2d8ff3964510ecaa0f7617fa9e482236c4/app/code/Magento/Developer/Console/Command/TemplateHintsEnableCommand.php#L20

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Cloning stage on Jenkins keeps timing out; suspect a networking issue. Will try again later.

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
