### PR TITLE
Mask cart_id in GraphQL request

### PR DESCRIPTION
**Pull request by vladyslav-sikailo-decima**
## Purpose of this pull request

This pull request (PR) masks cart_id in GraphQL request as it done in other examples.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/graphql/tutorials/checkout/checkout-shipping-address.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@vladyslav-sikailo-decima thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]

**Comment by dobooth** [comment]
@keharper

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@keharper the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-9071`.

**Pull request merged**
