### PR TITLE
Update php-settings.md

### PR DESCRIPTION
**Pull request by kandy**
The bcmath extension is required for RabbitMQ and it is available for Open Source as well (from 2.3 I believe)

## Purpose of this pull request

Removing outdated information from docs

## Affected DevDocs pages

-  src/guides/v2.4/install-gde/prereq/php-settings.md

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please can you fill in the PR description section as required.

**Comment by kandy** [comment]
@BarnyShergold done

**Review by BarnyShergold — APPROVED** [review]
Thanks!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8798`.

**Pull request merged**
