### PR TITLE
Changed the file path and made it clear that you need <vendor>_<modul…

### PR DESCRIPTION
**Pull request by edwinbos**
…e-name> instead of a directorty.

### CODE REVIEW

**Comment by tanberry** [comment]
Thanks, @edwinbos! @almarchenko  can you or @guz-anton take a look at this? We want to be careful to make it clear, because some environments might have modules in app/code while others are in /vendor.

**Comment by edwinbos** [comment]
Hmm, that you want to be carefull to make it clear sounds a kind of strange to me, but perhaps we can call it <vendor-name>_<module-name>, so there is less confusion with the vendor folder.

**Comment by almarchenko** [comment]
@edwinbos  You've pointed out really important issues! But after looking closer I realized it should be corrected in a little bit different way. Can I ask you to update the PR (I will give detailed explanations if you will be willing to do it yourself) or I can do it myself (but will close this PR then).
Please let me know what do you prefer!

**Comment by almarchenko** [comment]
@edwinbos  I guess you have more fun things to do) And I was leaving for vacation, so I went ahead and made the changes myself. Thank you very much for pointing this out!

**Pull request closed without merging**
