### PR TITLE
magento/devdocs#: The flow for the huge PR

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) adds a flow for the huge PRs and collaboration process.

## Affected DevDocs pages

- https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md

whatsnew
Added a `Work on the huge issues` section to the Contribution Guide.

## Links to Magento source code

- ...

CC: @jeff-matthews 

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Thanks @atwixfirster, but this info is incomplete and doesn't necessarily belong in the contribution guide. I'll create a wiki page.

**Comment by atwixfirster** [comment]
> Thanks @atwixfirster, but this info is incomplete and doesn't necessarily belong in the contribution guide. I'll create a wiki page.

That was a good try from my side ;)

Thanks, @jeff-matthews

**Comment by jeff-matthews** [comment]
Here's a link to the new wiki page: https://github.com/magento/devdocs/wiki/Markdown-linting-issues

**Pull request closed without merging**
