### PR TITLE
Update message-queues.md

### PR DESCRIPTION
**Pull request by ed007m**
## Purpose of this pull request

This pull request (PR) fixes a small typo in the Content Security Policy topic.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@ed007m thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@ed007m In order for us to merge your PR, we need you to sign the Adobe Contributor License Agreement. Thanks!

**Comment by keharper** [comment]
@ed007m A friendly reminder to accept the Adobe CLA so that we can merge this PR.

**Comment by dobooth** [comment]
Closing for lack of CLA.

**Pull request closed without merging**
