### PR TITLE
Corrected the COnfiguration section tab Name

### PR DESCRIPTION
**Pull request by Renu05**
Corrected the COnfiguration section tab Name

## Purpose of this pull request

The Configuration Tab name was mentioned as  "Advanced" the correct name is "Advanced Configuration"
**Stores** > Settings > **Configuration** > **Advanced** > **System** > **Full Page Cache** > **Fastly Configuration** > **Advanced Configuration**.

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/cdn/fastly-vcl-wordpress.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please can you complete the PR description as required? See the WIKI for format
Otherwise it's fine!

**Comment by Renu05** [comment]
@BarnyShergold ,

I have updated the description. Kindly let me know for further modification

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
