### PR TITLE
Separate indexing configuration into `_config.index.yml`

### PR DESCRIPTION
**Pull request by belbiy**
## Purpose of this pull request

- This pull request (PR) prevents the code blocks line numbers from being indexed by Jekyll Algolia.
- Separates indexing config from public search config (should be left at `_config.yml`)

We have to change the Jenkins indexing job in order for this to work:
```
ALGOLIA_API_KEY='$var' bundle exec jekyll algolia --config _config.yml,_config.index.yml
```

## Affected DevDocs pages

none

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@belbiy, are you separating the config because we expect it to get larger/more complex and this will make it easier to maintain?

Also, to update the Jenkins pipeline, do you mind creating a PR here?

https://git.corp.adobe.com/magento-docs/infrastructure/blob/master/jenkins/pipeline-scripts/devdocs-algolia-reindex.groovy

**Comment by belbiy** [comment]
@jeff-matthews , the main problem i'm trying to solve is indexing of the code line numbers:

Screen Shot 2019-06-20 at 11 26 11 AM

From my point of view, separate config is not much cleaner and maintainable, but it's the only way to achieve the difference with rendering for production and rendering for indexing.

And i will make PR to the jenkins pipeline, thank you for the link!

**Comment by belbiy** [comment]
Pipeline script updated. https://git.corp.adobe.com/magento-docs/infrastructure/pull/15

**Comment by belbiy** [comment]
running tests

**Pull request merged**
