### PR TITLE
Change description of running consumer

### PR DESCRIPTION
**Pull request by nuzil**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

Original description of consumer is technically wrong one. We are not enabling asynchronous requests (async and bulk requests are enabled by default in Magento without any effort from user).
This command is running consumer, that will read messages from queue and execute required operartions

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
Thank you @nuzil and @osrecio for the explanation. What about something like:
"Magento uses the `bin/magento queue:consumers:start async.operations.all` command to handle Asynchronous/Bulk API messages."

**Comment by keharper** [comment]
@erikmarr Rewrite the sentence to

Use the `bin/magento queue:consumers:start async.operations.all` command to start the consumer that handles asynchronous and bulk API messages.

**Comment by erikmarr** [comment]
Updated text per Kevin's edit.

**Comment by erikmarr** [comment]
running tests

**Comment by osrecio** [comment]
Thanks both of you @keharper and @erikmarr ! 👍

**Comment by erikmarr** [comment]
Thanks @nuzil and @osrecio for the contribution!

**Pull request merged**
