### PR TITLE
Added example for using block argument in template

### PR DESCRIPTION
**Pull request by drpayyne**
## Purpose of this pull request

This pull request (PR) adds an example on how to use block arguments in its template. Also fixed the hyperlink to block's argument.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-override.html
-  https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/templates/template-override.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @drpayyne. Thank you for the proposed addition. That's really useful

**Comment by drpayyne** [comment]
@rogyar Thank you! 😄

**Comment by dobooth** [comment]
running tests

**Comment by drpayyne** [comment]
@dobooth Thank you!

**Pull request merged**
