### PR TITLE
Replace symlinks to guides/v2.2 with real files

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request replaces all symlinks to files in `guides/v2.2` with real files. This is a required step in preparation of the 2.2 content transfer to a separate branch.

This PR also removes 2.3 redirects from 2.2 guides, and removes 2.2 redirects from 2.3 guides.

After this PR is merged, all new version-specific PRs should not affect the `guides/v2.2` files.

_Internal preview: 1257_

## Affected DevDocs pages

-  the content was not affected

### CODE REVIEW

**Comment by dshevtsov** [comment]
@hguthrie thank you for your review. I expect that changes in this PR will not affect a website user experience (neither human, nor technology as the user).

**Comment by jeff-matthews** [comment]
I've got a ton of small changes PRs that I'd like to merge into `master` from the `small-changes` branch as well as two new topics. However, I don't want to discourage this effort to break symlinks and prepare us to archive 2.2 content.

@dshevtsov, what's your preferred course of action here before I merge anything with `master`?

**Comment by dshevtsov** [comment]
@jeff-matthews go ahead and merge it.
The changes in this PR were made using automation. I will just rerun it on the updated `master` and override commits in this branch since I am the only contributor.

**Comment by jeff-matthews** [comment]
Ok, thanks @dshevtsov.

**Comment by dshevtsov** [comment]
hm, it was closed automatically after a force-push

**Comment by dshevtsov** [comment]
And the Reopen button is inactive

**Comment by dshevtsov** [comment]
I reset the branch to the latest state on master, but forgot to commit my changes 🙄

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
