### PR TITLE
Fixed line numbers. Now the links shows the right code.

### PR DESCRIPTION
**Pull request by barbanet**
## Purpose of this pull request

The link with the example code for Create a block and template was wrong. Now the highlighted lines of code are correct.

## Affected DevDocs pages

* /guides/v2.2/extension-dev-guide/cache/page-caching/private-content.html
* /guides/v2.3/extension-dev-guide/cache/page-caching/private-content.html

## Links to Magento source code

https://github.com/magento/magento2/blob/2.3/app/code/Magento/Catalog/view/frontend/templates/product/compare/sidebar.phtml

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @barbanet. Could I kindly ask you to fix other examples in this document as well, please. So we have all examples correct. It looks like most of them are broken.
Thank you!

**Comment by barbanet** [comment]
Hi @rogyar!
Sure! Let me check.

**Comment by barbanet** [comment]
Hi @rogyar!
Can you check if I miss anything?

**Pull request merged**
