### PR TITLE
Adding argument in payment gateway command

### PR DESCRIPTION
**Pull request by magesanjay**
## This PR is a:

- Adding Message Mapper argument

## Summary

When this pull request is merged, it will add the missing argument in payment command

## Additional information
 List affected URLs
https://devdocs.magento.com/guides/v2.2/payments-integrations/payment-gateway/gateway-command.html
https://devdocs.magento.com/guides/v2.3/payments-integrations/payment-gateway/gateway-command.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magesanjay** [comment]
Hi Osrecio,

I have made requested changes. please check it.

Thanks
Sanjay

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @magesanjay!

**Pull request merged**
