### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by SikailoISM**
Fix typo

This pull request (PR) is for typo fix

## Affected DevDocs pages

https://devdocs.magento.com/cloud/cdn/configure-fastly.html#purge

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Thanks for the fix @SikailoISM! I noticed you fixed another typo in #6318, which has already been merged If you plan on creating more PRs to fix typos, please do so in a single PR per our contribution guidelines: https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md#contribution-guidelines.

**Comment by SikailoISM** [comment]
@jeff-matthews no, it's last pr for now

**Pull request merged**
