### PR TITLE
MQP Release 1.0.4

### PR DESCRIPTION
**Pull request by ilima-ebay**
## Purpose of this pull request

 - Added RN for MQP v1.0.4
 - Updated RN for MQP v1.0.3

## Affected DevDocs pages

-  https://devdocs.magento.com/quality-patches/release-notes.html

whatsnew
Published [release notes](https://devdocs.magento.com/quality-patches/release-notes.html) for the 1.0.4 Magento Quality Patch (MQP) package release.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-engcom-team** [comment]
@ilima-ebay thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by jeff-matthews — APPROVED** [review]
@ilima-ebay, do you want the release notes published right away or at some other time?

**Comment by ilima-ebay** [comment]
@jeff-matthews  I'm checking with the team.

**Comment by ilima-ebay** [comment]
@jeff-matthews  we will let you know when the MPQ Release is ready on our side so that the RN get published as well.

**Comment by jeff-matthews** [comment]
@ilima-ebay, sounds good. It takes about 30 minutes to run PR validation and publish FYI.

**Comment by ilima-ebay** [comment]
@jeff-matthews  I updated my PR as we decided to update some constraints.
Please go ahead and run PR validation and publication.
Thanks!

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
@ilima-ebay, docs have been published. Thanks for the PR! 🏆

**Pull request merged**
