### PR TITLE
MAGECLOUD-2067 clarify branching

### PR DESCRIPTION
**Pull request by hguthrie**
The previous pull request corrupted during a GitHub brown out. This is a new PR with the same content. https://github.com/magento/devdocs/pull/3532

Bug fix

Clarified the use of magento-cloud CLI versus git to create active environment branches.
Also,

Cleaned up the topic flow with three distinct actions (Clone project, Change/add variables, Branch environment)
Updated the steps with magento-cloud commands (tested and provided output in some cases)
Cleaned up the markdown formatting
Corrected grammar in some cases
Affected topics

https://devdocs.magedevteam.com/hg-mc2067-cloudcli/guides/v2.3/cloud/before/before-setup-env-2_clone.html

whatsnew
Refreshed the Cloud topic for cloning and branching a project for local development.

### CODE REVIEW

**Comment by hguthrie** [comment]
@jeff-matthews  @meker12 
If one of you could give a lightning-quick review, this is content from the *corrupted* PR that you guys already approved. The only difference is the last commit before the merge...I committed the edits (the part that corrupted during the brown-out) I made based on your feedback.

**Comment by hguthrie** [comment]
running tests

**Comment by dshevtsov** [comment]
@hguthrie add version labels to the PR

**Comment by dshevtsov** [comment]
@hguthrie I removed a link to a preview in the description to follow the DevDocs convention to avoid links to internal resources.

**Pull request merged**
