### PR TITLE
Add Documentation for Operation Status Endpoints

### PR DESCRIPTION
**Pull request by nuzil**
## This PR is a:
- [x] New topic

## Summary
 
Adding new topic with operation statuses endpoints description.
Description of 2 Endpoints included responses

### CODE REVIEW

**Comment by nuzil** [comment]
@keharper can you please have a look at last line. I'm not sure how good to do it in documentation. I want to add this like a note, so developers know what is bulkUuid in endpoints. Also are there a way to create a relative links within documentation?

**Comment by keharper** [comment]
We prefer to use a variable that corresponds to `https://devdocs.magento.com/guides/v2.x` then specify the rest of the path. In this case, you'd have 

[Magento Asynchronous API Requests]({{ page.baseurl }}/rest/asynchronous-web-endpoints.html)

**Comment by keharper** [comment]
I missed the first part of your question. I would move the last line to line 13. We will also need to update the `asynchronous-web-endpoints` document to show a real call  where a UUID is returned.

**Comment by nuzil** [comment]
"document to show a real call where a UUID is returned" - yes correct, mentioned that when wrote this part

**Comment by keharper** [comment]
I'm closing this issue, since all the content is in [PR-2363](https://github.com/magento/devdocs/pull/2363/)

**Pull request closed without merging**
