### PR TITLE
Clarify global scoped config options

### PR DESCRIPTION
**Pull request by dcabrejas**
## Purpose of this pull request

At the moment this isn't clear and can take people a while to figure out how to do this even after having read the documentation.
This modification should make it clear to people how to configure config options in the global scope.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/test/integration/annotations/magento-config-fixture.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Example from the codebase:
https://github.com/magento/magento2/blob/36e99ac727d5dfadadcca0de8242c32566afc2a4/dev/tests/integration/testsuite/Magento/Sales/Model/GridAsyncInsertTest.php#L70

**Comment by rogyar** [comment]
Hi @dcabrejas. Thank you for your collaboration. Could I kindly ask you to sign CLA? You can check the details [here](https://github.com/magento/devdocs/pull/6084/checks?check_run_id=324513769).

**Comment by dobooth** [comment]
running tests

**Pull request merged**
