### PR TITLE
update m2-ece-scd-dump to ece-tools config:dump

### PR DESCRIPTION
**Pull request by taoufiqaitali**
## Purpose of this pull request

Replaced deprecated `m2-ece-scd-dump` command with the current command, `ece-tools config.dump`.

## Affected DevDocs pages

https://devdocs.magento.com/cloud/live/sens-data-initial.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@taoufiqaitali thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by meker12** [comment]
@taoufiqaitali  The deprecated command also shows up on some other topics. Can you locate those and update them as well.  Thanks!

**Comment by taoufiqaitali** [comment]
> Update to replace other occurrences of the deprecated command.

@meker12 ok done changed in other files

**Comment by taoufiqaitali** [comment]
> @taoufiqaitali Please fix the merge conflict? Thx!

@meker12 ok conflict fixed thanks

**Comment by dobooth** [comment]
running tests

**Pull request merged**
