### PR TITLE
Create Technical Vision intro page

### PR DESCRIPTION
**Pull request by keharper**
## This PR is a:

- [x] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will create an index page for the Technical Vision section of the Coding Standards guide.

### CODE REVIEW

**Comment by dshevtsov** [comment]
@keharper please add whatsnew

**Comment by keharper** [comment]
I removed the New doc label, because this PR merely created the infrastructure needed for #3418.

**Comment by dshevtsov** [comment]
A PR must always have a label to reflect a type of changes

**Comment by dshevtsov** [comment]
If it doesn't introduce any technical information, then it is editorial

**Pull request merged**
