### PR TITLE
Prepare 2.4.0-develop for contributions

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) introduces basic changes to enable contributions to 2.4 documentation:

- created the v2.4 directory with symlinks
- changed the site under the hood to enable 2.4 version
- added `rake symlink:create_from` and `rake symlink:replace_at` helper tasks
- added dummy files for future release notes (FYI @jfrontain )
- changed Liquid in reference templates to handle 2.4 reference topics with yet no data (FYI @dobooth)
- excluded redoc and mrg at 2.4 in the link checking config since there is no data for that yet (FYI @keharper)
- minor changes

Find more details in commits.

The introduced content is sufficient only to be testable to enable public contributions. It will still require more changes in future PRs though such as to review 2.4 topics that inherited notes 2.3-specific notes.

The magento2 code bases will need updates in Module Readmes such as:
- Update devdocs versions to the latest relevant minor version
- Replace a relative path to topic `ui-components/ui-listing-grid.html` with `ui_comp_guide/bk-ui_comps.html`
---
_Internal contributors, see DOC-64 for more details._

### CODE REVIEW

**Comment by dshevtsov** [comment]
I added them as a part of "standard kit", because contributors would expected them to be there I assume.
By the way, the are few files already that are not symlinks such as release notes topics and autogenerated references.

**Comment by jeff-matthews** [comment]
What do you mean by "standard kit"?

**Comment by dshevtsov** [comment]
> What do you mean by "standard kit"?

We provide them for each version.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
