### PR TITLE
[WIP] #3361 New Configuration Type Topic

### PR DESCRIPTION
**Pull request by diazwatson**
## Purpose of this pull request

#3361 This pull request (PR) adds a new topic / section to explain how to use the classes described in Overview of module configuration files.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/config/config-files.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @diazwatson. Thank you for your collaboration. The changed topic contains general information about module configuration files. Maybe we should move your example to a more specific place, like [this one](https://devdocs.magento.com/guides/v2.3/config-guide/config/config-create.html#config-files-extend-create-create)?

**Comment by rogyar** [comment]
One more thing. Your example is fair for both 2.2 and 2.3. So, it would be great if we extend the documentation for both versions.

**Comment by rogyar** [comment]
Hi @diazwatson. Just want to follow you up regarding this PR :) 
Thank you.

**Comment by dshevtsov** [comment]
@diazwatson please sync your branch with `master` to resolve the conflicts.

**Comment by dobooth** [comment]
Closing as abandoned. Please reopen if needed.

**Pull request closed without merging**
