### PR TITLE
Add information on install guide 

### PR DESCRIPTION
**Pull request by gelanivishal**
## This PR is a:

- [X] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will add the following missing parameter and description:
> --magento-init-params

## Additional information

List all affected URLs 
- https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-admin.html
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Hi, @gelanivishal. The Magento writers have recently discussed the proper way to refer to the `magento` command in command line examples. We came to the conclusion that `bin/magento rest:of:command` is the preferred way, but we haven't started implementing this decision. I'm changing the command line examples, but otherwise accepting your PR.

**Comment by keharper** [comment]
running tests

**Comment by jeff-matthews** [comment]
@keharper, I'm about to merge an update, so I would abort the test job and wait if I were you.

**Comment by keharper** [comment]
running test

**Comment by keharper** [comment]
running tests

**Pull request merged**
