### PR TITLE
Jf release notes 2 3 3

### PR DESCRIPTION
**Pull request by meker12**
## Purpose of this pull request

Final 2.3.3 release note updates

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/release-notes/bk-release-notes.html

### CODE REVIEW

**Comment by jeff-matthews** [comment]
running tests

**Comment by hostep** [comment]
@meker12: looks good at first sight 👍, but I only briefly went through this, haven't got much time nor energy anymore this late at night :)

**Comment by meker12** [comment]
@hostep   No worries.  We added you here mainly to give you credit for the updates that you submitted in https://github.com/magento/devdocs/pull/5403.

**Comment by hostep** [comment]
Ah it was already merged 6 days ago, didn't even notice that 😄 (really need some sleep  apparently 😉)

**Pull request merged**
