### PR TITLE
Improvements for CSS in responsive design doc

### PR DESCRIPTION
**Pull request by rossmc**
## This PR is a:
[ ] New topic
[✓] Content fix or rewrite
[✓] Bug fix or improvement

 

## Summary
Added more detail on the use of the the `.media-width()` mixin and the `@media-common` style group separation.

Rearranged sections in document to improve readability, so that things were explained before they were referenced.  For instance it's hard to explain how M2 uses media queries in their themes without first explaining their mobile first approach and use of breakpoints
  
**Preview...**

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=1963) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=1963) before we can accept your contribution.<br/>

**Comment by bdenham** [comment]
Hi @rossmc, thanks for adding more info to the topic. On first glance, your change to the content's order helps, but it still feels like the topic is missing information that would make it easier to understand. I'll take a look at this over the next few days. Thanks, again.

**Comment by rossmc** [comment]
@bdenham yes I agree it can probably improved further.  But I think the current doc is missing out on something very important by not mentioning `.media-width(`) mixins and the `@media-common` style group.  I've spoken with quite a few devs who have gotten stuck on this when first working with M2.

There is more info on it in the Magento UI library documentation
[/pub/static/frontend/Magento/blank/en_US/css/docs/responsive.html](http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/responsive.html)

Let me know if there is anyway I can help, to rewrite a section or something.

**Comment by bdenham** [comment]
Thanks, @rossmc. Yes, I completely agree with you on the importance of documenting the `.media-width()` mixins and the `@media-common` style group and will devote time early next week to work with you to get this merged into production. Thanks again for helping out with this!

**Comment by rossmc** [comment]
Any update on this @bdenham, let me know if I can amend in some way to help

**Comment by bdenham** [comment]
Hey @rossmc, so sorry I had to put this on the back burner for a bit, but I will commit to working with you to complete this before the end of this week! Stay tuned.

**Pull request merged**
