### PR TITLE
[2.3.3] Updated lock config and lock env short commands

### PR DESCRIPTION
**Pull request by shikhamis11**
## This PR is a:

- Content fix or rewrite

## Summary

When this pull request is merged, it will update the short commands for lock env and lock config
as updated in Pull Request on magento 2 core 
https://github.com/magento/magento2/pull/22720

## Additional information
reference page of configuration command - /config-guide/cli/config-cli-subcommands-config-mgmt-set.html
is only available from magento 2.2 version onwards  

List all affected URLs 

https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.html
https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-set.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shikhamis11** [comment]
#ContributionDay

**Comment by lorikrell** [comment]
@shikhamis11, thank you for your contribution!

FYI to DevDocs team: code change is part of 2.3.3 Milestone. Added label.

**Comment by dobooth** [comment]
Thanks @shikhamis11 !

**Pull request merged**
