### PR TITLE
Update project-multi-sites.md

### PR DESCRIPTION
**Pull request by lbortolotto-jakala**
## Purpose of this pull request

Corrected some typos

## Affected DevDocs pages

guides/v2.2/cloud/project/project-multi-sites.md

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@lbortolotto-jakala thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Thanks for the contribution, @lbortolotto-jakala! We recently updated the CLA and need you to sign this new one before we can merge. Thanks!

**Comment by shrielenee** [comment]
@lbortolotto-jakala Can you sign the CLA so we may proceed with merging this? 🙇‍♀

**Comment by lbortolotto-jakala** [comment]
I'm waiting for Jakala's legal team to complete the CLA :( we are a big company with big timings

**Comment by dobooth** [comment]
Closing due to lack of activity. Please reopen if you get the lawyers to approve.

**Pull request closed without merging**
