### PR TITLE
DEVDOCS-SMALL-FIXES: Fixed versions in "Example - Security patch"

### PR DESCRIPTION
**Pull request by andrewbess**
## Purpose of this pull request

This pull request (PR) fixes versions in "Example - Security patch"

## Affected DevDocs pages

-  [Command-line upgrade](https://devdocs-beta.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @andrewbess. I'm really not sure we should bring this update into example with every new patch version :) Could you shed more light on the idea, please?

**Comment by andrewbess** [comment]
> Hi @andrewbess. I'm really not sure we should bring this update into example with every new patch version :) Could you shed more light on the idea, please?

Hello @rogyar 
Thank you for your quick review.
My friend tried to update his Magento project from Magento 2.3.3 to Magento 2.3.3-p1. He has found this document and copied the suggested command. So, he has tried to downgrade his system from Magento 2.3.3 to Magento 2.3.2-p1.
My friend told me about this situation, and I decided to help the community by fixing this document.

**Comment by rogyar** [comment]
Yeah, it's better to upgrade Magento by a mistake than downgrade it :)

Thank you for the explanation.

**Pull request merged**
