### PR TITLE
magento/devdocs#: Fix php format on the "Plugins (Interceptors)" page

### PR DESCRIPTION
**Pull request by atwixfirster**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will replace `PHP` code style with the `php` on the "Plugins (Interceptors)" page.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hey @atwixfirster 
Thanks for the submission.
Couple things:
The correct format is ```php (no space). 
Second, the affected URL says v2.0 but the file you are changing is v2.2. Please clarify.
Thanks!

**Comment by atwixfirster** [comment]
Good morning, @dobooth !

> The correct format is ```php (no space).
Thank you for the clarification!

> Second, the affected URL says v2.0 but the file you are changing is v2.2. Please clarify.
Changed to https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html in the PR description

> Thanks!
Thank you! 😊

**Comment by keharper** [comment]
Thanks @atwixfirster

**Pull request merged**
