### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - php version 7.1 release is no longer supported. So it has been removed. And magento 2.4 supports php 7.4. So it was added.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/composer-integration.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @chandru-199. Thank you for your edit. I would go further and remove 7.2 as well. 7.2 (and 7.3 but let's leave it for now) is not supported by 2.4 so there's no reason to outline it in a Magento module. Thank you

**Comment by chandru-199** [comment]
Thanks @rogyar . Removed 7.2 as well. Can you please review?

**Comment by dobooth** [comment]
running tests

**Pull request merged**
