### PR TITLE
#8458 getViewModel() results in null

### LINKED ISSUE #8458: Feedback on page: /guides/v2.4/extension-dev-guide/view-models.html
# `getViewModel()` results in null

## Description:

Documentation explains to use `<argument name="viewModel">` within layout.xml and then to retrieve that viewModel in the template by calling `$viewModel = $block->getViewModel();`. This causes `$viewModel` to be null.

## Possible solutions:

Update layout.xml instructions to read `name="view_model"`

### PR DESCRIPTION
**Pull request by chrisfwd**
## Purpose of this pull request

This pull request (PR) fixes documentation about viewmodels that explains to use `name="viewModel"` in layout.xml and tries to retrieve that viewmodel in the template via `$block->getViewModel()`

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/view-models.html
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-instructions.html
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-manage.html

-  ...

Fixes #8458

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@chrisfwd thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by mrtuvn** [comment]
In my point of view this is preference choice. But default magento used argument viewModel instead view_model. Both way should work
Here is example code magento recommend
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Element/Template.php#L24

**Comment by dmytro-ch** [comment]
In my opinion, the `view_model` key is the correct one. Since the original idea was to retrieve the view model with the corresponding magic method and conventionally reserve this method name:
```
$viewModel = $block->getViewModel();
```
OR using getter in a conventional way, with snake case:
```
$viewModel = $block->get('view_model');
```

While the following approach is confusing and seems to be caused by a typo in documentation.
```
$viewModel = $block->get('viewModel');
```

**Comment by dmytro-ch** [comment]
I would prefer to fix this doc block accordingly:
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Element/Template.php#L24

**Review by dmytro-ch — COMMENTED** [review]
In my opinion, the `view_model` key is the correct one. Since the original idea was to retrieve the view model with the corresponding magic method and conventionally reserve this method name:
```
$viewModel = $block->getViewModel();
```
OR using getter in a conventional way, with snake case:
```
$viewModel = $block->get('view_model');
```

While the following approach is confusing and seems to be caused by a typo in documentation.
```
$viewModel = $block->get('viewModel');
```

I would prefer to fix this doc block accordingly:
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Element/Template.php#L24

**Review by BarnyShergold — APPROVED** [review]

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
