### PR TITLE
Added information about when a patch is being applied

### PR DESCRIPTION
**Pull request by dverkade**
## This PR is a:
- Content fix or rewrite
- Improvement
 

## Summary
 
When this pull request is merged, it will explain to developers when a patch is applied and where the list of applied patches is stored.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2521) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2521) before we can accept your contribution.<br/>

**Comment by keharper** [comment]
@sereban would you confirm this addition?

**Comment by keharper** [comment]
@sereban please confirm this change.

**Comment by keharper** [comment]
Thanks for the update, @dverkade

**Pull request merged**
