### PR TITLE
Content update for "Code Contributions" page

### PR DESCRIPTION
**Pull request by sdzhepa**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

- Removed reference to 2.1 as not supported version for contribution
- Added information about points for issue confirmation

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3829) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3829) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@sdzhepa thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by lorikrell** [comment]
running tests

**Pull request merged**
