### PR TITLE
magento/devdocs#: Add description to CSS examples

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) adds description to CSS examples.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/theme-ui-lib.html
- https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/theme-ui-lib.html
- https://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
From the developer's perspective, it's a good clarification. Commonly used in Magento core (https://github.com/magento/magento2/blob/f86e42146dfaaf5d7ff3b0b71ea7baee74c1638c/app/code/Magento/Contact/view/frontend/web/css/source/_module.less#L25)

**Comment by jeff-matthews** [comment]
I'm not quite sure what happened here, but I made a mess of this PR when I tried changing the base branch and I'm not sure how to fix it. I'm open to suggestions, but it might be best to cherry pick the commit for the change and create a new PR.

**Comment by jeff-matthews** [comment]
Ohhhhh, I think know what happened. I didn't delete my old `small-changes` branch the last time I ran through this workflow, so when I changed the base branch to `small-changes` and then resolved the merge conflict, I think I messed up the history and added a bunch of unnecessary commits.

**Pull request merged**
