### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ksrajath7**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@ksrajath7 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
Hi @ksrajath7 
Thanks for your contribution.
Can you please update the description and explain about your change.
Also, please Signed Adobe CLA.

**Comment by dobooth** [comment]
Hi @ksrajath7 I am going to close this PR. The change you are requesting is not valid code. The PR description is not filled out and you have not signed the CLA.

**Pull request closed without merging**
