### PR TITLE
Update unit_test_execution_cli.md

### PR DESCRIPTION
**Pull request by Echron**
Fix typo

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Good eye, @Echron. Would you mind making the same change to the v2.3 file as well?

**Comment by Echron** [comment]
@dobooth Sure (https://github.com/magento/devdocs/pull/9400)

**Comment by dobooth** [comment]
Thanks @Echron.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-Echron-devdocs-9392`.

**Pull request merged**
