### PR TITLE
magento/devdocs#: Add info about column types for which we can set a `length` attribute

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) adds explanations about column types for which we can use a `length` attribute.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html

## Links to Magento source code

-  [char](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/types/texts/char.xsd#L21)
-  [varchar](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/types/texts/varchar.xsd#L23)
-  [varbinary](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/types/binaries/varbinary.xsd#L20)

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Can confirm that the "length" parameter is applicable for variable-length binary types

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
