### PR TITLE
Documentation about new multiple processes option for consumers

### PR DESCRIPTION
**Pull request by adifucan**
## Purpose of this pull request

This pull request (PR) introduces documentation about new `multiple_processes` option in `app/etc/env.php` and new `--multi-process` option in `queue:consumers:start` CLI command.

## Affected DevDocs pages

-  src/_includes/config/message-queue-consumers.md
- src/guides/v2.4/config-guide/mq/manage-message-queues.md
- src/_data/codebase/v2_4/commerce/bin-magento.json
- src/_data/codebase/v2_4/open-source/bin-magento.json

## Links to Magento source code

-  https://github.com/magento-commerce/magento2ce/pull/7181

### CODE REVIEW

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
This is great, but please fix the linting issues for approval

**Review by BarnyShergold — APPROVED** [review]
Thanks!

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-magento-performance-devdocs-9239`.

**Pull request merged**
