### PR TITLE
Fix ElasticSuite documentation (wrong ES version).

### PR DESCRIPTION
**Pull request by afoucret**

### CODE REVIEW

**Comment by bmondolot** [comment]
You forgot to fix the other occurence of smile-es in the file : 

> If using smile-es, the required plugins are ...

**Comment by afoucret** [comment]
Fixed !!!

Thx

**Comment by afoucret** [comment]
@jeff-matthews,

I suppose that if someone added a reference to Elasticsuite in the doc because it is useful. 

But a this time there is an error in the required Elasticsearch version and the open source project receive a lot of demand related to Magento cloud. So it would be nice if this one was merged.

BR

**Comment by jeff-matthews** [comment]
Thanks for confirming @afoucret!

**Pull request merged**
