### PR TITLE
Update search-endpoint.md

### PR DESCRIPTION
**Pull request by philippsander**
Removed unnecessary signs

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Good spot!

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please fill in the PR description in the required manner - information can be found in the repo wiki.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
