### PR TITLE
DEVDOCS-FIXES: Actualization the document "Running Unit Tests in PhpStorm"

### PR DESCRIPTION
**Pull request by andrewbess**
## Purpose of this pull request

This pull request (PR) fixes the document "Running Unit Tests in PhpStorm" according to the last PhpStorm interface.
It used to have screenshots and links for the very old version of PHPStorm (2016.1, current version 2019.3).

So, this PR fixes:
- wrong screenshots (interface of PHPStorm has been changed);
- links (PHPStorm Help System has been updated by Jetbrains).

## Affected DevDocs pages

- [Running Unit Tests in PhpStorm](https://devdocs.magento.com/guides/v2.3/test/unit/unit_test_execution_phpstorm.html)

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dshevtsov** [comment]
You can also use `rake check path=<path to the image or to a directory with images>`, or resubmit the images. NOTE: When you run `rake check`, it verifies each uncommitted file for image compression and Markdown style. When you run `rake check path=<path>`  it checks each file in the provided file recursively, even if it was committed.

**Comment by andrewbess** [comment]
> Thanks for the contribution, Andrew. In order to keep our repo size reasonable, we are trying to optimize images before they get into the repo. I would like you to run it on this PR before we merge.
> It is build into the devdocs CLI. In your terminal, at the root of devdocs, type `rake -T`. It will list the rake tasks. One of them is `rake check:image_optim`. It will show you usage. Please run this on your images. You should see a good reduction in size. Then update your PR with these updated images. Thanks!

Hello @dobooth 
Yes, of course.
Thank you much for request.
I have optimized the images.
Please check.

**Comment by andrewbess** [comment]
> You can also use `rake check path=<path to the image or to a directory with images>`, or resubmit the images. NOTE: When you run `rake check`, it verifies each uncommitted file for image compression and Markdown style. When you run `rake check path=<path>` it checks each file in the provided file recursively, even if it was committed.

Hello @dshevtsov 
Both methods are good.
Thanks much

**Comment by dobooth** [comment]
running tests

**Pull request merged**
