### PR TITLE
Added customer search API request example

### PR DESCRIPTION
**Pull request by gelanivishal**
## This PR is a:

- [X] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary
I have added customer search API request example as per issue #3028

### CODE REVIEW

**Comment by keharper** [comment]
@gelanivishal We love code samples, so thanks for the contribution. To help address @bhargavmehta 's statement and also answer the original comment left  on HotJar, add a link to  "List of REST endpoints by module" at the bottom of the "Endpoints" section. The format of this link would be `[List of REST endpoints by module]({{ page.baseurl }}/rest/list.html` .

**Comment by gelanivishal** [comment]
@keharper I can't access hotjar link.

**Comment by keharper** [comment]
I can't either, but it's described in #3028

**Comment by gelanivishal** [comment]
@bhargavmehta Can you please explain to me where do you want to change/add content and give me that content so that PR will be processed for further test.

**Comment by bhargavmehta** [comment]
Hello @gelanivishal as suggested by @keharper we can add an additional line just above the code sample and after the line finishes with ``` searchCriteria usage``` . Line text is mentioned by @keharper in the previous comment.

Thank you

**Comment by gelanivishal** [comment]
@keharper I have added explanation, Please check it.

**Comment by keharper** [comment]
Thanks for your contribution @gelanivishal

**Pull request merged**
