### PR TITLE
Web API allows to create Customer for admin and for guest user.

### PR DESCRIPTION
**Pull request by TomashKhamlai**
## Purpose of this pull request

Web API allows creating Customers for admin and for guest users.
It can be checked in Swagger too.

This pull request (PR) documents that the token is not required.

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@TomashKhamlai As of last Friday, there's a new top-level directory (`src/`) above `guides/`. Please pull in those changes and fix the merge conflict.

**Comment by osrecio** [comment]
Hi @TomashKhamlai , I think after your merge, we don't have changes to merge. It's ok?

**Comment by TomashKhamlai** [comment]
@osrecio, please check again. It is because of moving to `src/` folder

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks for the clarification @TomashKhamlai. The deleted information was an artifact of a very early draft of the tutorial.

**Pull request merged**
