### PR TITLE
Adding Super Linter

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR):
- Checks as much of the source code as possible with linters
- Adds [SuperLinter](https://github.com/github/super-linter) with disabled HTML and Markdown linting
- Sets the linter to use same triggers as existing _Markdown linting test_
- Sets the linter to run only on new or edited files
- Adds custom configurations for Ruby and Markdown
- Fixes style in the Ruby and Markdown files
- Remains the file with Markdown rules reserved for future use (after the bug is fixed) and adds a symlink at the root of project for IDEs that support [markdownlint](https://github.com/DavidAnson/markdownlint#related).

## Additional information

Markdown linter has false positive failures `MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 3]`. Looks like a bug.
The project does not contain pure HTML code at source code.

### CODE REVIEW

**Comment by dshevtsov** [comment]
Looks like there is some bug in MD linter of the SuperLinter.
It detects false positive violations such as
```
MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 3]
```
whereas, in fact, the rule is set to [indent: 3](https://github.com/magento/devdocs/blob/0bfdbe7416370fe8836a3be91a08977517ee6542/.github/linters/.markdownlint.json#L8)

**Review by jeff-matthews — APPROVED** [review]
Jus to confirm, two GitHub Actions will run on each PR to a protected branch: 1) MD lint using MDL and 2) Super Linter?

**Comment by dshevtsov** [comment]
Correct,
1) MD lint using MDL on entire codebase
2) Super Linter on new or modified files with all linters enabled except HTML and MD

And only the first option is set as a required check at the moment.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
