### PR TITLE
Miss-spellings and typos!

### PR DESCRIPTION
**Pull request by EmilyPepperman**
When this pull request is merged, it will...
Fix some typos and misspellings

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4062) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4062) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Thanks @EmilyPepperman!

**Pull request merged**
