### PR TITLE
compensations command changes

### LINKED ISSUE #8758: Feedback on page: /guides/v2.3/inventory/inventory-cli-reference.html
# General issue

## Description:

Missing info on section Create compensations command (https://devdocs.magento.com/guides/v2.3/inventory/inventory-cli-reference.html#create-compensations-command)

## Possible solutions:

Recommend you add that if the sku for a compensation entry includes spaces, enclose the sku in quotation marks for example, the command:

bin/magento inventory:reservation:create-compensations 172:bike space 123:+2.000000:1

above will create an error, but add the quotation marks around the sku and the below works:

bin/magento inventory:reservation:create-compensations 172:"bike space 123":+2.000000:1

## Additional information:

While not popular, many businesses, especially small businesses use spaces in SKU's.

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Adding additional information with example in create compensation command

Fixes #8758 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/inventory/inventory-cli-reference.html

### CODE REVIEW

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
@chandru-199 Be sure to claim ownership of an issue (#8758 in this case) before starting work on the PR. We don't want multiple people working on the same issue.

**Comment by chandru-199** [comment]
@keharper : Please add partner:ziffity label to this PR.

**Comment by chandru-199** [comment]
@ajithkumar-maragathavel : Could you Please add partner:ziffity label to this PR.

**Pull request merged**
