### PR TITLE
Update sample-data.md

### PR DESCRIPTION
**Pull request by 7php**
should add -f (php commandline)
Ommitting it will not work.

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
Thanks!

**Comment by xcomSteveJohnson** [comment]
Omitting -f works if you also omit the first set of double-dashes.

php dev/tools/Magento/Tools/SampleData/install.php --admin_user=

**Comment by 7php** [comment]
ok thanks Steve!

**Comment by xcomSteveJohnson** [comment]
BTW, the documentation is changing again, possibly today. The above script still works but will likely be removed from the Magento code base in the near future.

It's being replaced by a 'magento' CLI command. Wanted to give you a heads up.

**Comment by 7php** [comment]
Woooo, thanks for this update Steve, really appreciate!!
By Magento CLI, I assume it's the bin/magento right?
That would be a better option actually, centralizing all commands-related-things at one place

**Comment by xcomSteveJohnson** [comment]
Yes, bin/magento. There was a glitch with the sample data package that prevented us from verifying the new CLI command. I will try that again today and will tweet the documentation update.

**Comment by 7php** [comment]
Fantastic Steve, thank you for all that you do, you are amazing!
Btw what's your twitter handle?

**Comment by xcomSteveJohnson** [comment]
MagentoDevDocs, you're following us.

**Comment by 7php** [comment]
Cheers!

**Comment by xcomSteveJohnson** [comment]
@7php Just published the update here: http://bit.ly/1HSALaY

**Comment by 7php** [comment]
Thanks a lot Steve!

**Pull request merged**
