### PR TITLE
Update private-content.md

### PR DESCRIPTION
**Pull request by vzabaznov**
## Purpose of this pull request

This pull request (PR) adds information about invalidating private content.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
This PR appears to be a follow-up to ##5461 

@dobooth would you handle this one?

**Comment by dobooth** [comment]
running tests

**Pull request merged**
