### PR TITLE
Removed duplicate explanation for "You must not hard-code inline Java…

### PR DESCRIPTION
**Pull request by sanganinamrata**
## Purpose of this pull request

This pull request (PR) is to finetune document for **Code demarcation standard** page on Magento 2 devdoc. I've removed duplicate explanation for **You must not hard-code inline JavaScript in PHP classes** section in both Magento 2.2 and Magento 2.3 devdoc versions.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/coding-standards/code-standard-demarcation.html
- https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-demarcation.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Good catch @sanganinamrata ! Can you please include the v2.2 file in this PR and update the description above.
Then we can get it into devdocs.
Thanks for the update.

**Comment by sanganinamrata** [comment]
Sure I'll update it as per your instructions quickly on both branches

**Comment by sanganinamrata** [comment]
@rogyar, @dobooth Hi, I've updated changes as mentioned by you.

**Comment by dobooth** [comment]
Excellent! Thanks for the help.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
