### PR TITLE
Update whatsnew for Q1 2021 release

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) updates the [What's New](https://devdocs.magento.com/whats-new.html) page with entries for the 2.4.2 release.

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Comment by jeff-matthews** [comment]
Missing PR #8646. Investigating cause.

**Comment by keharper** [comment]
The whatsnew statement for #8646 is missing, but I won't make that a blocker.

**Review by keharper — APPROVED** [review]

**Comment by jeff-matthews** [comment]
There are actually quite a few missing entries in addition to #8646. 

#8657 fixes the issue. I'll push the updates as soon as I figure out why the link to the [renameRequisitionList mutation](https://devdocs.magento.com/guides/v2.4/graphql/mutations/rename-requisition-list.html) in #8093 is 404ing.

**Comment by jeff-matthews** [comment]
It must have been removed in the `2.4.2-develop` branch prior to the merge to `master` because the file doesn't exist.

**Comment by jeff-matthews** [comment]
Confirmed with @keharper that it was removed. Update dPR description accordingly.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
