### PR TITLE
Update Release Notes 2.3.2 Open Source

### LINKED ISSUE #4924: Feedback on page: /guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.html
# 2.3.2 Release Notes: missing known issue

## Description:

There is a confirmed issue https://github.com/magento/magento2/issues/23462 which [reportedly](https://github.com/magento/magento2/issues/23462#issuecomment-507177403) was introduced in version 2.3.2.
This is a rather unpleasant issue and it has been confirmed by multiple users in comments and also elsewhere, as well:
https://magento.stackexchange.com/questions/279726/magento-2-3-category-products-indexer-takes-so-much-time-although-i-have-littl

## Possible solutions:

Please add mention of this issues to the [Known Issues](https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.html#known-issues) section of release notes.

### PR DESCRIPTION
**Pull request by korostii**
##  Purpose of this pull request

This pull request (PR) resolves https://github.com/magento/devdocs/issues/4924

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.html

Fixes #4924

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4927) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4927) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@korostii thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jfrontain** [comment]
whatsnew
Added new known issue to the Magento Open Source 2.3.2 Release Notes.

**Pull request merged**
