### PR TITLE
Improved explanation & context of setCurrentPage method.

### PR DESCRIPTION
**Pull request by erfanimani**
## Purpose of this pull request

This pull request (PR) fixes an example of the `setCurrentPage` method usage that doesn't make sense.

## Affected DevDocs pages

- https://github.com/magento/devdocs/blob/master/guides/v2.3/extension-dev-guide/searching-with-repositories.md

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4666) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4666) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
Hi @erfanimani 
Please sign the [Contributor License Agreement](https://github.com/magento/devdocs/pull/4666#issuecomment-498168597).

**Comment by dobooth** [comment]
Hi @erfanimani, seems like we should be updating the v2.2 page at the same time. Could you add it to this PR?

**Comment by erfanimani** [comment]
Thanks Donald, I've updated the PR.

**Comment by dobooth** [comment]
Thanks @erfanimani!

**Pull request merged**
