### PR TITLE
Fixed directory to match module structure

### PR DESCRIPTION
**Pull request by joeybab3**
## Purpose of this pull request

This pull request (PR) fixes a directory that does not match with the folder of the module.
The module used /Dev/Grid/ and it seems that the developer just left this one in by accident.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/admin-grid.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@joeybab3 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
