### PR TITLE
GraphQl Example of adding product to cart with customizable options

### PR DESCRIPTION
**Pull request by rogyar**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

This PR introduces adds request and response examples for adding a simple product with customizable options to the shopping cart

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/reference/quote.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
@keharper. Could you review my 2 cents when you have time, please? 
Thank you!

**Comment by keharper** [comment]
@rogyar I don't expect to merge this for another week or two. I'm in the processing of scoping the documentation impact of all PRs and issues expected to make it into the 2.3.2 release.

It would be helpful to me if you did the following:

* Provide a link to the PR that enabled this mutation (if known)
* Change the branch to `magento:develop`.  The `master` branch is for documenting published code.  `develop` is for future code.

**Comment by rogyar** [comment]
Hi @keharper. Thank you for the clarification. I'm familiar with the process. 
This functionality has been introduced and merged to the mainline a long time ago (https://github.com/magento/graphql-ce/pull/170/files#diff-795a33fde881f18aba5165a5a8c7513fR48) but never documented. So, this PR brings an example of how to add products to the shopping cart with customizable options.

Thanks

**Comment by rogyar** [comment]
Hi @keharper. I've created another PR to the develop branch with link to the codebase there 
https://github.com/magento/devdocs/pull/4316
Closing this one. Thank you

**Pull request closed without merging**
