### PR TITLE
Reference for setPaymentMethodAndPlaceOrder Mutation

### PR DESCRIPTION
**Pull request by pmclain**
Fixes magento/graphql-ce#769

## Purpose of this pull request

This PR adds reference material for the `setPaymentMethodAndPlaceOrder` mutation.

## Links to Magento source code
https://github.com/magento/magento2/blob/1cf357bf8ac263919c69f3e7709291add01ff5fd/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L21

whatsnew
Added the [setPaymentMethodAndPlaceOrder](https://devdocs.magento.com/guides/v2.3/graphql/quote-set-payment-place-order.html) mutation.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by pmclain** [comment]
@keharper Sorry, I lack permission to request reviewers.

**Comment by pmclain** [comment]
@keharper Added to TOC.

**Comment by keharper** [comment]
Thanks @pmclain

**Pull request merged**
