### PR TITLE
Asynchronous image resizing

### PR DESCRIPTION
**Pull request by o-iegorov**
## Purpose of this pull request

This pull request (PR) is describes async image resizing. Added new option for catalog:image:resize command to trigger async mode. Should be added to the 2.3.5 release. 

Internal ticket: MC-22998

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-images.html

## Links to Magento source code

TBD:
-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@o-iegorov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dshevtsov** [comment]
I assume that the Markdown linting test failed because of invalid symlink in this pull request.
The symlink has to be replaced with real `.md` file.

**Comment by dshevtsov** [comment]
Reopened in #5982

**Pull request closed without merging**
