### PR TITLE
add missing expanded option in menu widget

### PR DESCRIPTION
**Pull request by talalus**
add expanded option which display top level navigational items in mobile menu or all items.

### CODE REVIEW

**Comment by tanberry** [comment]
Thanks @talalus , we appreciate that additional info. @almarchenko can you take a look and merge when verified?

**Comment by almarchenko** [comment]
@talalus @tanberry Thank you, I will handle it.

**Comment by almarchenko** [comment]
Thank you for your input!

**Comment by talalus** [comment]
Sure :D

**Pull request merged**
