### PR TITLE
Update fastly-vcl-bypass-to-origin.md

### PR DESCRIPTION
**Pull request by michaeldyl520**
Solve a lot of graphql requests fastly return 403 error

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages
https://devdocs.magento.com/cloud/cdn/fastly-vcl-bypass-to-origin.html

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by meker12** [comment]
This contribution will require technical review and approval before adding to the documentation. In general, we don't recommend bypassing the WAF.

**Comment by meker12** [comment]
@michaeldyl520 Can you revise your PR based on the feedback provided by the technical review? Also wondering if @keharper  might have some feedback about the proposed request since he focuses on the GraphQL documentation.

**Comment by keharper** [comment]
I think I would keep this info with the cloud documentation, and place a link in the `guides/v2.3/graphql/caching.md` file to this new info.

**Comment by michaeldyl520** [comment]
@meker12 We have a site using graphql, and a 403 error occurs in normal requests. This is a suggestion sent to us by the cloud team. I think other people may encounter the same problem, so submit this PR.

**Comment by meker12** [comment]
> @meker12 We have a site using graphql, and a 403 error occurs in normal requests. This is a suggestion sent to us by the cloud team. I think other people may encounter the same problem, so submit this PR.

**Comment by meker12** [comment]
@michaeldyl520  Thanks for bringing this to our attention. Looks like we need to provide some guidance either in the DevDocs or the Magento Support Knowledge base about how to resolve the 403 errors with GraphQL requests in a secure way.

**Pull request closed without merging**
