### PR TITLE
GraphQL: Add basic B2B company queries

### LINKED ISSUE #7988: GraphQL: Add basic company queries
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28866

Magento 2 GitHub PR: https://github.com/magento/partners-magento2b2b/pull/191

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add documentation for the following B2B company queries

company
checkCompanyEmail
checkCompanyAdminEmail
checkCompanyUserEmail

### PR DESCRIPTION
**Pull request by keharper**
## Purpose of this pull request

This pull request (PR) adds support for the following B2B queries:

* company
* checkCompanyEmail
* checkCompanyAdminEmail
* checkCompanyUserEmail

Note that the link to the `company.md` include file is invalid. It is defined in #7949, which has not been merged yet.

Fixes #7988 

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

whatsnew
Added the following queries in support of B2B companies: [company](https://devdocs.magento.com/guides/v2.4), [checkCompanyEmail](https://devdocs.magento.com/guides/v2.4/graphql/queries/check-company-email.html), [checkCompanyAdminEmail](https://devdocs.magento.com/guides/v2.4/graphql/queries/check-company-admin-email.html), and [checkCompanyUserEmail](https://devdocs.magento.com/guides/v2.4/graphql/queries/check-company-user-email.html).

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @keharper. Just wanted to ask. Will we cover `checkCompanyRoleName` query within another PR? 
Thanks.

**Comment by keharper** [comment]
@rogyar Yes, it's mentioned in the description of #7986

**Comment by rogyar** [comment]
Awesome, thank you!

**Review by cpartica — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Review by dobooth — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by jeff-matthews** [comment]
@keharper, please update the whatsnew link. It's currently linking to `https://devdocs.magento.com/guides/v2.4`.

**Pull request merged**
