### PR TITLE
Use delegated mounts to improve performance

### PR DESCRIPTION
**Pull request by carlos-reynosa**
Use delegated mounts to improve performance when running composer install. Perfect consistency is not required so we can use delegate mounts to improve performance. 

* https://docs.docker.com/docker-for-mac/osxfs-caching/#tuning-with-consistent-cached-and-delegated-configurations

## Purpose of this pull request

To improve the performance of running composer install using a container on an initial project. 

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/docker/docker-config.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@carlos-reynosa thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
This is something that the Cloud team is investigating. I have to place this on hold for now.

**Comment by hguthrie** [comment]
Update: I haven't forgotten about this, but I need to see if it has to wait for a Cloud release or if it can publish directly.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
