### PR TITLE
Add Visual Studio Code on catalog generation

### PR DESCRIPTION
**Pull request by manuelcanepa**
## Purpose of this pull request

This pull request (PR) updates guide according to https://github.com/magento/magento2/pull/26296

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-urn.html

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please complete the PR description required by the template and Wiki - check other PRs for examples.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
The PR on magento/magento2 indicates this was done on the 2.4 branch and not on the 2.3

If this is correct, then these changes need to be removed from the 2.3 version of the doc file, the 2.4 document changed from a symlink to a real file and then the changes applied there.

Please confirm if this is the case or not?

**Comment by manuelcanepa** [comment]
This is correct. Its possible to change the symlink from github or i need to clone the repo?

**Comment by BarnyShergold** [comment]
I think you need to clone the repo - I always make my changes from a cloned repo as then I can run tests and also view the content locally

**Pull request closed without merging**
