### PR TITLE
Update mage-profiler.md

### PR DESCRIPTION
**Pull request by zeeshan2523806**
fix repetitive words.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@zeeshan2523806 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
@zeeshan2523806 Please sign the Adobe CLA so we can process this PR. Thanks!

**Comment by zeeshan2523806** [comment]
@dobooth i have signed the CLA as suggested in the PR.

**Pull request merged**
