### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by chandran-wagento**
Updated the spelling of instructions.

## Purpose of this pull request

This pull request (PR) Spell Correction

## Affected DevDocs pages

https://devdocs.magento.com/extensions/amazon-sales/

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4416) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4416) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@chandran-wagento thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
Hi @chandran-wagento  can you update the [PR Template](https://github.com/magento/devdocs/blob/master/.github/PULL_REQUEST_TEMPLATE.md) with all information required?

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @chandran-wagento! Welcome aboard.

**Pull request merged**
