### PR TITLE
Update adding-attributes.md

### PR DESCRIPTION
**Pull request by marcneubauer**
## This PR is a:

- [ ] New topic
- [ x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary
First half of doc rewrite, I'll follow up with second half
Fixing some grammar and flow of instructions. 
Updates tooltips.

## Additional information

List all affected URLs 

- ...
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by marcneubauer** [comment]
@jeff-matthews :
 Is something holding this up?
 is there anything I can do?

**Comment by jeff-matthews** [comment]
Hey @marcneubauer, I think I was waiting for you to make more changes since your PR description indicates as much:

> First half of doc rewrite, I'll follow up with second half

Maybe you meant you'd follow up with a separate PR? I'll start processing if this is complete. Just let me know,

**Comment by marcneubauer** [comment]
Ah, yes sorry about that. 
Before I go ahead with edits on the second half, I want to confirm that the code samples in there work, so I can only make edits to the copy, and haven't had the time yet.  
This PR has enough, to improve the article on it's own, so yes, please go ahead, and I'll make a separate PR for the other half when I can.

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
