### PR TITLE
Document Redis Sentinel settings

### PR DESCRIPTION
**Pull request by pmclain**
magento-engcom/php-7.2-support#39
magento-engcom/php-7.2-support#1

### CODE REVIEW

**Comment by vkublytskyi** [comment]
Seems this changes should be targeted to `guides/v2.3/config-guide/redis/redis-session.md` as provided information will not be correct for M2.2.

@pmclain, @buskamuza we need to discuss where to contribute docuemntation regarding changes introduced for PHP 7.2 support. Delivering it directly in `guides/v2.3/` may cause an issue if project will not be finished before 2.3.0 release.

**Comment by buskamuza** [comment]
@vkublytskyi , general rule is to deliver docs together with PRs. So I think it's ok to target 2.3 for now. But some doc PRs may be not merged because corresponding dev PRs are not merged. In this case we should be able to duplicate the doc PRs to a necessary branch later.

This specific one should be OK - the dev PR should be merged to 2.3-develop w/o waiting for all other tasks.

**Comment by jeff-matthews** [comment]
@buskamuza, it sounds like everyone agrees that this is a 2.3 change, however this PR is modifying the 2.2 version of the file. If we're targeting 2.3, we must update the 2.3 version of the file; not the 2.2 version.

@dshevtsov, please don't merge this PR until we get confirmation.

**Comment by buskamuza** [comment]
Yes. It should be 2.3.

**Comment by dshevtsov** [comment]
I created an internal ticket: MAGEDOC-2798

**Comment by dshevtsov** [comment]
@pmclain I replaced a symlink `guides/v2.3/config-guide/redis/redis-session.md` with a copy of the `guides/v2.2/config-guide/redis/redis-session.md` file.

Please update your PR to move your changes to `guides/v2.3/config-guide/redis/redis-session.md` instead of `guides/v2.2/...` (according to the above conversation).

**Comment by dshevtsov** [comment]
@buskamuza is this PR still relevant?

**Comment by dshevtsov** [comment]
I pulled the changes, moved them to 2.3, and published in a separate commit.

**Pull request closed without merging**
