### PR TITLE
Content fixed

### PR DESCRIPTION
**Pull request by marcinsdance**
## This PR is a:

- [ ] Content fix or rewrite

## Summary

When this pull request is merged, it will...

Change:
This topic describes the general concepts of how to work with JavaScript components is organized in Magento.

to

This topic describes the general concepts of how JavaScript components are organized in Magento.

## Additional information

List all affected URL's 

https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js-resources.html

https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js-resources.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3016) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3016) before we can accept your contribution.<br/><hr/>**Marcin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
@marcinsdance thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by shrielenee** [comment]
Thanks @marcinsdance!

**Comment by shrielenee** [comment]
Please sign the CLA as shown above.

**Comment by marcinsdance** [comment]
Thanks @shrielenee , that's signed now!

**Pull request merged**
