### PR TITLE
Described missed prompt widget options and added code samples of prompt widget initialization

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) describes missed options of the prompt widget and also it adds the code samples of the prompt widget initialization.
The PR is an adjusted copy of https://github.com/magento/devdocs/pull/4736 PR.
I've created it on purpose to not to increase repo size too much.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_prompt.html
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_prompt.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/templates/modal/modal-prompt-content.html
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Ui/view/base/web/templates/modal/modal-prompt-content.html
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Ui/view/base/web/js/modal/prompt.js
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/modal/prompt.js
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/set/main.phtml#L283
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/set/main.phtml#L282

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
> Please, do not capitalize the "Admin" word. In this case, we don't describe a product name or a personal name. Thank you.
> https://github.com/magento/devdocs/pull/4782/files#diff-4671b33861390321846f924cf04f205eR15

Nevermind. I've just noticed that this change is from the previous version. Thank you

**Comment by dobooth** [comment]
running tests

**Comment by meker12** [comment]
@dobooth Please add the whatsnew info to the PR description. Thx.

**Pull request merged**
