### PR TITLE
Changing duplicate "Magento Commerce"

### PR DESCRIPTION
**Pull request by MellenIO**
under "Set up RabbitMQ" section

## Purpose of this pull request

This pull request (PR) removes the duplicate "Magento Commerce" present on the 2.3x page of Advanced Setup. Since 2.3.0 Magento Open Source supports it, so assuming one of the variables meant to be **ce** rather than **ee**.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-setup.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@MellenIO thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Good eye, @MellenIO. Can you please sign the new Adobe CLA? Then we can get this in. Thanks.

**Comment by MellenIO** [comment]
@dobooth should be signed now. Need me to close & re-open this PR?

**Pull request merged**
