### PR TITLE
Updated Consumer Runner class

### PR DESCRIPTION
**Pull request by rev42**
The class has been changed on Magento 2.1

### CODE REVIEW

**Comment by keharper** [comment]
Thanks!

**Comment by hostep** [comment]
@rev42: if this class was changed in version 2.1, why was the 2.0 version of the documentation updated? You should update version 2.1 of the docs, if a version 2.1 of this particular page doesn't exist yet, copy 2.0 to 2.1 and modify the new file.

(Sorry if what I'm saying is incorrect, I have no way of verifying this, since I don't have access to the EE sourcecode.)

**Comment by keharper** [comment]
@hostep  I didn't notice that. I'll break the symlink between the 2 versions and make sure that only the 2.1 version contains this info.

**Comment by rev42** [comment]
@hostep Good point. My intent was indeed to update 2.1 docs but I didn't notice I was on 2.0 docs.
Nevertheless I just checked Magento 2.0.x EE source code and the class ConsumerRunner was already into Magento\MessageQueue\Model namespace.
So I guess we're safe.

/cc @keharper

**Pull request merged**
