### PR TITLE
Added response for graphql query

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - I am interested to add response for example query in this topic.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/product/customizable-option-interface.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by nuzil** [comment]
Hi @chandru-199 
can you please sync your branch for eliminate conflict? Thanks

**Comment by chandru-199** [comment]
@nuzil Done. Thanks.

**Comment by keharper** [comment]
running tests

**Pull request merged**
