### PR TITLE
Added new step for custom shipping address renderer page

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Added new step for custom shipping address renderer page

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_address.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by chandru-199** [comment]
Thanks @dobooth.

**Comment by rogyar** [comment]
Hi @chandru-199. My message will be the same as [here](https://github.com/magento/devdocs/pull/6498). I believe it's better to put this information somewhere in the topic introduction ([here](https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_overview.html) for example) instead of copying it over to all documents.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
