### PR TITLE
Checkout new field

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this PR

This PR updates content of "Add a new field in address form" page and replaces `var/generation` with `var/generated/code`. 

## Affected URLs

- https://devdocs.magento.com/guides/v2.2/howdoi/checkout/checkout_new_field.html
- https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_new_field.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
According to the [codebase](https://github.com/magento/magento2/blob/2.2/lib/internal/Magento/Framework/App/Filesystem/DirectoryList.php#L164) the provided change is correct.

**Comment by atwixfirster** [comment]
Hello, @erikmarr !

> Because you are replacing the v2.2.x symlink with an actual topic, please recreate the v2.3.x symlink to this new v2.2.x topic.

I've already did that.

In my first commit, I've [removed](https://github.com/magento/devdocs/pull/4372/commits/42e2e02b7d214cc7fe0adc724699cfae7d06d37f) both symlinks:
- guides/v2.2/howdoi/checkout/checkout_new_field.md
- guides/v2.3/howdoi/checkout/checkout_new_field.md 

In the [second one](https://github.com/magento/devdocs/pull/4372/commits/95bfff5048fc5f408620426a45f8fd6f0154dc64) I've added content to `guides/v2.2/howdoi/checkout/checkout_new_field.md` and created a symlink to it for `guides/v2.3/howdoi/checkout/checkout_new_field.md`.

Thank you!

**Comment by erikmarr** [comment]
Thanks @atwixfirster I clearly miss that!

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @atwixfirster!

**Pull request merged**
