### PR TITLE
Removed unnecessary comma (,) from the page 

### PR DESCRIPTION
**Pull request by shikhamis11**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix the issue of unnecessary comma added in the page.

**Additional information**

List all affected URLs

https://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3563) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3563) before we can accept your contribution.<br/>

**Comment by nuzil** [comment]
I would say it’s the next part of the same sentence, and coma is ok.

**Comment by shikhamis11** [comment]
Okay . But it is not looking correct there as it is not there in v2.1 concept
https://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.html

**Comment by osrecio** [comment]
Hi @shikhamis11 you should edit: https://github.com/magento/devdocs/blob/master/guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.md instead of 2.2 revision.

Please update your template of PR to add affected page. Please check: https://github.com/magento/devdocs/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Thanks!

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
Thanks for this small but important revision @shikhamis11 and thanks for reviewing @osrecio! 🏆

**Pull request merged**
