### PR TITLE
Update technical-details.md

### PR DESCRIPTION
**Pull request by maniprakash**
wrong directory path corrected.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by dobooth** [comment]
Hi @maniprakash Can you please sign the Adobe CLA so we can process your PR? Thanks.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please -
Fill in the PR description as required. A good example - 

- https://github.com/magento/devdocs/pull/8599
- Make the same change to the 2.4 version of the file (okay to include on this PR) as it is a different file and not a SymLink
- Sign Adobe CLA

**Comment by BarnyShergold** [comment]
@maniprakash - We cannot proceed with this PR until you have updated it and signed the CLA.

**Comment by BarnyShergold** [comment]
PR is classed as abandoned but is being fixed on #8717

**Pull request closed without merging**
