### PR TITLE
Dockerfile > Updating MAINTAINER declaration

### PR DESCRIPTION
**Pull request by rafaelstz**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

The purpose of instantiating `labels` is different, is to automatize and use the params, instead of that, we can use the default **MAINTAINER** tag.

Reference: [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#label)

### CODE REVIEW

**Comment by jeff-matthews** [comment]
I think we can remove this file; we no longer use it. @dshevtsov, can you take care of this please?

**Comment by dshevtsov** [comment]
@jcalcaben owns the DevDocs Docker project.
@jcalcaben what do you think?

**Comment by jcalcaben** [comment]
Yes, let's remove it.

**Comment by jeff-matthews** [comment]
This isn't for the devdocs docker project. This is for that failed CICD process we were working on with devops.

**Pull request merged**
