### PR TITLE
Add info about backward incompatible changes in 2.1.17 release

### PR DESCRIPTION
**Pull request by magento-cicd2**
The changes are generated automatically and require review and processing before publication.

whatsnew
Added information about backward incompatible changes in 2.1.17 release for [Open Source](https://devdocs.magento.com/guides/v2.1/release-notes/backward-incompatible-changes/open-source.html#releases-2_1_16-2_1_17) and [Commerce](https://devdocs.magento.com/guides/v2.1/release-notes/backward-incompatible-changes/commerce.html#releases-2_1_16-2_1_17).

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4044) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4044) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dshevtsov** [comment]
There is a new file `_includes/backward-incompatible-changes/open-source/2.1.16-2.1.17.md`
The file is included into a new section in `guides/v2.1/release-notes/backward-incompatible-changes/open-source.md`

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
