### PR TITLE
Finalize the style for Markdown linting

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) finalizes the style that is checked by the embedded Markdown linter.

### CODE REVIEW

**Comment by dshevtsov** [comment]
@hguthrie could please give an example?

**Comment by dshevtsov** [comment]
running tests

**Comment by hguthrie** [comment]
```
guides/v2.2/cloud/docker/docker-config.md:5: MD032 Lists should be surrounded by blank lines
guides/v2.2/cloud/docker/docker-config.md:6: MD032 Lists should be surrounded by blank lines
guides/v2.2/cloud/docker/docker-config.md:8: MD032 Lists should be surrounded by blank lines
guides/v2.2/cloud/docker/docker-config.md:10: MD032 Lists should be surrounded by blank lines
```

**Comment by dshevtsov** [comment]
I see, so the issue is that the linter checks the front matter.

**Comment by dshevtsov** [comment]
@hguthrie I enabled the `ignore_front_matter` flag. Should be fine now. Thank you!

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
