### PR TITLE
Update getting-started.md (2.2)

### PR DESCRIPTION
**Pull request by dewimagento**
typofix - this is a path, not a password.

## This PR is a:

- [ ] Content fix or rewrite

## Summary

When this pull request is merged, it will...

Change 'ss' to 'th' and fix up surrounding grammar. Line describes path, not password.

## Additional information

List all affected URLs 
- https://devdocs.magento.com/mftf/2.2/getting-started.html

2.3 version will be separate PR because I can't github.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3384) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3384) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@dewimagento thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
run tests

**Pull request merged**
