### PR TITLE
Added headers for the customer resource api

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will...
Reference URLs:
https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/app/code/Magento/Quote/etc/webapi.xml#L139

https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/app/code/Magento/Quote/etc/webapi.xml#L234

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/b2b/negotiable-order-workflow.html
- https://devdocs.magento.com/guides/v2.2/b2b/negotiable-update.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @ronak2ram!

**Pull request merged**
