### PR TITLE
Updated option descriptions for CLI command to start message consumers

### PR DESCRIPTION
**Pull request by meker12**
# Purpose of this pull request

This pull request (PR) updates information regarding the CLI command `queue:consumers:start`
After fixing these bugs https://jira.corp.magento.com/browse/MC-18834 and https://jira.corp.magento.com/browse/MC-18477, the option `--pid-file-path` was marked as deprecated and the new option `--single-thread` was added.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html
- https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-queue.html

## Links to Magento source code

- ...

whatsnew
Updated the  option descriptions for the `queue:consumers:start`Magento CLI command:
- Removed the `--pid-file-path` option which was deprecated in version 2.3.3 and 2.2.10.
- Added the `--single-thread` option which prevents running multiple copies of a consumer simultaneously

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5256) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5256) before we can accept your contribution.<br/>**4** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: erikmarr<br/>:white_check_mark: jfrontain<br/>:white_check_mark: keharper<br/>:white_check_mark: dshevtsov<br/>:x: Jeanne Frontain<br/>:x: ImgBotApp<hr/>**Jeanne Frontain** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by dshevtsov** [comment]
@meker12 seems like you created the branch from `master` but you want to merge it into `develop`.

**Comment by meker12** [comment]
> @meker12 seems like you created the branch from `master` but you want to merge it into `develop`.

Yes. I realized that.  Created a new one: https://github.com/magento/devdocs/pull/5257

**Comment by dshevtsov** [comment]
@meker12 remove the links to internal resources with restricted access (Jira) from the pull request description.

**Pull request closed without merging**
