### PR TITLE
Fixing jslint errors

### PR DESCRIPTION
**Pull request by bdenham**
## Purpose of this pull request

This pull request (PR) fixes [jslinting errors](https://github.com/magento/devdocs/runs/1518728314) from the superlinter.

### CODE REVIEW

**Comment by dshevtsov** [comment]
@belbiy please review and approve the changes

**Comment by dobooth** [comment]
@belbiy

**Review by belbiy — APPROVED** [review]
The executable JS that's part of the site looks good. Dont know anything about the `samples/` though...

**Review by dshevtsov — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
