### PR TITLE
Update on beta conditions - allowing customers to join beta program

### PR DESCRIPTION
**Pull request by sgonzalezmangana**
We are allowing customers to participate in beta program, the only limitation, for now, is that they won't have access to our private repo and won't be able to share their feedback. 
I've made some suggestions on how to update the page accordingly.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@sgonzalezmangana thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by BarnyShergold** [comment]
This PR makes no sense as to why it has been opened, so it is being closed.

**Comment by sgonzalezmangana** [comment]
Hi @BarnyShergold this PR needs to be merged as part of changes we are doing on Beta program. Feel free to reach out to me directly if you have any question

**Comment by BarnyShergold** [comment]
Okay I'll take your word for it :)

**Comment by jeff-matthews** [comment]
@dobooth, please process by the end of this week.

@sgonzalezmangana, you must sign the Adobe CLA in order for us to proceed.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
