### PR TITLE
Updated interface link in document

### PR DESCRIPTION
**Pull request by gelanivishal**
## This PR is a:

- [ ] New topic
- [X] Content update
- [X] Content fix or rewrite
- [X] Bug fix or improvement

## Summary
Updated interface link on Magento document.
When this pull request is merged, it will...

## Additional information

List all affected URLs 
- https://devdocs.magento.com/guides/v2.3/config-guide/config/config-create.html
- https://devdocs.magento.com/guides/v2.2/config-guide/config/config-create.html
- https://devdocs.magento.com/guides/v2.1/config-guide/config/config-create.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by gelanivishal** [comment]
@jeff-matthews I have updated changes as requested.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
@gelanivishal, how did you remove the symlinks between 2.1 --> 2.2 and 2.2 --> 2.3? The build server is throwing the following errors when attempting to clone the repo, which indicates a problem with symlinked files:

```
stderr: error: unable to create symlink guides/v2.2/config-guide/config/config-create.md: File name too long
error: unable to create symlink guides/v2.3/config-guide/config/config-create.md: File name too long
```

**Comment by gelanivishal** [comment]
@jeff-matthews I haven't idea about it so I have copied 2.1 content to 2.2 file and replace appropriate things same thing I have done for 2.3 file.

**Comment by jeff-matthews** [comment]
@gelanivishal, you must actually remove/delete symlinks and create new files.

For example:

> rm guides/v2.2/config-guide/config/config-create.md && cp guides/v2.1/config-guide/config/config-create.md guides/v2.2/config-guide/config/config-create.md
> rm guides/v2.3/config-guide/config/config-create.md && cp guides/v2.1/config-guide/config/config-create.md guides/v2.3/config-guide/config/config-create.md

Then, you must

**Comment by gelanivishal** [comment]
@jeff-matthews I have performed your above steps and created a new PR. Check https://github.com/magento/devdocs/pull/3449

**Pull request closed without merging**
