### PR TITLE
Improved the JS Mixins documentation

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) improves the JS mixins documentation.

Improvements:
- Improved the example in _Extend JS Object_ section
- Added the _Extend JS Function_ section

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js_mixins.html
-  https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/js_mixins.html

## Links to Magento source code

-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/CheckoutAgreements/view/frontend/web/js/model/place-order-mixin.js
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/CheckoutAgreements/view/frontend/web/js/model/place-order-mixin.js

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Example from the codebase of the original `setHash` method (overridden in the mixin) 

https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/code/Magento/Checkout/view/frontend/web/js/model/step-navigator.js#L190

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
