### PR TITLE
change container name attribute required value - fix issue #3168

### PR DESCRIPTION
**Pull request by Karlasa**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary
fix for issue #3168
When this pull request is merged, it will...
change container name attribute requirement from Yes to No

## Additional information

List all affected URLs 

- ...
- ...

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@Karlasa, have you verified that `name` is not required for 2.2 or are you just trying to make the 2.2 file match the 2.1 file?

https://github.com/magento/devdocs/blob/master/guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md

**Comment by Karlasa** [comment]
@jeff-matthews  i think it changed from required to not required in the same update as block name one 
Notification text in top of block attributes 

> The class attribute is no longer required in versions 2.2.1 and above as it will default to Magento\Framework\View\Element\Template. In versions lower than 2.2.1, the class attribute is still required.

Also tested and it works well without name

**Comment by jeff-matthews** [comment]
Thanks for confirming @Karlasa.

@osrecio or @mhauri, if either of you can please verify, I'll merge this PR.

**Comment by Karlasa** [comment]
@mhauri  Based on the framework:View/Layout/etc/page_configuration.xsd schema it also says the same about **block** and yet it's optional. It's not about having it set or not it's about defining it. If you don't define it it will be still exist but it will be random name. 

Of course it's best practice to have it, but still it's not required ;)

**Comment by lorikrell** [comment]
Definitely worth adding a note. @Karlasa I can help with the note if you like!

**Comment by lorikrell** [comment]
Adding the note in another PR, will link it to this one. Thanks!

**Pull request merged**
