### PR TITLE
magento/devdocs#: Describe customerDownloadableProducts query errors

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) adds some info about https://github.com/magento/graphql-ce/issues/1004

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/graphql/queries/customer-downloadable-products.html

## Links to Magento source code

- [The current customer isn\'t authorized.](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/CustomerDownloadableGraphQl/Model/Resolver/CustomerDownloadableProducts.php#L59)

CC: @keharper

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Thanks @atwixfirster

**Comment by dobooth** [comment]
Removed small-changes since this goes to `develop`.

**Comment by keharper** [comment]
@atwixfirster Can this PR be rebased to `develop`?

**Comment by atwixfirster** [comment]
> @atwixfirster Can this PR be rebased to `develop`?

It's already rebased, sir :)

**Comment by keharper** [comment]
running tests

**Pull request merged**
