### PR TITLE
Fix class namespace

### PR DESCRIPTION
**Pull request by vasadibt**
## Purpose of this pull request

Fix DevDocs

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/howdoi/customize-modifier-class.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@vasadibt thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by nuzil** [comment]
@vasadibt can you please sign CLA?

**Comment by dobooth** [comment]
Hi @vasadibt Thanks for making this contribution! If you can please sign the Adobe CLI below, we can get this merged.

**Comment by dobooth** [comment]
Abandones. Please sign the CLA for future PRs.

**Pull request closed without merging**
