### PR TITLE
#7496: Feedback on page: /guides/v2.4/extension-dev-guide/routing.html

### PR DESCRIPTION
**Pull request by brucemead**
- Resolving incorrect URL references to source code

## Purpose of this pull request

This pull request is to resolve incorrect links to source code relating to issue https://github.com/magento/devdocs/issues/7496

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.4/extension-dev-guide/routing.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dshevtsov** [comment]
[2.4-develop](https://github.com/magento/magento2) is a development branch for future patch 2.4.1 already, not 2.4.0.
The devdocs 2.4 documentation covers only incoming 2.4.0 release. The source code for incoming 2.4.0 release is not subject for contributions on pre-release stages and therefore not public.

**Comment by brucemead** [comment]
@dshevtsov so these 404's will be resolved once you tag/release `2.4`?

**Comment by dshevtsov** [comment]
They will be resolved only after 2.4.0 is released.

**Pull request closed without merging**
