### PR TITLE
Remove note as 2.3 is officially released

### PR DESCRIPTION
**Pull request by Zifius**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Remove the note which no longer makes sense

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@Zifius thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3894) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3894) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Checked with Kevin. Ok to remove.

**Comment by dobooth** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks, @Zifius

**Pull request merged**
