### PR TITLE
remove dead link pictos.cc from both references I found

### PR DESCRIPTION
**Pull request by operator888**
## Purpose of this pull request

This PR removes 2 deadlinks from the references. domain name is not registered any more.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.2/pattern-library/graphics/iconography/iconography.html#creating-icons

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@operator888 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @operator888. Thanks for the contribution. A couple things: 1) We are no longer accepting PRs for v2.1 or v2.2 files. 2) I removed that broken link in the v2.3 files a few weeks ago. There's not more to be done here. Still appreciate the effort and still sign the Adobe CLA below so future PRs can get in easily.

**Pull request closed without merging**
