### PR TITLE
ACMP-971: C&O | Document the developer extension guideline for AWS Aurora compatibility

### PR DESCRIPTION
**Pull request by oshmyheliuk**
## Purpose of this pull request

This pull request (PR) will add recommendation of usage InnoDB storage engine and having Primary Key on each table

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/ext-best-practices/extension-coding/security-performance-data-bp.html

### CODE REVIEW

**Comment by hguthrie** [comment]
@oshmyheliuk @bdenham  Is this only for 2.4? The 2.3 version of the topic was updated, but if it is only for 2.4, then we will have to break the symlink and create the topic for 2.4.

**Review by hguthrie — APPROVED** [review]
Per Bruce, it's fine for 2.3. Ship it!

**Comment by bdenham** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@bdenham the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8998`.

**Pull request merged**
