### PR TITLE
Update /inventory/create-customer.md

### PR DESCRIPTION
**Pull request by ygyryn**
## Purpose of this pull request
This pull request (PR) add links to appropriate steps, adjust text in links according to steps titles.

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/rest/tutorials/inventory/create-customer.html

## Links to Magento source code
https://github.com/magento/devdocs/blob/master/guides/v2.3/rest/tutorials/inventory/create-customer.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @ygyryn

**Pull request merged**
