### PR TITLE
Hide "CSS Critical Path" mentioned in documentation pages as it is not port of stable Magento version yet (nor 2.2 or 2.3)

### PR DESCRIPTION
**Pull request by vasilii-b**
## Purpose of this pull request

Hide "CSS Critical Path" page from documentation and mentions in other pages as this feature is only present in **2.3-develop** branch:
2.3-develop

#### Magento 2.3

- **Remove "CSS Critical Path" page. from the v2.2 documentation**
This feature is not available in 2.2 version.
- **Move "CSS Critical Path" page to v2.3 of documentation**

**Note:** Original PR https://github.com/magento/devdocs/pull/4726 was merged to `master` when he had to be merged to `develop`, most probably. Also, it was not pointing to the Magento source code.

This is confusing for Front-End developers, as they are provided a feature that can't be used actually.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.html
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-critical-path.html
- https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/css-overview.html
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-overview.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml

### CODE REVIEW

**Comment by rogyar** [comment]
I can confirm that the mentioned functionality is not present in the latest release yet. We do have the same documentation in the develop branch so it won't be missing. 
However, I'm not sure how we should handle such cases when we need to re-add some info from develop branch after a new release once it has been removed from master branch @keharper 
Thank you

**Comment by vasilii-b** [comment]
Hi @rogyar ,
I wasn't sure how we should proceed here:

> Do we still need the following file `guides/v2.3/frontend-dev-guide/css-topics/css-critical-path.md` ?
> I believe it should be removed as well. Even if we don't have links to this topic, it might be still indexable by search crawlers.

But after it's confirmed that changes are present in the `develop` branch we can remove the file at all. Totally agree here.

Thank you!

**Comment by bdenham** [comment]
running tests

**Comment by keharper** [comment]
@rogyar @vasilii-b  I'm just now seeing this PR. Since the PR affects the Frontend Development Guide, I probably ignored the thread.

Since the contributor of #4726 is an Adobe employee, I think the functionality being documented will be in the 2.3.4 release. I think the content that was removed in this PR should be added back, but in the `Q4-integration` branch.

**Comment by hostep** [comment]
@keharper: the functionality is definitely part of Magento 2.3.3
Screenshot 2019-10-04 at 22 46 46

So this content should be restored in `master` in a few days when 2.3.3 is opened to the public.

**Comment by keharper** [comment]
Thanks for confirming, @hostep.

If at all possible, the info should be restored to the `develop` branch before it gets merged to `master` for 2.3.3 on Tuesday morning (Austin time). That's a very short turnaround time, and might not be realistic.

I became aware of this PR because @jfrontain asked me about the deleted file, which was to be referenced in the release notes. It'd be nice to include the reference without having to update the release notes later on.

**Comment by keharper** [comment]
I created the PR myself. https://github.com/magento/devdocs/pull/5586

**Pull request merged**
