### PR TITLE
MERGE IN 2.3.2: Fixed grammar

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix grammar.

## Additional information

Codebase:
1. https://github.com/magento/magento2/blob/75cf82651deefef6c38b052ce40e771475607d7c/app/code/Magento/Backend/etc/adminhtml/system.xml#L115
2. https://github.com/magento/magento2/blob/75cf82651deefef6c38b052ce40e771475607d7c/app/code/Magento/Backend/etc/adminhtml/system.xml#L119

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-most.html
- https://devdocs.magento.com/guides/v2.2/config-guide/prod/config-reference-most.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
The field label changes were made in this PR: https://github.com/magento/magento2/pull/21431

We can't work on it now, because the changes were merged for 2.3.2.

**Comment by erikmarr** [comment]
The screenshot in this topic will also need to be updated:
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/debug-theme.html

[Internal note] We'll need to update merchant docs as well:
https://docs.magento.com/m2/ce/user_guide/system/template-path-hints.html
https://docs.magento.com/m2/ce/user_guide/configuration/advanced/developer.html

**Comment by keharper** [comment]
running tests

**Pull request merged**
