### PR TITLE
Default breakpoint file path added

### PR DESCRIPTION
**Pull request by rajesh-mage**
## Purpose of this pull request

This pull request (PR) Default break-point file path added on RWD topic

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/responsive-web-design/rwd_css.html

## Links to Magento source code

https://github.com/magento/magento2/blob/2.4-develop/lib/web/css/source/lib/variables/_responsive.less

### CODE REVIEW

**Comment by rajesh-mage** [comment]
Hi @BarnyShergold @dobooth,
> Have you missed adding a link to the file indicated in the PR description?

I do not get what you are saying. This PR is created and related to the following PR. Because my last changes are not merged on that PR.
https://github.com/magento/devdocs/pull/8917

The line 31 we have a sentence with : at the end and without any logical conclusion : 
That's why this PR created. In this PR I'm moving lines 33 and 34 to 40 and 41.

**Comment by BarnyShergold** [comment]
> Hi @BarnyShergold @dobooth,
> 
> > Have you missed adding a link to the file indicated in the PR description?
> 
> I do not get what you are saying. This PR is created and related to the following PR. Because my last changes are not merged on that PR.
> #8917
> 
> The line 31 we have a sentence with : at the end and without any logical conclusion :
> That's why this PR created. In this PR I'm moving lines 33 and 34 to 40 and 41.

You did not link this PR to the other PR for reference. You need to do this going forward please. But i will pass this PR

**Review by BarnyShergold — APPROVED** [review]

**Comment by rajesh-mage** [comment]
> > Hi @BarnyShergold @dobooth,
> > > Have you missed adding a link to the file indicated in the PR description?
> > 
> > 
> > I do not get what you are saying. This PR is created and related to the following PR. Because my last changes are not merged on that PR.
> > #8917
> > The line 31 we have a sentence with : at the end and without any logical conclusion :
> > That's why this PR created. In this PR I'm moving lines 33 and 34 to 40 and 41.
> 
> You did not link this PR to the other PR for reference. You need to do this going forward please. But i will pass this PR

@BarnyShergold Sure I will do that. 

Thanks.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8932`.

**Pull request merged**
