### PR TITLE
adding in EOS date

### PR DESCRIPTION
**Pull request by misuadobe**
## Purpose of this pull request

This pull request (PR) is to add a specific date to the EOS table.

## Affected DevDocs pages

https://devdocs.magento.com/release/lifecycle-policy.html

whatsnew
Updated the [end of support date](https://devdocs.magento.com/release/lifecycle-policy.html) for 2.4.0-2.4.3.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
Hi @misuadobe,

Thanks for the contribution. Please provide a brief explanation of your change in the PR description. We provide a template to get you started. We require all PRs to have a basic description.

Thanks!

**Comment by misuadobe** [comment]
Done!

**Comment by jeff-matthews** [comment]
Thanks @misuadobe!

**Comment by jeff-matthews** [comment]
@magento import code to magento-devdocs/devdocs

**Review by jeff-matthews — APPROVED** [review]

**Comment by m2-github-services** [comment]
@jeff-matthews the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-misuadobe-devdocs-9416`.

**Pull request merged**
