### PR TITLE
Adding additional step in custom payment method

### PR DESCRIPTION
**Pull request by VinothKumar361**
## Purpose of this pull request

Adding additional step in custom payment method

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_payment.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by VinothKumar361** [comment]
@dobooth - thanks, changes for v2.3 have been added.

**Comment by dobooth** [comment]
Thanks @VinothKumar361 I appreciate it. This PR currently has 22 files changed. Is that what you meant? Looks like a branch needs to be synced...

**Comment by keharper** [comment]
It's probably better to close this PR and start over. Currently, this PR does not include changes in the `checkout_payment.md` file. Instead, it affects multiple GraphQL files, which should not be a part of this PR.

**Pull request closed without merging**
