### PR TITLE
Custom Config Files Require Full or Relative Paths

### PR DESCRIPTION
**Pull request by carlos-reynosa**
When defining custom config files within a custom Migration Module used to extend the migration tool, it is not enough to just remove the '.dist' extension. You must provide a full path or path relative to the Magento install directory. 

- Issue: magento/data-migration-tool/issues/757 
-  File: https://github.com/magento/data-migration-tool/commit/e80bddf8c00d1ef946745acb89b5fe3538ca4eb9

## Purpose of this pull request

To provide further clarification on what value to provide within a custom module for a custom configuration file. It seems that some type of fallback mechanism is not used to load custom configuration files. 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html

## Links to Magento source code

-  https://github.com/magento/data-migration-tool/commit/e80bddf8c00d1ef946745acb89b5fe3538ca4eb9

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Nicely done PR. Good work on a proper description. Thanks!

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
Sorry, tried to merge too quickly.

**Comment by victor-v-rad** [comment]
Thank you @carlos-reynosa for your contribution!

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
