### PR TITLE
Update tech-vision.md

### PR DESCRIPTION
**Pull request by SoulAdor**
Remove unnecessary full stop

## Purpose of this pull request

Small grammar fix

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/architecture/archi_perspectives/tech-vision.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@SoulAdor thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
Good eye, @SoulAdor. Please sign the Adobe CLA and we can then process this PR. Thanks for contributing.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
