### PR TITLE
Add SOA section

### PR DESCRIPTION
**Pull request by melnikovi**
## This PR is a:

- Content update

## Summary

Added section that describes recommended approach for implementing new features.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.0/coding-standards/technical-guidelines.html
- https://devdocs.magento.com/guides/v2.1/coding-standards/technical-guidelines.html
- https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html
- https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4211) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4211) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
@melnikovi Any update on this PR?

**Comment by melnikovi** [comment]
Resolved conflicts.

**Comment by dobooth** [comment]
Hi @melnikovi We recently ended support for v2.1, so we can't take any PRs that edit that version. Can you please pull/merge and remove the 2.1 file from this PR? Thanks!

**Pull request merged**
