### PR TITLE
Correct a typo

### PR DESCRIPTION
**Pull request by hanhpv**
## Purpose of this pull request

Fixes a small typo in https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5116) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5116) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@hanhpv thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hello @hanhpv can you sign the CLA?

Even though I haven't signed the CLA and it doesn't have content in the PR template, I think the change is so small that we should handle it internally.

**Comment by hanhpv** [comment]
Just signed the CLA

**Pull request merged**
