### PR TITLE
Added new nfinset search condition

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will show **nfinset** condition for the search.
Reference Pulls:
https://github.com/magento/magento2/pull/20607
https://github.com/magento/magento2/pull/21123

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/rest/performing-searches.html
- https://devdocs.magento.com/guides/v2.3/rest/performing-searches.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Thanks @ronak2ram! We don't often receive doc contributions that accompany code contributions, but when we do, we're very grateful.

**Comment by ronak2ram** [comment]
It's my pleasure @jeff-matthews

**Comment by keharper** [comment]
Thanks for the code contribution and doc update, @ronak2ram and Krish TechnoLabs!

**Pull request merged**
