### PR TITLE
Update site-wide-analysis.md

### PR DESCRIPTION
**Pull request by hellotaran**
Fixed broken URL

## Purpose of this pull request

This pull request (PR) is to fix a broken link on https://devdocs.magento.com/tools/site-wide-analysis.html URL.

## Affected DevDocs pages

-  https://devdocs.magento.com/tools/site-wide-analysis.html

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-hellotaran-devdocs-9359`.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
