### PR TITLE
Fixing Mutagen typo

### PR DESCRIPTION
**Pull request by rafaelstz**
## Purpose of this pull request

This pull request (PR) fixes the Mutagen typo. All the time it's mentioned in other pages Mutagen with uppercase later has been used instead of lowercase.

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/docker/docker-development.html

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
You also need to update the reference in  for consistency

**Review by rafaelstz — COMMENTED** [review]
@BarnyShergold  Mutagen reference updated, thank you for reviewing it!

**Review by BarnyShergold — APPROVED** [review]
Excellent!

**Review by hguthrie — APPROVED** [review]

**Comment by hguthrie** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@hguthrie the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-rafaelstz-devdocs-9453`.

**Pull request merged**
