### PR TITLE
MAGEDOC-3277: Fix redirects

### PR DESCRIPTION
**Pull request by jeff-matthews**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix redirects in the UI Components Guide. 

To test, go to https://devdocs.magento.com/guides/v2.0/ui-components/ui-component.html and use the version switcher to jump to 2.3. After this PR is merged, the file should redirect instead of throwing a 404.

### CODE REVIEW

**Comment by bdenham** [comment]
Jumping from version 2.0 directly to 2.3 still gives me a 404.

**Comment by jeff-matthews** [comment]
You won't be able to test until the PR is merged @bdenham.

**Comment by bdenham** [comment]
Hah! Duh. I'm obviously not all here yet this morning.

**Comment by jeff-matthews** [comment]
No, the original PR description was misleading. I updated it.

**Comment by jeff-matthews** [comment]
run tests

**Pull request merged**
