### PR TITLE
Updated composer_lock data after 2.3.4 release

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) updates data that are used to generate content about Magento packages (dependencies) and PHP requirements.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@dshevtsov, is this a duplicate of #6486?

**Comment by dshevtsov** [comment]
@jeff-matthews I didn't know about that PR. The purpose is the same but I cannot verify since I didn't create it.

**Comment by jeff-matthews** [comment]
Ok thanks @dshevtsov. 

@dobooth, please confirm whether we can close this as a duplicate.

**Comment by dshevtsov** [comment]
I don't think that we have to close it since it shows a big number of differences.

**Comment by jeff-matthews** [comment]
Good point. It would be helpful to understand why.

**Comment by dshevtsov** [comment]
I checked just one file in #6486
The `content hash` does not correspond to the [one tagged by 2.3.4 for Open Source](https://github.com/magento/magento2/blob/2.3.4/composer.lock#L7)

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
> Good point. It would be helpful to understand why.

The updates were done before the actual release, that's why the substituted files were different.

**Pull request merged**
