### PR TITLE
For Modal widget, Add Language Translate Method

### PR DESCRIPTION
**Pull request by hardikm-cirkleinc**
For Modal widget, Add __('<your_string>') method in Example because this method is used for translation of the string into another Languages.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_modal.html
https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_modal.html

## Links to Magento source code

-https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/modal/modal.js#L80
-https://github.com/magento/magento2/blob/2.2/app/code/Magento/Ui/view/base/web/js/modal/modal.js#L80

### CODE REVIEW

**Comment by hardikm-cirkleinc** [comment]
Thanks

**Comment by hardikm-cirkleinc** [comment]
Sorry. By Mistake, I have closed this ticket yesterday.

**Comment by hardikm-cirkleinc** [comment]
Hello, Please Pull the Request

**Comment by jcalcaben** [comment]
running tests

**Pull request merged**
