### PR TITLE
Clarify EAV Attribute Options 

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request

To clarify some of the EAV attribute options as per issue #7739 

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html (covers 2.4)
-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by aleron75 — APPROVED** [review]
well done!

**Comment by BarnyShergold** [comment]
@aleron75 - Thanks!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
