### PR TITLE
Fix module name (case)

### PR DESCRIPTION
**Pull request by real34**
## Purpose of this PR

This PR fixes the module name to prevent the `Unknown module(s): 'Magento_InventoryElasticSearch'` error below when disabling modules on 2.3.1:

```sh
bin/magento module:disable  Magento_Inventory Magento_InventoryAdminUi Magento_InventoryApi Magento_InventoryBundleProduct Magento_InventoryBundleProductAdminUi Magento_InventoryCatalog Magento_InventorySales Magento_InventoryCatalogAdminUi Magento_InventoryCatalogApi Magento_InventoryCatalogSearch Magento_InventoryConfigurableProduct Magento_InventoryConfigurableProductAdminUi Magento_InventoryConfigurableProductIndexer Magento_InventoryConfiguration Magento_InventoryConfigurationApi Magento_InventoryGroupedProduct Magento_InventoryGroupedProductAdminUi Magento_InventoryGroupedProductIndexer Magento_InventoryImportExport Magento_InventoryIndexer Magento_InventoryLowQuantityNotification Magento_InventoryLowQuantityNotificationAdminUi Magento_InventoryLowQuantityNotificationApi Magento_InventoryMultiDimensionalIndexerApi Magento_InventoryProductAlert Magento_InventoryReservations Magento_InventoryReservationsApi Magento_InventoryCache Magento_InventorySalesAdminUi Magento_InventorySalesApi Magento_InventorySalesFrontendUi Magento_InventoryShipping Magento_InventorySourceDeductionApi Magento_InventorySourceSelection Magento_InventorySourceSelectionApi Magento_InventoryShippingAdminUi Magento_InventoryDistanceBasedSourceSelection Magento_InventoryDistanceBasedSourceSelectionAdminUi Magento_InventoryDistanceBasedSourceSelectionApi Magento_InventoryElasticSearch Magento_InventorySetupFixtureGenerator
Unknown module(s): 'Magento_InventoryElasticSearch'
```

## Affected URLs

- https://devdocs.magento.com/extensions/inventory-management/index.html

## Links to source code

- https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryElasticsearch/registration.php

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4257) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4257) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
Hie @real34,
Thanks for your contribution.
I update the PR description for the Affected URLs and Links to the source code.

**Comment by shrielenee** [comment]
Thanks @ronak2ram. @real34 completely fill out the PR description when submitting a contribution PR so we can efficiently process it. Thanks!

**Pull request merged**
