### PR TITLE
Magento admin product video option added

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
## Purpose of this pull request

This pull request (PR) adds information about the Magento admin product option configurations.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/product-video.html

whatsnew
Added the "Configure product video options from Magento Admin" section to the [Configure product video](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/product-video.html) topic.

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Nice addition

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
Hi @ajithkumar-maragathavel. Thanks for the contribution. Please add a symlink to the image in the correct spot for the v2.4 version.

**Comment by ajithkumar-maragathavel** [comment]
> Hi @ajithkumar-maragathavel. Thanks for the contribution. Please add a symlink to the image in the correct spot for the v2.4 version.

@dobooth  Can you please let me know how to do that. I am not sure what change I should make here.  Thanks for the review

**Comment by dobooth** [comment]
Hi @ajithkumar-maragathavel There is information here: https://github.com/magento/devdocs/wiki/Symlinks You will see many of the v2.4 files are symlinks to v2.3 files, like this one: https://github.com/magento/devdocs/blob/master/src/guides/v2.4/config-guide/cron/custom-cron.md

**Comment by ajithkumar-maragathavel** [comment]
> Hi @ajithkumar-maragathavel There is information here: https://github.com/magento/devdocs/wiki/Symlinks You will see many of the v2.4 files are symlinks to v2.3 files, like this one: https://github.com/magento/devdocs/blob/master/src/guides/v2.4/config-guide/cron/custom-cron.md

@dobooth  Thanks for the help. I have added the symlink of the image in the respective v2.4 directory. Please review it.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
