### PR TITLE
GraphQL request and response correction

### PR DESCRIPTION
**Pull request by hiren-wagento**
Instead of "relative_url" it should be "canonical_url"

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary
When this pull request is merged, it will correct the Example usage of urlResolver endpoint

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.3/graphql/reference/url-resolver.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
The attribute was renamed from `canonical_url` to `relative_url` in https://github.com/magento/graphql-ce/pull/185 I'm guessing that the PR wasn't merged as quickly as I expected.

**Comment by nuzil** [comment]
Yes correct. Basically for 2.3 it makes sense, but from 2.3.1 it will be switched back

**Comment by keharper** [comment]
The rename of renamed from `canonical_url` to `relative_url` won't be merged until 2.3.2 at best.  Accepting this PR.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
I finished this because it was holding up changes to be made in the 2.3.1 integration branch.

**Pull request merged**
