### PR TITLE
Added default value for block cacheable attribute

### PR DESCRIPTION
**Pull request by drpayyne**
## Purpose of this pull request

This pull request (PR) adds the default value for `<block/>`'s `cacheable` attribute. 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by drpayyne** [comment]
Hey @dobooth, I’m not sure if we need a new column just for this since there aren’t many default attribute values. Very few have a default value.

**Comment by dobooth** [comment]
Ok, that's fine with me.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
