### PR TITLE
Add support for DELETE async calls

### PR DESCRIPTION
**Pull request by nuzil**
## Purpose of this pull request

DELETE support for Async/Bulk calls was added from 2.3.2, so I adding it to the list

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/rest/bulk-endpoints.html
https://devdocs.magento.com/guides/v2.3/rest/asynchronous-web-endpoints.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@nuzil Would you add at least one example showing the usage of a DELETE call?

**Comment by nuzil** [comment]
@keharper 
Good point, will do

**Comment by nuzil** [comment]
@keharper 
I added only for BULK requests, cause for Async there are nothing special you have to think about

**Pull request merged**
