### PR TITLE
Added warning about HTTP Access and Fastly Caching

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request

This pull request (PR) fixes issue #9446 

## Affected DevDocs pages
https://devdocs.magento.com/cloud/project/project-webint-basic.html
https://devdocs.magento.com/cloud/project/project-webint-branch.html

### CODE REVIEW

**Review by hguthrie — APPROVED** [review]

**Comment by hguthrie** [comment]
@BarnyShergold  Would it be helpful to link to our topic on [blocking requests](https://devdocs.magento.com/cloud/cdn/fastly-vcl-blocking.html)?

**Review by hguthrie — APPROVED** [review]
Awesome, thanks for the update!

**Comment by hguthrie** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@hguthrie the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-BarnyShergold-devdocs-9451`.

**Pull request merged**
