### PR TITLE
Adding new system specific path as per Backend

### PR DESCRIPTION
**Pull request by magesanjay**
## This PR is a:

- Adding Remaining system-specific paths

## Summary

When this pull request is merged, it will add Remaining system-specific paths as per backend system configuration

Codebase Urls: 

- https://github.com/magento/magento2/blob/2.1/app/code/Magento/Cookie/etc/adminhtml/system.xml#L10
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cookie/etc/adminhtml/system.xml#L10
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Cookie/etc/adminhtml/system.xml#L10

## Additional information

List all affected URLs

1. https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-sens.html
2. https://devdocs.magento.com/guides/v2.2/config-guide/prod/config-reference-sens.html
3. https://devdocs.magento.com/guides/v2.1/config-guide/prod/config-reference-sens.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magesanjay** [comment]
Hello @ronak2ram 
I have updated code base link as per your suggestion in PR description.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @magesanjay!

**Pull request merged**
