### PR TITLE
Changed kramdown wording

### PR DESCRIPTION
**Pull request by rogyar**
## This PR is a:

- [x] Bug fix or improvement

## Summary

This PR fixes the wording of kramdown tool. The tool's name should be presented as a lower case since it's a part of the name's idea. Take a look at https://kramdown.gettalong.org/index.html and check the definition:

> kramdown (sic, not Kramdown or KramDown, just kramdown) is a free MIT-licensed Ruby library for parsing and converting a superset of Markdown.

## Additional information

List all affected URLs 

- https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
running tests

**Comment by dobooth** [comment]
Didn't catch this one in time for small_changes build.

**Comment by hguthrie** [comment]
running tests

**Pull request merged**
