### PR TITLE
Rename file system-requirements2.md and do changed for file path

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- Content fix or rewrite

## Summary

When this pull request is merged, it will show user-friendly URL of system-requirements.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi Ronak. Thanks for this update.
I am going to keep this open because I have to do more work around this.
There are redirects that we use internally that also need fixing before this can go in.

**Comment by osrecio** [comment]
#3915 We accept this PR before @dobooth (to have in mind)

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
Looks there are some linking errors.  

- internally linking to /guides/v2.1/install-gde/system-requirements2.html, which does not exist
  *  _site/guides/v2.1/index.html (line 1515)
     <a href="/guides/v2.1/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.1/install-gde/install-quick-ref.html (line 4634)
     <a href="/guides/v2.1/install-gde/system-requirements2.html">system requirements</a>
  *  _site/guides/v2.1/install-gde/prereq/prereq-overview.html (line 4708)
     <a href="/guides/v2.1/install-gde/system-requirements2.html">Magento system requirements</a>
  *  _site/guides/v2.1/release-notes/ReleaseNotes2.1.0CE.html (line 5019)
     <a href="/guides/v2.1/install-gde/system-requirements2.html" target="_blank">System Requirements</a>
  *  _site/guides/v2.1/release-notes/ReleaseNotes2.1.0EE.html (line 5434)
     <a href="/guides/v2.1/install-gde/system-requirements2.html" target="_blank">System Requirements</a>
  *  _site/guides/v2.1/release-notes/ReleaseNotes2.1.1CE.html (line 3024)
     <a href="/guides/v2.1/install-gde/system-requirements2.html" target="_blank">System Requirements</a>
  *  _site/guides/v2.1/release-notes/ReleaseNotes2.1.1EE.html (line 3030)
     <a href="/guides/v2.1/install-gde/system-requirements2.html" target="_blank">System Requirements</a>
  *  _site/guides/v2.1/release-notes/ReleaseNotes2.1.2CE.html (line 3166)
     <a href="/guides/v2.1/install-gde/system-requirements2.html" target="_blank">System Requirements</a>
  *  _site/guides/v2.1/release-notes/ReleaseNotes2.1.2EE.html (line 3167)
     <a href="/guides/v2.1/install-gde/system-requirements2.html" target="_blank">System Requirements</a>
- internally linking to /guides/v2.2/install-gde/system-requirements2.html, which does not exist
  *  _site/guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.html (line 2370)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.html (line 2449)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/install-gde/install-quick-ref.html (line 4696)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">system requirements</a>
  *  _site/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html (line 4844)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/release-notes/ReleaseNotes2.2.1CE.html (line 2737)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/release-notes/ReleaseNotes2.2.1EE.html (line 2805)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/release-notes/ReleaseNotes2.2.2CE.html (line 3826)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/release-notes/ReleaseNotes2.2.2EE.html (line 3826)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/release-notes/ReleaseNotes2.2.3CE.html (line 2315)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.2/release-notes/ReleaseNotes2.2.3EE.html (line 2315)
     <a href="/guides/v2.2/install-gde/system-requirements2.html">System Requirements</a>
- internally linking to /guides/v2.3/install-gde/system-requirements2.html, which does not exist
  *  _site/guides/v2.3/cloud/release-notes/CloudReleaseNotes2.2.html (line 2192)
     <a href="/guides/v2.3/install-gde/system-requirements2.html">System Requirements</a>
  *  _site/guides/v2.3/install-gde/install-quick-ref.html (line 4708)
     <a href="/guides/v2.3/install-gde/system-requirements2.html">system requirements</a>
  *  _site/index.html (line 1631)
     <a href="/guides/v2.3/install-gde/system-requirements2.html">System Requirements</a>

**Comment by ronak2ram** [comment]
Hey, @dobooth I updated remaining files changes. Can you please review again.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
You left off the file extensions in this last batch. Please check the list.

**Comment by ronak2ram** [comment]
Hello @dobooth 
Can you please share me the latest error logs?

**Comment by ronak2ram** [comment]
Hi @dobooth 
I updated PR can you please review again.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
