### PR TITLE
Update lifecycle.md

### PR DESCRIPTION
**Pull request by ldebord**
## This PR is a 
Content fix or rewrite

## Summary

When this pull request is merged, it will fix name of class

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@ldebord thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3504) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3504) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
