### PR TITLE
magento/devdocs#: Adding additional information to Non-secure functio…

### PR DESCRIPTION
**Pull request by DenisSaltanahmedov**
## Purpose of this pull request

This pull request (PR) adds additional information to the topic of the Non-secure PHP functions.

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/security/non-secure-functions.html

## Links to Magento source code
-  https://github.com/magento/devdocs/blob/master/src/guides/v2.3/extension-dev-guide/security/non-secure-functions.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
More technical info about security issues of the mentioned functions can be found in the following resources:

- https://www.php.net/manual/en/function.sha1.php
- https://www.php.net/manual/en/function.include.php

**Comment by DenisSaltanahmedov** [comment]
Yep, I left the links in the topic.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
