### PR TITLE
update javascript in magento rwd

### PR DESCRIPTION
**Pull request by mrtuvn**
## Purpose of this pull request

This pull request (PR) update content in javascript rwd section
In 2.4 core team remove usage of file responsive.js so we need update content in this section

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/responsive-web-design/rwd_js.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Can confirm that `responsive.js` has been removed from the core in the mainline 

https://github.com/magento/magento2/pull/27617/files

**Comment by rogyar** [comment]
Hi @mrtuvn. Thank you for your contribution. Since this change affects 2.4 release, I believe we should introduce the new version of the documentation in the [2.4](https://github.com/magento/devdocs/tree/master/src/guides/v2.4) version of user guides as well

**Comment by mrtuvn** [comment]
@rogyar current files in repo have symlink. So when you changes in 2.4 folder 2.3 folder will be changed as well Can you confirm that ?

**Comment by mrtuvn** [comment]
remove symlink and update content for only file changed

**Comment by dobooth** [comment]
Ah sorry @rogyar. I tagged you on this before I saw you were already on it! Thanks.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
