### PR TITLE
Missing explanation on depends argument.

### PR DESCRIPTION
**Pull request by mehmetuygun**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@mehmetuygun thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
There's a good example in the test fixtures 
https://github.com/magento/magento2/blob/f30a06a6695f590f261953d2b576efcb1ce512a3/app/code/Magento/Config/Test/Unit/Model/_files/system_2.xml#L85

**Comment by rogyar** [comment]
Hi @mehmetuygun. Thank you for your collaboration. Could I kindly ask you to sign CLA, so the pull request can be processed? 

Thank you!

**Comment by dobooth** [comment]
Closed as abandoned, no CLA.

**Pull request closed without merging**
