### PR TITLE
magento/devdocs#: Fix for ResolverInterface return type

### PR DESCRIPTION
**Pull request by atwixfirster**
## This PR is a:

- [ ] New topic
- [X] Content update
- [X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix the Mangento documentation for the \Magento\Framework\GraphQl\Query\ResolverInterface interface. The return type there’s no requirement for ValueInterface anymore.

## Additional information

List all affected URLs 
- https://devdocs.magento.com/guides/v2.3/graphql/develop/resolvers.html

Thank you!

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4000) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4000) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @atwixfirster

**Pull request merged**
