### PR TITLE
Adding additional info about buttons for alert and confirm widgets

### LINKED ISSUE #4937: Alert and Confirmation Widgets aren't well documented
### Summary (*)
After doing some research on the Alert and Confirmation widgets, I noticed some lack in documentation about these widgets on their documentation pages ([here ](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_alert.html) and [here](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_confirm.html)).
Appearently, both widgets have a `buttons` property, containing an array of buttons which will be displayed. The documentation does not mention you can fill this property yourself, and more so, it simply doesn't even specify is exists. I request that this will be changes, so other developers see this earlier in their development process.

### Examples (*)
```
                              require([
                                  'jquery',
                                  'Magento_Ui/js/modal/alert'
                              ], function ($) {
                                  'use strict';
                                  
                                  $('.alert-modal-content').alert({
                                      title: 'Title',
                                      modalClass: 'alert',
                                      buttons: [{
                                          text: $.mage.__('Button Label'),
                                          class: 'action-primary action-accept',
                        
                                          /**
                                           * Click handler.
                                           */
                                          click: function () {
                                            this.closeModal(true);
                                          }
                                      }]
                                  });
                              });
```

### Proposed solution
Add an explanation to the documentation mentioning the `button` property

SEE https://github.com/magento/magento2/issues/23519

### PR DESCRIPTION
**Pull request by eduard13**
## Purpose of this pull request

This pull request (PR) adds additional info for alert and confirm widgets, by describing the possibility to add additional buttons to the modal window.
It also fixes some aspect issues for widgets' options.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_alert.html
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_alert.html
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_confirm.html
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_confirm.html

## Links to Magento source code
- Alert  widget https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/modal/alert.js#L29
- Confirm widget https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/modal/confirm.js#L40

## Issues

Fixes #4937

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @eduard13. Thank you for your contribution. Would you add the buttons example to the 2.2 version as well (https://github.com/magento/devdocs/pull/4974/files#diff-dbbddd32d873f29658524cd3cf5f74ccR218), please?

**Comment by eduard13** [comment]
Hi @rogyar, thank you for the suggestion, the buttons were included into confirm widgets' examples and the result image was also updated.
Thank you.

**Comment by dobooth** [comment]
Hi @eduard13 One more thing: alert-image-result.png is way bigger than it needs to be. Can you please resize it?

**Comment by eduard13** [comment]
Hi @dobooth, yeah, looks like I forgot to resize and optimize it. Now it should have the right size.
Thank you.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
