### PR TITLE
Update label based on modules names

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will show the correct header name based on the module.
Referance page : https://devdocs.magento.com/guides/v2.3/rest/list.html 

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/rest/rest_endpoints.html
- https://devdocs.magento.com/guides/v2.3/b2b/integrations.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by nuzil** [comment]
I do not expect here header name based on the module, its more a headers for devdoc reader for have understanding of what is this list about.

**Comment by nuzil** [comment]
@keharper what do you think?

**Comment by keharper** [comment]
Hey, @nuzil we decided the inconsistency between using actual module names in the headings where we list endpoints and descriptive names where we list service names wasn't good. We went with module names, because they're more accurate.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @ronak2ram for your contribution!

**Pull request merged**
