### PR TITLE
Products graphql - deprecated fields removed

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Deprecated fields are removed in all product related graphql topics.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/product/product-interface-implementations.html
-  https://devdocs.magento.com/guides/v2.3/graphql/product/bundle-product.html
-  https://devdocs.magento.com/guides/v2.3/graphql/product/configurable-product.html
-  https://devdocs.magento.com/guides/v2.3/graphql/product/grouped-product.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Examples from the codebase: 

- https://github.com/magento/magento2/blob/388f2e95d36ddae1ecb2a6c2730672e55c859720/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L103
- https://github.com/magento/magento2/blob/388f2e95d36ddae1ecb2a6c2730672e55c859720/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L108

**Comment by chandru-199** [comment]
@keharper : changes updated. Thanks.

**Comment by keharper** [comment]
running tests

**Comment by chandru-199** [comment]
Hi @keharper : I have one doubt. what is the criteria for major update label?

**Comment by keharper** [comment]
@chandru-199 The major update label requires significant new content. This PR corrects oversights, so falls under Technical

**Comment by chandru-199** [comment]
@keharper Thanks for the information.

**Pull request merged**
