### PR TITLE
Added missing parameters and default value column

### LINKED ISSUE #3475: Parameter related issue on Deploy static view files
# Bug report
There is parameter are missing with on setup:static-content:deploy command

## Description
Check document https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-static-view.html

### PR DESCRIPTION
**Pull request by gelanivishal**
## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Improvement

## Summary
I have added missing below parameters and added default value column for v2.x.
> --symlink-locale
> --content-version=CONTENT-VERSION

When this pull request is merged, it will fixed #3475 issue.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
Looks like this only affects v2.2 so I removed the URL to 2.1.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @gelanivishal!

**Pull request merged**
