### PR TITLE
Update user-admin.md

### PR DESCRIPTION
**Pull request by manish-sp**
## Purpose of this pull request

Updated correct link

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/project/user-admin.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-engcom-team** [comment]
@manish-sp thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by manish-sp** [comment]
I accepted Adobe CLA too.

**Comment by meker12** [comment]
running tests

**Pull request closed without merging**
