### PR TITLE
Fix wrong path and update path of indexing

### PR DESCRIPTION
**Pull request by mageprince**
## This PR is a:

- Content fix or rewrite

## Summary

When this pull request is merged, it will fix and add proper configuration path.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Good morning @mageprince and @osrecio,
 Thanks for the work here.
When writing breadcrumbs, we **bold** items you click on and do not bold headings like   > Tools > . 
I only bring this up since we have gotten a few PRs lately with breadcrumb fixes in it and we  (including internal writers) should start being consistent with this.

**Comment by mageprince** [comment]
Hi @dobooth I have update PR as per your suggestion.

**Comment by dobooth** [comment]
Very nice! Thanks!

**Comment by dobooth** [comment]
running tests

**Pull request merged**
