### PR TITLE
Create symlink for MSI release notes

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) creates a symlink for the Inventory Management release notes and corrects the package version in the compatibility matrix.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/inventory/release-notes.html
- https://devdocs.magento.com/release

### CODE REVIEW

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by jeff-matthews** [comment]
Fixed broken links

**Comment by dobooth** [comment]
running tests

**Pull request merged**
