### PR TITLE
MAGEDOC-3399: Product availability update

### PR DESCRIPTION
**Pull request by jeff-matthews**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will update the availability timeline for the Amazon Sales Channel extension.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/availability

whatsnew
Updated the [availability timeline](https://devdocs.magento.com/availability) for the Amazon Sales Channel extension.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
running tests

**Comment by dshevtsov** [comment]
@jeff-matthews please add labels with target versions

**Comment by jeff-matthews** [comment]
@dshevtsov, this topic and these changes are not specific to core Commerce.

**Comment by dshevtsov** [comment]
@jeff-matthews in this case **Versions** cell will be empty in https://devdocs.magento.com/whats-new.html for this entry. Is it expected result?

**Comment by dshevtsov** [comment]
we can use `N/A` when version was not specified in a PR label.

**Comment by dshevtsov** [comment]
or `2.x` that would mean that the update is generally applicable for Magento 2

**Comment by jeff-matthews** [comment]
I think N/A is an acceptable temporary solution. Have you considered how the whatsnew might change after we start publishing docs like PageBuilder? Perhaps we should consider adding some new labels tot he repo. What do you think?

**Comment by dshevtsov** [comment]
A lot of open questions here, we will need to discuss them with projects teams.

**Pull request merged**
