### PR TITLE
Update webapi.xml reference

### PR DESCRIPTION
**Pull request by AlexMaxHorkun**
Added description for the new attribute for route element in webapi.xml files, valid for 2.1, 2.2, 2.3 versions

## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Reflect all existing attributes of route element in webapi.xml files

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/service-contracts/service-to-web-service.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/service-contracts/service-to-web-service.html
- https://devdocs.magento.com/guides/v2.1/extension-dev-guide/service-contracts/service-to-web-service.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4028) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4028) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@AlexMaxHorkun  Does this doc update apply to 2.3.1 and the other versions released at the same time? I expected `soapOperations` to appear in the `webapi.xsd` file, but I don't see it. Then again, this might not be a correct expectation.

**Comment by AlexMaxHorkun** [comment]
> @AlexMaxHorkun Does this doc update apply to 2.3.1 and the other versions released at the same time? I expected `soapOperations` to appear in the `webapi.xsd` file, but I don't see it. Then again, this might not be a correct expectation.

My mistake, I thought it's been merged in time for 2.3.1 but it turns out it will only appear in the next patch versions

**Pull request merged**
