### PR TITLE
Change the test configuration file(s)

### PR DESCRIPTION
**Pull request by hitarthpattani**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

This will use to provide proper phpunit configuration files use to run api-functional test cases based on required API adaptor i.e. `soap` or `rest`. Earlier version has information about only single `phpunit.xml` configuration file instead of separate `phpunit_soap.xml` and `phpunit_rest.xml` configuration files.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/get-started/web-api-functional-testing.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4081) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4081) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
This looks good to me, but waiting for @dthampy to review before continuing.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @hitarthpattani!

**Pull request merged**
