### PR TITLE
Command line config

### PR DESCRIPTION
**Pull request by manavluhar**
## Purpose of this pull request

This pull request (PR) is for updating, removing and adding details to Command Line Configuration Documents.

-  For **1**st Page listed underneath, I have added  **Current status:** in sample result of `bin/magento cache:status` as it shows when we execute the command.
- For **2**st Page listed underneath, I have attached a glossary link to **framework** terminology & updated commands by adding `bin` directory path before the command.
- For **3**rd Page listed underneath, I have removed `bin/magento indexer:info` command details from three sections as there is a separate section namely **View a list of indexers** where it is described in detail. Also Updated the sort description for `indexer:reindex` & `indexer:status` commands.
- For **4**th Page listed underneath, I have updated it by removing `bin` before the commands as that practice is described in the **First Steps** section and followed throughout the page. I also added a small styling change for one command as per the standards
- For **5**th Page listed underneath, I have updated the path description of the **db.log** file and removed the extra description. 

## Affected DevDocs pages
1: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cache.html#view-the-cache-status : config-cli-subcommands-cache.md

2: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-depen.html : config-cli-subcommands-depen.md  

3: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-index.html : config-cli-subcommands-index.md

4: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands.html#config-cli-summary : config-cli-subcommands.md 

5: https://devdocs.magento.com/guides/v2.4/config-guide/cli/logging.html#database-logging : logging.md

See Contribution guidelines (https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md) for more information.
-->

### CODE REVIEW

**Review by hguthrie — APPROVED** [review]
Great cleanup, thanks!

**Comment by hguthrie** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@hguthrie the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-manavluhar-devdocs-9484`.

**Comment by manavadobe** [comment]
> Great cleanup, thanks!

Thank you @hguthrie 🙌

**Comment by manavluhar** [comment]
> Great cleanup, thanks!

Thank you @hguthrie 🙌

**Pull request merged**
