### PR TITLE
Module version dependencies.

### PR DESCRIPTION
**Pull request by novikor**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

Updated 'Determine module dependency' section.
Added versions for class constants and class not marked with @api.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html
- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/dependencies.html
- https://devdocs.magento.com/guides/v2.1/extension-dev-guide/versioning/dependencies.html
- https://devdocs.magento.com/guides/v2.0/extension-dev-guide/versioning/dependencies.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
@jeff-matthews For me this PR is OK. I have some doubts about some points. Perhaps it would be convenient to have it checked by an internal core developer to determine exactly.

What do you think?

**Comment by jeff-matthews** [comment]
Thanks @osrecio. I'll request a review from an internal core developer.

**Comment by novikor** [comment]
Hi, Guys. 
Any updates?

**Comment by jeff-matthews** [comment]
@buskamuza?

**Comment by melnikovi** [comment]
I will try to review it today.

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
