### PR TITLE
Cache clean after modifying configuration file

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) : Adding additional step to clean the Magento cache after editing configuration file(system.xml). cleaning the cache is must while Modify or create any configuration file.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/dynamic-row-system-config.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@chandru-199 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by chandru-199** [comment]
I need to add partner label.Is it possible?

**Comment by keharper** [comment]
Which partner?

**Comment by chandru-199** [comment]
Ziifity

**Comment by keharper** [comment]
@chandru-199 I've added the partner label to this PR. Please ask the person who controls the Ziffity team account to make sure the list of team members is up to date.

**Pull request merged**
