### PR TITLE
Update Top Contributors Data File Url

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
## This PR is a:
- [ ] New topic
- [ ] Content fix or rewrite
- [x] Bug fix or improvement
 

## Summary
When this pull request is merged, it will update the URL for the Top Contributors data file. 
 
## Additional information
Top Contributors data has been moved to another resource and now has gzip compression enabled improving page load speed.
Old resource will be accessible as long as this PR is open to maintain the page during transition period.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2006) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2006) before we can accept your contribution.<br/>

**Comment by jeff-matthews** [comment]
@ishakhsuvarov, please don't shut down the old S3 bucket until this change goes live. I'll let you know when it's live.

**Comment by ishakhsuvarov** [comment]
@jeff-matthews Sure. It is going to be live and up-to-date as long as needed.

**Comment by jeff-matthews** [comment]
@ishakhsuvarov, the new data source URL is now live and everything looks good. You can shut down that other data source.

**Pull request merged**
