### PR TITLE
updating output of this command bin/magento queue:consumers:list

### PR DESCRIPTION
**Pull request by aman3103**
## Purpose of this pull request

This pull request (PR) is updating the out of bin/magento queue:consumers:list mentioned in issue #5294 i.e https://github.com/magento/devdocs/issues/5294

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html
- ...

## Links to Magento source code

- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@aman3103 

B2B was probably the first subsystem to use message queues, and `sharedCatalogUpdatePrice` and `sharedCatalogUpdateCategoryPermissions` are absolutely valid message queue names. Since then, we've added more. We should not be maintaining an ever-expanding list of message queues. It would be better to delete the list entirely.

**Comment by aman3103** [comment]
@keharper okay I will remove this list then, will push the code again

**Comment by keharper** [comment]
@aman3103 Looks good, except you accidentally checked in several files from your `.idea` directory.

**Comment by aman3103** [comment]
@keharper I have removed the files now

**Comment by keharper** [comment]
Thanks @aman3103 . We'll merge this in our next batch.

**Pull request merged**
