### PR TITLE
Patch widget_gallery configuration typo

### PR DESCRIPTION
**Pull request by jakubmakielkowski**
## Purpose of this pull request

This pull request (PR) fixes a typo in example widget configuration. A missing comma might be misleading.

## Affected DevDocs pages

-  https://github.com/magento/devdocs/blob/master/src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@jakubmakielkowski thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]
Nice spot!!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Good eye.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
