### PR TITLE
Updated upgrade magento doc

### PR DESCRIPTION
**Pull request by vgelani**
## This PR is a:
- [ ] New topic
- [x] Content update
- [ ] Bug fix or improvement
 

## Summary
Updated upgrade magento document. https://devdocs.magento.com/guides/v2.2/comp-mgr/cli/cli-upgrade.html

### CODE REVIEW

**Comment by lorikrell** [comment]
Please revert your style changes, including the collapsible sections and code formatting. We don't want to introduce new expandable sections due to blocking search on page. We also use language-specific code blocks (see bash commands in original). We will review further after those changes.

**Comment by vgelani** [comment]
@lorikrell I have just added this content, Please check here https://github.com/magento/devdocs/pull/2225/commits/9986410e985e3101b799dd12f9b4c17c842c363f

**Comment by vgelani** [comment]
@dshevtsov I have just added this content, Please check here 9986410

**Comment by dshevtsov** [comment]
@vgelani your second commit (merge with develop) introduces changes that must be reverted.
You can try to reset your `format-issue-10` branch to the commit you want to contribute and push it to the remote branch again:
```
git checkout format-issue-10
git reset --hard 9986410
git push
```

**Comment by vgelani** [comment]
@dshevtsov It didn't work so I have created new PR #2313

**Pull request closed without merging**
