### PR TITLE
Fixed path to Restricting access to anonymous web APIs v.2.1

### PR DESCRIPTION
**Pull request by ygyryn**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Add missed option *Settings* in updated path in template
guides/v2.1/rest/anonymous-api-security.md

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.1/rest/anonymous-api-security.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ygyryn** [comment]
I did it before in:
https://github.com/magento/devdocs/pull/3750

**Comment by jeff-matthews** [comment]
You should combine these two contributions into a single PR.

**Comment by ygyryn** [comment]
Can you help me how to do it correctly?

**Comment by jeff-matthews** [comment]
Of course. Give me a few minutes and I'll show you what I mean.

**Comment by jeff-matthews** [comment]
running tests

**Comment by ygyryn** [comment]
Thank you, jeff-matthews!

**Comment by jeff-matthews** [comment]
Thanks for your contribution @ygyryn!

**Pull request merged**
