### PR TITLE
Update ui-form.md

### PR DESCRIPTION
**Pull request by sanjay-wagento**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

In Magento 2.2.* ui-form definition change. So I modified the example code of customer module.

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-form.html

https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-form.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @sanjay-wagento Can you merge this PR with the other one: #3726 ?

**Comment by sanjay-wagento** [comment]
@osrecio I modified different pages so I created different PR per page.
Previously we agree that if we have more than one changes on same page then create single PR for multiple changes.
Still, you want to create single PR for different pages? If yes then can you please provide steps?

**Comment by osrecio** [comment]
Hi @sanjay-wagento . 
I am commenting internally to see which is the best way and that you have a clear way to do the PR's.

But first of all thank you for your effort. Are very valuated

**Comment by shrielenee** [comment]
Filling out the PR form is mandatory for each contribution. This helps us efficiently process your PRs.

**Comment by sanjay-wagento** [comment]
@shrielenee , I updated PR form please review and let me know if you need more information

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
