### PR TITLE
Remove old data from the What's New page

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) removes data from the following years from the What's New data file:

- 2018
- 2017
- 2016

Our new data retention policy dictates that we keep data for the current and previous years only.

## Affected DevDocs pages

- https://devdocs.magento.com/whats-new.html

### CODE REVIEW

**Comment by dshevtsov** [comment]
FYI I can do this programmatically without need to change the data file.

**Comment by jeff-matthews** [comment]
Sounds good. Technically, either way changes the data file, so if you prefer to enhance the existing tool to limit the data that's fine. I'd like to get this done before shutdown, so if you can't do it before then @dshevtsov, please approve this PR.

**Comment by dshevtsov** [comment]
@jeff-matthews I'll commit the changes to this PR.

**Comment by jeff-matthews** [comment]
Thanks @dshevtsov

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
