### PR TITLE
Adding additional step in custom shipping carrier validations page

### PR DESCRIPTION
**Pull request by VinothKumar361**
## Purpose of this pull request

Adding additional step in custom shipping carrier validations page

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_carrier.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by VinothKumar361** [comment]
thanks @dobooth

**Pull request merged**
