### PR TITLE
Changes array syntax `[]` instead of long `array()`.

### PR DESCRIPTION
**Pull request by pratikhmehta**
## Purpose of this pull request

Array syntax changes.
Like bellow "array syntax `[]` instead of long `array()`".

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@pratikhmehta thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @pratikhmehta. Thank you for your contribution. Please, next time provide the PR description according to the template. It will speed up the review and delivery process.

**Comment by keharper** [comment]
Thanks @pratikhmehta. We'll merge this PR in the next batch.

**Pull request merged**
