### PR TITLE
Update project-routes-more-redir.md

### PR DESCRIPTION
**Pull request by chellinki**
## Purpose of this pull request

Removed extra curly brace

## Affected DevDocs pages

https://devdocs.magento.com/cloud/project/project-routes-more-redir.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@chellinki thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]
Good spot!
You will need to sign the Adobe CLA (see the link in the PR test area) before this can be merged

**Review by BarnyShergold — APPROVED** [review]

**Review by meker12 — APPROVED** [review]

**Comment by dobooth** [comment]
FYI, Small Changes are generally for PRs to master only.

**Comment by meker12** [comment]
> FYI, Small Changes are generally for PRs to master only.

ah, I didn't notice that this was against the integration branch.  Thx.

**Pull request merged**
