### PR TITLE
Need to modify config.php before running docker:build

### PR DESCRIPTION
**Pull request by joeshelton-wagento**
## Purpose of this pull request

Recent changes to Docker configuration require the config.php file to exist before running the docker:build command in order for customizations to be effective. A couple steps in the setup doc need to be reversed.

## Affected DevDocs pages

https://devdocs.magento.com/cloud/docker/docker-config.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
We are working on major changes to the Cloud Docker documentation. The two modes are now in two different topic files. See the Docker branch for comparison: https://github.com/magento/devdocs/tree/Cloud-Docker-1.0.0

**Comment by joeshelton-wagento** [comment]
Should I create a new PR, or somehow modify this one?

**Comment by jeff-matthews** [comment]
I think it depends on when the `Cloud-Docker-1.0.0` integration branch will be merged with `master`. If it will be more than a couple of weeks, I say we merge the PR as-is now. Especially if our docs are incorrect per current, released functionality.

**Comment by hguthrie** [comment]
Yes, I agree with @jeff-matthews . I just reviewed the other branch and the "switch" is not in there, either. So, it would be fine to merge this to master.

**Pull request merged**
