### PR TITLE
Adjusting the modifier by including the required componentType attribute

### LINKED ISSUE #5015: Incorrect Example: /guides/v2.3/howdoi/customize-modifier-class.html
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/howdoi/customize-modifier-class.html

## Description

`Example::modifyMeta` in the first code sample under the **Add your modifier** section is not adding the required `componentType` argument to the `test_fieldset_name`'s configuration. This throws a `LocalizedException`.

## Possible solutions

```diff
public function modifyMeta(array $meta)
    {
        $meta['test_fieldset_name'] = [
            'arguments' => [
                'data' => [
                    'config' => [
                        'label' => __('Label For Fieldset'),
                        'sortOrder' => 50,
                        'collapsible' => true,
+                        'componentType' => 'fieldset',
                    ]
                ]
            ],
```

### PR DESCRIPTION
**Pull request by eduard13**
## Purpose of this pull request

This pull request (PR) adds in provided Modifier class example the required attribute `componentType` for the new added fieldset. It also improves the current document by linking the mentioned Modifiers with Magento repo.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/howdoi/customize-modifier-class.html
- https://devdocs.magento.com/guides/v2.2/howdoi/customize-modifier-class.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Bundle/Ui/DataProvider/Product/Form/Modifier/BundlePanel.php#L86

## Fixed issues

Fixes #5015

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
This looks good to me, but I'll wait for @osrecio to confirm the technical side.

**Comment by osrecio** [comment]
Testing in my local environment :)

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @eduard13!

**Pull request merged**
