### PR TITLE
Updated composer_lock data after 2.3.5 release

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) updates data file that serves as a data source for packages and PHP requirements in documentation.

whatsnew
Updated [PHP requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php) and [packages](https://devdocs.magento.com/guides/v2.3/release-notes/packages-open-source.html).

### CODE REVIEW

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
HTML check fails because the composer files contain an SSH link in `laminas/laminas-inputfilter`.`source`.`url` that is used as a hyperlink to the package's source. Failure report:

```
- git@github.com:laminas/laminas-inputfilter.git is an invalid URL

  *  _site/guides/v2.3/release-notes/packages-cloud.html (line 2827)

     <a href="git@github.com:laminas/laminas-inputfilter.git">laminas/laminas-inputfilter</a>

  *  _site/guides/v2.3/release-notes/packages-commerce.html (line 556)

     <a href="git@github.com:laminas/laminas-inputfilter.git">laminas/laminas-inputfilter</a>

  *  _site/guides/v2.3/release-notes/packages-open-source.html (line 556)

     <a href="git@github.com:laminas/laminas-inputfilter.git">laminas/laminas-inputfilter</a>
```

**Comment by jeff-matthews** [comment]
Sounds like we need to exclude the `composer_lock.json` file in the htmlproofer config.

**Comment by dshevtsov** [comment]
> Sounds like we need to exclude the `composer_lock.json` file in the htmlproofer config.

html-proofer is run only on HTML pages at `_site`, that's why we cannot exclude data files, we can only exclude pages by path in this case. We just need to update Liquid generator to create hyperlinks only if `url` is an HTTP link.

**Comment by dshevtsov** [comment]
Having those issues with bad input data, I start thinking that it may make sense to dump only data we need in a format we can work with instead of copying entire files from codebases and creating workarounds. From the other hand, we can catch code issues and this is a kind of testing for a code.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
