### PR TITLE
Add __('<your_string>') method in Prompt widget

### PR DESCRIPTION
**Pull request by magehardik**
## Purpose of this pull request

Added __('<your_string>') method in examples because this method is used for translation of the string

This pull request (PR) ...

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_prompt.html
- https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_prompt.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/modal/prompt.js
- https://github.com/magento/magento2/blob/2.4/app/code/Magento/Ui/view/base/web/js/modal/prompt.js

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Nice little update! Please don't forget to sign the Adobe CLA so this PR can be processed. You only need to do this once.

**Comment by hguthrie** [comment]
@magehardik Can you please sign the CLA? Once you do that, we can continue to process your PR.

**Comment by magehardik** [comment]
Hello @hguthrie,

I have already signed with the Adobe CLA. I have also closed the PR and Re-opened it. But here Adobe CLA is displayed not signed. If you want the Adobe CLA signed doc then please let me know I will attach it. 

Thank you

**Comment by hguthrie** [comment]
@adobe/open-source-office Contributor confirmed signing the CLA, but it still appears to fail verification. Please advise.

**Comment by hguthrie** [comment]
Several days without reply, so I sent an email. Hopefully will find out what happened to CLA. Thanks for your patience.

**Comment by macdonst** [comment]
@hguthrie the `@adobe/open-source-office` doesn't actually generate an email to us. We'll have to fix that in the CLA-bot help message.

**Comment by macdonst** [comment]
@magehardik you are going to need to sign the CLA again and for the filed that asks for your Github Login just put `magehardik` not the url to your profile.

**Comment by magehardik** [comment]
@macdonst I have signed using the Github Login: magehardik.

**Comment by keharper** [comment]
running tests

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
Thanks @magehardik

**Comment by dshevtsov** [comment]
@keharper please add labels for type of changes and target versions.

**Pull request merged**
