### PR TITLE
Upgrade to latest version of Magento

### PR DESCRIPTION
**Pull request by diazwatson**
## Purpose of this pull request

This pull request (PR) upgrades the install instructions with the latest version of Magento

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/project/ece-tools-upgrade-project.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
@diazwatson  I am placing this PR on hold because Cloud is releasing in a few days and we are busy merging MAJOR updates to the Cloud guide. We will resume this review after the release updates are merged. Thanks for contributing! 👍

**Comment by dobooth** [comment]
Hi @diazwatson Can you please update your branch and take care of this merge conflict? Thanks!

**Comment by diazwatson** [comment]
Sure!

**Comment by diazwatson** [comment]
@dobooth change are now in this PR
https://github.com/magento/devdocs/pull/6595

Thanks

**Pull request closed without merging**
