### PR TITLE
Fixing "Mangento" typo in cloud guide

### PR DESCRIPTION
**Pull request by eduard13**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix the Mangento typo in cloud guide.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/cloud/before/before-workspace-cloud-account.html
- https://devdocs.magento.com/guides/v2.2/cloud/before/before-workspace-cloud-account.html
- https://devdocs.magento.com/guides/v2.1/cloud/before/before-workspace-cloud-account.html
- https://devdocs.magento.com/guides/v2.0/cloud/before/before-workspace-cloud-account.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3984) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3984) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
@eduard13 Completely fill out the **This PR is:** form each time you submit a PR. PRs without that section completed are subject to closing.

**Comment by shrielenee** [comment]
running tests

**Comment by eduard13** [comment]
Hi @shrielenee, thank you for noticing, but what do you mean by completely fill out the **This PR is:** form? Currently it's checked the _Content fix_ which I guess is the right one, but what else?
I was checking some other PRs before opening, and I thought that this it the right way of doing it.

**Comment by shrielenee** [comment]
Hey @eduard13 -- It may be my mistake but it appeared earlier that you had not filled out the Summary section. As it is now, it seems that is filled out! Thanks! I will be merging this soon.

**Pull request merged**
