### PR TITLE
Include notice regarding `sysvar_explicit_defaults_for_timestamps`

### PR DESCRIPTION
**Pull request by cmacdonald-au**
## Purpose of this pull request

As per https://github.com/magento/magento2/issues/19597#issuecomment-573510633

If this setting is not enabled, `setup:db:status` will continuously return the following;

```
Declarative Schema is not up to date
Run 'setup:upgrade' to update your DB schema and data.
```

MariaDB appears to be unaffected.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/install-gde/prereq/mysql.html#instgde-prereq-mysql-config

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @cmacdonald-au Thanks for contributing! A couple things: First, please sign the Adobe CLA so we can process this. Second, the Markdown linting test is showing an issue. Click the Details link for info on what to fix.

**Comment by cmacdonald-au** [comment]
@dobooth yeah, the Adobe CLA is a bit tricker to get processed on this side than the old Magento one. Am getting there...

**Comment by cmacdonald-au** [comment]
@dobooth , @davidalger was kind enough to get this through faster than I could get the CLA processed. 
ref: https://github.com/magento/devdocs/pull/6916

Closing this one off, thx for your time!

**Pull request closed without merging**
