### PR TITLE
Updating mixin from .font-face to .lib-font-face

### PR DESCRIPTION
**Pull request by maderlock**
.font-face does not seem to work on 2.0.1, whereas .lib-font-face does

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
@maderlock @almarchenko This PR is attempting to merge with the `develop` branch, which we don't use anymore.

@maderlock should make the PR against the `2.0` branch and we can take a look; otherwise, we'll have to close this without making changes.

Thanks

**Comment by Vinai** [comment]
@xcomSteveJohnson Just FYI, to delete the remote branch "develop" run the command

```
$ git push origin :develop
```

The trick is to prefix the remote branch with a colon `:`.

**Comment by xcomSteveJohnson** [comment]
@Vinai Thanks. I need to check with Magento CICD first. They originally set up the `develop` branch and automation might still need it, I'm not sure.

**Comment by almarchenko** [comment]
@maderlock Your update is absolutely correct, I went ahead and updated the docs by creating internal PR. Hope you do not mind. Thank you for your input, keep it coming:))
Can I close this PR?

**Comment by maderlock** [comment]
Slightly confused with the branching structure, but glad this was helpful.

**Pull request closed without merging**
