### PR TITLE
Removing unlinked images.

### PR DESCRIPTION
**Pull request by dobooth**
## Purpose of this pull request

This PR removes images and symlinks that are not referenced in the source code.
Made a script that looked for all images within devdocs+multirepo folders.
Then counted source code references for each of them. This list is images with no refs.
[sorted.txt](https://github.com/magento/devdocs/files/3198013/sorted.txt)
Rake build with 0 errors.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
I suspect that some of the files being removed are artifacts that pre-date when we split the devdocs from the theme. It would be good to get @belbiy to take a quick look.

**Comment by dobooth** [comment]
I have removed the requested files from this PR.

**Comment by dobooth** [comment]
@belbiy , look ok to you now?

**Comment by dobooth** [comment]
running tests

**Pull request merged**
