### PR TITLE
Fix typos on Multiselect Widget page

### LINKED ISSUE #9264: Typo needs fixing
# Typo issue

## Description:

https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget-multiselect.html

Typo in the text on the "Multiselect Widget" page.

Typo in the "The RedirectUrl widget has the following options:" sentence, expected result is the "The Multiselect widget has the following options:" sentence.

image

## Actual result

"The RedirectUrl widget has the following options:"

## Expected result

"The Multiselect widget has the following options:"

## Possible solutions:

The typo should be corrected.

### PR DESCRIPTION
**Pull request by Viper9x**
Fixes #9264 
Fix typos on the Multiselect Widget page

## Purpose of this pull request
Fix typos on the Multiselect Widget page

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget-multiselect.html
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget-multiselect.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by Viper9x** [comment]
@dobooth do you think I need to update my branch (Viper9x:patch-1) to be up to date with magento/devdocs master branch?

**Comment by dobooth** [comment]
Something is amiss with our import bot and are trying to figure out why. If you could update your fork/branch, that would help!

**Comment by Viper9x** [comment]
@dobooth I have updated my fork/branch. Thanks.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
