### PR TITLE
Bulk changes in cli commands

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - bin directory missing in cli commands written in many documents. Made changes in all those files. 

## Affected DevDocs pages

-  15 files changed.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by meker12** [comment]
@chandru-199  Thanks for your contribution.  However, I am closing this PR because there are several ways to run the `bin/magento` commands, and users can learn about them in the [Get started with the command-line installation](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands.html#instgde-cli-before) topic.  This topic is in the same place as all the install topics where you changed the commands to add `bin/magento`.

In the Varnish topics, the [magento setup:config:set](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-deployment.html) is linked to the topic that provides instructions for running the bin/magento commands.

image

**Comment by keharper** [comment]
@meker12 I disagree with closing this PR. Over the past year+, we've been making the format of sample commands more consistent. When I edit a file with commands, I use the `bin/magento` format, and we've been encouraging contributors to do the same.

**Comment by keharper** [comment]
running tests

**Comment by chandru-199** [comment]
cli command changes are editorial or technical ?. Can any one clear this out?

**Comment by keharper** [comment]
Editorial. It's a style/consistency issue.

**Comment by chandru-199** [comment]
Thanks @keharper

**Pull request merged**
