### PR TITLE
Update payment-token.md

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will update function getVaultPaymentToken as per the latest code repository v.2.3.x [File link](https://github.com/magento/magento2/blob/4fb0f1af1e1bd7735f0a1d7caed85f322df84905/app/code/Magento/Braintree/Gateway/Response/VaultDetailsHandler.php#L98
)

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/payments-integrations/vault/payment-token.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@mage2pratik, from what I can tell, it looks like you changed the `getVaultPaymentToken` function from `private` to `protected`. Please update your PR description with an explanation for why you did this.

**Comment by jeff-matthews** [comment]
Spoke to @mage2pratik via Slack. This PR brings 2.3 docs up to date with 2.3 codebase.

See https://github.com/magento/magento2/blob/2.3/app/code/Magento/Braintree/Gateway/Response/VaultDetailsHandler.php#L98

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
