### PR TITLE
Information about patch PRODSECBUG 2233

### PR DESCRIPTION
**Pull request by jfrontain**
## Purpose of this pull request

This pull request (PR) added information about Patch PRODSECBUG-2233 to the relevant release notes for affected Magento versions. Affected versions include Magento Commerce and Magento Open Source v2.3.1, 2.3.0, 2.2.8, and 2.2.7.

## Affected DevDocs pages

Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.html https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.html https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.html https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.8CE.html https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.8EE.html https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.7CE.html https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.7EE.html

whatsnew
Added information about patch PRODSECBUG-2233.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5091) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5091) before we can accept your contribution.<br/><hr/>**Jeanne Frontain** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by keharper** [comment]
Be sure to add the `internal-dev` and `Major update` labels, and add a `whatsnew` statement.

**Comment by jfrontain** [comment]
running tests

**Comment by jfrontain** [comment]
running tests

**Comment by jfrontain** [comment]
running tests

**Comment by jfrontain** [comment]
running tests

**Comment by jfrontain** [comment]
running tests

**Comment by jfrontain** [comment]
running tests

**Pull request merged**
