### PR TITLE
Removed unused and wrong type

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- Content fix or rewrite

## Summary

When this pull request is merged, it will remove unused and wrong type.

## Additional information

Codebase link:
https://github.com/magento/graphql-ce/blob/4a28abb62b4f879794b44c2b2230db15ddea46ba/app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls#L51

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/reference/configurable-product.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
@mage2pratik Any reason you picked the `develop` branch for this PR?

**Comment by keharper** [comment]
@dobooth This PR was opened against develop because it fixes 2.3.2 documentation. 

I'm not ready for this to be merged. Putting this on hold until I am.

**Comment by keharper** [comment]
Thanks @mage2pratik

**Pull request merged**
