### PR TITLE
Fix/broken symlink - issue 8787

### LINKED ISSUE #8787: Add symlink for missing file
# General issue

## Description:

This page doesn't exist.

/guides/v2.4/extension-dev-guide/framework/datetime.html

The v2.3 version does

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request

This pull request (PR) fixes #8787 

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/framework/datetime.html

### CODE REVIEW

**Comment by BarnyShergold** [comment]
@jeff-matthews - Not sure what's happened here but a commit from an old PR on branch that has already been merged has been included. What's the best way to deal with this?

**Comment by dobooth** [comment]
We saw something like that yesterday. Someone had made commits directly to master rather than making a branch and tried to merge master => master. Not clear how this PR got out of sync but I am troubled by this type of error happening again...with different commits.

**Comment by dobooth** [comment]
Oh...updating the branch seems to have fixed it. Weird.

**Comment by BarnyShergold** [comment]
> We saw something like that yesterday. Someone had made commits directly to master rather than making a branch and tried to merge master => master. Not clear how this PR got out of sync but I am troubled by this type of error happening again...with different commits.
> But updating your branch and re-making the PR is a place to start.

Yeah - I never use master branch. But thanks for sorting with the merge.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8817`.

**Pull request merged**
