### PR TITLE
Update index.php location

### PR DESCRIPTION
**Pull request by Viper9x**
## Purpose of this pull request

This pull request (PR) updated **Magento application initialization and bootstrap** page content

## Affected DevDocs pages

Magento application initialization and bootstrap
https://devdocs.magento.com/guides/v2.4/config-guide/bootstrap/magento-bootstrap.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@Viper9x thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by BarnyShergold** [comment]
@Viper9x - Can you signed the Adobe CLA please?

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
@Viper9x 
Please can you add the correct information to the PR description - you need to include a link to the page(s) involved.

Secondly, you seem to have replaced the content of the symlink file by pasting in the content of the 2.3 version and changing it - this can't be done this way.

You need to revert the changes, then follow this process : https://github.com/magento/devdocs/wiki/Symlinks to replace the 2.4 file with a copy of the 2.3, THEN make the change and then commit.

THis is what is causing the lint check to fail. I suspect it thinks the complete file content is the filename the symlink points to 😄

**Comment by Viper9x** [comment]
@BarnyShergold Thanks for letting me know all about them, I've signed Adobe CLA. I'll edit the file now.

**Comment by Viper9x** [comment]
> You need to revert the changes, then follow this process : https://github.com/magento/devdocs/wiki/Symlinks to replace the 2.4 file with a copy of the 2.3, **THEN make the change and then commit.**

@BarnyShergold I want to update page content on v2.4 because its content must be changed in Magento 2.4 release and nothing changes on v2.3. What should I do right now?
["DevDocs uses symlinks to inherit content from a previous minor version for topics that have **not been affected** by new releases."](https://github.com/magento/devdocs/wiki/Symlinks)

**Comment by keharper** [comment]
@Viper9x Run the following command

rake symlink:replace_at src/guides/v2.4/config-guide/bootstrap/magento-bootstrap.md

Breaking a symlink makes the changed file look like a new file. It would help with the review if you state which lines/sections you changed.

**Comment by keharper** [comment]
Also, the Adobe CLA signature didn't seem to stick. Try closing and reopening the PR.

**Comment by keharper** [comment]
I gave the wrong command earlier. It should be

rake symlink:replace_at path=src/guides/v2.4/config-guide/bootstrap/magento-bootstrap.md

**Comment by Viper9x** [comment]
@BarnyShergold I've done the changes, please review.

**Review by BarnyShergold — APPROVED** [review]
This looks great now!
I used a text compare to check for actual changes :)

**Comment by Viper9x** [comment]
@BarnyShergold I want to modify the content for some pages (minor change), what should I do? Commit to this branch or create a new branch for it?

**Comment by BarnyShergold** [comment]
> @BarnyShergold I want to modify the content for some pages (minor change), what should I do? Commit to this branch or create a new branch for it?

Is it is directly related to this issue then you can add it to this PR. If they are unrelated pages then it should be a different PR. Also if you have small corrections to several pages then you can have a "Minor Corrections" PR - so you don't end up with 10 PRs each with one page and one tiny correction!

**Comment by Viper9x** [comment]
Yes, I have small corrections to several pages so I'll do it on another PR. Thanks @BarnyShergold

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8762`.

**Pull request merged**
