### PR TITLE
Added the error coverage for cmsPage query

### PR DESCRIPTION
**Pull request by dineshvb**
## Purpose of this pull request

This pull request (PR) adds the error coverage for cmsPage query.

## Affected DevDocs pages

-  /guides/v2.3/graphql/queries/cms-page.html
-  /guides/v2.4/graphql/queries/cms-page.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Comment by BarnyShergold** [comment]
@dineshvb - This PR is identical to one yesterday - can I suggest if you have very similar changes to do to multiple pages that they all get done on the same PR? It would help :)

**Comment by dineshvb** [comment]
> @dineshvb - This PR is identical to one yesterday - can I suggest if you have very similar changes to do to multiple pages that they all get done on the same PR? It would help :)

Yeah sure @BarnyShergold

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Pull request merged**
