### PR TITLE
Data migration tool doc update, map files override step, fixed typo

### PR DESCRIPTION
**Pull request by vovsky**
## Purpose of this pull request

This pull request (PR) clarifies info regarding path of mapping files that should be updated in config.xml file in case data migration tool is extended in separate module.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html#migration-config
- https://devdocs.magento.com/guides/v2.3/migration/extend-the-tool.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
@vovsky could you check the failing linting tests, please?

**Comment by dobooth** [comment]
running tests

**Comment by carlos-reynosa** [comment]
The changes here go agains @victor-v-rad said in a similar config issue. 

https://github.com/magento/devdocs/pull/6732#pullrequestreview-365807119

@rogyar

**Comment by victor-v-rad** [comment]
@carlos-reynosa is right. @rogyar @dobooth I would be thankful to be included into future reviewing process of each contribution into data migration tool.

**Pull request merged**
