### PR TITLE
Fixed broken URL links on REST API Overview menu

### LINKED ISSUE #7930: Feedback on page: /guides/v2.4/rest/bk-rest.html
# General issue

## Description:

Getting "404 Page not found" when I navigate to Admin REST endpoints by clicking one side menu Quick Reference > REST Endpoint (ReDoc) > Admin REST endpoints.

## Possible solutions:

Repairs the url

## Additional information:

I opened https://devdocs.magento.com/guides/v2.4/rest/bk-rest.html , this displays me REST API Overview section and a sidebar to navigate to different section. But, when I click on one of menu item Quick Reference > REST Endpoint (ReDoc) > Admin REST endpoints, it displays me "404 Page not found" page. 
image

This also happen when I navigate using any menu item of Quick Reference > REST Endpoint (ReDoc) .

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request

This pull request (PR) fixes #7930 

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.4/rest/bk-rest.html (Menu points)

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by BarnyShergold** [comment]
@jeff-matthews - Over to you

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
Thanks @BarnyShergold 🥇

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
