### PR TITLE
update links for logging methods

### PR DESCRIPTION
**Pull request by roman204**
The links of the methods where outdated, i input the correct links.

## Purpose of this pull request
The links of the methods where outdated, i input the correct links.

This pull request (PR) correct the links for to loggingInterface at github

## Affected DevDocs pages

-  [..](https://devdocs.magento.com/guides/v2.4/config-guide/log/log-magento.html)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@roman204 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]
Nice update

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
