### PR TITLE
Update ui-form.md

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will update ui-form definition and codebase as per Magento v2.3.x.

## Additional information
[Link](https://github.com/magento/magento2/blob/9cdc1b70c9a40c63fbb58ffd5a8e5385255ef319/app/code/Magento/Customer/view/base/ui_component/customer_form.xml#L8) to the codebase.

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-form.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@mage2pratik, can you include links to the codebase to help verify these doc updates?

**Comment by mage2pratik** [comment]
@jeff-matthews, added link in description.

**Comment by jeff-matthews** [comment]
Thanks @mage2pratik!

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
