### PR TITLE
setup_version not needed in magento 2.3

### PR DESCRIPTION
**Pull request by dani97**
As declarative schema is in magento 2.3 we don't need setup_version in module declaration

## Purpose of this pull request

This pull request (PR) is intended to remove setup_version mentioned in module declaration in module.xml for 2.3.X version under Initial boiler plate sections etc/module.xml section

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @dani97 Thanks for the contribution.
It looks like you are overwriting a symlink.
The proper way to do so it to:
- Delete the symlink file from the system with the `rm` command.
- Add a new file with your content to the PR.
If you just overwrite the symlink, it will fail in our build system. 
Fix that up and we can move on this PR.

**Comment by dani97** [comment]
@dobooth  thanks will make and update the PR

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4724) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4724) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dani97<br/>:x: Christopher Daniel<hr/>**Christopher Daniel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by dani97** [comment]
@dobooth  @rogyar  please validate the changes

**Comment by keharper** [comment]
@dani97  Module developers aren't absolutely required to implement declarative schema yet, so are we jumping the gun by deleting the reference to setup_version?

See https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/create_component.html

**Comment by dani97** [comment]
@keharper  Agreed. I have edited a you have suggested. :+1:

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
