### PR TITLE
Remove multi-tenant notice

### PR DESCRIPTION
**Pull request by Leland**
## Purpose of this pull request

This pull request (PR) removes notices of the now-removed multi-tenant compiler.

This command was removed entirely in 2016 as part of v2.1.0-rc1, see https://github.com/magento/magento2/commit/6bb447cbcacb9974a072aebdf31fd1e9ed7dc7c6 and https://github.com/magento/magento2/commit/f9236a7

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-compiler.html

## Links to Magento source code

-  https://github.com/magento/magento2/commit/6bb447cbcacb9974a072aebdf31fd1e9ed7dc7c6
- https://github.com/magento/magento2/commit/f9236a7

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @Leland. Thank you for your collaboration. Please, sign CLA to proceed the PR processing. 

Thank you

**Comment by Leland** [comment]
@rogyar done!

**Comment by dobooth** [comment]
running tests

**Pull request merged**
