### PR TITLE
fix broken troubleshooting link

### PR DESCRIPTION
**Pull request by sad270**
## Purpose of this pull request

Fix broken link after https://github.com/magento/pagebuilder-docs/pull/49

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@sad270 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]
Nice spot! Thanks for your first contribution.

You will need to sign the Adobe CLA before this PR can progress, this is something you only need to do once.

**Review by bdenham — COMMENTED** [review]
Just waiting on the workflow for the pagebuilder-docs site to get fixed. After it's ready, I'll tend to this fix. Thanks!

**Comment by sad270** [comment]
I change the page label into `Troubleshooting` too like the page name

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Comment by m2-github-services** [comment]
@bdenham the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-sad270-devdocs-9258`.

**Pull request merged**
