### PR TITLE
Added sensitive configuration of braintree phone

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will show the sensitive configuration of braintree phone
[Codebase file v2.2](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Braintree/etc/di.xml#L619)
[Codebase file v2.3](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Braintree/etc/di.xml#L619)

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/config-guide/prod/config-reference-sens.html
- https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-sens.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @ronak2ram!

**Comment by erikmarr** [comment]
Adding technical label back to provide points for the PR submission to devdocs.

**Pull request merged**
