### PR TITLE
Update project-routes-more-redir.md

### PR DESCRIPTION
**Pull request by theloveofcode**
The mapping key "partial" is invalid and results in the error: Unrecognized keys in mapping; Unknown key "partial"

The correct mapping key for this option is "prefix"

## This PR is a:

- [ ] New topic
- [ ] Content update
- [X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will correct the code samples under the "prefix" section.

## Additional information

List all affected URLs 
- https://devdocs.magento.com/guides/v2.1/cloud/project/project-routes-more-redir.html
- https://devdocs.magento.com/guides/v2.2/cloud/project/project-routes-more-redir.html
- https://devdocs.magento.com/guides/v2.3/cloud/project/project-routes-more-redir.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3703) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3703) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@theloveofcode thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
running tests

**Comment by hguthrie** [comment]
I'm sorry. I ran the tests yesterday and then something came up. I will run them again today and merge these changes when there is a window of opportunity.

**Comment by hguthrie** [comment]
running tests

**Pull request merged**
