### PR TITLE
Container component page: Update page content

### LINKED ISSUE #8571: Example not working - more information needed
# General issue

## Description:

Feedback on page: /guides/v2.4/ui_comp_guide/components/ui-container.html

There is not enough information provided to be able to test the example.
Where do we have to add the code?

I created a layout file for the checkout for testing and added the code into it:

**app\design\frontend\company\fresh\Magento_Checkout\layout\checkout_index_index.xml**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <container name="container_name">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="template" xsi:type="string">ui/form/components/complex</item>
                    <item name="sortOrder" xsi:type="number">10</item>
                    <item name="label" xsi:type="string">Container Label</item>
                    <item name="additionalClasses" xsi:type="string">sample-additional-class</item>
                    <item name="text" xsi:type="string" translate="true"><![CDATA[
                        <p>
                            Container Text.
                        </p>
                    ]]></item>
                </item>
            </argument>
            <field name="sort_direction"
                   sortOrder="20"
                   formElement="select">
                <settings>
                    <dataType>text</dataType>
                    <label translate="true">Sort Direction</label>
                    <dataScope>data.sort_direction</dataScope>
                </settings>
                <formElements>
                    <select>
                        <settings>
                            <options class="Vendor\Module\Model\Source\Config\SortDirection" />
                            <caption translate="true">-- Please Select --</caption>
                        </settings>
                    </select>
                </formElements>
            </field>
        </container>
    </body>
</page>
```

But I get this error:

**1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'argument': This element is not expected. Expected is one of ( block, container, referenceBlock, referenceContainer, uiComponent ).
Line: 3753**

So either your example is not working or you missed some important steps in the instructions.

### PR DESCRIPTION
**Pull request by Viper9x**
## Purpose of this pull request

Update **container component** page: Added more details about where <container> node be localted
Fixes #8571

## Affected DevDocs pages
Container component: https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-container.html

### CODE REVIEW

**Comment by Viper9x** [comment]
Can anyone tell me how can I add linked issues?
I want to add #8571 to linked issues.

**Comment by ajithkumar-maragathavel** [comment]
@Viper9x  If you are fixing a GitHub issue, note it using GitHub keyword format (https://help.github.com/en/articles/closing-issues-using-keywords#closing-an-issue-in-a-different-repository) to close the issue when this pull request is merged. 

Example: `Fixes #1234`

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

You  need to add this in the PR description.

**Comment by Viper9x** [comment]
Thanks @ajithkumar-maragathavel for your answer.
I don't have write permission to this repository so I can't _manually linking a pull request to an issue_. In this case, the way _Linking a pull request to an issue using a keyword_ work for me.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8807`.

**Pull request merged**
