### PR TITLE
Fixed code format issue

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
## Purpose of this pull request

- Corrected the `<code>` format issue.
- Removed un-necessary spaces
 
## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-radioset.html
-  https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-radioset.html

## Links to Magento source code

-  N/A

## Screenshot:
screenshot-devdocs magento com-2019 10 24-13_07_03

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @yogeshsuhagiya, thanks for your PR,

Can you take advantage of this PR, to make the board Markdown style? Will very useful.

Thanks!

**Comment by yogeshsuhagiya** [comment]
@osrecio Hi,
Will you please share some examples for table Markdown style?

**Comment by osrecio** [comment]
You have some examples here: More information: https://help.github.com/en/github/writing-on-github/organizing-information-with-tables

In the other PR that you created you had an example: https://github.com/magento/devdocs/pull/5832/files#diff-d54e2ea94cbe1aa68b8d27cab03aaff7L12

**Comment by hickskenh** [comment]
the fixed file has 2 close code commands.  needs to be fixed when the table is converted to markdown. line 18 <td><code>component</code></code></td>

**Comment by yogeshsuhagiya** [comment]
> the fixed file has 2 close code commands. needs to be fixed when the table is converted to markdown.
> image

Removed multiple close code commands.

**Comment by yogeshsuhagiya** [comment]
Hi @osrecio, I've updated PR as per your guidance, will you please take a look?

**Comment by dobooth** [comment]
running tests

**Pull request merged**
