### PR TITLE
Update technical-guidelines.md

### PR DESCRIPTION
**Pull request by neeta-wagento**
## This PR is a: Correct Grammatical mistake

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.1/coding-standards/technical-guidelines.html
https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html
https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3429) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3429) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: neeta-wagento<br/>:x: erikmarr

**Comment by erikmarr** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks, @neeta-wagento

**Pull request merged**
