### PR TITLE
Added cli command for static content signing to enable/disable

### PR DESCRIPTION
**Pull request by Mohamed-Asar**
## Purpose of this pull request

CLI command added for enable/disable static content signing

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/config-guide/cache/static-content-signing.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@Mohamed-Asar Please indicate what the 0/1 values indicate.

**Comment by Mohamed-Asar** [comment]
@keharper I have made the changes please review.

**Comment by keharper** [comment]
Thanks @Mohamed-Asar

**Pull request merged**
