### PR TITLE
Fix small typo in example

### PR DESCRIPTION
**Pull request by AlexCostello91**
## Purpose of this pull request

This pull request (PR) fixes a small typo in an example on extension attributes.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/extension_attributes/adding-attributes.html

### CODE REVIEW

**Comment by dobooth** [comment]
Good eye, @AlexCostello91. Please sign the Adobe CLA so that we may process this PR. Thanks.

**Comment by dobooth** [comment]
Thanks!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
