### PR TITLE
Wrong arguments for Stopwords directory

### PR DESCRIPTION
**Pull request by ntmhung**
The argument for directory of stopwords for <type name="Magento\Elasticsearch\SearchAdapter\Query\Preprocessor\Stopwords"> should be stopwordsDirectory, not fileDir.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-stopwords.html

## Links to Magento source code

-https://github.com/magento/magento2/blob/7ffabd074c457edb7a3f2d8eacbc21a1dd188692/app/code/Magento/Elasticsearch/etc/di.xml

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5191) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5191) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-engcom-team** [comment]
@ntmhung thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ronak2ram** [comment]
Hi @ntmhung 
Thanks for your contribution.
Can you please update the description.
Affected DevDocs pages, Links to Magento source code

**Comment by dobooth** [comment]
running tests

**Pull request merged**
