### PR TITLE
Add MSI to the Module Reference Guide

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request adds topics for MSI modules to the Module Reference Guide. The topics are generated from files at the `_data/mrg/msi`. The data files are generated from the [magento/inventory:1.1.2](https://github.com/magento/inventory/tree/1.1.2) codebase.

This also changes the `mgr-generator` plugin to generate topics from subdirectories in `_data/mrg`. The data files for topics have been rearranged in subdirectories. This is done to be able to process modules with the same names that exist in different categories like [Open Source](https://github.com/magento/magento2/tree/2.3-develop/app/code/Magento) and [MSI](https://github.com/magento/inventory/tree/2.3-develop/app/code/Magento).

## Additional details

Staging build: 907

### CODE REVIEW

**Comment by dshevtsov** [comment]
The table of contents is not complete.

**Comment by dshevtsov** [comment]
Fixed the table of contents

**Comment by dobooth** [comment]
@dshevtsov 455 changed files? Is that correct?

**Comment by keharper** [comment]
I spot-checked some of the MSI-specific topics, and they all look fine. However, we need to find a way to filter out all READMEs that are not specific to Inventory from the "Inventory Management" section. (All the modules that don't start with `Inventory` are duplicates from Open Source.)

**Comment by dshevtsov** [comment]
> @dshevtsov 455 changed files? Is that correct?

@dobooth Yes, this PR relocates existing files to subdirectories and adds new topic for each module in the MSI repository. 


> All the modules that don't start with `Inventory` are duplicates from Open Source.

@keharper, I confirmed this with @naydav. I will change the automation to filter the MSI modules by Inventory prefix and to update this PR.

**Comment by dshevtsov** [comment]
Removed the duplicates from MSI.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
