### PR TITLE
MAGETWO-93012 Make UI comp sections consistent

### PR DESCRIPTION
**Pull request by shrielenee**
## This PR is a:
- [ ] New topic
- [X] Content fix or rewrite
- [ ] Bug fix or improvement
 

## Summary
 
When this pull request is merged, it will make all sections in individual UI components pages consistent.

Summary: Removed top Overview heading, removed Structure sections, renamed other headings for consistency.
 

## Additional information

Jira: https://jira.corp.magento.com/browse/MAGETWO-93012

HTML preview: http://cicd1.corp.magento.com/~mmansoor/devdocs/gh-pages/branches/ss_MAGETWO-93012_UI-sections/_site/guides/v2.2/ui_comp_guide/components/ui-actiondelete.html

### CODE REVIEW

**Comment by shrielenee** [comment]
@bdenham Were you able to take a look at this?

**Comment by shrielenee** [comment]
Hold off on reviewing this for now @bdenham - I'm going to add links to blobs/working reference in API section.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2506) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2506) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: shrielenee<br/>:x: Shrie Spangler<hr/>**Shrie Spangler** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by shrielenee** [comment]
OOKKKKK - I revised based on your feedback, fixed all the merge conflicts, and created a new HTML preview. 🤙

**Comment by bdenham** [comment]
Boss! I'll review soon and merge.

**Comment by bdenham** [comment]
Thanks, Shrie! Big help!

**Pull request merged**
