### PR TITLE
Update php_codesniffer dependency version for 2.3.2

### PR DESCRIPTION
**Pull request by ffauvel**
## Purpose of this pull request

This pull request (PR) is changing the require version for php_codesniffer to 3.3.1 for magento 2.3.2 to fix composer error on updating to 2.3.2.

composer update with version 3.2.2 of php_codesniffer package, as mention in the doc, is not compatible with magento/magento-coding-standard 1.0.2.

Error from composer:
magento/magento-coding-standard 1.0.2 requires squizlabs/php_codesniffer ~3.3.0 -> satisfiable by squizlabs/php_codesniffer[3.3.0, 3.3.1, 3.3.2] but these conflict with your requirements or minimum-stability.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4919) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4919) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@ffauvel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Codebase reference: magento-coding-standard 1.0.2 requires codesniffer ~3.3.0 https://github.com/magento/magento-coding-standard/blob/f7de26fb6add389d1b42286f67ee87424588a868/composer.json#L12

**Pull request merged**
