### PR TITLE
magento/devdocs#: Add information about Magento_Persistent module for Magento 2.1 and 2.2 versions

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) adds missing description about  `Magento_Persistent ` module for Magento **2.1** and **2.2** versions.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.1/mrg/ce/Persistent.html
- https://devdocs.magento.com/guides/v2.2/mrg/ce/Persistent.html

## Links to Magento source code

- [2.1](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Persistent/README.md)
- [2.2](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Persistent/README.md)

Thank you!

CC: @erikmarr

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @atwixfirster!

**Comment by dshevtsov** [comment]
@erikmarr add whatsnew to the PR description

**Pull request merged**
