### PR TITLE
Update config-cli-subcommands-index.md

### PR DESCRIPTION
**Pull request by convenient**
## This PR is a:
- [ ] New topic
- [x] Content fix or rewrite
- [ ] Bug fix or improvement
 

## Summary
 
To display the updated `indexer:status` output
 

## Additional information
N/A

### CODE REVIEW

**Comment by shrielenee** [comment]
Thanks for changing this to markdown, @convenient!

**Comment by shrielenee** [comment]
I notice that this change also needs to be propagated to v2.1 and v2.3, as they are not currently symlinked (and so won't see the changes of this v2.2 file). Can you implement those changs and resubmit? Thanks!

**Comment by convenient** [comment]
@shrielenee completed 👍

**Comment by shrielenee** [comment]
Wonderful! Thanks @convenient. 🥇

**Pull request merged**
