### PR TITLE
Upgrade Bundler from 1.17.3 to 2.1.4, refs #8370

### LINKED ISSUE #8370: Container started using Docker Compose terminates with unexpected error
# Bug report

## Description

When using `docker-compose up` the container is terminated with the error below.

```
jekyll_1  | /usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /srv/jekyll/Gemfile.lock. (Gem::GemNotFoundException)
jekyll_1  | To update to the latest version installed on your system, run `bundle update --bundler`.
jekyll_1  | To install the missing version, run `gem install bundler:1.17.3`
jekyll_1  |     from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
jekyll_1  |     from /usr/local/bin/bundle:23:in `<main>'
```

### Steps to reproduce

- Clone the repository
- Run `docker-compose up`

## Expected result

Container is started without any issues.

## Possible solutions

Use `jekyll/jekyll:3` as the Docker image in the Docker Compose configuration.

### PR DESCRIPTION
**Pull request by Serializator**
## Purpose of this pull request

In this pull request Bundler is upgraded from 1.17.3 to 2.1.4, to resolve #8370

In #8370 I mentioned locking the `jekyll/jekyll` Docker image to `jekyll/jekyll:3` as a possible solution. But locking the version of a Docker image to be compatible with an outdated version of Bundler didn't seem like the right approach.

I did lock the Docker image to `jekyll/jekyll:4.0`, as it is / I find it to be a "Best Practice" to do so.

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Nice!

**Comment by dshevtsov** [comment]
We cannot upgrade Bundler to version 2 at the moment, because of other dependencies.

**Comment by dshevtsov** [comment]
cc @hguthrie

**Comment by Serializator** [comment]
@dshevtsov, what about locking the used Docker image within Docker Compose to `jekyll/jekyll:3`? Because `jekyll/jekyll` (latest) does not support Bundler 1.17.3.

**Comment by dshevtsov** [comment]
@hguthrie can you help with the Docker question?

**Pull request closed without merging**
