### PR TITLE
Add reference documentation for `bin/magento` commands

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) adds latest data for `bin/magento` commands reference at Magento OpenSource and Magento Commerce.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html
- https://devdocs.magento.com/guides/v2.4/reference/cli/magento-commerce.html

whatsnew
Updated `bin/magento` commands reference at [Magento OpenSource](https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html) and [Magento Commerce](https://devdocs.magento.com/guides/v2.4/reference/cli/magento-commerce.html).

### CODE REVIEW

**Comment by dshevtsov** [comment]
> Don't you need to break symlinks and create files for Commerce and Cloud?
> 
> ```
> devdocs/src/guides/v2.4/reference/cli/magento-commerce.md
> devdocs/src/guides/v2.4/reference/cli/magento-cloud.md
> ```

No, Cloud is versionless and has a separate release line. It is supported by @meker12

**Comment by jeff-matthews** [comment]
What about Commerce?

**Comment by dshevtsov** [comment]
As far as I know, @meker12 has plans to move this reference to `/cloud/`.

**Comment by dshevtsov** [comment]
> What about Commerce?

Commerce and OpenSource are not symlinks.
OpenSource was a symlink, but this pull request replaces it with a file.

**Comment by jeff-matthews** [comment]
The Commerce file is still symlinked to 2.3:

https://github.com/magento/devdocs/blob/ds_gendocs-magento-cli/src/guides/v2.4/reference/cli/magento-commerce.md

**Comment by dshevtsov** [comment]
> The Commerce file is still symlinked to 2.3:
> 
> https://github.com/magento/devdocs/blob/ds_gendocs-magento-cli/src/guides/v2.4/reference/cli/magento-commerce.md

Ah, you are right.
I added changes to the 2.3 version instead of 2.4.

**Comment by dshevtsov** [comment]
IDE showed it as a real file. Fixed.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
