### PR TITLE
Update upgrade-start.md

### PR DESCRIPTION
**Pull request by chirag-wagento**
## This PR is a:
- [ ] New topic
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement
 

## Summary
 Typo Fixes

When this pull request is merged, it will...

### CODE REVIEW

**Comment by chirag-wagento** [comment]
@keharper

Any update in this PR?

Thanks

**Comment by keharper** [comment]
@chirag-wagento We want to standardize on highlighting only the UI names when we list clickable paths on Admin and no highlighting on the > symbols. So, change **System > Tools > Web Setup Wizard** to **System** > **Tools** > **Web Setup Wizard**

Also changing "installs" to "install" on line 64 was incorrect. Please revert that change.

**Comment by chirag-wagento** [comment]
@keharper  As per your suggestion i committed new coding please check it.

Thanks

**Comment by keharper** [comment]
👍 Thanks, @chirag-wagento

**Pull request merged**
