### PR TITLE
Add the "XSS prevention strategies" page for 2.4.0 with the new approach to sanitize strings in the .phtml templates 

### PR DESCRIPTION
**Pull request by vasilii-b**
## Purpose of this pull request

This pull request (PR) updates the "XSS prevention strategies" page with the new approach to sanitize strings in .phtml templates since the Magento 2.4 (`2.4-develop` branch) changes.

The changes that took place in the Magento core are here - https://github.com/magento/magento2/commit/9125aa6a4af4a8d99a9980cc810b11368af4a99f

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/xss-protection.html

## Links to Magento source code

-  https://github.com/magento/magento2/commit/9125aa6a4af4a8d99a9980cc810b11368af4a99f
- https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/view/frontend/templates/product/list.phtml#L16

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Here's a couple of examples from `2.4-develop` codebase that show the deprecation fact of the mentioned methods.

- https://github.com/magento/magento2/blob/ba1a0990d00fa8592aafe731da7c66e7b3cebc51/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L909
- https://github.com/magento/magento2/blob/ba1a0990d00fa8592aafe731da7c66e7b3cebc51/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L923

**Comment by vasilii-b** [comment]
Hi @rogyar,
Thank you for the review.

I added the requested changes.

Thank you!

**Comment by dobooth** [comment]
Nice work, @vasilii-b, thanks.

**Comment by dobooth** [comment]
running tests

**Comment by jeff-matthews** [comment]
Is this related to #6057 @vasilii-b?

**Comment by vasilii-b** [comment]
Hi @jeff-matthews ,
Yes, that's related to #6057. As far as I see, the author changes the files in the `2.2` version, which is not correct. The new way to sanitize the strings comes with Magento 2.4-develop and the documentation in devdocs should be added for the 2.4 respectively.
Please let me know should there be any questions. Thank you!

**Comment by jeff-matthews** [comment]
Thanks for confirming and thanks for porting the original PR!

**Pull request merged**
