### PR TITLE
Update the install extension link

### PR DESCRIPTION
**Pull request by DanielSousa**
## Purpose of this pull request

Update with the correct link to show users how to install the extension from Marketplace

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-install.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @DanielSousa Thanks for the contribution. We recently stopped updating the v2.2 branch. Can you please update your repo and remove the v2.2 files from this PR. Then we should be able to merge this PR. Thanks!

**Comment by DanielSousa** [comment]
@dobooth Could you please check again? I reverted the changes on 3a20cac

**Comment by dobooth** [comment]
Very good! Thanks @DanielSousa

**Pull request merged**
