### PR TITLE
Updated example of logical AND and OR search

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will updated example of logical AND and OR search.
Currently display wrong result(The query returns 4 items). So, I've updated example.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/queries.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Hmm. The original example used to work. I've tested that your example works, but I want to understand why the original no longer works before I merge this PR.

**Comment by mage2pratik** [comment]
@keharper I'm not sure but may be sample data has been updated.

**Comment by keharper** [comment]
I can't figure out why the old query failed, but I've done my due diligence. Thanks for the updates, @mage2pratik

**Pull request merged**
