### PR TITLE
Modify a Core or 3rd party table

### PR DESCRIPTION
**Pull request by matinict**
Modify a Core or 3rd party table

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- ...

## Links to Magento source code

- ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@matinict thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by matinict** [comment]
Hi I am new here if any guide line please inform me .

**Comment by shrielenee** [comment]
Hey @matinict --- welcome! You can learn all about contributing in our wiki: https://github.com/magento/devdocs/wiki.

Let us know if you have any questions.

**Comment by shrielenee** [comment]
Oh, and also @matinict, go ahead and fill out the PR description form at the top of this page, answering the prompted questions. This gives us the info we need to begin processing your PR.

**Comment by matinict** [comment]
@rogyar Thanks for information, recently i face scenario base question on magento 2 exam but i can not clearly understand devdocs lack of my deep knowledge. it may be give clear instruction especially who are beginner level programmer like me.

**Comment by rogyar** [comment]
Hi @matinict. Let's discuss concrete points where there's a lack of clear instructions.

The question is "How to add a column to a table using the declarative schema?"
The detailed answer is here: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html#add-a-column-to-table

So, basically, we have this information. I'm curious what another problem we are trying to solve here? 
From my understanding, it's a missing mention that you can add a column in the same way to any table (however, this point should be obvious since there are no mentions about limitations of this method). So, we may provide a few words for clarifying this point, that's exactly what I've suggested. 

However, bringing another example which is almost the same as the existing example is really confusing practice. If we have thousands of similar examples, this fact will not be helpful for developers at all.

If not talking about the code, this practice is like the following. We have information and an example of how to open the door by a key. Then, instead of mentioning that this information is applicable for all key colors (golden, bronze, silver), we provide a separate example of how to open the door with different key colors (keeping in mind absolutely the same process). 

Then we have 10 doors and 30 examples of the same process. I would say that describing the process in that way will make the documentation uneffective.

**Pull request closed without merging**
