### PR TITLE
magento/devdocs#: Add removeCouponFromCart mutation API errors

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) adds information about the API errors of `removeCouponFromCart` mutation.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/mutations/remove-coupon.html

## Links to Magento source code

- [Cart does not contain products.](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Resolver/RemoveCouponFromCart.php#L68)
- [Could not find a cart with ID "XXX"](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php#L61)
- [Current user does not have an active cart.](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php#L76)
- [Required parameter "cart_id" is missing](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Resolver/RemoveCouponFromCart.php#L54)
- [The coupon code couldn't be deleted. Verify the coupon code and try again.]()
- [The current user cannot perform operations on cart XXX](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php#L99)
- [Wrong store code specified for cart](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php#L83)

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@atwixfirster @rogyar Under what circumstances would the first message (`Cart does not contain products.`) be returned? Would the integrator be required to remove an applied coupon before removing the last product from a cart? If yes, then we should say that in the main section of this topic.

If any further changes are required to this topic, be sure to pull in my changes into your local branch.

**Comment by atwixfirster** [comment]
@keharper 
> Under what circumstances would the first message (Cart does not contain products.) be returned? 

When customer's cart is empty. Please check [Magento\Quote\Model\CouponManagement](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Quote/Model/CouponManagement.php#L89).

Customer's quote(cart) keeps a coupon code in the `quote`.`coupon_code` field. So, quote may be without products but with coupon :)

Please let me know if my explanations are clear for you.

Thank you!

**Comment by keharper** [comment]
@atwixfirster Here's my scenario

1. I add one product to the cart. For example, the water bottle (sku: "24-UG06").
2. I apply the `H2O` coupon.
3. I remove the water bottle from the cart. The cart is now empty.
4. I try to remove the coupon. I get the error message.
5. I add an unrelated product to the cart. 
6. I try to remove the coupon. Success.

To me, this is not the expected behavior. So, I'd like to add a note to the main section stating that you can't run the `removeCouponFromCart` mutation if the cart is empty.

**Pull request merged**
