### PR TITLE
Update codebase-changes.md

### PR DESCRIPTION
**Pull request by irenelagno**
## Purpose of this pull request

This pull request (PR) adding information about version policy for @api class update. 

whatsnew
Added 'New optional method argument' to both `PHP Interface` and to `PHP Class` in [Codebase Changes](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/codebase-changes.html).

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4676) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4676) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@irenelagno thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by joni-jones** [comment]
@irenelagno, please, add the same rule for @api interfaces.

**Comment by irenelagno** [comment]
@joni-jones , added

**Comment by dobooth** [comment]
running tests

**Pull request merged**
