### PR TITLE
Fixed table format issue

### PR DESCRIPTION
**Pull request by jignesh-baldha**
## This PR is a:
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement
 

## Summary
Fixed table format issue.
Please check table format issue in below links:
https://devdocs.magento.com/guides/v2.1/howdoi/howdoi_contribute.html
https://devdocs.magento.com/guides/v2.2/howdoi/howdoi_contribute.html
https://devdocs.magento.com/guides/v2.3/howdoi/howdoi_contribute.html

### CODE REVIEW

**Comment by shrielenee** [comment]
Hey @jignesh-baldha - I am rejecting this PR because we aren't facilitating the change of markdown tables to HTML tables. We typically use markdown for all coding, unless there is an existing HTML table. However, markdown tables are perfectly fine. Thanks for your contribution proposal - until next time!

**Comment by jignesh-baldha** [comment]
@shrielenee Hi, I've found markup table doesn't appear correct in following link, so I've changed markup table to html table.
https://devdocs.magento.com/guides/v2.1/howdoi/howdoi_contribute.html
https://devdocs.magento.com/guides/v2.2/howdoi/howdoi_contribute.html
https://devdocs.magento.com/guides/v2.3/howdoi/howdoi_contribute.html
contributor sign up sheet magento 2 developer documentation

**Comment by keharper** [comment]
I've encountered this type of problem before. Please remove all the glossarytooltip tags from the table.

**Comment by jignesh-baldha** [comment]
@keharper Removed glossarytooltip from markup table and changes committed.

**Comment by keharper** [comment]
@jignesh-baldha And you also removed the blank line at the end of the table. Perfect. Thanks!

**Pull request merged**
