### PR TITLE
Generated backward incompatible changes reference for Magento 2.2.10

### PR DESCRIPTION
**Pull request by devops-devdocs**
Adding reference documentation about backward incompatible changes introduced by Magento 2.2.10.

whatsnew
Added [Backward incompatible changes reference](https://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes/reference.html#releases-2_2_9-2_2_10) for the Magento 2.2.10 release.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@devops-devdocs thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
