### PR TITLE
Update resource_customer_addresses.html

### PR DESCRIPTION
**Pull request by timrsfo**
added json for get customer addresses, get address by id and update address

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
Thanks!

**Comment by xcomSteveJohnson** [comment]
@timrsfo If you'll tell me your first and last time, I'll be glad to add it to the pages you changed. If you'd like, I can add a link to your web site as well.

**Comment by timrsfo** [comment]
@xcomSteveJohnson  Steve, I don't have a webpage, my name is Tim Reynolds

**Comment by xcomSteveJohnson** [comment]
@timrsfo I added your name to this page: http://devdocs.magento.com/guides/m1x/api/rest/Resources/resource_customer_addresses.html

Please tell me what you think. Does it look OK? If so I'll add you to the other two pages. Otherwise, let me know what you'd like me to change.

Thanks again

**Pull request merged**
