### PR TITLE
magento/devdocs#5249: Markdown linting: Spaces after list markers (MD030). Part 01

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request provides changes regarding `Markdown linting: Spaces after list markers (MD030)` rule in the folder: `_includes`. 

**Part 01**

## Affected DevDocs pages

- ...

## Links to Magento source code

- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by atwixfirster** [comment]
@jeff-matthews , could you please verify now.

Many thanks as always :)

**Comment by atwixfirster** [comment]
> Try to resist the urge to change note classes in future PRs ;)

@jeff-matthews , you are the BOSS here but I want to inform you that per Dmitry Shevtsov notice in https://github.com/magento/devdocs/pull/4908 we should use a short format for note classes.

Thank you!

**Comment by jeff-matthews** [comment]
Yes of course. That's true, but per issue description in #5249, you should limit scope to resolving MD030 errors only. It'll make PR reviews faster and easier.

**Comment by atwixfirster** [comment]
> Yes of course. That's true, but per issue description in #5249, you should limit scope to resolving MD030 errors only. It'll make PR reviews faster and easier.

sure, BOSS

Thank you!

**Comment by jeff-matthews** [comment]
@atwixfirster,

It appears that I made a mistake when planning the initiative for #5249. I failed to take into account how many PRs would be associated with this effort. Awarding a Special achievement label (30 points) for each of the [26 PRs that you created](https://github.com/magento/devdocs/pulls?q=is%3Apr+label%3A%22Special+achievement%22+is%3Aclosed+author%3Aatwixfirster) creates imbalance in the community and is contrary to the spirit and intent of the rewards program.

I apologize for the mistake, but I'm going to have to award you a single Special achievement label for all  the PRs that you created related to this issue. The remaining will receive the `Editorial` label.

I'm reviewing all other MD linting issues and PRs to apply the same standard to other contributors. See #5720. 

Thank you for your all of your contributions to devdocs. We truly appreciate it.

**Comment by jeff-matthews** [comment]
@atwixfirster, 

I'm not denying that I made that announcement. I consider that announcement the mistake. I am taking responsibility.

**Pull request merged**
