### PR TITLE
MQP Release 1.0.5

### PR DESCRIPTION
**Pull request by Rykh**
## Purpose of this pull request

Added RN for MQP v1.0.5

## Affected DevDocs pages

https://devdocs.magento.com/quality-patches/release-notes.html

whatsnew
Published [release notes](https://devdocs.magento.com/quality-patches/release-notes.html) for the 1.0.5 Magento Quality Patch (MQP) package release.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
@Rykh, do you want the release notes published right away or at a specific time in the future?

**Comment by Rykh** [comment]
> @Rykh, do you want the release notes published on devdocs right away or at a specific time in the future?

Please publish these changes right now

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
