### PR TITLE
Fixed javascript code sample

### PR DESCRIPTION
**Pull request by barbanet**
Entities < and > were replaced.

## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix the javascript content sample for widget initialization.

The initializacion javascript code is using htmlentities.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_modal.html
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_modal.html
- https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_modal.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@barbanet thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
Thanks for this @barbanet! 🎉

**Comment by shrielenee** [comment]
running tests

**Comment by navarr** [comment]
@shrielenee could you please add a "Partner: Mediotype" label to this PR?

**Pull request merged**
