### PR TITLE
Add new Page Builder links

### PR DESCRIPTION
**Pull request by bdenham**
## Purpose of this pull request

This pull request (PR) adds new Page Builder links to devdocs home page and within Developer main nav menu.

whatsnew
Links to the Page Builder Developer Guide are now more accessible from the [devdocs homepage](https://devdocs.magento.com) under the Frontend Development section, as well as within the Development main nav menu.

### CODE REVIEW

**Comment by bdenham** [comment]
running tests

**Comment by jeff-matthews** [comment]
Staging builds are really helpful for PRs like this. Also, did you consider adding a Page Builder topic (similar to [PWA](https://devdocs.magento.com/guides/v2.3/pwa/)) so that it shows up in search results?

**Comment by jeff-matthews** [comment]
Also, if you want this to appear on the whastnew page, you need to change the label to editorial, technical ,or major update.

**Comment by bdenham** [comment]
Got it. I'll add all missing elements. Thanks!

**Pull request merged**
