### PR TITLE
Add SelectionProvider

### PR DESCRIPTION
**Pull request by gioal**
## Purpose of this pull request

This pull request (PR) ...

This pull-request aims to clear some doubts on how to bring the data from a listing to the form to persist in the database.
Researching some solutions, it was notable that in StackOverflow other developers are experiencing the same difficulty, usually solved by JavaScript. But, there is this feature made available in magento to give this type of support in a much simpler and more practical way.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-insertlisting.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@gioal thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
I suspect that the description could be clarified a bit. Can one of you give me a plain-speech version of what this attribute does?

**Comment by gioal** [comment]
Good Morning,

Through the InsertListing component we can make a listing within a form,
correct? Within the list we can use the component 'selectionsColumn' to
select the items listed.
The 'selectionsProvider' component brings exactly all items selected for
the same request, so we can work with all the data in the controller.
Without this 'selectionsProvider' the items selected in the list do not
arrive in the controller request.

Em ter., 3 de mar. de 2020 às 12:48, Donald Booth <notifications@github.com>
escreveu:

**Comment by dobooth** [comment]
running tests

**Pull request merged**
