### PR TITLE
Fixed unused script

### PR DESCRIPTION
**Pull request by gelanivishal**
## Purpose of this pull request

This pull request (PR) removed unused script which threw an error on the console log. This PR is related to https://github.com/magento/devdocs/issues/7935 issue

## Affected DevDocs pages

Link: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_collapsible.html
Link: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_collapsible.html (v2.3)
(All pages)

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Can you add a link to the 2.3 version of the page which is also affected?

Please also change "through" to "threw"

**Comment by gelanivishal** [comment]
Hi @BarnyShergold 

That error comes from only one page so after merge it will remove v2.3 also.

**Comment by BarnyShergold** [comment]
Yes but we still usually put links to both pages as when you are using the DevDocs site both pages are affected

**Comment by gelanivishal** [comment]
Updated.

**Comment by BarnyShergold** [comment]
BTW I remember someone mentioning this _satellite and then remembered #7935 - can you link this PR to that issue please?

**Comment by gelanivishal** [comment]
How do I link it?

**Comment by BarnyShergold** [comment]
Normally if you put the issue in the description (eg This pull request (PR) fixes #7935) it picks it up and does it for you

You should be able to click on the "Linked Issues" on the right menu of the PR and then type in the issue number.

If neither of these work, we can ask one of the Adobe people

**Comment by dobooth** [comment]
In the description add a line that says `Fixes #IssueNumber` or `Closes #IssueNumber`

**Comment by dobooth** [comment]
running tests

**Review by dobooth — APPROVED** [review]

**Pull request merged**
