### PR TITLE
lk_80789_reindex-how-to

### PR DESCRIPTION
**Pull request by lorikrell**
## This PR is a:
[X] New topic
[ ] Content fix or rewrite
[ ] Bug fix or improvement
 

## Summary
Adds new content for 2.2.5 reindex in parallel mode. Added content into an existing topic Manage the indexers.
- Add Reindex in Parallel Mode 
- MAGETWO-80789 - content from dev
- Removed symlink and added new topic with added section. Content for 2.2.5

## Additional information
Moved from internal PR https://github.com/magento/devdocs_internal/pull/1801

whatsnew
Added [Reindex in Parallel mode](https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-index.html#config-cli-subcommands-index-reindex-parallel) for new indexing options with better performance.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=1959) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=1959) before we can accept your contribution.<br/>

**Comment by jcalcaben** [comment]
Testing comment

**Comment by keharper** [comment]
Due to weird GH issues, I sent Lori my comments offline.

**Comment by lorikrell** [comment]
Review comments from Kevin. Adding in PR comment (inline comments encountering issues on Github).

`magento indexer:info` content out of date
```
design_config_grid                       Design Config Grid
customer_grid                            Customer Grid
catalog_category_product                 Category Products
catalog_product_category                 Product Categories
catalog_product_price                    Product Price
catalog_product_attribute                Product EAV
catalogrule_rule                         Catalog Rule Product
catalogrule_product                      Catalog Product Rule
cataloginventory_stock                   Stock
catalogsearch_fulltext                   Catalog Search
```
- Done, updated command results and formatted.

Check all command code formatting: wrap all the command line examples in ''' bash tags (only with backticks instead of single quotes).
- Done, updated all code formatting in topic.

`In Magento 2.2.5` > Change to "As of" (unless you know the behavior will change in 2.2.6
- Done. Updated. For 2.3, will remove symlink and create another file. Will remove mention 2.2.5 from 2.3 file.

Change your `<div> to
<div class="bs-callout bs-callout-info" markdown="1">
And then git rid of the `<p>` and `</p> tags
- Done, updated format.

**Comment by lorikrell** [comment]
Merging when 2.2.5 goes live.

**Pull request merged**
