### PR TITLE
Update guides/v2.3/install-gde/prereq/prereq-overview.html

### PR DESCRIPTION
**Pull request by ygyryn**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...
- Change outdated text regarding  already released Magento release 2.3,0.
- Added link to release notes page.

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.3/install-gde/prereq/prereq-overview.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by ygyryn** [comment]
Thank you for!

**Comment by ygyryn** [comment]
Thank you!

**Pull request merged**
