### PR TITLE
Remove  from pages because index.php removed from Magento v2.4

### PR DESCRIPTION
**Pull request by Viper9x**
## Purpose of this pull request

This pull request (PR) removed `index.php` from pages because index.php removed from Magento v2.4

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/config-guide/db-profiler/db-profiler.html
https://devdocs.magento.com/guides/v2.4/architecture/archi_perspectives/components/modules/mod_and_areas.html
https://devdocs.magento.com/guides/v2.4/comp-mgr/prereq/prereq_compman-checklist.html
https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/example/environment-variables.html
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/prepare/dev-modtypes.html
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/package/package_module.html

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Can't make comments on your PR so - 

1 issue : 
**db-profiler.md**
Line 56 : Should this not be <magento_root>/pub/index.php? According to a file compare this 2.4 file is still the same as the 2.3 version.

**Comment by Viper9x** [comment]
@BarnyShergold Thanks for your report. You are right, I've just copy the file but I forgot update file content. I'll update this file then push it now.

**Review by BarnyShergold — APPROVED** [review]
👍

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8821`.

**Pull request merged**
