### PR TITLE
PAY-226: Info architecture for Magento Payments

### PR DESCRIPTION
**Pull request by shrielenee**
## Purpose of this pull request

This pull request (PR) creates a draft of initial EAP Magento Payments info architecture.

See preview build [91](https://devdocs.magedevteam.com/91/magento-payments/payments.html).

This is one of two PRs to satisfy PAY-226---the other PR is in the MerchDocs repo: https://github.com/magento/merchdocs/pull/890.

This PR will merge into an integration branch.

## Affected DevDocs pages

-  magento-payments/payments.html and child pages

## Links to Magento source code

-  ...

### CODE REVIEW

**Review by crmccann — APPROVED** [review]
After mini-demo at daily and explanation in slack it looks good as a start and we will be iterating a lot here.

**Comment by jeff-matthews** [comment]
Sorry it took me a while to get to this @shrielenee. I was reviewing a monster PR. 

My only comment on this is that the metadata (aka front matter) for your placeholder files includes obsolete parameters. The only required parameters in devdocs right now are `group` and `title`, but since you've added a scope for your payments docs in the `_config.yml` file, I don't think you even need the `group` parameter; you just need `title`.

**Comment by shrielenee** [comment]
> Sorry it took me a while to get to this @shrielenee. I was reviewing a monster PR.
> 
> My only comment on this is that the metadata (aka front matter) for your placeholder files includes obsolete parameters. The only required parameters in devdocs right now are `group` and `title`, but since you've added a scope for your payments docs in the `_config.yml` file, I don't think you even need the `group` parameter; you just need `title`.

@jeff-matthews  Gotcha. Is it preferable to use a scope, or to do the `group` parameter for new topics? I can use either method.

**Comment by jeff-matthews** [comment]
@shrielenee, I actually don't think we have a preference. Either way os fine. Using a scope may be more efficient. What do you think @dshevtsov?

**Comment by dshevtsov** [comment]
I do not recommend to use configuration scope on a guide level.
We use scope defaults for parameters that cannot be defined in topics such as multirepos and autogenerated topics, or that can be applied entirely to all documentation or to all guides of a version.
Usage of scope defaults on a guide level would make it huge and hard to maintain.

**Pull request merged**
