### PR TITLE
Updated What's New for the 2.3.4 release

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) adds what's new entries pulled from the `2.3.4-develop` release integration branch.

I was able to pull 6 entries only (all `Technical`), which seems to indicate that we're not using labels for all release work.

See this query for a list of PRs to the `2.3.4-develop` branch: https://github.com/magento/devdocs/pulls?q=is%3Apr+base%3A2.3.4-develop+is%3Aclosed 

I wonder if the the revert in #6349 has anything to do with the lack of entries...

Ran the following command to pull entries:

```
rake whatsnew since='dec 11 2019'
```

I'm not seeing an entry for the new topic added in #6107. 

## Affected DevDocs pages

-  https://devdocs.magento.com/whats-new.html

### CODE REVIEW

**Comment by keharper** [comment]
My GraphQL updates are missing. For example:

https://github.com/magento/devdocs/pulls?q=is%3Amerged+is%3Apr+label%3A2.3.4+author%3Akeharper+label%3A%22Major+update%22

**Comment by jeff-matthews** [comment]
> https://github.com/magento/devdocs/pulls?q=is%3Amerged+is%3Apr+label%3A2.3.4+author%3Akeharper+label%3A%22Major+update%22

That's because the tool only pulls from one branch. The PRs you mentioned @keharper were merged into 2-3 different base branches. So to grab these updates, it looks like I'll have to run the tool multiple times on different branches.

**Comment by dshevtsov** [comment]
> So to grab these updates, it looks like I'll have to run the tool multiple times on different branches.

yes

**Comment by jeff-matthews** [comment]
Added entries from defunct `develop` and `Q4-integration` branches.

**Comment by keharper** [comment]
I only included the "Major Update" label in my previous comment because I don't know how to use an OR filter in GH (if they exist).

I added these new topics in 2.3.4, but they're missing here:

* 5562
* 5899
* 5900

This is the only Technical PR that has a whatsnew statement but isn't in this draft

* 6468

**Comment by jeff-matthews** [comment]
I think it's because the label in the tool config doesn't match the actual lable we use on GitHub (`New topic`).

```
# Name of the base branch in GitHub PRs
base_branch: Q4-integration

# Repositories for scanning. If you want to search private repositories, use credentials to specify 
repos:
  - magento/devdocs

# Labels for filtering (currently, hard-coded)
labels:
  - New doc
  - Major update
  - Technical

# Output format
output_format:
#  - markdown
  - yaml
  
```

**Comment by jeff-matthews** [comment]
Thanks @keharper. The PRs you mentioned are now in there.

#6468 was already there: https://github.com/magento/devdocs/pull/6495/files#diff-55941e922b7ce68e108ed55dc309977eR14

**Comment by jeff-matthews** [comment]
Looks like I still need to grab 6107.

**Comment by jeff-matthews** [comment]
I think i'm finally done

**Comment by jeff-matthews** [comment]
man... no wonder no one wants to do this task. it's a huge pain in the ass

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by meker12** [comment]
> I think it's because the label in the tool config doesn't match the actual lable we use on GitHub (`New topic`).
> 
> ```
> # Name of the base branch in GitHub PRs
> base_branch: Q4-integration
> 
> # Repositories for scanning. If you want to search private repositories, use credentials to specify 
> repos:
>   - magento/devdocs
> 
> # Labels for filtering (currently, hard-coded)
> labels:
>   - New doc
>   - Major update
>   - Technical
> 
> # Output format
> output_format:
> #  - markdown
>   - yaml
>   
> ```

I submitted a PR to the whatsup_github project to correct the "New topic" label in the template for the whatsnew.yml file.  (https://github.com/dshevtsov/whatsup_github/pull/12)

We can manually edit the `whatsnew.yml` file to fix change the topic label, but if we update it in the tool, then we'll get the right value when we install the tool.

**Pull request merged**
