### PR TITLE
Fix custom logo example

### LINKED ISSUE #7276: Incorrect parameter specified for theme logo
# Bug report

## Description

In the current documentation for creating a custom theme, the instructions for specifying a custom logo uses an incorrect parameter name, which means the logo will not be displayed.

### Steps to reproduce

1. Follow directions at https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-create.html#logo_declare to specify a logo file other than `logo.svg`
1. Logo is not displayed

## Expected result

Logo is displayed correctly.

## Possible solutions

The parameter `logo_src` should instead be `logo_file`. This is because `\Magento\Theme\Block\Html\Header\Logo.php` uses the function `getLogoFile()` to get the path of the image to be used.

### PR DESCRIPTION
**Pull request by styler3**
## Purpose of this pull request
Fixes #7276 
Fix the example for declaring a custom theme logo. If the argument `logo_src` is passed, this will directly inject the passed string into the images `src` attribute. This is not correct in the example and is unlikely to be correct in most cases.

The `logo_file` argument will use the correct, fully qualified, static versioned URL.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-create.html

## Links to Magento source code

-  https://github.com/magento/magento2/blob/8d90d12c2e0573a5ff898d6695cf730cd5a5792c/app/code/Magento/Theme/Block/Html/Header/Logo.php#L138

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by aligent-lturner** [comment]
Fixes #7277

**Comment by dobooth** [comment]
running tests

**Comment by bdenham** [comment]
@rogyar Please add a whatsnew entry to your description below your Links entry. Thanks.

**Pull request merged**
