### PR TITLE
Updated Extension guides links to 2.4 release line

### PR DESCRIPTION
**Pull request by igorin**
## Purpose of this pull request

- changed links to PHP dev guide, Best Practices, Magento Web API, Frontend dev guide to 2.4 release line
- fixed mistake "submitting your extension review" to "submitting your extension for Marketplace review"

## Affected DevDocs pages

-  https://devdocs.magento.com/marketplace/sellers/extension-create.html

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
running tests

**Review by BarnyShergold — APPROVED** [review]
Nice updates

**Comment by jeff-matthews** [comment]
New commits killed the test run

**Comment by BarnyShergold** [comment]
We seem to have a cross-bleed between this PR and #8100

**Comment by BarnyShergold** [comment]
@igorin - Please can you fix this PR? We've not heard from you for a week 😄

**Comment by dobooth** [comment]
running tests

**Pull request merged**
