### PR TITLE
Clarify "most popular" recommendation name

### PR DESCRIPTION
**Pull request by misha-kotov**
## Purpose of this pull request

This pull request (PR) fixes a recommendation name.

## Affected DevDocs pages

https://devdocs.magento.com/recommendations/test.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by nuzil** [comment]
@misha-kotov want to get some contributor points? :-D

**Comment by misha-kotov** [comment]
@nuzil I'm trying to get on the leaderboard! 🏅

**Comment by dobooth** [comment]
running tests

**Comment by nuzil** [comment]
@misha-kotov dont forget Contribution Survey :-)

**Pull request merged**
