### PR TITLE
example snippet added for composer.json

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - added example snippet for composer.json topic

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/composer-integration.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
I'm not committing to doing a full review at this time, but make sure the sample code you're committing is valid. The PHP versions are very outdated.

**Comment by chandru-199** [comment]
Thanks @keharper . I have changed to the php versions.

**Comment by dobooth** [comment]
running tests

**Comment by chandru-199** [comment]
Why this PR closed without Any labels?

**Comment by jeff-matthews** [comment]
Looks like an oversight on our part @chandru-199.

@dobooth, please apply the appropriate label.

**Comment by chandru-199** [comment]
Thanks Jeff....

**Pull request merged**
