### PR TITLE
Removed duplicated section

### PR DESCRIPTION
**Pull request by vkublytskyi**
## Purpose of this pull request

This pull request (PR) fixes "What is being checked" section duplication at https://devdocs.magento.com/marketplace/sellers/mftf-vendor.html

## Affected DevDocs pages

-  https://devdocs.magento.com/marketplace/sellers/mftf-vendor.html

CC @keharper, @dobooth

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Hmm, have you signed the Adobe CLA, @vkublytskyi ? If not, please do.

**Comment by vkublytskyi** [comment]
@dobooth, strange. Previously made a contribution and the system recognized me as an employee. Anyway signed now.

**Comment by dobooth** [comment]
I thought it strange too, @vkublytskyi. Sometimes opening and closing the PR gets it into the correct status. Please update the branch and ping me when you do and I can merge it.

**Comment by vkublytskyi** [comment]
@dobooth branch updated

**Comment by dobooth** [comment]
running tests

**Pull request merged**
