### PR TITLE
Update ReleaseNotes2.1.16CE.md

### PR DESCRIPTION
**Pull request by ygyryn**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...
update path settings to correct in sections: General, Reports

## Additional information
List all affected URLs 
https://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.16CE.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
@jfrontain to investigate

**Comment by jfrontain** [comment]
Thanks!

**Comment by jcalcaben** [comment]
running tests

**Pull request merged**
