### PR TITLE
Dead links on the Code Contributions page, updated all 404 pages with correct pages.

### PR DESCRIPTION
**Pull request by manishmittalm**
Dead links on the Code Contributions page has been removed and updated all 404 pages with correct pages.

## Purpose of this pull request

Dead links on the Code Contributions page has been removed and updated all 404 pages with correct pages.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html
https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by manishmittalm** [comment]
@dshevtsov @dobooth I have added fixes as suggested, please review.

**Comment by manishmittalm** [comment]
@sdzhepa Please help to review this. Thanks

**Comment by dshevtsov** [comment]
@dobooth, please approve the pull request if you don't have objections regarding the changes.

**Comment by manishmittalm** [comment]
Any update on this?

**Comment by manishmittalm** [comment]
@magento please take action on this, its being pending since long time.

**Comment by dobooth** [comment]
Hi @manishmittalm Sorry for the delay. The entire company was shut down all last week for a holiday.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
