### PR TITLE
Add newly introduced field(EE only) in config guide - Synchronize with Catalog

### PR DESCRIPTION
**Pull request by sandipklevu**
Field info added - Synchronize with Catalog
Module name: `Magento_InventoryCatalog`

## Purpose of this pull request

This pull request (PR) provides information about the newly introduced field in the 2.3.5 Commerce Edition.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-most.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@sandipklevu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by sandipklevu** [comment]
> Hi @sandipklevu. Could you clarify, please, within the scope of what module this new option has been introduced? Thank you.

Module name added

**Comment by dobooth** [comment]
Hi @sandipklevu Can you please sign the Adobe CLA so we can process your PR? Thanks!

**Comment by sandipklevu** [comment]
> Hi @sandipklevu Can you please sign the Adobe CLA so we can process your PR? Thanks!

Hi @dobooth, I signed the Adobe CLA.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
