### PR TITLE
2 times describes

### PR DESCRIPTION
**Pull request by kdey-adobe**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@kdey-adobe thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please fill out the PR description as required (even though this is a small change) and give the PR a more meaningful title. You also need to add the pages affected and sign the Adobe CLA. Thanks

**Comment by dobooth** [comment]
Closing for lack of CLA.

**Pull request closed without merging**
