### PR TITLE
DEL: doc section related to enable_lazy_loading_for_images_without_borders

### PR DESCRIPTION
**Pull request by GrimLink**
## Purpose of this pull request

Removes the docs related to the option `enable_lazy_loading_for_images_without_borders`.
This section is not needed anymore when PR magento/magento2#30139 is merged.

For info on why and how.
Please read the related PR.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-images.html#lazy_loading

## Links to Magento source code

See the PR for the changed files:
-  https://github.com/magento/magento2/pull/30139

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by BarnyShergold — APPROVED** [review]

**Comment by jeff-matthews** [comment]
Since the code PR hasn't been merged yet, we can't merge this doc PR. I'm guessing that the code PR will be merged for the 2.4.2 release. If that's true, then this Pr will need to be rebased onto the `2.4.2-develop` branch.

**Comment by dobooth** [comment]
@GrimLink So if this is indeed for 2.4.2, it should be rebased here.

**Comment by GrimLink** [comment]
@dobooth I have changed the target branch to 2.4.2-develop.

@jeff-matthews The PR has been megred for the 2.4.2 release -> https://github.com/magento/magento2/issues/30186#issuecomment-701115821

**Comment by dobooth** [comment]
@BarnyShergold Can you please look at line 185? It seems to want to say "outside of the defined module", or rather "outside of the module in which it is defined."

**Comment by BarnyShergold** [comment]
@dobooth - Good spot, that line doesn't make sense even before the changes.

IMO I think it may also be trying to say "Variables may be used within the scope of modules other than the defined one"?

What do you think @GrimLink ?

**Comment by GrimLink** [comment]
@BarnyShergold wille I agree.
And your suggestion makes this line better.
This should be its own PR.

This PR is purely for the removal of a section for a feature that is going to be removed in Magento 2.4.2

**Comment by BarnyShergold** [comment]
Like code if we spot an error in a file we are modifying in docs we should simply fix it. 

Otherwise, someone will have to create another PR and go through the whole process when it would take 5 mins to reword on this PR. 

@hguthrie  @meker12 - What's the opinion of the Docs team?

**Comment by hguthrie** [comment]
Regarding PR scope creep, I do advocate keeping within scope.
However, it is at the Author's discretion if they feel comfortable making the additional change, as long as it is **clearly** noted in the PR description.

**Comment by BarnyShergold** [comment]
@hguthrie - Okay if that is the general practise, I'll go with this - we should therefore consider this PR reviewed and passed - thanks for the feedback

**Comment by hguthrie** [comment]
> @hguthrie - Okay if that is the general practise, I'll go with this - we should therefore consider this PR reviewed and passed - thanks for the feedback

It is the general practice, although we discourage tiny updates, like a single spelling correction, because it does create unnecessary overhead. For things like that, it is better to group those changes in a single PR.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Pull request merged**
