### PR TITLE
Add command to configure varnish section so that Varnish is purged wh…

### PR DESCRIPTION
**Pull request by mattskr**
## Purpose of this pull request

Updates cloud docker documentation with the extra command to configure Varnish as a http-cache-host so that Varnish will purge when you do a Magento cache clean

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-config.html
https://devdocs.magento.com/guides/v2.2/cloud/docker/docker-config.html

## Links to documentation on how to configure Varnish

https://devdocs.magento.com/guides/v2.3/config-guide/varnish/use-varnish-cache.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
I marked waiting for response because I am waiting for an internal dev to get back to me. I'm in the process of updating the Varnish section. I want to make sure this is placed properly. Thanks for your patience!

**Comment by mveeramneni** [comment]
Hi @hguthrie, I QA'ed the changes and everything is working good. I have one suggestion for @mattskr, can you please make the same change for production mode too?
Thank you.

**Comment by mattskr** [comment]
yes, I will do that now.

**Comment by hguthrie** [comment]
running tests

**Comment by hguthrie** [comment]
Thanks @mattskr  👍

**Pull request merged**
