### PR TITLE
Uniform margin

### PR DESCRIPTION
**Pull request by rafaelstz**
image

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
We're going to fix this with our RWD fix, which should be coming in the next weeks. Stay tuned, leaving open for now.

**Comment by rafaelstz** [comment]
Ok, thank's :smile: :+1:

**Comment by xcomSteveJohnson** [comment]
We're close to pushing the responsive design! Found some issues with search on some devices. We'll make other improvements with time but as soon as we get search working, we'll push it and make an announcement.

**Comment by jfrontain** [comment]
Well done, capitaine! I need to run an errand (car dashboard gauge not working, and I kinda need them to work) but then will be back online.

**Comment by xcomSteveJohnson** [comment]
@rafaelstz Our responsive change has finally been done! Please check to see if this PR is necessary and if not close it.

Thanks!

**Comment by rafaelstz** [comment]
@xcomSteveJohnson That is not necessary now. :+1: :smile: 

Thanks!

**Pull request closed without merging**
