### PR TITLE
Sync develop with master

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) pulls the latest changes from the `master` branch into the `develop` branch. This is a weekly task to make sure `develop` stays up-to-date with `master`.

It helps resolve issues when contributors create their branches from `master` instead of `develop` and then create PRs to `develop` that contain extra commits.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5454) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5454) before we can accept your contribution.<br/>**8** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: atwixfirster<br/>:white_check_mark: dmytro-ch<br/>:white_check_mark: eduard13<br/>:white_check_mark: dobooth<br/>:white_check_mark: serhiyzhovnir<br/>:white_check_mark: vasilii-b<br/>:white_check_mark: rogyar<br/>:white_check_mark: rodrigowebjump<br/>:x: iproger

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
HTML tests failed:

```
+ rake test:html
[35mChecking links with html-proofer...[0m
Running ["LinkChecker::DoubleSlashCheck", "HtmlCheck", "ImageCheck", "ScriptCheck", "LinkCheck"] on ["_site"] on *.html... 


Ran on 2865 files!


- internally linking to /guides/v2.2/install-gde/prereq/php-ubuntu.html, which does not exist
  *  _site/guides/v2.2/install-gde/prereq/apache.html (line 551)
     <a href="/guides/v2.2/install-gde/prereq/php-ubuntu.html">PHP Ubuntu</a>
  *  _site/guides/v2.2/install-gde/prereq/apache.html (line 664)
     <a href="/guides/v2.2/install-gde/prereq/php-ubuntu.html">PHP Ubuntu</a>
  *  _site/guides/v2.2/install-gde/prereq/apache.html (line 783)
     <a href="/guides/v2.2/install-gde/prereq/php-ubuntu.html">PHP Ubuntu</a>
- internally linking to /guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu, which does not exist
  *  _site/guides/v2.3/install-gde/prereq/apache.html (line 549)
     <a href="/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu">PHP Ubuntu</a>
  *  _site/guides/v2.3/install-gde/prereq/apache.html (line 662)
     <a href="/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu">PHP Ubuntu</a>
  *  _site/guides/v2.3/install-gde/prereq/apache.html (line 782)
     <a href="/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu">PHP Ubuntu</a>
- trying to find hash of /guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu, but /apps/slave/workspace/devdocs-test/_site/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html does not exist
  *  _site/guides/v2.3/install-gde/prereq/apache.html (line 549)
     <a href="/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu">PHP Ubuntu</a>
  *  _site/guides/v2.3/install-gde/prereq/apache.html (line 662)
     <a href="/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu">PHP Ubuntu</a>
  *  _site/guides/v2.3/install-gde/prereq/apache.html (line 782)
     <a href="/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu">PHP Ubuntu</a>
rake aborted!
HTML-Proofer found 9 failures!
```

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
