### PR TITLE
config-varnish-magento.md Minor changes.

### PR DESCRIPTION
**Pull request by denish-c-vachhani**
config-varnish-magento.md. Minor change as per standard.

## Purpose of this pull request

This pull request (PR) Minor fixes as per standard.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-magento.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@denish-c-vachhani thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Thanks @denish-c-vachhani

**Pull request merged**
