### PR TITLE
doc block added for example php file

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Adding doc block for example php file

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @chandru-199. Thanks for all the work. If you are going to make a multiple small changes like this, it's best to put them in one PR. It saves us a lot of work on our end. Thanks!

**Comment by chandru-199** [comment]
Thanks @dobooth ,It makes sense. If i found any other small issue, will commit into same PR.

**Comment by dobooth** [comment]
Hi @chandru-199 Looks like a merge conflict slipped in. Can you please resolve that?

**Comment by chandru-199** [comment]
Sorry @dobooth, It is wrong one.I forgot to close this. It shouldn't be merged.

**Pull request merged**
