### PR TITLE
Fixed huge number of spelling typo mistakes.

### PR DESCRIPTION
**Pull request by NamrataChangani**
## This PR is a:
- [ ] Content fix or rewrite
 

## Summary
Fixed huge number of spelling typo mistakes.
 

## Additional information
N/A

### CODE REVIEW

**Comment by mhauri** [comment]
Hi @NamrataChangani what's the point of creating a PR which I created already before? See #2040
It seems that you created a lot of PR's today which are a duplicate of existing ones. 

#2038 duplicates #1992
#2034 duplicates #2028
#2039 duplicates #2036
and so on.

If you see that a PR misses a file either inform the creator of the original PR or create a new PR only containing the missing file, otherwise it will be really confusing. 

Thank you in advance

**Comment by shrielenee** [comment]
Hey @NamrataChangani - thanks for taking the time to submit this. It looks like a lot of your changes have been addressed in an already merged PR, and you also submitted revisions for v2.0 docs, which we are no longer updating due to the their EOL status.

Can you revise your PR to include ONLY v2.1+ changes? You may want to pull down recent changes into your branch before redoing your PR so you can see what has already been addressed.

**Comment by shrielenee** [comment]
@NamrataChangani  - It looks like there are a lot of merge conflicts on your branch now. If you can fix those and push them back up, I will facilitate all your typo changes (even the 2.0.x ones).

**Comment by NamrataChangani** [comment]
@shrielenee I have resolved merge conflicts.

**Comment by shrielenee** [comment]
Thanks for resolving the conflicts @NamrataChangani - these changes will appear in production soon.

**Pull request merged**
