### PR TITLE
MQE-1057: Update metadata filenames convention

### PR DESCRIPTION
**Pull request by tomreece**
- For MFTF, add details about `*Meta.xml` file naming.

## Purpose of this pull request

- https://jira.corp.magento.com/browse/MQE-1057

## Affected DevDocs pages

- Technical Guidelines

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by tomreece** [comment]
> This rule checks for the number of spaces between a list marker (e.g. '-', '*', '+' or '1.') and the text of the list item.
> The number of spaces checked for depends on the document style in use, but the default is 1 space after any list marker

I have one space after my list item markers.

I don't know what this linter wants me to do. Please advise @dobooth.

**Comment by jeff-matthews** [comment]
@tomreece, here's a list of our rules, specifically for rule 30: https://github.com/magento/devdocs/blob/master/_checks/styles/style-rules-prod#L26

We require two spaces between the marker and text for first-level unordered lists.

**Comment by tomreece** [comment]
@jeff-matthews Thanks! I fixed it. 👍

**Comment by dobooth** [comment]
running tests

**Pull request merged**
