### PR TITLE
magento-cloud ssh changed, so our instructions needed updating

### PR DESCRIPTION
**Pull request by simensen**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [X] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Show correct instructions accounting for changes to `magento-cloud ssh` command.

## Additional information

List all affected URLs 

- /guides/v2.1/cloud/project/project-integrate-blackfire.html
- /guides/v2.2/cloud/project/project-integrate-blackfire.html
- /guides/v2.3/cloud/project/project-integrate-blackfire.html

whatsnew
Corrected the command syntax in the [log preparation instructions](https://devdocs.magento.com/guides/v2.3/cloud/project/project-integrate-blackfire.html#blackfire-support)  for troubleshooting Blackfire issues.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Screenshot of test in my local enviroment with same approach (different command but same result)
screenshot 2019-01-18 at 10 07 30

**Comment by osrecio** [comment]
Hi @meker12 Can I help you with something related with Tests? 
Thanks!

**Comment by hguthrie** [comment]
running tests

**Pull request merged**
