### PR TITLE
Update checkout_new_step.md

### PR DESCRIPTION
**Pull request by jakobmeissner**
Custom step is hidden when using back button

## Purpose of this pull request

Updates javascript example to include the custom step in browser history.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@skymeissner thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @skymeissner , Can you update your PR adding information required. Please¿?

- Purpose of PR
- Link Affected in devdocs.magento.com
- Links to codebase if needed

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4399) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4399) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dobooth<br/>:x: jakobmeissner

**Comment by dobooth** [comment]
Researched this and the answer is correct.

**Pull request merged**
