### PR TITLE
Update text to match the values in the image

### PR DESCRIPTION
**Pull request by letronghieu4897**
1. salable quantity of 50  ==> salable quantity of 95
2. King Street store ==> US store 
3. The German (DE) web store => Amazon Marketplace

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/inventory/index.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@letronghieu4897 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4948) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4948) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
@letronghieu4897 Can you add all iformation about Url and the Purpose of PR please?

This will help us to review the PR easily 😃 

Thanks!

**Pull request merged**
