### PR TITLE
Update manage-sources.md

### PR DESCRIPTION
**Pull request by danieldespainTLS**
## Purpose of this pull request

Table is not rendered correctly in section beginning with "In-Store Pickup functionality enhance Sources" because it is missing the --- | --- | --- | --- line

This pull request (PR) adds the --- | --- so table renders correctly

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/rest/modules/inventory/manage-sources.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@danieldespainTLS thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]
This is great but you do need to sign the Adobe CLA before this PR can be progressed - you only need to do this once

**Comment by danieldespainTLS** [comment]
CLA wasn't signed.  Now it is.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @danieldespainTLS

**Pull request merged**
