### PR TITLE
Add MBI navigation and config

### PR DESCRIPTION
**Pull request by jeff-matthews**
## This PR is a:

- [ ] Content update

## Summary

When this pull request is merged, it will add the navigation and scope configuration for MBI docs, which have already been published to production.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/mbi/docs/getting-started.html

### CODE REVIEW

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by dshevtsov** [comment]
@jeff-matthews, @erikmarr please consider adding the `Major update` label and a whatsnew section to the PR description with news about adding the BI guide so we could publish this on the What's New on Devdocs page.

**Pull request merged**
