### PR TITLE
Message queue topic described as API.

### PR DESCRIPTION
**Pull request by vkublytskyi**
## This PR is a:

- [x] Content update

## Summary

When this pull request is merged, it will provide more information on how a message queue topic names should be treated in the context of Magento API and so will give external developers information on what they may depend and what may be changed during Magento patch releases.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/ (Actual for all Magento versions)

whatsnew
Added information about message queues to [Magento APIs](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#magento-apis).

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3932) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3932) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
