### PR TITLE
magento/devdocs#: Fixes to GraphQl Checkout Tutorial.

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) provide some fixes to GraphQL Checkout Tutorial
1. Remove `address_type` from `shipping_addresses` and `billing_addresses`.
2. Remove `label` from `selected_shipping_method`

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.html
- https://devdocs.magento.com/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.html
- https://devdocs.magento.com/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-method.html

## Links to Magento source code

- [SelectedShippingMethod ](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L227)
- [CartAddressInterface](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L189)

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @atwixfirster. Thank you for splitting the old PR!

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
The tutorial updates are complete. Thanks for all your contributions @atwixfirster

**Pull request merged**
