### PR TITLE
Remove part of JS Framework section from DB Framework section in Magento Open Source 2.3.0 Release Notes

### PR DESCRIPTION
**Pull request by oleksii-lisovyi**
## Purpose of this pull request

This pull request (PR) removes part of JS Framework section from DB Framework section in Magento Open Source 2.3.0 Release Notes.

## Affected DevDocs pages

 
Magento Open Source 2.3.0:
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@oleksii-lisovyi, it is customary to explain _why_ you are removing content from documentation. What reason do you have for making this change?

**Comment by oleksii-lisovyi** [comment]
@jeff-matthews, I just was reading that document page and realized, that I already read some points a moment ago. And I found, that there is content duplication. 
Also I re-checked, that there is no duplication in the similar document for Magento Commerce:
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.html#database-framework

**Comment by jeff-matthews** [comment]
Thanks for explaining @oleksii-lisovyi and thanks for the contribution!

**Pull request merged**
