### PR TITLE
Update project-conf-files_services-rabbit.md

### PR DESCRIPTION
**Pull request by tristanblattmansh**
Specify does not apply to Pro.

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

## Additional information

List all affected URLs 

- ...
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3087) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3087) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@tristanblattmansh thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by meker12** [comment]
@tristanblattmansh  Not sure why we need to add the note about Magento Commerce Pro here. The instructions in the [Set up RabbitMQ service](https://devdocs.magento.com/guides/v2.1/cloud/project/project-conf-files_services-rabbit.html)  article are for configuring Magento Commerce Cloud environments with RabbitMQ. 

Can you provide some additional info about why you want to add the note?

**Comment by tristanblattmansh** [comment]
Customers are submitting tickets quoting this article and saying that these
instructions are why their RabbitMQ isn't working on Pro

**Comment by meker12** [comment]
@tristanblattmansh  Do you mean that Magento Commerce Cloud customers on the Pro plan are saying that the instructions are incorrect.  I'm not sure what Magento Commerce Pro refers too. 

If the instructions are incorrect, it would be better to [submit an issue](https://github.com/magento/devdocs/issues/new/choose) about that. In the issue, it would be useful to include the context of what's not working. Then, we can fix the instructions as needed.

**Comment by meker12** [comment]
@tristanblattmansh Do you still require people to submit a support ticket to configure services on Pro Staging and Production? 

Also, I'm going to commit some additional changes to provide the information inline rather than making it a note, and also adding it to the other service setup topics.

**Comment by shrielenee** [comment]
Wooo! Thanks @meker12 and @tristanblattmansh! 🏆

**Pull request merged**
