### PR TITLE
magento/devdocs#: Add a custom payment method to checkout. Fix Step 4

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) fixes XML example in the Step 4.

Current example, describes add new payment method in the following way:

```
<item name="payment" xsi:type="array">
  <item name="children" xsi:type="array">

      <item name="beforeMethods" xsi:type="array">
      </item>

      <item name="renders" xsi:type="array">
          <item name="children" xsi:type="array">
          </item>
          <item name="afterMethods" xsi:type="array">
          </item>
      </item>

  </item>
</item>
```

The correct schema is (`afterMethods` locates not in the `renders` section):

```
<item name="payment" xsi:type="array">
  <item name="children" xsi:type="array">

      <item name="beforeMethods" xsi:type="array">
      </item>

      <item name="renders" xsi:type="array">
          <item name="children" xsi:type="array">
          </item>
      </item>

      <item name="afterMethods" xsi:type="array">
      </item>
  </item>
</item>
```

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/howdoi/checkout/checkout_payment.html
- https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_payment.html

## Links to Magento source code

- [checkout_index_index.xml](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Checkout/view/frontend/layout/checkout_index_index.xml#L326)

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Good catch!

**Comment by keharper** [comment]
Thanks @atwixfirster .

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running test

**Comment by dobooth** [comment]
running tests

**Pull request merged**
