### PR TITLE
Fixing the Markdown syntax in checkout_new_field

### PR DESCRIPTION
**Pull request by rafaelstz**
## Purpose of this pull request

Fix the Markdown syntax in the checkout new field page, as you can see below.

Screen Shot 2019-09-16 at 1 25 17 PM

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_new_field.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
@rafaelstz It looks like you branched off `develop` when creating this PR. It should have been branched off `master`. I changed the target branch, but now there are some issues. Please take a look and remedy!

**Comment by rafaelstz** [comment]
Hi @shrielenee 
All set, this is the new PR https://github.com/magento/devdocs/pull/5423

**Pull request closed without merging**
