### PR TITLE
Formatting the configuration to match to the configurations' styling

### PR DESCRIPTION
**Pull request by eduard13**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix the command line arguments' styling for some to match the other ones.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-install.html
- https://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-install.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
Thanks @eduard13! ⭐️

**Pull request merged**
