### PR TITLE
GraphQL: Updated the undateCustomerAddress syntax

### PR DESCRIPTION
**Pull request by VenkataRamanaGandham**
## Purpose of this pull request

This pull request (PR) updates the syntax for updateCustomerAddress Mutation.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/mutations/update-customer-address.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@VenkataRamanaGandham thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Reference to the codebase 

https://github.com/magento/magento2/blob/69b70b908ad7cb5b32df53ce1a00328897270487/app/code/Magento/CustomerGraphQl/etc/schema.graphqls#L18

**Comment by keharper** [comment]
running tests

**Pull request merged**
