### PR TITLE
magento/devdocs#3361: Configuration object topic

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/devdocs/issues/3361.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/config/config-create.html
- https://devdocs.magento.com/guides/v2.3/config-guide/config/config-files.html

## Links to Magento source code

-  [Example source - pdf.xml](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Sales/etc/pdf.xml)
- [\Magento\Framework\Config\Reader\Filesystem](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Config/Reader/Filesystem.php)

whatsnew
Added an example to [Create or extend configuration types](https://devdocs.magento.com/guides/v2.3/config-guide/config/config-create.html).

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
Thanks for picking this up @atwixfirster!

**Comment by atwixfirster** [comment]
> Thanks for picking this up @atwixfirster!

Hi, @shrielenee !

Looks like my PR has pushed @diazwatson to work on the https://github.com/magento/devdocs/issues/3361 again. :)

So, to avoid a double work I will probably stop my work on this one and will wait for the @diazwatson updates.

Thank you!

**Comment by shrielenee** [comment]
Whoever wants to do it is fine by us! @atwixfirster @diazwatson It was just such an easy grab... so you can fight it out over this one 👊 😄

**Comment by diazwatson** [comment]
@atwixfirster https://www.youtube.com/watch?v=2NUn0HxvEDU

**Comment by atwixfirster** [comment]
> It would be great if we leave a reference in this topic to the following topic so developers will know where to go for the detailed information.

The appropriate link has been added.

> Then, the following topic describes the general idea of the configuration file merge. It would be awesome if we could have a few sentences about how to see (debug) the merged configuration. So, the question is if a developer wants to verify that a custom configuration is present in the merged config, what he is going to do?

The appropriated callout block has been added with reference to debug entry point.

@rogyar , could you please review?

Thank you!

**Comment by atwixfirster** [comment]
> It would be great if we leave a reference in this topic to the following topic so developers will know where to go for the detailed information.

The appropriate link has been added.

> Then, the following topic describes the general idea of the configuration file merge. It would be awesome if we could have a few sentences about how to see (debug) the merged configuration. So, the question is if a developer wants to verify that a custom configuration is present in the merged config, what he is going to do?

The appropriated callout block has been added with reference to debug entry point.

@rogyar , could you please review?

Thank you!

**Comment by rogyar** [comment]
From a technical perspective, the information in the current PR is correct. However, we have another PR with more extended information on the same matter. 

https://github.com/magento/devdocs/pull/6539

The advantage of the current PR is the creation time. The advantage of the PR mentioned above is richer information. 

I'm not sure about the fair decision here. We could either ask @atwixfirster to extend info in this PR and accept it as a preceding one or accept the last one from @diazwatson.

@dobooth could you assist in this tricky decision, please? :)

Thank you!

**Comment by dobooth** [comment]
Happy to arbitrate here, gents. This is the kind of debate we like! Thanks to @rogyar for having a great awareness of what's happening in the repo. And thanks to you all for your continued efforts. I am going to go with #6539 since it does seem to have a bit more data. I will head over there and clean up those linting errors... 😉

**Comment by rogyar** [comment]
Hi @dobooth. Thanks a lot for your arbitration 👍

**Comment by dobooth** [comment]
Closing. This was handled in another PR.

**Pull request closed without merging**
