### PR TITLE
Added/Updated attributes and datatypes in the ConfigurableProduct endpoint

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will add/update attributes and datatypes in the ConfigurableProduct endpoint.

## Additional information

Codebase Link:
https://github.com/magento/magento2/blob/f4c1d7526f05bdfb1327b0701cc345f94aadcaed/app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls#L4

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/reference/configurable-product.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@mage2pratik  Would you pull in the changes from #3930 and also alphabetize the attributes in the "Configurable product options values" table?

**Comment by mage2pratik** [comment]
@keharper I've just resolved conflict and fixed changes.

**Comment by keharper** [comment]
running tests

**Pull request merged**
