### PR TITLE
Fix array formatting for other config settings

### PR DESCRIPTION
**Pull request by robbie-thompson**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Fix the array formatting for the config examples that were missed in #3171.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/cloud/live/sens-data-initial.html

### CODE REVIEW

**Comment by osrecio** [comment]
Hi @robbie-thompson Thanks for your contribution.

I would add a tab for your code highlighting.

What do you think @lorikrell or @jeff-matthews ?

**Comment by robbie-thompson** [comment]
@osrecio I've just copied the format that was merged earlier on #3171, so I assume that would need changing too?

**Comment by hguthrie** [comment]
@osrecio on the Cloud docs we require **no tabs**, but four space indents. Is that what you are referring to? This was confirmed by our Cloud team.

**Comment by hguthrie** [comment]
This topic is kind of old. These code blocks would be better if they were inside a proper Markdown code block.

**Comment by osrecio** [comment]
Hi @hguthrie I'm talking about that the code would be better in a proper Markdown code block.

I'm sorry if I explained wrong.

**Pull request closed without merging**
