### PR TITLE
Added layout block example

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Added example code snippet for layout block.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by chandru-199** [comment]
Hi @ronak2ram 
But PR #6225 merged already.

**Comment by ronak2ram** [comment]
@chandru-199 
Don't need to do anything on this PR. That is my suggestion for your upcoming contribution :-)

**Comment by chandru-199** [comment]
Ok @ronak2ram .Will keep it in mind.

**Pull request merged**
