### PR TITLE
Added remaining soap services

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will show soap services catalogInventoryStockItemApi and customerCustomerGroupConfigV1.

**customerCustomerGroupConfigV1**

2.2. https://github.com/magento/magento2/blob/2.2/dev/tests/api-functional/testsuite/Magento/Customer/Api/CustomerGroupConfigTest.php#L16
2.3. https://github.com/magento/magento2/blob/2.3/dev/tests/api-functional/testsuite/Magento/Customer/Api/CustomerGroupConfigTest.php#L16

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/soap/bk-soap.html
- https://devdocs.magento.com/guides/v2.3/soap/bk-soap.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@ronak2ram  I can accept the changes for `customerCustomerGroupConfigV1` but not `catalogInventoryStockItemApi`. There is no PHP class by that name. I believe you've discovered a that doesn't work as expected.

Please update your PR to remove `catalogInventoryStockItemApi`. I also encourage you to file an issue against the code to get the test corrected.

**Comment by ronak2ram** [comment]
Hey @keharper
I updated PR as per your suggestion please review it.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @ronak2ram!

**Pull request merged**
