### PR TITLE
Added the documentation for Sortable widget

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds the documentation for the Sortable widget.

## Affected DevDocs pages

This documentation will have the following links:

- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget-sortable.html
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget-sortable.html

_Page look_

screencapture-127-0-0-1-4000-guides-v2-3-javascript-dev-guide-widgets-widget-sortable-html-2019-09-11-13_38_54

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Theme/view/adminhtml/web/js/sortable.js
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Theme/view/adminhtml/web/js/sortable.js

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by serhiyzhovnir** [comment]
Hi @jcalcaben 
The requested changes were added.
Can you, please, review the PR again?
Thank you!

**Comment by serhiyzhovnir** [comment]
Hey @jcalcaben 
The conflict is resolved.
Thank you!

**Comment by jcalcaben** [comment]
running tests

**Pull request merged**
