### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mrtuvn**
## Purpose of this pull request

This pull request (PR) Correct some mistakes in docs

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/config-guide/db-profiler/db-profiler.html
https://devdocs.magento.com/guides/v2.4/config-guide/db-profiler/db-profiler.html

https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-envphp.html
https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-envphp.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Nice attention to detail!

**Review by dobooth — APPROVED** [review]
Good lord the typos!

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8853`.

**Pull request merged**
