### PR TITLE
Updates method name to the common method used for database lookup by ID

### LINKED ISSUE #6713: Typo on the Service contract design patterns page
# Topic clarification/correction request
There is a typo on the Service contract design patterns page 

## Topic Link
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.html

## Description

**get(id)** | Performs a database lookup by ID.

is not correct, the correct method name is **getById(id)**
## Possible solutions
replace **get(id)**  by **getById(id)**

## Additional information
I am going to create a PR with a fix.

### PR DESCRIPTION
**Pull request by u-maxx**
I know that CustomerRepositoryInterface has the custom **get**($email, $websiteId = null) method which is retrieving customer by email, but for lookup by ID correct method name will be **getById**

## Purpose of this pull request

This pull request (PR) fixes typo in the method name

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.html

## Links to Magento source code
- https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Api/CustomerRepositoryInterface.php

-  Fixes #6713

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by atwixfirster** [comment]
Thank you for PR, @u-maxx !

From my side this PR looks correct.

But we need the approve from the maintainer side. 

@rogyar , could you please care of this one?

Thank you!

**Comment by atwixfirster** [comment]
By the way, @u-maxx please sign the CLA :))

Have a nice day!

**Comment by u-maxx** [comment]
Hello @atwixfirster! 

Thanks, I will sign it shortly.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
