### PR TITLE
Update ui_comp_data_source.md

### PR DESCRIPTION
**Pull request by hgajjar**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Fix not correct item name value in template: guides/v2.3/ui_comp_guide/concepts/ui_comp_data_source.md

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_data_source.html
https://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_data_source.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@hgajjar thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3847) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3847) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
