### PR TITLE
Community edition also need the bcmath extension

### PR DESCRIPTION
**Pull request by Arthur2Sereno**
Magento 2.3 Community edition also need the `bcmath` extension.

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-ubuntu
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3856) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3856) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-engcom-team** [comment]
@Arthur2Sereno thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by osrecio** [comment]
Please @Arthur2Sereno complete your PR Template with all information.

**Comment by osrecio** [comment]
Hi @Arthur2Sereno I updated your comment to add the url.

Please can you add the same change to this [url](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-centos) (Centos) You have the file [here](https://github.com/magento/devdocs/blob/master/guides/v2.3/install-gde/prereq/php-centos-ubuntu.md).

If you modify it I will review your PR.

**Comment by Arthur2Sereno** [comment]
> Hi @Arthur2Sereno I updated your comment to add the url.
> 
> Please can you add the same change to this [url](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-centos-ubuntu.html#php-for-centos) (Centos) You have the file [here](https://github.com/magento/devdocs/blob/master/guides/v2.3/install-gde/prereq/php-centos-ubuntu.md).
> 
> If you modify it I will review your PR.

Sorry for late, add it in this commits now.

**Comment by jeff-matthews** [comment]
running tests

**Comment by Arthur2Sereno** [comment]
> Hi @Arthur2Sereno, thank you for your contribution! 
> Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+devdocs+3856), it will take less than a minute. 
> Your feedback will help us to improve contribution process.

Completed the survey, very fast processing, good job!

**Pull request merged**
