### PR TITLE
magento/devdocs#: added example of using dropdown widget

### PR DESCRIPTION
**Pull request by volodymyrDashuk**
## Purpose of this pull request

This pull request (PR) adds an example of using the dropdown widget to the existing documentation.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_dropdown.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Excellent!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Hi @volodymyrDashuk Thanks for contributing. Please sign the Adobe CLA so we can continue with this PR.

**Comment by volodymyrDashuk** [comment]
Hi @dobooth At your request, everything is done!
Please proceed.
Thank you!

**Comment by dobooth** [comment]
running tests

**Pull request merged**
