### PR TITLE
Fix formatting of sample in setup-cron-jobs.md

### PR DESCRIPTION
**Pull request by gwillem**
## Purpose of this pull request

This pull request (PR) repairs broken formatting of two samples on the cron setup page for 2.3 (which links to 2.2):

image

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/cloud/configure/setup-cron-jobs.html
- https://devdocs.magento.com/guides/v2.3/cloud/configure/setup-cron-jobs.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5120) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5120) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@gwillem thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
