### PR TITLE
Update queries.md

### PR DESCRIPTION
**Pull request by dasharath-wagento**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- ...
- ...

## Links to Magento source code

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@dasharath-wagento We are not accepting PRs against the `queries` topic while we refactor it for 2.3.2. If the error exists after the refactoring, feel free to open a new PR, but you'll need to fully fill out the form.

**Comment by keharper** [comment]
Re-opening and accepting since you were participating in a Contribution Day.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Running tests

**Comment by keharper** [comment]
Thanks @dasharath-wagento

**Pull request merged**
