### PR TITLE
magento/devdocs#:6443 Align Magento PHP prerequisites in different topics

### PR DESCRIPTION
**Pull request by DenisSaltanahmedov**
## Purpose of this pull request

This pull request (PR) fix the hardcoded PHP requirements in different topicks

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html
- https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html
- https://devdocs.magento.com/guides/v2.3/performance-best-practices/software.html

## Links to Magento source code
- https://github.com/magento/devdocs/blob/master/src/guides/v2.3/install-gde/system-requirements-tech.md
- https://github.com/magento/devdocs/blob/master/src/guides/v2.3/install-gde/prereq/php-settings.md
- https://github.com/magento/devdocs/blob/master/src/guides/v2.3/performance-best-practices/software.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dshevtsov** [comment]
running tests

**Comment by DenisSaltanahmedov** [comment]
Hi @dshevtsov
How can I check the test details?
I can not check any information
err-2020-02-03_0905

**Comment by dshevtsov** [comment]
> Hi @dshevtsov
> How can I check the test details?
> I can not check any information

The reason of fail from logs:
```
Liquid Exception: Could not locate the included file 'mftf/mftf_data.md'. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in mftf/docs/mftf-tests.md
```

This issue was caused by the docs from one of our external sources and should be fixed now.

Thank you for your feedback, it is important to understand that this feature is requested by contributors. Making the error logs public is in my backlog.

Note, that you can run tests locally using rake commands `rake test:md` to test the Markdown style and `rake test:html` to test HTML (if you build the site locally).

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
