### PR TITLE
MQP Release 1.0.8

### PR DESCRIPTION
**Pull request by Rykh**
## Purpose of this pull request
 
Added RN for MQP v1.0.8
 
## Affected DevDocs pages
 
https://devdocs.magento.com/quality-patches/release-notes.html
 
whatsnew
Published [release notes](https://devdocs.magento.com/quality-patches/release-notes.html) for the 1.0.8 Magento Quality Patch (MQP) package release.

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Review by jeff-matthews — APPROVED** [review]
@Rykh, do you want the release notes published now or should we wait?

**Comment by Rykh** [comment]
Hi @jeff-matthews  Please release this PR

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
@Rykh, release notes will be published in the next ~30 minutes.

**Pull request merged**
