### PR TITLE
Update create_component.md

### PR DESCRIPTION
**Pull request by torhoehn**
## Purpose of this pull request

This pull request (PR) corrects a small mistake: setup_version is only required if Declarative Schema isn't used, as it is mentioned before.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/create_component.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by bdenham** [comment]
running tests

**Comment by bdenham** [comment]
running tests

**Comment by bdenham** [comment]
running tests

**Comment by bdenham** [comment]
running tests

**Pull request merged**
