### PR TITLE
Description Fix

### PR DESCRIPTION
**Pull request by OleksiiBulba**
Fixed description for `closeBtnLabel`

## Purpose of this pull request

This pull request (PR) fixes typo in optins table

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-secondary-uiselect.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4619) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4619) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@OleksiiBulba thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Pull request merged**
