### PR TITLE
Fix search results page redirect issue

### PR DESCRIPTION
**Pull request by belbiy**
## Purpose of this pull request

This pull request (PR) fixes the redirect to a correct search results page based on version of the guide.

## Affected DevDocs pages

-  all

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by belbiy** [comment]
running tests

**Comment by meker12** [comment]
When I change to version to 2.3 and search, the results page shows 2.3 links as expected.

If I am on the 2.3 search results page with 2.3 selected, then pick version 2.4 --   The search results page refreshes with blank search field, and empty results page. 

Is that expected?

What I hoped for before when I clicked:   Changing to version 2.4 on the Search results page would retain the search string and update to show the 2.4 results.

**Comment by jeff-matthews** [comment]
I can't remember how it worked before or whether that's expected behavior. 

According to [this blog post](https://community.magento.com/t5/Magento-DevBlog/Improved-search-for-Magento-docs/ba-p/127157), switching versions should return results for the search term.

**Comment by belbiy** [comment]
I 100% agree that the search query should remain while switching versions. Can't yet wrap my head around how to achieve that...

**Comment by meker12** [comment]
> I 100% agree that the search query should remain while switching versions. Can't yet wrap my head around how to achieve that...

Is it possible to save the search string entered, and then repopulate when the page refreshes?

**Comment by belbiy** [comment]
@meker12 , yes, i'm trying to do that with JavaScript. I probably would want to do that in the theme. Give me some time, and i'll come with the solution.

**Comment by belbiy** [comment]
I managed to build the script to retain search query: https://github.com/magento-devdocs/devdocs-theme/pull/61
Once merged, i will build the devdocs on staging so y'all can test it.

**Comment by belbiy** [comment]
The preview with the fixed search and correct search results switching behavior is available for preview at magedevteam.com/2142/

**Comment by belbiy** [comment]
running tests

**Comment by belbiy** [comment]
running tests

**Pull request merged**
