### PR TITLE
Restructured themes overview page

### PR DESCRIPTION
**Pull request by drpayyne**
## Purpose of this pull request

This pull request (PR) removes the theme-general page content and replaces it with theme-overview page content as theme-general page has redundant content. Also, the themes main page now aligns with [Layout overview](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-overview.html) page by having the overview content as the main content.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-general.html
-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-overview.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by drpayyne** [comment]
Hi @dobooth, I've fixed those issues. Also, did you mean to add the `2.3.x` label instead of `2.2.x` label?

**Comment by dobooth** [comment]
running tests

**Pull request merged**
