### PR TITLE
Update search-pagination.md

### PR DESCRIPTION
**Pull request by sanjay-wagento**
Solved below issue
"message": "Cannot query field \"total_pages\" on type \"SearchResultPageInfo\".",
"message": "Field \"description\" of type \"String\" must not have a sub selection."

## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [X] Bug fix or improvement

## Summary

When this pull request is merged, it will...

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.3/graphql/search-pagination.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by osrecio** [comment]
Hi @sanjay-wagento  can you update the PR Template to add the list affected urls. Please?

**Comment by sanjay-wagento** [comment]
@osrecio https://devdocs.magento.com/guides/v2.3/graphql/search-pagination.html

**Comment by sanjay-wagento** [comment]
@osrecio I updated

**Comment by osrecio** [comment]
Hi @erikmarr can you run the tests over this PR?

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @sanjay-wagento for your contribution and @osrecio for your review (and checking in)! We were waiting to confirm a couple things on the backend before running the tests again. We're all set now.

**Pull request merged**
