### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AsherThomasBabu**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- ...

## Links to Magento source code

- ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@AsherThomasBabu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Thanks for your PR @AsherThomasBabu.

But I need to say the same on your previous PR. I don't see that your PR give a differentiate value.

P.S. Please add more information in your PR Info.

**Comment by meker12** [comment]
Agree with @orecio. Closing this PR. @AsherThomasBabu Check the [DevDocs GitHub issues](https://github.com/magento/devdocs/issues) to find areas where we need help from contributors. You'll notice a few issues labeled _good first issue_, which might be a good place to focus your efforts. Thanks!

**Pull request closed without merging**
