### PR TITLE
Magento did not release it at late september

### PR DESCRIPTION
**Pull request by scholtz**
## Purpose of this pull request

This pull request (PR) update release date for M2.3.3 - September has passed

## Affected DevDocs pages

- Release/Index

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5521) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5521) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@scholtz thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Thanks for the contribution @scholtz, but technically we _did_ release 2.3.3 and 2.3.2-p1 in late September.

Beginning with 2.3.3 and 2.3.2-p1, Commerce/Enterprise customers can access patches approximately two weeks before General Availability (GA).

**Comment by scholtz** [comment]
Hi Jeff, thanks for heads up. However I still cannot find any way how to install magento 2.3.3. In https://repo.magento.com/packages.json i see only versions 

2.3.2
2.3.1
2.3.0
2.2.9
2.2.8
2.2.7
2.2.6
..

of the project magento/project-community-edition..

neither at github there is no 2.3.3 version: https://github.com/magento/magento2/tree/2.3.3

Therefore the information that "Commerce/Enterprise customers can access patches approximately two weeks before General Availability (GA)." might be wrong because as magento commerce customer i do not see the version 2.3.3 before the GA. 

We do the translations for the magento, so if we cannot install the version before GA, the translations are delayed..

If I am wrong, please take it as a suggestion to update devdocs to clearly state how to install the prerelease.

**Comment by jeff-matthews** [comment]
@scholtz, this applies to Commerce (formerly known as Enterprise Edition) packages only; not Open Source (formerly known as Community Edition).

**Comment by scholtz** [comment]
> 
> 
> @scholtz, this applies to Commerce (formerly known as Enterprise Edition) packages only; not Open Source (formerly known as Community Edition).

Thanks.

So perhaps someone should consider adding Magento Open Source to Upcoming releases page, so that it does not cause confusion. :) I believe that most people who is looking on when the magento is going to do next release are the Magento Open Source clients..

**Comment by jeff-matthews** [comment]
That's good feedback, we'll consider it. Thank you!

**Comment by hostep** [comment]
@jeff-matthews : actually Magento Open Source packages are also already available as pre-release. I can certainly access them.
And it makes sense, since Commerce relies on Open Source packages.

The biggest problem in our case for finding them, is the fact that it wasn't communicated properly that only the *main contactperson* of a Partner account can access them. All the other members of the same Partner account do not have access which made it hard to find, had to sort it out with partner support going back and forth during 2 days until we found out how to properly get access.

@scholtz: if you know who the *main contactperson* of your Partner account is, ask them to create an access keypair in the Magento Marketplace using their account, and using that you should be able to access the pre-releases.

**Comment by scholtz** [comment]
@hostep Thanks for the info. However we have only partners for Magento Open Source, as i dont see the Magento Commerce we cannot do translations for it, nor i am not aware how much does it differ from open source. Thus we cannot sell the magento commerce translations or extensions. To become partner it is cost inefficient because we barely get enough money for the translators. 

@jeff-matthews Perhaps there might be the exact date when it was released to partner, and the date when it is expected to be released for GA ?

**Pull request closed without merging**
