### PR TITLE
Likemusic bugfix/case sensitive broken links

### PR DESCRIPTION
**Pull request by jeff-matthews**
## This PR is a:
[ ] New topic
[ ] Content fix or rewrite
[X] Bug fix or improvement
 

## Summary
 
When this pull request is merged, it will resolve broken links.
 

## Additional information
This PR resolves merge conflicts in https://github.com/magento/devdocs/pull/1532.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@likemusic, I can't add you as a reviewer because you're not part of the Magento organization, but please review and let me know if I missed anything.

**Comment by jeff-matthews** [comment]
@likemusic, please review and sign the CLA so I can merge this PR.

**Comment by likemusic** [comment]
@jeff-matthews, CLA signed, but somehow status not changed.

**Comment by jeff-matthews** [comment]
Thanks @likemusic!

**Pull request merged**
