### PR TITLE
Update release-notes-2-4-0-open-source.md

### PR DESCRIPTION
**Pull request by chakravarthykalyan90**
##  Purpose of this pull request

This pull request (PR) fix for issue #7709 

Considering the current behavior, corrected the text "cannot be disabled" to "but can be disabled"

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by lbajsarowicz** [comment]
Could you provide the steps to **disable** the 2FA without disabling / removing whole module?

**Comment by chakravarthykalyan90** [comment]
> Could you provide the steps to **disable** the 2FA without disabling / removing whole module?

I didn't work on that but found a third party module which can do the same without actually disabling the core module. This may help. Please check.

[https://github.com/markshust/magento2-module-disabletwofactorauth](https://github.com/markshust/magento2-module-disabletwofactorauth)

**Comment by lbajsarowicz** [comment]
Just to make sure: @chakravarthykalyan90 You want to update the Magento Core documentation, because you found the extensions that enables you to turn off 2FA?

**Comment by chakravarthykalyan90** [comment]
Hi @lbajsarowicz 

I think there is misunderstanding. I actually disabled the module using the Magento command but not using the third party module. Doc says it cannot be disabled but it can be disabled in open source. 

```
php bin/magento module:disable Magento_TwoFactorAuth

```

I thought you wanted to know how to bypass 2FA without touching the core one, so shared the third party module.

Hope I clarified.

**Comment by lbajsarowicz** [comment]
I'm really sorry, but I think that you misunderstood the intention of "cannot be disabled"
It refers to the fact, that without removing module from Magento (disabling **whole module**) you are unable to disable 2FA (the requirement of providing 2FA).

You can always remove / disable whole modules, but the configuration refers to the fact, that Magento Security Team once again haven't discussed with community about the changes introduced and they removed an option from configuration to turn off the feature.

**Comment by chakravarthykalyan90** [comment]
aah it makes sense to me now. Got it. Yes there is no option to enable or disable it via Admin without using the command. I was always in the developer mode when reading that :) 

Ok please guide me the next steps.

**Comment by lbajsarowicz** [comment]
Maintainers responsible for this project are going to close the issue.

But (!) if you really want to contribute, you can adjust the documentation for Magento Security Package, as it still mentions possibility to turn off the 2FA without removing extension.

**Comment by chakravarthykalyan90** [comment]
Thanks for that. Happy to contribute. I will take a look into it.

**Comment by jeff-matthews** [comment]
Magento does not recommend disabling 2FA by disabling the module and we request that customers not take such actions as it would impact the security of their Magento environment.

**Pull request closed without merging**
