### PR TITLE
Product add attribute reference

### PR DESCRIPTION
**Pull request by jasonevans1**
## This PR is a:

- [X] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary
When creating a new product attribute in an install script. I am not able to easily find a listing of the options available. This issue magento/magento2#14793 the user is asking for documentation on the available options.

When this pull request is merged, it will add add a product attribute options reference table to the devdocs.

## Additional information
This is a new document. I do not know where in the menu this document should be put?

whatsnew
Added a new [product attribute reference section](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html#add-product-eav-attribute-options-reference).

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@jasonevans1, it seems like this info should go in the [EAV and extension attributes](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html) page. What do you think?

**Comment by keharper** [comment]
I would add this info to the "EAV and extension attributes" page Jeff mentioned above. Long term, we probably need more reference info about the attribute that we define in the various `eav_attributes.xml` files.

**Comment by jasonevans1** [comment]
I have moved this to the "EAV and extension attributes" page.

**Comment by keharper** [comment]
I took the liberty of alphabetizing the table by attribute name. I also cleaned up the intro sentence a bit. 

Thanks for your contribution, @jasonevans1 .

**Comment by dshevtsov** [comment]
@jeff-matthews @keharper 
The whatsnew content must be added at the very end of the PR description, including commented out content. It makes sense to remove the commented out text for clarity when you add a whatsnew.
Also, use only one label to indicate a PR type: _Major update_ or _Technical_. _Major update_ covers _Technical_.

I'll make all the required changes in this PR.

**Pull request merged**
