### PR TITLE
2.4.3 backward incompatible changes reference

### PR DESCRIPTION
**Pull request by devops-devdocs**
Updated reference documentation on backward incompatible changes for 2.4.2-2.4.3-develop versions delta.

NOTE: This pull request will be open until 2.4.3 beta to collect the backward incompatible changes and to allow tracking the updates.

### CODE REVIEW

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dshevtsov, an error occurred during the Pull Request import.

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dshevtsov, an error occurred during the Pull Request import.

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dshevtsov, an error occurred during the Pull Request import.

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dshevtsov the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8675`.

**Comment by dshevtsov** [comment]
The pull request will be processed internally.

**Pull request closed without merging**
