### PR TITLE
Update setup-cron.md

### PR DESCRIPTION
**Pull request by tank-crd**
switched "send automated e-mails" to "sends automated e-mails"

### CODE REVIEW

**Comment by tanberry** [comment]
Thanks @tank-crd ! We appreciate the help with our grammar (subject-verb agreement).

**Comment by tank-crd** [comment]
Thanks for the warm welcome tanberry :-)

Real quick, could you elaborate a little on "subject-verb agreement"? Is this referencing something I need to read? I just want to be sure that I made this pull correctly.

**Comment by tanberry** [comment]
;-) Oh you did the PR perfectly, thank you! The term "subject-verb agreement" is about grammar, not legal agreements. I was confirming that your grammar is correct in your contribution, because it follows the rule that the subject of the sentence must "agree" with the verb. That is, if the subject is singular, the verb must also be singular. So, in our sentence the subject is 'command' and the verb is 'sends' (now that you fixed it), so all is good.  Sorry, we writers geek out sometimes.

**Comment by tank-crd** [comment]
Oh okay. Thank you very much Miss.

**Pull request merged**
