### PR TITLE
Content staging basics

### PR DESCRIPTION
**Pull request by dshevtsov**
## This PR is a:
- [x] New topic
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement
 
## Summary
 
When this pull request is merged, it will explain Content staging basics, how the code base was affected to implement it.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@dshevtsov, what's the status on this?

**Comment by dshevtsov** [comment]
@jeff-matthews 
waiting for commits from @akaplya to finalize the draft

**Comment by magento-cicd2** [comment]
Can one of the admins verify this patch?

**Comment by jeff-matthews** [comment]
@dshevtsov, please finish processing this PR and merge it or close.

**Pull request closed without merging**
