### PR TITLE
Updated component image #2381

### PR DESCRIPTION
**Pull request by gelanivishal**
## This PR is a:
- [ ] New topic
- [X] Content fix or rewrite
- [X] Bug fix or improvement
 

## Summary
Fixed component image issue in #2381
When this pull request is merged, it will...

### CODE REVIEW

**Comment by bdenham** [comment]
Hey @gelanivishal, thanks for fixing the initialize function in the image. I want to crop the image and do some minor cleanup before publishing, so I'll send you a new image as soon as I can so you can replace and recommit it to this PR.

**Comment by gelanivishal** [comment]
@bdenham please provide me.

**Comment by gelanivishal** [comment]
@bdenham I'm waiting for your image. 

Thank you.

**Comment by gelanivishal** [comment]
Hello @bdenham,

I have updated image as your given.

Thank you.

**Pull request merged**
