### PR TITLE
Clarify some info regarding around plugins

### PR DESCRIPTION
**Pull request by AydinHassan**
Some info was lacking, regarding forwarding arguments so I clarified it with some more examples. Let me know if anything is missing 😄

### CODE REVIEW

**Comment by tanberry** [comment]
@AydinHassan  Thank You so much for this contribution!! @jcalcaben Can you take a look and then merge? Also, Aydin, is "variatics" something that the majority of developers will know about? If can you add a link or an explanation?
Thanks again, please keep the contributions coming!

**Comment by jcalcaben** [comment]
Everything looks good. Thanks for the clarification @AydinHassan !

**Comment by AydinHassan** [comment]
thanks guys, @tanberry regarding variadics, it's a core PHP construct, so I don't think there will be an issue there. If we get questions then I'm happy to update.

**Comment by tanberry** [comment]
@AydinHassan , a new word for my internal glossary, thanks so much. BTW... if you are ever interested in helping out with a specific area in the docs, or even our nascent Glossary, please let me know. We have in the past recognized major contributors to our docs by displaying their names on the Jumbotron at events like Australia Live and UK Live, and we also add the name of the contributor to the top of any page for topics that are written completely by the contributor. Give it a thought and let us know! ;-)

**Pull request merged**
