### PR TITLE
Fix misleading variable name

### PR DESCRIPTION
**Pull request by cmuench**
Replace $searchCriteria with $searchResults

## Purpose of this pull request

This pull request (PR) fixes a misleading variable name which was introduced by copy&paste.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/extension-dev-guide/extension_attributes/adding-attributes.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
The Lint checks failed but it looks like a system fault. Might be worth doing an empty commit to make them run again 

@dobooth - Is there a way to manually kick off the tests on DevDocs? Like "magento run all tests" on magento2?

**Comment by keharper** [comment]
running tests

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
Running tests didn't do the trick, so I found a cosmetic change I could make so that the lint checks would run again.

@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@keharper the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-9078`.

**Pull request merged**
