### PR TITLE
Fix incorrect "Include CSS" example

### PR DESCRIPTION
**Pull request by Tazaf**
## Purpose of this pull request

This pull request (PR) fixes an incorrect example in the **Include CSS** documentation page.

Using the example in the **Include CSS** section _as-is_ causes an issue that actually prevents the CSS file from being properly loaded by the webpage.

This is caused by the presence of the `src_type="url"` attribute in the `<css>` node, which in turn causes the `href` property of the generated `link` node not to contain the expected URL of `pub/static/versionXYZ/frontend/<Vendor>/<theme>/<locale>/css/custom.css`, but rather an absolute URL to `css/custom.css` (which obvisouly yields a 404).

Removing the `src_type` attribute fixed that, hence this proposal.

See this MagentoStack thread _(disclaimer: posted by myself)_: [Custom CSS file present in head but fails to load](https://magento.stackexchange.com/questions/312692/custom-css-file-present-in-head-but-fails-to-load)

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-themes.html#fedg_css-in-themes_xml

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@Tazaf thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @Tazaf. Thank you for your contribution. There another PR that fixes the same issue

https://github.com/magento/devdocs/pull/7212

However, the original author has not signed CLA. Considering the fact that this issue needs to be addressed ASAP, I'm approving this one.

**Comment by Tazaf** [comment]
Hi!

Sorry for the duplicate, I looked at the other PRs, but this one has eluded me.

Thx for the approval 👍

**Comment by teo-oliver** [comment]
The CLA is signed now, sorry for the delay.

**Pull request merged**
