### PR TITLE
magento/devdocs#: Docs: Add documentation for related/upsell/crosssell products

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) provides docs for the https://github.com/magento/graphql-ce/issues/766 issue.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/graphql/reference/products.html
- https://devdocs.magento.com/guides/v2.3/graphql/queries.html

## Links to Magento source code

- ...

Thank you!

CC: @keharper

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @atwixfirster. Since the described functionality is not present in 2.3.2 release, the PR should be created to the develop branch instead of master. Please, create a new PR using develop as a target branch.
Thank you.

**Comment by atwixfirster** [comment]
> Hi @atwixfirster. Since the described functionality is not present in 2.3.2 release, the PR should be created to the develop branch instead of master. Please, create a new PR using develop as a target branch.
> Thank you.

New pull request: https://github.com/magento/devdocs/pull/4986

Thanks , @rogyar

**Comment by osrecio** [comment]
This PR is closed in favor of #4986 
Thanks @atwixfirster

**Pull request closed without merging**
