### PR TITLE
command arguments added for migration command syntax

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
## Purpose of this pull request

This PR adds a command-line argument that can be used with the migration command list in Magento2.

**[--auto | -a]**  argument is added with description for migration command syntax.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/migration/migration-migrate.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Reference to the codebase 

https://github.com/magento/data-migration-tool/blob/f8c44f4784b5ded5c903017bdae0f1f3e79b6287/src/Migration/Console/AbstractMigrateCommand.php#L96

**Comment by ajithkumar-maragathavel** [comment]
> Investigate whether the -a flag needs to be added to the other topics about the migrate command.
> 
> Change the numbered list beginning at line 49 to an ordered list and make them flush left. That is:
> 
> *(space)(space)`<text>`

@keharper  Hi, Thanks for the review.
I have further investigated the migration command reference in the other dev docs pages and found below references from the migration dev docs.

1. https://devdocs.magento.com/guides/v2.3/migration/migration-migrate-data.html#migrate-data-cmd
2. https://devdocs.magento.com/guides/v2.3/migration/migration-migrate.html#migration-command-run-syntax
3. https://devdocs.magento.com/guides/v2.3/migration/migration-migrate-delta.html#migrate-data-cmd
4. https://devdocs.magento.com/guides/v2.3/migration/migration-migrate-settings.html#migrate-data-cmd

Also found that **--auto** argument is missing from the last _two pages (3 & 4)_. I have also added a command argument for those pages as well.

Thanks.

**Comment by keharper** [comment]
running tests

**Pull request merged**
