### PR TITLE
Update module-load-order.md

### PR DESCRIPTION
**Pull request by sedonik**
## This PR is a:

- Content fix or rewrite

## Summary

When this pull request is merged, it will correct description.  According to logic and code example component B should be loaded after component A because component A is listed in component B’s <sequence> tag.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/module-load-order.html
- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/module-load-order.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-load-order.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4136) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4136) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@sedonik thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by sedonik** [comment]
Hi @osrecio,
I have updated branch. Please check. 
Thanks.

**Pull request merged**
