### PR TITLE
Adding the new GraphQL Area

### PR DESCRIPTION
**Pull request by rodrigowebjump**
## Purpose of this pull request

This pull request (PR) adds the new GraphQL Area to doc.

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_and_areas.html
https://devdocs.magento.com/guides/v2.3/architecture/archi_perspectives/components/modules/mod_and_areas.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rodrigowebjump** [comment]
Hi @keharper I commit again to follow your recommendation.
Please could you check if everything is ok.

**Comment by keharper** [comment]
@osrecio Can you complete your review?

**Comment by dobooth** [comment]
Hi @rodrigowebjump Thanks for the contribution. Since you made it, we have ended support for v2.2 and can no longer accept PRs for that version. Can you please: 1) Remove the 2.2 file, 2) Fix the merge conflict in 2.3 and 3)Ensure that all your changes have made it to the v2.3 file. Then we will be happy to merge this PR. Thanks!

**Comment by dobooth** [comment]
@rodrigowebjump can we get an update with this PR?

**Comment by keharper** [comment]
Closing due to inactivity.

**Pull request closed without merging**
