### PR TITLE
Information added for all the nodes in env.php

### LINKED ISSUE #5927: Update env.php ref page with config options + descriptions
# General issue

The env.php reference page is lacking most configuration options or detailed descriptions

## Description:

The current reference page includes 11 top-level configuration sections, but little-to-no detailed information that is easily accessible. Additionally, there are dozens of env.php sub-sections which are not mentioned at all in this page, and indeed may not be detailed anywhere in any documentation. An example would be db -> indexer -> persistent.

## Possible solutions:

Provide a well organized, easy to read, and understandable reference which includes all configuration options, what version they were introduced, and links to pages on how those various options can be used effectively.

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
## Purpose of this pull request

Additional information added for all the nodes in app/etc/env.php

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-envphp.html

`Fixes` https://github.com/magento/devdocs/issues/5927

whatsnew
Added reference information to [env.php reference](https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-envphp.html).

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @ajithkumar-maragathavel Thanks for the contribution. Here is the dilemma: It would be better to either document all the attributes or none of them, rather than just one. Any interest in fleshing out the rest of the attributes?

**Comment by ajithkumar-maragathavel** [comment]
@dobooth  I will document all the attributes and it's purpose and commit the changes.

**Comment by ajithkumar-maragathavel** [comment]
@dobooth I have added information for the all the attributes in env.php as you suggested. Please review it. Thanks for your suggestion.

**Comment by dobooth** [comment]
Ah good man! Thanks for the effort, @ajithkumar-maragathavel!

**Comment by dobooth** [comment]
running tests

**Pull request merged**
