### PR TITLE
Line errors

### PR DESCRIPTION
**Pull request by rafaelstz**

### CODE REVIEW

**Comment by rafaelstz** [comment]
Lines not accepted by the file.

**Comment by xcomSteveJohnson** [comment]
Can you elaborate on this change?

**Comment by rafaelstz** [comment]
"=========" is not a file, then you should be in a commented line as it made no sense being talked I removed.

**Comment by xcomSteveJohnson** [comment]
Understood, thanks.

**Comment by rafaelstz** [comment]
:smile: :+1:

**Pull request merged**
