### PR TITLE
td not created make align issue

### PR DESCRIPTION
**Pull request by chandranm**
td tag not avialable from 2.1 version . align issue and difficult to read the file

## This PR is a:
- [ ] New topic
- [ ] Content fix or rewrite
- [x] Bug fix or improvement
 

## Summary
 
When this pull request is merged, it will...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2510) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2510) before we can accept your contribution.<br/>

**Comment by chandranm** [comment]
align issue fixed.

**Comment by chandranm** [comment]
td tag not available from 2.1 version . align issue and difficult to read the file. please apply the same from 2.1 to all

**Comment by keharper** [comment]
Thanks @chandranm

**Pull request merged**
