### PR TITLE
Update the technical content as per the codebase repository

### PR DESCRIPTION
**Pull request by ParthBrahmbhatt**
## Scope of this PR

We set [labels](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#devdocs) based on the scope of changes with a PR.

- Technical: Changes to technical content/code/processes/naming conventions (any change to technical content)

Note the scope of this PR by leaving one of the options and deleting the others.

## Purpose of this PR (required)

When this PR will merge, it will be update technical content based on the latest magento codebase repository.

## Affected URLs (required)

- https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_payment.html

## Links to source code (remove if unused)

If this PR references a file in a Magento codebase repository, add it here.

- https://github.com/magento/magento2/blob/aec044d29b380a2fa15c3726fa733778388bb093/app/code/Magento/Authorizenet/view/frontend/layout/checkout_index_index.xml#L8

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
@ParthBrahmbhatt since this change would affect v2.1, v.2.2, and v.2.3 can you confirm the code change is relevant for all versions?

**Comment by ParthBrahmbhatt** [comment]
yes @erikmarr , this code change is affect v2.1, v.2.2, and v.2.3 version and I have also added into link of source code for reference.

**Comment by erikmarr** [comment]
Thanks @ParthBrahmbhatt for confirming. This will be merged soon.

**Pull request merged**
