### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by vzabaznov**
Add info about how to optimize index process based on latest features released

## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2820) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2820) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@vzabaznov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by shrielenee** [comment]
@vzabaznov - I don't see an index parallelization feature available in store admin. Is this a specific feature, or are you referring more to the functionality? And will users know how and where to set thread counts on the index process?

**Comment by keharper** [comment]
@shrielenee, @vzabaznov is probably referring to https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-index.html#config-cli-subcommands-index-reindex-parallel

**Comment by shrielenee** [comment]
Great! Thanks @keharper and @vzabaznov for this information. 🏆

**Comment by shrielenee** [comment]
I added an edit to the piece of content you added, including a link back to the Manage the indexers page for more info.

**Comment by vzabaznov** [comment]
@shrielenee thanks a lot

**Pull request merged**
