### PR TITLE
Update migration-overview-how.md

### PR DESCRIPTION
**Pull request by SivakumarTim**
## Purpose of this pull request

This pull request (PR) fixes a typo.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/migration/migration-overview-how.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@SivakumarTim thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please can you complete the PR description as defined in the repo WIKI & also sign the Adobe CLA (this is a once only thing)

Thanks for your first submission!

**Comment by BarnyShergold** [comment]
@SivakumarTim - If you don't sign the CLA within the next 2 days this PR will be closed as "Abandoned"

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Pull request merged**
