### PR TITLE
Option added for secure DB connection

### PR DESCRIPTION
**Pull request by konarshankar07**
## Purpose of this pull request

This pull request (PR) will add the option for secure DB connection whilst installation done via cli 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-install.html#instgde-install-cli-magento

## Links to Magento source code

-  https://github.com/magento/magento2/pull/25398

Fixes https://github.com/magento/devdocs/issues/5951

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by konarshankar07** [comment]
I've deleted the symlink to the Magento 2.3 version doc but in order to do that somehow Magento 2.2 version doc link is broken. Any would be appreciated!
Thanks

**Comment by rogyar** [comment]
Hi @konarshankar07. It looks like the direct base change will not work since the branch needs to be created from the `develop` mainline, not from `master`.

**Comment by keharper** [comment]
@konarshankar07 There's now merge conflicts, and so I'd recommend starting over with a new PR off the `develop` branch.

To break a symlink

1. From the `devdocs` directory, run the following command:

git rm guides/v2.3/path/to/file.md

2. Copy the file from the 2.2 directory to the 2.3 directory:
cp guides/v2.2/path/to/file.md guides/v2.3/path/to/file.md

3. Make all edits in the 2.3 file.

**Comment by konarshankar07** [comment]
Hello @rogyar and @keharper ,
I have created a new PR https://github.com/magento/devdocs/pull/6021 and closing this one.
Thanks

**Pull request closed without merging**
