### PR TITLE
MQP Release 1.0.6

### PR DESCRIPTION
**Pull request by ilima-ebay**
## Purpose of this pull request
 
Added RN for MQP v1.0.6
 
## Affected DevDocs pages
 
https://devdocs.magento.com/quality-patches/release-notes.html
 
whatsnew
Published [release notes](https://devdocs.magento.com/quality-patches/release-notes.html) for the 1.0.6 Magento Quality Patch (MQP) package release.

### CODE REVIEW

**Comment by ilima-ebay** [comment]
@jeff-matthews please review, you can publish right away. Thanks!

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
running tests

**Comment by ilima-ebay** [comment]
thanks @jeff-matthews !

**Comment by jeff-matthews** [comment]
thanks for the PR @ilima-ebay! release notes have been published.

**Pull request merged**
