### PR TITLE
Update mysql.md - remove line referring non existent admin feature

### PR DESCRIPTION
**Pull request by kovinet**
In admin interface there is no option to change database engine.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@kovinet thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by BarnyShergold — APPROVED** [review]
Well spotted!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Hi @kovinet Please sign the Adobe CLA, so that we can process this PR. Thanks for the contribution!

**Comment by kovinet** [comment]
> Hi @kovinet Please sign the Adobe CLA, so that we can process this PR. Thanks for the contribution!

I have signed it now.

**Pull request merged**
