### PR TITLE
Updated sample data clone commands

### LINKED ISSUE #8277: Feedback on page: /guides/v2.4/install-gde/install/sample-data-after-clone.html
# General issue

## Description:

In the latest Magento 2.4, there should not be a var/generation folder

## Possible solutions:

Update Text from "rm -rf var/generation/" to "rm generated/*"

### PR DESCRIPTION
**Pull request by chiranjeevi-cj**
## Purpose of this pull request

In the latest Magento 2.4, there should not be a var/generation folder. This pull request (PR) updates the command.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/install-gde/install/sample-data-after-clone.html
-  https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-sample-data-clone.html
-  https://devdocs.magento.com/guides/v2.4/install-gde/install/sample-data-before-clone.html

## Links to Magento source code

-  Fixes #8277 

Screenshot from 2020-11-27 13-54-32

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Nice little addition!

**Comment by keharper** [comment]
@chiranjeevi-cj Since this PR is an update for 2.4, all the discussions about 2.2 branches in the topic need to be updated.

**Comment by chiranjeevi-cj** [comment]
@keharper Sure I will update that too. Thanks!

**Comment by chiranjeevi-cj** [comment]
@keharper Did those changes you mentioned. Can you please verify it? Thanks!

**Review by jeff-matthews — COMMENTED** [review]
Since 2.4.2 won't be released for another ~2 months, we should probably change references to 2.4.2 to 2.4.1.

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
Thanks @chiranjeevi-cj. I'm adding a technical label because of the extra work creating new include files and breaking symlinks.

**Pull request merged**
