### PR TITLE
when we used Breakpoint 'screen__xl' also added in 'style-l.css'

### PR DESCRIPTION
**Pull request by abrarpathan19**
## Purpose of this pull request

This pull request (PR) will provided the information when we used Breakpoint `screen__xl `also added in `style-l.css`

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by abrarpathan19** [comment]
> Hi @abrarpathan19. Thank you for your collaboration.
> Could you, please, clarify what exactly shows the added example. Also, take a look at the markdown usage, the code block section is not completed.

My concern to show this code here that,  If we write code in Breakpoint `screen__xl ` condition our code will added in `style-l.css`

**Comment by rogyar** [comment]
Hi @abrarpathan19. Thank you for the adjustments. I got your point

Example from the codebase: 

https://github.com/magento/magento2/blob/1aed73ef7b48ea17e9f5f52d949dba056b591cfd/app/design/frontend/Magento/blank/Magento_Catalog/web/css/source/_module.less#L614

**Comment by abrarpathan19** [comment]
> Hi @abrarpathan19. Thank you for the adjustments. I got your point
> 
> Example from the codebase:
> 
> https://github.com/magento/magento2/blob/1aed73ef7b48ea17e9f5f52d949dba056b591cfd/app/design/frontend/Magento/blank/Magento_Catalog/web/css/source/_module.less#L614

@rogyar  Thanks

**Pull request merged**
