### PR TITLE
Static content deploy and cache clean commands added

### PR DESCRIPTION
**Pull request by VinothKumar361**
## Purpose of this pull request

Adding additional step 5 Static content deploy and cache clean

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_carrier.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by VinothKumar361** [comment]
@dobooth : thanks changes have been made.

**Comment by dobooth** [comment]
Thanks @VinothKumar361 Looks like this PR branch needs updating as well...22 files in the PR.

**Pull request closed without merging**
