### PR TITLE
Postman url open in new tab

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will redirect the postman URL in the new tab.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/rest/tutorials/index.html
- https://devdocs.magento.com/guides/v2.3/rest/tutorials/bulk-configurable-product/config-product-intro.html
- https://devdocs.magento.com/guides/v2.3/rest/tutorials/inventory/index.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@ronak2ram  We've made the editorial decision to let the reader decide whether they want to open an external link in a separate tab. We've been removing instances of `{:target="_blank"}` when we come across them.

**Comment by ronak2ram** [comment]
@keharper Can I help to remove **{:target="_blank"}** ?

**Comment by keharper** [comment]
@ronak2ram That'd be great if you want to take that on. Don't make any changes under the `v2.0`, since this isn't a technical change, and the directory is going away soon.

**Pull request closed without merging**
