### PR TITLE
remove directly specified version for github-pages gem

### PR DESCRIPTION
**Pull request by likemusic**
When I run jekyll I got error.

```
root@magentodevdocs:~/devdocs# bundle exec jekyll serve --incremental
Configuration file: /root/devdocs/_config.yml
            Source: /root/devdocs
       Destination: /root/devdocs/_site
 Incremental build: enabled
      Generating...
  Liquid Exception: invalid byte sequence in US-ASCII in _layouts/redirect.html
jekyll 3.6.2 | Error:  invalid byte sequence in US-ASCII
```

I found issue https://github.com/jekyll/jekyll-redirect-from/issues/139 and saw that it was fixed in v0.13.0.

`bundle show jekyll-redirect-from` said that v0.12.1 used.
`bundle update` didn't help me to update `jekyll-redirect-from` version to latest.

I looked at Gemfile.lock and found:

```
    github-pages (167)
...
      jekyll-redirect-from (= 0.12.1)
...
```

I locked at `Gemfile` and found:
```
gem 'github-pages', '167'
```

Latest version for 'github-pages' already is v183.

After removing directly defined version `bundle exec jekyll serve --incremental` done without errors.

Here is result example: http://45.77.67.98:4000/

### CODE REVIEW

**Comment by dshevtsov** [comment]
@likemusic thank you for the information.
We experienced issues with unspecified gh-pages in the past. Some versions were incompatible with devdocs.
We will test the newest gh-pages gem and update the Gemfile.

**Comment by dshevtsov** [comment]
Created an internal issue to update the Gemfile: MAGEDOC-2949.

**Comment by dshevtsov** [comment]
@likemusic we updated the [Gemfile](https://github.com/magento/devdocs/blob/develop/Gemfile#L3) and [Gemfile.lock](https://github.com/magento/devdocs/blob/develop/Gemfile.lock#L56).

**Comment by likemusic** [comment]
@dshevtsov I tested building devdocs with current develop-branch.  It works as well without any exception when build by `$ bundle exec jekyll serve --incremental` even under windows.

`$ rake preview` generates some exception under windows:

```
D:\!Valera\!NOW\Magento 2\devdocs>rake preview
rake aborted!
LoadError: Could not open library 'libcurl': ?? ?????? ????????? ??????.
.
Could not open library 'libcurl.dll': ?? ?????? ????????? ??????.
.
Could not open library 'libcurl.so.4': ?? ?????? ????????? ??????.
.
Could not open library 'libcurl.so.4.dll': ?? ?????? ????????? ??????.
D:/!Valera/!NOW/Magento 2/devdocs/Rakefile:1:in `<top (required)>'
```

After I tried install `libcurl` from https://curl.haxx.se/ but haven't success.
Then I looked where `libcurl` should be placed by [Process Monitor](https://technet.microsoft.com/ru-ru/sysinternals/bb896645).

- C:\Ruby25-x64\bin\libcurl.dll
- D:\usr\lib\libcurl
- D:\usr\local\lib\libcurl

Place some libcurl versions from https://curl.haxx.se/ didn't help.
Then I download dll from http://www.dlldownloader.com/libcurl-dll/ and place in `C:\Ruby25-x64\bin\` and have success.

Maybe it will be useful for someone.

**Pull request closed without merging**
