### PR TITLE
fix inconsistency between configuration code and documentation

### PR DESCRIPTION
**Pull request by aeu**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Fix an inconsistency between the name of the module used sample configuration provided and the copy associated with it. 

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3617) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3617) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@aeu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @aeu I think due to context your PR is OK.

We're disabling: `Magento_Review` and not `Magento_Newsletter`.

What do you think @shrielenee ?

**Comment by shrielenee** [comment]
No, I don't think this change is applicable. If you read the pagehttps://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html they are using the newsletter module as an example of something that will not be sent, by editing the `backend` modules config.xml file. The sentence is correct. Does this make sense?

**Comment by shrielenee** [comment]
You are totally right @keharper! I attributed the changes to the wrong section.

@aeu Can you add changes specifying what module each example is modifying?

Thanks all!

**Comment by shrielenee** [comment]
running tests

**Pull request merged**
