### PR TITLE
Update tech-stack.md

### PR DESCRIPTION
**Pull request by rodrigowebjump**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [] Content fix or rewrite
- [X] Bug fix or improvement

## Summary

When this pull request is merged, it will 
Fix broken url in "see the System Requirements"

## Additional information

List all affected URLs 
- https://devdocs.magento.com/guides/v2.3/architecture/tech-stack.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3411) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3411) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Thanks or fixing this @rodrigowebjump. 

The real problem here is that our hosting solution doesn't ignore double forward slashes in a URL. For internal reference, here's what we need to do:

- Create a custom htmlproofer test to catch URLs with double slashes
- Either remove the trailing slash from the Jekyll variables or remove the slash between the variable and the path in all links

^^^ FYI @dshevtsov

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
