### PR TITLE
Update gs-authentication-token.md

### PR DESCRIPTION
**Pull request by ygyryn**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Add missed option 'Extensions' in "Integration tokens" section in p.1. in template: 
guides/v2.1/get-started/authentication/gs-authentication-token.html

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.1/get-started/authentication/gs-authentication-token.html
https://devdocs.magento.com/guides/v2.2/get-started/authentication/gs-authentication-token.html
https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-token.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Pull request merged**
