### PR TITLE
Providing additional info on how an observer can be disabled.

### PR DESCRIPTION
**Pull request by eduard13**
## Purpose of this pull request

This pull request (PR) provides a new section that show how to disable an already created observer.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/events-and-observers.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php#L65

whatsnew
Added the 'Disabling an Observer' section to [Events and Observers](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html).

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @eduard13, Adobe has a new CLA and we need everyone to sign it before we can merge PRs. If you could sign it, we can move forward with this. Thanks for the contribution.

**Comment by eduard13** [comment]
Hi @dobooth, I'm trying to sign it, already did couple of times, getting the confirmation by email, but anyway looks like something goes wrong. 
I've already tried 2 emails, both are linked to this account.
Is there anything else that's needed, except filling in that form?
Thank you.

**Comment by eduard13** [comment]
@dobooth looks like I missed the part with closing/reopening the PR.
Now it's fine.

**Comment by dobooth** [comment]
@eduard13 I have a green checkmark on my side, so it looks like it worked! Thanks for the fast feedback.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
