### PR TITLE
SELinux + Magento 2.3.5 also needs generated

### PR DESCRIPTION
**Pull request by fruit-ninja**
SELinux + Magento 2.3.5 also needs to chcon the generated directory into httpd_sys_rw_content_t

## Purpose of this pull request

Added to guide: SELinux + Magento 2.3.5 also needs to chcon the generated directory into httpd_sys_rw_content_t

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/install-gde/prereq/security.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@fruit-ninja thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Ideally, we should add read+write permission to all directories with files that are being generated upon the runtime. `generated` is definitely one of them. 

@fruit-ninja. Would you sign CLA, please, so we can proceed with the PR processing? 

Thank you

**Comment by fruit-ninja** [comment]
@rogyar I have gone ahead and signed the CLA. Thank you so much.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
