### PR TITLE
Update using-fonts.md

### PR DESCRIPTION
**Pull request by PierW**
##  Purpose of this pull request

With the version 2.4.2 of Magento, there will be the new parameter for the `font-type: <font_type>` for the mixin .lib-font-face(). (See issue #30288 on Magento2 repo)
This update describes it.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@PierW thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
The changes themselves read okay but you have linting errors.

Also it is mentioned that this change is not going to be available until 2.4.2 - should this PR then not be merged into the 2.4.2-develop branch, not master? @dobooth can you comment?

**Comment by PierW** [comment]
> The changes themselves read okay but you have linting errors.
> 
> Also it is mentioned that this change is not going to be available until 2.4.2 - should this PR then not be merged into the 2.4.2-develop branch, not master? @dobooth can you comment?

Yes right. Now we are on develop 2.4.2. But I don't find linting errors. What should I do?

**Comment by BarnyShergold** [comment]
@dobooth  Linting tests are throwing this error : "unable to create symlink src/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.md: File name too long" - I'm not sure what is causing this.

@PierW - You also seem to now have a large number of non-relevant changes in your PR as well as a conflicting file

**Comment by keharper** [comment]
@PierW Because of all the unrelated changes that have bled into this PR, I think you'd be better off closing this one and opening another.

In your new PR, checkout the `2.4.2-develop` branch and be sure to pull in the latest changes before creating  your new local branch. To break the symlink, run the `rake symlink:replace_at path=src/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.md` command from devdocs home directory. That will probably solve the linting error.

**Comment by PierW** [comment]
> @PierW Because of all the unrelated changes that have bled into this PR, I think you'd be better off closing this one and opening another.
> 
> In your new PR, checkout the `2.4.2-develop` branch and be sure to pull in the latest changes before creating your new local branch. To break the symlink, run the `rake symlink:replace_at path=src/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.md` command from devdocs home directory. That will probably solve the linting error.

Thanks, it will be done.

**Pull request closed without merging**
