### PR TITLE
DO NOT MERGE: Update antiXSS guide due to new escaper

### PR DESCRIPTION
**Pull request by AlexMaxHorkun**
New escaper variable has been introduced

## Purpose of this pull request

This pull request (PR) notify developer about the new `#escaper` variable available for .phtml template in 2.4

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/xss-protection.html
-  https://devdocs.magento.com/guides/v2.2/extension-dev-guide/xss-protection.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
This PR is on hold until we finalize the 2.4 branching strategy.

**Comment by dobooth** [comment]
@keharper Moved this to the 2.4.0-develop branch. Good to go?

**Comment by jeff-matthews** [comment]
The `2.4.0-develop` branch isn't quite ready yet. The contributor's branch will need to be updated.

**Comment by dshevtsov** [comment]
@AlexMaxHorkun, please open a new pull request with the corresponding changes to the `src/guides/v2.4/extension-dev-guide/xss-protection.md` file.

Make sure that your topic branch is created off the `2.4.0-develop` branch. The `src/guides/v2.4/extension-dev-guide/xss-protection.md` file will probably be a symlink, that means you have to replace it with a real file before you make any changes. You can use a rake tasks for this if you installed the devdocs project locally (recommended):
```
rake symlink:replace_at path=src/guides/v2.4/extension-dev-guide/xss-protection.md
```
or replace it using Bash explicitly:
```
unlink src/guides/v2.4/extension-dev-guide/xss-protection.md
cp src/guides/v2.3/extension-dev-guide/xss-protection.md src/guides/v2.4/extension-dev-guide/xss-protection.md
```

Please do not hesitate to ask me if you have technical issues in the new PR.
Sorry for the inconvenience.

**Comment by jeff-matthews** [comment]
Changes from this PR ported to the `2.4.0-develop` branch in #6836.

**Pull request closed without merging**
