### PR TITLE
Add response for graphql query

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Response for graphql request is missing in this document. So added response section. 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/product/product-interface-implementations.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@chandru-199 I don't want to maintain a full example/response here, especially with a product that isn't already defined in Luma.
o
I will accept the PR if you move the grouped product example/response into an include file and reference that file from `product-interface-implementations.md` and `grouped-product.md`. Place the file in `src/_includes/graphql/grouped-product-sample.md` and reference the file by adding this line

{% include graphql/grouped-product-sample.md %}

**Comment by chandru-199** [comment]
@keharper : Thanks for your feedback. I added example into include file for the product defined in Luma. Please review it..

**Comment by keharper** [comment]
running tests

**Pull request merged**
