### PR TITLE
Fixed #4894 /guides/v2.3/extension-dev-guide/events-and-observers.html and v2.2

### LINKED ISSUE #4894: Subscribed object is singleton in events by default
# Bug report

shared - Determines the lifestyle of the class. Default is **false**.

### Steps to reproduce

Open https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html and check the `Subscribing to events` section

## Expected result

shared - Determines the lifestyle of the class. Default is **true**.

```
see \Magento\Framework\Event\Invoker\InvokerDefault::dispatch
...
       if (isset($configuration['shared']) && false === $configuration['shared']) {
            $object = $this->_observerFactory->create($configuration['instance']);
        } else {
            $object = $this->_observerFactory->get($configuration['instance']);
        }
...
```

### PR DESCRIPTION
**Pull request by kirtinariya1**
## Purpose of this pull request

This pull request (PR) will be merge the show correct 

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/events-and-observers.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html

## Links to Magento source code
N/A

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
@kirtinariya1 it looks like this PR is a dup of the following:
https://github.com/magento/devdocs/pull/4878
Can we close this one?

**Comment by kirtinariya1** [comment]
@erikmarr T

> @kirtinariya1 it looks like this PR is a dup of the following:
> #4878
> Can we close this one?

Yes

**Comment by erikmarr** [comment]
This is a duplicate of #4878. Closing.

**Pull request closed without merging**
