### PR TITLE
Change redis log level to 4

### LINKED ISSUE #7518: Feedback on page: /guides/v2.4/config-guide/redis/redis-session.html
# General issue

## Description:

Redis won't log anything lower than 4. Current guide says log level = 3

## Possible solutions:

Change log level to 4

## Additional information:

Looking at the Cm\RedisSession\Handler class, it doesn’t write anything below LoggerInterface::WARNING which is 4

### PR DESCRIPTION
**Pull request by miguelbalparda**
Changed log level for redis

## Purpose of this pull request

This pull request (PR) fixes #7518 

## Affected DevDocs pages

- /guides/v2.4/config-guide/redis/redis-session.html 

## Links to Magento source code

- Looking at the Cm\RedisSession\Handler class, it doesn’t write anything below LoggerInterface::WARNING which is 4

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Let me provide another reference here for details

https://github.com/magento/magento2/blob/e60d3a2d8ff3964510ecaa0f7617fa9e482236c4/lib/internal/Magento/Framework/Session/SaveHandler/Redis/Logger.php#L57

The system will create a log record only If the log level of the logger is higher or equals the log level provided to the `::log` method. If we have logger log level = 3, it will be always lower than the log level provided by `Cm\RedisSession\Handler` class (which is 4). So the log record will never be created.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
