### PR TITLE
Add 2021 release dates to release info page

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) adds the 2021 release dates to the release info page. Info provided by Product Management team.

## Affected DevDocs pages

-  https://devdocs.magento.com/release/

whatsnew
Added 2021 release dates to the [release information page](https://devdocs.magento.com/release/).

### CODE REVIEW

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Tests failing on broken links unrelated to this PR. The MFTF team merged breaking changes that cause broken links. Can't merge this until they resolve the error.

Cc: @dobooth & @dshevtsov

**Comment by dobooth** [comment]
running tests

**Comment by jeff-matthews** [comment]
Thanks @dobooth!

**Comment by hostep** [comment]
Hi @jeff-matthews, is the pre-release date for Magento 2.4.1 correct? It says 'October 15, 2021' which is the same date as the 'General Availability' + 1 year, which makes not much sense ? 🙂

**Comment by jeff-matthews** [comment]
Thanks @hostep! That's definitely an error, haha! I'll fix it.

**Comment by jeff-matthews** [comment]
See #7520

**Pull request merged**
