### PR TITLE
Removing the usage of ObjectManager

### LINKED ISSUE #4784: Feedback on page: /guides/v2.3/howdoi/checkout/checkout_new_field.html
# General issue

## Description:

Usage of the **ObjectManager** is strongly discouraged(and for good reason) yet you use is in official how to tutorials.

## Possible solutions:
Remove the usage of the **objectManager** in the tutorial.

### PR DESCRIPTION
**Pull request by LucasCalazans**
## Purpose of this pull request

To remove the usage of ObjectManager in an example

## Affected DevDocs pages

v2.3
https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_new_field.html

v2.2
https://devdocs.magento.com/guides/v2.2/howdoi/checkout/checkout_new_field.html

## Issue
Closes #4784

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @LucasCalazans, thanks for the submission. A question: Did you write this function or does it come from Magento? The "Links to Magento Source Code" section above is for links to the magento2 repository so we can quickly validate the code added to Devdocs.

**Comment by LucasCalazans** [comment]
@dobooth I wrote this function, the section "Links to Magento Source Code" was added wrongly, sorry. I've just edited and removed the section.

**Comment by atwixfirster** [comment]
@LucasCalazans, can you please add

```
/**
  * @var ShippingInformationInterface
  */
```

above line 170:
 
```
private $_addressInformation;
```

Thank you!

**Comment by atwixfirster** [comment]
Also, please sort use classes, lines 164-166.

I would like to see:

```
use Magento\Checkout\Api\Data;
use Magento\Checkout\Api\Data\ShippingInformationInterface;
use Magento\Framework\View\Element;
```

Many thanks!

**Comment by LucasCalazans** [comment]
@atwixfirster done

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
