### PR TITLE
Update searching-with-repositories.md

### PR DESCRIPTION
**Pull request by marcneubauer**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

Removes incorrect tooltip.

## Additional information

List all affected URLs 

- ...
- ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@marcneubauer thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3397) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3397) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Thanks @marcneubauer. In the future, please push changes to the existing PR instead of creating a new one.

**Pull request merged**
