### PR TITLE
Update gem dependencies (github-pages 194)

### PR DESCRIPTION
**Pull request by dshevtsov**
## This PR is a:

Improvement

## Summary

When this pull request is merged, it will update gem dependencies in the `Gemfile.lock`.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@dshevtsov, please don't merge this yet. I'm waiting for the maintainers of the `github-pages` gem to bump the version of `jekyll-relative-links gem` so we can merge https://github.com/magento/devdocs/pull/3695.

I also want to standardize how we make `Gemfile.lock` updates so that all team members are aware of what it means.

**Comment by dshevtsov** [comment]
The latest github-pages (194) has been released today.
The previous release was published in November.
I think next release will not be published earlier than at least in a month.

**Comment by jeff-matthews** [comment]
I'll verify with the maintainers.

**Comment by jeff-matthews** [comment]
They've already released v195, but it doesn't include the gem bump we need. Please standby.

**Comment by dshevtsov** [comment]
The github-pages gem was removed in #3753

**Pull request closed without merging**
