### PR TITLE
Add Braintree VBE and update UG links

### PR DESCRIPTION
**Pull request by leslietilling**
## Purpose of this pull request

This pull request (PR) updates the VBE page to include Braintree as a VBE and update the URLs for user guide links using the old URL path.

## Affected DevDocs pages

-  https://devdocs.magento.com/extensions/vendor/

### CODE REVIEW

**Review by jeff-matthews — COMMENTED** [review]
Do we need to add Braintree to the compatibility matrix?

**Comment by leslietilling** [comment]
> Do we need to add Braintree to the compatibility matrix?

Yes, we should. In 2.4.0, it was removed as core integration and added as VBE.

**Comment by dobooth** [comment]
@leslietilling

**Comment by leslietilling** [comment]
@jeff-matthews  This is the version information from Daisy:

Braintree Version     Magento Version 
v4.1.0                            v2.4.0                 
v4.2.0                             v2.4.1

**Comment by jeff-matthews** [comment]
I'll add the 2.4.0 entry in this PR and open a new PR to the `2.4.2-develop` branch to add the 2.4.1 entry.

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Oops... I just realized that we didn't update the matrix for 2.4.1 and I confused myself thinking that 2.4.1 was the next release.

I've added 2.4.1 entries for all other VBEs in the `2.4.2-develop` branch, so I'm going to stick to the plan and add the Braintree entry for 2.4.1 there as well. We've gone this long, what's a few more days?

**Pull request merged**
