### PR TITLE
magento/devdocs#5924: Add clarification to required files in About component file structure page

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/devdocs/issues/5924.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/prepare/prepare_file-str.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/prepare/prepare_file-str.html

## Links to Magento source code

-  ...

Thank you!

whatsnew
Added [clarification](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/prepare/prepare_file-str.html) about required component files.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
These will likely need a technical review, as it contains a newly created include.

**Comment by jeff-matthews** [comment]
@osrecio, waiting for your review.

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
