### PR TITLE
Fix root to be visible on Magento DevDocs website

### PR DESCRIPTION
**Pull request by twocs**
## Purpose of this pull request
The Magento website (https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-mode.html) renders the <magento_root> tags as html, so they are not visible to the reader.

On the Magento website the command looks like
`rm -rf /generated/metadata/* /generated/code/*`
But it should look like 
`rm -rf <magento_root>/generated/metadata/* <magento_root>/generated/code/*`
Note that GitHub is rendering it as intended.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-mode.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4779) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4779) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@twocs thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Good catch!

**Comment by jeff-matthews** [comment]
@dobooth, please add appropriate labels.

**Pull request merged**
