### PR TITLE
update using-font for 2.4.2. New parameter font-type for custom fonts

### PR DESCRIPTION
**Pull request by PierW**
##  Purpose of this pull request

With the version 2.4.2 of Magento, there will be the new parameter for the `font-type: <font_type>` for the mixin .lib-font-face(). (See issue #30288 on Magento2 repo)
This update describes it.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.html

### Resolved issues:
1. [x] resolves magento/devdocs#8027: update using-font for 2.4.2. New parameter font-type for custom fonts

### CODE REVIEW

**Comment by PierW** [comment]
@magento create issue

**Review by BarnyShergold — APPROVED** [review]
Looks all good now!

**Comment by mrtuvn** [comment]
`@font-type: 'truetype` seem you missing this one quote at line 50

**Comment by BarnyShergold** [comment]
> @PierW `@font-type: 'truetype` seem you missing this one quote at line 50

Blimey - Eagle eyes - well spotted! I'd read that twice and didn't see that!

**Comment by PierW** [comment]
> @PierW `@font-type: 'truetype` seem you missing this one quote at line 50

@mrtuvn Eagle eyes, I fixed it, thanks!
@BarnyShergold

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
