### PR TITLE
Fix documentation for clearCustomerCart

### PR DESCRIPTION
**Pull request by danmooney2**
Update documentation to match definitions in the schema files.

## Purpose of this pull request

This pull request (PR) fixes descriptions of input/output for clearCustomerCart.

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.4/graphql/mutations/clear-customer-cart.html

## Links to Magento source code
- https://github.com/magento-commerce/magento2b2b/blob/caae8db28cc56efce89fbc707d06b195285ff814/app/code/Magento/RequisitionListGraphQl/etc/schema.graphqls#L185
- https://github.com/magento-commerce/magento2b2b/blob/caae8db28cc56efce89fbc707d06b195285ff814/app/code/Magento/RequisitionListGraphQl/etc/schema.graphqls#L98

### CODE REVIEW

**Review by dhaecker — APPROVED** [review]

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
@danmooney2 Can this be merged now, or does it need to wait to the next release of B2B?

**Comment by danmooney2** [comment]
Hi @keharper, this change is a fix for an issue in existing releases and does not need to wait to be merged.

**Comment by keharper** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-danmooney2-devdocs-9531`.

**Pull request merged**
