### PR TITLE
Fix markdown for `variables` link.

### PR DESCRIPTION
**Pull request by likemusic**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix markdown for `variables` link.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/cloud/project/projects.html
- https://devdocs.magento.com/guides/v2.2/cloud/project/projects.html
- https://devdocs.magento.com/guides/v2.3/cloud/project/projects.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Pull request closed without merging**
