### PR TITLE
magento/devdocs#6689: Add information about required Apache configuration adjustment

### PR DESCRIPTION
**Pull request by atwixfirster**
##  Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/devdocs/issues/6689

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/install-gde/prereq/apache.html

## Links to Magento source code

-  ...

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by atwixfirster** [comment]
> If it is important, let's tell them why it is important and what might happen if they don't.

I've extended my a bit a clarification.

**Comment by ihor-sviziev** [comment]
@atwixfirster i think it’s better to clarify that misconfiguration will cause an issues for URLs that contains slash, for instance retrieving products with slash in SKU via API, applying coupon code with slash

**Comment by atwixfirster** [comment]
Suggestions have been **implemented**.

@ihor-sviziev , could you please review?

Thanks

**Comment by dobooth** [comment]
running tests

**Pull request merged**
