### PR TITLE
Removed triple dots to stop appearing in Apache configuration block

### LINKED ISSUE #7542: Clean up sample in Apache documentation
# General issue

## Description: AllowEncodedSlashes code snippet - Copy Issue

Clicking on "Copy" to copy the code for AllowEncodedSlashes copies text along with the three dots that act as a line separator i.e. "..." and for a non tech savvy person this might cause issue with the server.

Path to file: /guides/v2.4/install-gde/prereq/apache.html

## Possible solutions:

Remove the dots and let the code be : 

<VirtualHost *:443>
# Allow encoded slashes
AllowEncodedSlashes NoDecode
</VirtualHost>

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request

This pull request (PR) fixes #7542 

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/install-gde/prereq/apache.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/apache.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
On the other hand, the three dots indicate content has been omitted for brevity. A reader naive enough to copy and paste that sample might also replace their `VirtualHost` section with the example with just one directive. As a compromise, I suggest adding a comment line that says something like "other directives may apply".

I'm not saying I'm right, and if you push back, I'll relent. To me, this is a "meh" style issue.

**Comment by BarnyShergold** [comment]
I would tend to agree with you but it's a quick change and any thing that can eliminate a mistake.....

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Pull request merged**
