### PR TITLE
Adding additional information regarding InstallData and a reference to data patches for 2.3.

### PR DESCRIPTION
**Pull request by brobie**
https://github.com/magento/devdocs/issues/3700

## Purpose of this pull request
This pull request seeks to satisfy the suggestions and comments in #3700.  It adds clarity around InstallData/UpgradeData scripts in relation to customer EAV attributes.  Since this method of attribute adding does not exist in 2.3, the 2.3 documentation was update to include information about data patch files.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html
- https://devdocs.magento.com/guides/v2.1/extension-dev-guide/attributes.html

whatsnew
Added clarity for `InstallData`/`UpgradeData` in relation to customer EAV attributes for [EAV and extension attributes](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html) for all versions.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4494) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4494) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by lorikrell** [comment]
@brobie Thanks for the contribution! Starting reviews!

**Comment by lorikrell** [comment]
running tests

**Comment by lorikrell** [comment]
running tests

**Comment by lorikrell** [comment]
Merging into another branch to complete link tests and resolve. Then will merge branch.

**Pull request merged**
