### PR TITLE
Update multirepo script

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) removes the fetch command from the multirepo script.

It seems unnecessary to fetch all branches from a repo if we only need the latest version of the main branch. The `init` stage on our pipelines is hanging periodically for some builds. My expectation after merging this PR is that we will reduce times for the `init` stage.

We don't have the visibility into the network infrastructure to troubleshoot the long stage times, so this seems like the most effective way to eliminate one possible cause for the long `init` stage times.

### CODE REVIEW

**Comment by dshevtsov** [comment]
This will create empty local repositories and as a result - empty folders.
You have to fetch to download git history from a remote repository.

**Comment by dshevtsov** [comment]
To test changes to the script locally, remove all directories that contain subrepositories and run `rake init`.

**Comment by jeff-matthews** [comment]
Bleh... you're right.

**Comment by jeff-matthews** [comment]
Since we're removing 2.0 content next week, hopefully this issue will become a moot.

**Comment by dshevtsov** [comment]
To avoid fetching the repo for 2.0, we can use `git worktree add -f guides/v2.0 2.0` instead.
I plan to implement this to the script later when I have time.

**Pull request closed without merging**
