### PR TITLE
Update migration-migrate-delta.md

### PR DESCRIPTION
**Pull request by brentwpeterson**
Add a link to table list for delta migration tables in M1

## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

Added link to update delta migration with a list of table changes that will go into the M1 version

This adds a link to the new page I created on pull request #3678 

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.3/migration/migration-migrate-delta.html
- ...
- ...

### CODE REVIEW

**Comment by brentwpeterson** [comment]
#mm19in

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
This PR can't be merged until #3678  be merged

**Comment by shrielenee** [comment]
Hey @osrecio --- This change should be added in #3678 so that they are batched together. I will be closing this PR so that you may batch the changes. Thanks!

**Pull request closed without merging**
