### PR TITLE
deleted basics_software.md file and removed the reference for 'What i…

### LINKED ISSUE #8201: Feedback on page: /guides/v2.4/install-gde/basics/basics_software.html
# General issue

## Description:
This page doesn't really add any information to the devdocs. The https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html page covers everything.

## Possible solutions:

Remove the page.

## Additional information:

It doesn't make sense to support two pages with system requirements.

### PR DESCRIPTION
**Pull request by chiranjeevi-cj**
## Purpose of this pull request

1. This pull request (PR) removes https://devdocs.magento.com/guides/v2.4/install-gde/basics/basics_software.html page.
2. This page doesn't really add any information to the dev docs. 
3. The https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html page covers everything.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/install-gde/basics/basics_software.html
-  https://devdocs.magento.com/guides/v2.3/install-gde/basics/basics_software.html

Fixes #8201

### CODE REVIEW

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Review by BarnyShergold — APPROVED** [review]
I concur that the removed page is redundant - good clean up, thanks!

**Comment by dobooth** [comment]
@chiranjeevi-cj Thanks for the contribution. We wanted to invite you to make this PR against the `install-guide-refresh` branch. We recently started to rethink the install guide: cleaning up redundant content, simplifying the Table of Contents, etc.
We just started the project and it might be some time before it goes live, but this PR would fit in nicely with our goals. If you want to do so, it would have to be rebased against the correct branch. Thanks!

**Comment by chiranjeevi-cj** [comment]
@dobooth Rebased to the requested branch. Please have a look at it. Thanks

**Comment by dobooth** [comment]
Rake build passed with no issues.

**Comment by dobooth** [comment]
Thanks @chiranjeevi-cj !

**Pull request merged**
