### PR TITLE
HTML anchor to markdown.

### PR DESCRIPTION
**Pull request by jignesh-baldha**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will convert HTML anchor to markdown.

### CODE REVIEW

**Comment by osrecio** [comment]
Hi @jignesh-baldha Try to resolve conflicts updating your branch with master

**Comment by jignesh-baldha** [comment]
@osrecio Merged branch `master` into my branch `jignesh-patch6`. Please check now.

**Comment by osrecio** [comment]
Now is OK, thanks @jignesh-baldha

**Comment by dshevtsov** [comment]
Markdown links inside HTML won't be converted correctly.

To make it work, use `markdown='span'` attribute.

Example: `<td markdown='span'>[text](link)</td>`

**Comment by dshevtsov** [comment]
I strongly recommend to test the output when you automate find and replace.

For this case, search for occurrences `](` in the `_site` directory.

**Comment by jeff-matthews** [comment]
I should've caught that before merging. I'll fix these.

**Comment by jeff-matthews** [comment]
See Pr https://github.com/magento/devdocs/pull/2765

**Pull request merged**
