### PR TITLE
Improves GraphQL queries indentation

### PR DESCRIPTION
**Pull request by williankeller**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Improves the GraphQL queries indentation and also, change the markdown code `json` to `text` since it's not a JSON format and it's causing error lines at the GitHub.
#### Before:
https://github.com/magento/devdocs/blob/master/guides/v2.3/graphql/search-pagination.md
image
#### After:
https://github.com/williankeller/devdocs/blob/improve/graphql/guides/v2.3/graphql/search-pagination.md
image

## Additional information

List all affected URLs 
- https://devdocs.magento.com/guides/v2.3/graphql/search-pagination.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@williankeller We formerly used a different mechanism for wrapping this type of text, but we discontinued that in favor of the triple backticks like "```json", causing this display problems in GitHub. 

I've built your PR internally to see how it will display on devdocs. This screenshot is a code snippet in the current version:

screen shot 2019-02-01 at 9 47 06 am

And this is with your applied changes:

Screen Shot 2019-02-01 at 9.47.51 AM

We lose a little bit of formatting, but I'm OK with this. As you said, the text isn't really json, and this will make the errors go away. 

I'd appreciate it if you'd create an issue to change all the GraphQL request examples (and not result examples) to use text formatting instead of json.

**Comment by williankeller** [comment]
Hi @keharper 
The syntax for that query didn't change. I just improved the text formatting and the code indentation.
Just to keep the code clearer and easier to understand, I moved the `like` conditions into a new line.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks, @williankeller

**Pull request merged**
