### PR TITLE
Cloud 2002.0.19 release

### PR DESCRIPTION
**Pull request by hguthrie**
This contains one update for the Cloud 2002.0.19 release.

whatsnew
Updated the [Cloud Release notes for ece-tools version 2002.0.19](https://devdocs.magento.com/guides/v2.3/cloud/release-notes/cloud-tools.html#v2002019).

### CODE REVIEW

**Comment by hguthrie** [comment]
Note has technical approval; just waiting for the actual release.

**Comment by hguthrie** [comment]
running tests

**Comment by hguthrie** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
