### PR TITLE
magento/devdocs#: UrlRewrite endpoint

### PR DESCRIPTION
**Pull request by atwixfirster**
Updates to "UrlRewrite endpoint" regarding to `Magento2 version 2.3.1`.

## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix visual issue on the page "UrlRewrite endpoint" 

UrlRewrite_endpoint_01

and updates information about `UrlRewrite` regarding to `Magento2 version 2.3.1`.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/reference/url-resolver.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@atwixfirster The parts about `relative_url` and `canonical_url` are not correct for 2.3.1. Those changes appear in the `2.3-develop` branch of the graphql-ce repo, but they won't be merged into mainline until 2.3.2. Please back out those changes.

Note: Those changes have been applied to 2.3.2 in the `develop` branch per #3925 

I'm not sure if the `url` parameter was removed at some time in the past, or if it's there due to some copy/paste mistake, but I verified it's not in the 2.3.1 branch. I'll merge the non `relative_url`/`canonical_url` changes you made in thus PR.

**Comment by atwixfirster** [comment]
> @atwixfirster The parts about `relative_url` and `canonical_url` are not correct for 2.3.1.

I am sorry @keharper . I used a wrong branch when wrote about `relative_url`

😊

**Comment by atwixfirster** [comment]
@keharper , so when this pull request is merged, it will fix visual issue on the page "UrlRewrite endpoint" 

UrlRewrite_endpoint_01

Thank you!

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks, @atwixfirster

**Pull request merged**
