### PR TITLE
magento/devdocs#: Mutation query for addDownloadableProductsToCart

### PR DESCRIPTION
**Pull request by atwixfirster**
## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will update content of "DownloadableProduct endpoint" page. Pull request adds mutation queries and clarifications for the `addDownloadableProductsToCart` operation.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/reference/downloadable-product.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by atwixfirster** [comment]
Can we hold on with this pull request. I've added information about new feature that already under develop branch. 

PR: https://github.com/magento/graphql-ce/pull/412

Thank you!

**Comment by keharper** [comment]
Reviewing GraphQL PRs. `addDownloadableProductsToCart` is not currently in the 2.3.2 build. Assigning the 2.3.3 label.

**Comment by keharper** [comment]
@atwixfirster I'm closing this PR because by the time the code is merged into a release branch (presumably 2.3.4), queries and mutations will be documented separately. In addition, there are numerous deprecated attributes. I think the overall amount of work will be less way.

**Pull request closed without merging**
