### PR TITLE
Magento/magento2#28803

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
## Purpose of this pull request

This pull request (PR) creates documentation for commands added in https://github.com/magento/magento2/pull/28677.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html
- https://devdocs.magento.com/guides/v2.4/reference/cli/magento-commerce.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by BarnyShergold** [comment]
@engcom-Foxtrot - As this is thousands of lines of JSON - how do you want this 'reviewed'?

**Comment by jeff-matthews** [comment]
This looks like a bot user. @dshevtsov, so you know anything about this? I know we have some internal automation that generates the CLI reference JSON from a running instance of Magento 2 after each release. As such, these files should not be manually edited by contributors.

**Comment by engcom-Foxtrot** [comment]
@BarnyShergold hello. I've divided PR into two commits - https://github.com/magento/devdocs/pull/7838/commits/77d28257eb78b076fe37ca3de44059831c613e6c should not be reviewed, as its only JSON reformatting, and all of the real changes are in https://github.com/magento/devdocs/pull/7838/commits/3737b2a7a3474c090efccc4756a032c7d727ed5d.

**Comment by engcom-Foxtrot** [comment]
@jeff-matthews maybe you're right about CLI reference auto-generation. In that case, this PR should be closed.

**Comment by jeff-matthews** [comment]
hi @engcom-Foxtrot, sorry for suspecting you of being a bot!

Did you notice some 2.4 commands that were not listed in the published reference? If not, I'm going to close this PR since our internal automation updates these reference files after every release.

**Comment by jeff-matthews** [comment]
The PR to magento/magento2 mentioned in the PR description is for a future 2.4.x version. Since it has not been merged yet, I don't think it will make it into 2.4.1, so I'm closing this PR. Our automation will pick up the new commands when they're merged.

**Pull request closed without merging**
