### PR TITLE
Update identity-class.md

### PR DESCRIPTION
**Pull request by Vinai**
## Purpose of this pull request

* Import the correct `Magento\Framework\GraphQl\Query\Resolver\IdentityInterface`.
* Clarify what is required and what is an implementation detail.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/graphql/develop/identity-class.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Example from the core codebase: https://github.com/magento/magento2/blob/0a5b24a93fb31707f4745c5354fdff82376a9b65/app/code/Magento/CmsGraphQl/Model/Resolver/Page/Identity.php

**Comment by dobooth** [comment]
Hi @Vinai Looks like it wants you to sign the new Adobe CLA. Please do so and we can get this through.

**Comment by Vinai** [comment]
@dobooth done! I thought signing it once for the magento/magento2 repository would suffice, but it seems to be required for each individual repository.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
