### PR TITLE
Update the Multiline component documentation

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) updates the documentation for the Multiline UI component.

Updates:
- Adjusted the markup for the options table
- Fixed the wrong default values for some options
- Added the Source files section 
- Added the Example section
- Added the Result section

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-multiline.html
- https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-multiline.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/templates/group/group.html
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Ui/view/base/web/templates/group/group.html
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/form/components/group.js
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Ui/view/base/web/js/form/components/group.js
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Customer/view/base/ui_component/customer_form.xml#L151
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Customer/view/base/ui_component/customer_form.xml#L151

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by serhiyzhovnir** [comment]
Hi @erikmarr @bdenham
Any updates here?

**Comment by bdenham** [comment]
running tests

**Comment by keharper** [comment]
@bdenham You need to add a `whatsnew` statement.

**Pull request merged**
