### PR TITLE
Expanded info on factories and proxies

### PR DESCRIPTION
**Pull request by CNanninga**
… to provide more details and make info easier to find at a glance.  (Particularly info on factories, which are essential for most development but are somewhat buried in the current documentation.)

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
@CNanninga  This looks really fantastic, thanks! I'm not all that familiar with the PHP Dev Guide so I need to know if you're replacing topics or just adding some and reordering them in the TOC?

If you're replacing topics I need to add redirects, be glad to do that, just need to know.

**Comment by CNanninga** [comment]
@Steve

I'm not sure I quite understand the thrust of the question, so I'll just be
really verbose!

The Factories and Proxies pages are both new pages.  However, there were a
few snippets of information about factories and proxies among the rest of
the content on the Dependency Injection and Code Generation pages.  I
trimmed these a bit and put in links to the new pages instead of having
much detail in those locations.  There was previously a *section *of the
Dependency Injection page about factories (#dep-inj-mod-type-fact) that a
few links targeted directly.  I believe I took care of all such links,
though, and I don't believe such a scenario would necessitate any redirects.

I hope that gives you the info you needed.  If not, let me know!


Chris Nanninga
Senior Engineer, Classy Llama
MAGENTO CDP, Magento CFED, Magento CSS, Zend Ce
*o* 417.866.8887 ext. 105 | *chris.nanninga@classyllama.com
<chris.nanninga@classyllama.com>*

**Comment by davidalger** [comment]
@steverobbins quick glance over the diff; no changed urls, so shouldn't necessitate any redirects, as it's only re-ordering and adding new pages.

Nice work, Chris!

**Comment by xcomSteveJohnson** [comment]
Thanks all. I'll merge this soon.

**Comment by xcomSteveJohnson** [comment]
@CNanninga and @davidalger I did some proofreading on the two new topics and created another PR for it: #535. Closing this one to avoid redundancy.

**Comment by xcomSteveJohnson** [comment]
BTW, I haven't done this exact thing before so maybe you can advise me... By closing @CNanninga's PR, he doesn't get credit for it but I wasn't sure if there was an alternative. 

Let me know if there is a different way to do this and next time I won't have to close the original PR. But we're still giving you credit on the topics themselves. (Look at the top under the topic title.)

**Comment by tanberry** [comment]
Wow. Christmas in Febuary. Thanks so much @CNanninga and @davidalger!! The PHP Dev Guide lost its main writer last fall; it has been a bit neglected, so we really appreciate the help! Good news is that we have made an offer to a new writer (who is also a developer, gasp!) named James Calcaben; he will hopefully be onboard her at Magento and interacting with the terrific Llamas soon. There is tons of work to be done on this dev guide, everything from info architecture down to nitty gritty details in the content. And eventually adding tutorials, scenario-based topics, and more. Thanks again!!

**Comment by davidalger** [comment]
> BTW, I haven't done this exact thing before so maybe you can advise me... By closing @CNanninga's PR, he doesn't get credit for it but I wasn't sure if there was an alternative.

Since his actual commit is in the new PR and wasn't squashed into your's, this PR should show as merged when you merge the other one and it should report in the GH contributors tab. ;)

**Pull request closed without merging**
