### PR TITLE
MQP Release 1.0.14

### PR DESCRIPTION
**Pull request by abukatar**
## Purpose of this pull request
 
Added RN for MQP v1.0.14
 
## Affected DevDocs pages
 
https://devdocs.magento.com/quality-patches/release-notes.html
 
whatsnew
Published [release notes](https://devdocs.magento.com/quality-patches/release-notes.html) for the 1.0.14 Magento Quality Patch (MQP) package release.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@abukatar thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
@abukatar, please sign the Adobe CLA and let me know when you'd like this PR merged and published on devdocs.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
@abukatar, the release notes have been published on devdocs. Thanks for the PR!

**Pull request merged**
