### PR TITLE
Frontend area layout xml improvements.

### PR DESCRIPTION
**Pull request by sanganinamrata**
## Purpose of this pull request

This pull request (PR) is an update for https://github.com/magento/magento2/pull/30539 improvements.
- Removed `class="Magento\Framework\View\Element\Template"` from frontend layout xml files, as `"Magento\Framework\View\Element\Template"` is the default frontend class taken by Magento.

## Affected DevDocs pages

- [Create a new page layout in custom theme
](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-create.html#create-a-new-page-layout-in-custom-theme)
- [Create a new page layout in custom theme
](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-create.html#create-a-new-page-layout-in-custom-theme)
- [Customize recommendation unit positioning
](https://devdocs.magento.com/recommendations/customize.html#customize-recommendation-unit-positioning)
- [Create a layout update to add a template that will enable the JavaScript module](https://devdocs.magento.com/videos/fundamentals/add-a-javascript-module/#step-3-create-a-layout-update-to-add-a-template-that-will-enable-the-javascript-module)

## Links to Magento source code

- This PR doesn't affect Magento core code. This is layout XML examples improvements on devdoc.

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please add ALL pages that are affected by this (inc 2.4 versions) to the description
Please add a link to the Magento code changed that this PR refers to
Add a whatsnew to the description

**Comment by sanganinamrata** [comment]
@BarnyShergold I've updated the PR Description. Please have a look.

**Review by BarnyShergold — APPROVED** [review]
Thanks for the updates!

**Comment by sanganinamrata** [comment]
@BarnyShergold Will you please proceed this PR?

**Comment by keharper** [comment]
@sanganinamrata The code PR you reference is for the 2.4-develop branch. One of your changes was against a 2.3 file, and that shouldn't be changed.

I have to ask you make the following changes to this PR:

1. Rebase to the `2.4.2-develop` branch.

2. Break the symlink between the 2.3 and 2.4 versions of `layout-create.md`. To do this, run the `rake symlink:replace_at path=src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md` command from the devdocs root directory. Revert the changes in the v2.3 version and keep them in the v2.4 version.

**Comment by dobooth** [comment]
@sanganinamrata

**Comment by dobooth** [comment]
Closing as abandoned. Please file another PR with these changes, including the requested changes and we will be happy to process it.

**Pull request closed without merging**
