### PR TITLE
Create a page describing working with async code

### PR DESCRIPTION
**Pull request by AlexMaxHorkun**
Page described how to work with DeferredInterface introduced in https://github.com/magento/architecture/pull/71

## Purpose of this pull request

This pull request (PR) will guide developers through writing asynchronous code in Magento

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/module-development.html

## Links to Magento source code

- https://github.com/magento/architecture/pull/71

whatsnew
Added the [Asynchronous and deferred operations](http://devdocs.magento.com/guides/v2.3/extension-dev-guide/async-operations.md) topic to the PHP Developer Guide.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4820) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4820) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
