### PR TITLE
Update widget_modal.md for JS syntax error

### PR DESCRIPTION
**Pull request by MikeSheward**
Fixing syntax errors in the document.

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Fix a syntax error for initialising modals.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_modal.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3684) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3684) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@MikeSheward thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
Hello @MikeSheward - thanks for this change. The v2.3 version of this page is symlinked back to v2.2, to v2.1. This change should be completed in the v2.1 version so that all forward versions receive the change. Please make this change and resubmit for approval. Thanks!

**Comment by MikeSheward** [comment]
@shrielenee I've made the requested changes,

Thanks.

**Comment by shrielenee** [comment]
running tests

**Comment by MikeSheward** [comment]
I've made the changes to the 2.1 file, and the 2.3 changes have been reverted back to it's original contents.

**Comment by shrielenee** [comment]
Hey there @MikeSheward - It still looks like the content for the v2.3 version is completely gone.

screen shot 2019-02-11 at 8 03 12 am

To be clear, you only need to make your changes in the v2.1 version of the file, as both the v2.2 and v2.3 versions are symlinked back to v2.1 and will show the same content.

To complete this PR, re-add all previous content to the v2.3 version, keep your v2.1 changes (which will apply to v2.2 and v2.3) and resubmit. Let me know if you have any questions!

**Comment by shrielenee** [comment]
Hey @MikeSheward - Did you see my previous comments? Let me know if you don't plan to make those revisions and I'll close this PR. Thanks!

**Comment by MikeSheward** [comment]
Ok i've fixed the symlink file for 2.3, so it now points to 2.2, which falls back to the fixed 2.1.

Thanks

**Comment by shrielenee** [comment]
@MikeSheward As you can see, you still have no files changed. My comment from 28 days ago instructs you on what you need to do to remedy this.

Screen Shot 2019-03-11 at 10 42 39 AM

At this juncture, I am going to close this PR. If you want to resubmit it with appropriate changes, we'd love that! Thanks for taking the time to contribute---we just need some more revision to make it applicable to our docs.

**Pull request closed without merging**
