### PR TITLE
Update install-cli-subcommands-admin.md

### PR DESCRIPTION
**Pull request by chickenland**
updated example admin user creation to include quotes wrapped around it as per the requirement in the definition for it above

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Nice little tweak

**Review by hguthrie — DISMISSED** [review]
Interesting. I bet there are few other places in the docs where this could be added for consistency.

**Comment by BarnyShergold** [comment]
> Interesting. I bet there are few other places in the docs where this could be added for consistency.

I found at least 20 instances....

**Comment by keharper** [comment]
The command works for me as listed. Why do we state to enclose the password in single quotes?

**Comment by keharper** [comment]
Let me ask a more directed question. Are there special characters that can interfere with the execution of the command if the entire password is not enclosed in single quotes? I can't think of any other possible reason that we'd state to enclose the password value.

**Comment by hguthrie** [comment]
I agree with you. The only reason that instantly comes to my mind is to assure literal interpretation.

**Comment by keharper** [comment]
I'm requesting the following modifications to this PR.

1. Revert the command example.

2. Modify the description of the `--admin-password` argument (line 47) to be similar to the following

If the password string contains special characters that require literal interpretation (such as backslashes or spaces), enclose the password in single quotations.

Then delete the "For example" sentence.

**Comment by keharper** [comment]
I forgot to mention @chickenland @BarnyShergold

**Comment by dobooth** [comment]
Hi @chickenland Any updates here?

**Comment by dobooth** [comment]
Closing as abandoned.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Pull request merged**
