### PR TITLE
Made semantic change in phrase

### PR DESCRIPTION
**Pull request by Neeldip-GTL**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/cache/page-caching/private-content.html
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/message-queues/async-message-queue-config-files.html
-  ...

## Links to Magento source code

https://github.com/magento/devdocs/blob/src/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
https://github.com/magento/devdocs/blob/src/guides/v2.3/extension-dev-guide/message-queues/async-message-queue-config-files.md
-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@Neeldip-GTL thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please fill in PR description as required, https://github.com/magento/devdocs/pull/8283 is a good example.
Please also sign the Adobe CLA

**Review by hguthrie — APPROVED** [review]

**Comment by hguthrie** [comment]
@Neeldip-GTL  Please sign the CLA so that we can continue to process your PR.

**Review by BarnyShergold — APPROVED** [review]

**Comment by hguthrie** [comment]
Closing this due to lack of response.

**Pull request closed without merging**
