### PR TITLE
make link clickable

### PR DESCRIPTION
**Pull request by misha-kotov**
## Purpose of this pull request

This pull request (PR) makes clickable the account.magento.com link so users do not have to copy-paste the URL into their browser.

## Affected DevDocs pages

-  https://devdocs.magento.com/recommendations/configure.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
duplicates #6614

**Comment by erikmarr** [comment]
running tests

**Comment by jeff-matthews** [comment]
Since @atwixfirster already created a PR to fix this (#6614) we should merge it and close this.

Thanks for opening a PR though @misha-kotov.

**Pull request closed without merging**
