### PR TITLE
Update project-conf-files_services-mysql.md

### PR DESCRIPTION
**Pull request by MarkADurham**
## Purpose of this pull request

Fixed the mysql command syntax for setting the port number.

Change from:
   "mysql -h<db> -p<number> -u<username> -p<password>"
to:
   "mysql -h<db> -P<number> -u<username> -p<password>"

That is, change the first lowercase "-p" to an uppercase "-P". The lowercase "-p" is for the password (as seen in the second instance of "-p"). The first instance is supposed to be the option to set the port, which should be an uppercase "-P".

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/project/project-conf-files_services-mysql.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @MarkADurham. If you could sign the Adobe CLA below, we can get this merged. Thanks for the contribution.

**Comment by MarkADurham** [comment]
> Hi @MarkADurham. If you could sign the Adobe CLA below, we can get this merged. Thanks for the contribution.

I am waiting on approval from my place of employment. I will sign as soon as I get it.

**Comment by MarkADurham** [comment]
> > Hi @MarkADurham. If you could sign the Adobe CLA below, we can get this merged. Thanks for the contribution.
> 
> I am waiting on approval from my place of employment. I will sign as soon as I get it.

CLA is signed.

**Comment by magento-engcom-team** [comment]
@MarkADurham thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
