### PR TITLE
Update Advance Reporting XML configuration

### PR DESCRIPTION
**Pull request by magesanjay**
## Scope of this PR

- __Technical__: Update Advance Reporting XML configuration.

## Purpose of this PR

When this pull request is merged, it will update Advance Reporting XML file configuration.

## Affected URLs

- https://devdocs.magento.com/guides/v2.2/advanced-reporting/data-collection.html
- https://devdocs.magento.com/guides/v2.3/advanced-reporting/data-collection.html

## Links to source code

Codebase Urls:

- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Analytics/etc/analytics.xml#L8
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Analytics/etc/analytics.xml#L8

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magesanjay** [comment]
@jeff-matthews It's too old file.
I have just check code base file history and last modification date of the files is given below:
[2.2-develop is Sep 29, 2017](https://github.com/magento/magento2/commits/2.2-develop/app/code/Magento/Analytics/etc/analytics.xml)
[2.3-develop is Dec 8, 2017](https://github.com/magento/magento2/commits/2.3-develop/app/code/Magento/Analytics/etc/analytics.xml)

**Comment by jeff-matthews** [comment]
@magesanjay, my point is that when contributors link to the develop branches in the source code, it signals the devdocs admins and maintainers that the PR supports an upcoming release. Since that's not the case here, you should not link to the develop branches. You should link to the release branches:

https://github.com/magento/magento2/blob/2.2/app/code/Magento/Analytics/etc/analytics.xml#L8
https://github.com/magento/magento2/blob/2.3/app/code/Magento/Analytics/etc/analytics.xml#L8

**Comment by magesanjay** [comment]
@jeff-matthews Ok Understood.
This is updated Urls: 
https://github.com/magento/magento2/blob/2.2/app/code/Magento/Analytics/etc/analytics.xml#L8
https://github.com/magento/magento2/blob/2.3/app/code/Magento/Analytics/etc/analytics.xml#L8

**Pull request merged**
