### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manavluhar**
## Purpose of this pull request

This pull request (PR):
- Adds **devdocs Slack Channe**l Link and adds Link of **Magento Community Engineering** Slack Group link.
- Changes Twitter link text from **Follow @MagentoDevDoc**s to **Twitter @MagentoDevDocs** as Functionality of this link not for follow the @MagentoDevDocs Twitter page Functionality of this link is to open @MagentoDevDocs Twitter page.

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by dobooth** [comment]
Hi @manavluhar Thanks for these recent PRs. In the future, when making a series of small changes, please bundle them into a single PR. This will save us a good amount of processing time.

**Comment by manavluhar** [comment]
Okay @dobooth, Thank you!

**Comment by dshevtsov** [comment]
@shrielenee, @jeff-matthews please review.

**Review by keharper — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
