### PR TITLE
MAGEDOC-2641: Refresh HTML

### PR DESCRIPTION
**Pull request by jeff-matthews**
Purge orphaned HTML (i.e., HTML that lack corresponding source files) to eliminate navigation issues.

Test locally before merging.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
Can we delete the following files?

- Gemfile
- Gemfile.lock

We only needs these in the source repo to build the site. We should be excluding them from the generated output.

**Comment by jcalcaben** [comment]
Yes, we should delete/exclude these files in the gh-pages branch

**Comment by jcalcaben** [comment]
Are the images being deleted valid?

**Comment by jeff-matthews** [comment]
I'm not rally sure how to do that without closing this PR and opening a new one... Am I missing something obvious @jcalcaben?

**Comment by jcalcaben** [comment]
@jeff-matthews 
Download a zip of the current `gh-pages` branch and extract the images directory onto this branch to "restore" the images. 
If you want, I can do this.

**Comment by jeff-matthews** [comment]
Aha! Yes please!!! I'm swamped with Cloud v2.2.2 release docs at the moment and would appreciate the help.

**Pull request merged**
