### PR TITLE
MERGE IN 2.3.2: Fixed table structure with removing space and removed deprecated attribute.

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix table structure and removed deprecated attribute "canonical_url", added "relative_url".

## Additional information
Codebase:
https://github.com/magento/graphql-ce/blob/6cc68c64c91aee7bc1f4a66a3892b94843df78a6/app/code/Magento/UrlRewriteGraphQl/etc/schema.graphqls#L10

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
I'd like to get @keharper to take a look at this one as he recently merged in the following PR that reverts relative to canonical:
https://github.com/magento/devdocs/pull/3859

I do see the codebase change where the schema was updated, however I'm not seeing that in the latest 2.3.1-release branch.

**Comment by keharper** [comment]
GraphQL PR-https://github.com/magento/graphql-ce/pull/398 will be part of 2.3.2. We can't merge it into the `2.3.1-integration` branch. Putting this on hold until we have a `2.3.2-integration` branch.

**Comment by keharper** [comment]
Thanks, @mage2pratik  I think this is the first 2.3.2 PR.

**Pull request merged**
