### PR TITLE
Added new topic for create custom rest api

### LINKED ISSUE #9117: New topic for creating custom REST Api
# New topic request

## Description

In the rest tutorial documentation, there is no example to create a custom rest API

We can add a new topic under the rest tutorials with examples

### PR DESCRIPTION
**Pull request by nitish-ranjan05**
## Purpose of this pull request
Fixes #9117, #9161

## Description

- This page describes how you can create a custom REST API in Magento 2.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/create-custom-rest-api.html
-  https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/create-custom-rest-api.html

## What's new

whatsnew
Added the [Create a custom REST API](https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/create-custom-rest-api.html) topic.

### CODE REVIEW

**Review by keharper — CHANGES_REQUESTED** [review]

**Comment by nitish-ranjan05** [comment]
Hi @keharper, Thank you for the suggestions. I have updated the changes. Kindly review it.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper an error occurred during the Pull Request import.

**Comment by keharper** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@sidolov an error occurred during the Pull Request import.

**Comment by keharper** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper an error occurred during the Pull Request import.

**Comment by keharper** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper an error occurred during the Pull Request import.

**Comment by m2-github-services** [comment]
@keharper an error occurred during the Pull Request import.

**Comment by keharper** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper an error occurred during the Pull Request import.

**Comment by nitish-ranjan05** [comment]
@keharper Do you think I need to update my branch(new-topic-1) with the latest devdocs master branch?

**Comment by keharper** [comment]
@nitish-ranjan05 This PR hasn't been merged due to problems with our backend  automation. You don't need to do anything further with this PR. Thanks for checking in.

**Comment by keharper** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper an error occurred during the Pull Request import.

**Comment by nitish-ranjan05** [comment]
@keharper Thanks for the reply. I would like to make a small change in header. Can I?

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by dobooth** [comment]
@nitish-ranjan05 Sorry this has been such a hassle. We have solved this issue with other contributors by either: 1) updating the branch and syncing the PR, or 2) recreating the fork on your end. If you could try either of these, that would be helpful.

**Comment by nitish-ranjan05** [comment]
@dobooth Hi, I have updated my fork/branch. Thanks!

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-nitish-ranjan05-devdocs-9300`.

**Pull request merged**
