### PR TITLE
Update data-patches.md

### PR DESCRIPTION
**Pull request by sanjay-wagento**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix the file paths to schema patch interfaces.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/data-patches.html

### CODE REVIEW

**Comment by jeff-matthews** [comment]
Thanks for the contribution @sanjay-wagento, but please complete the template when opening PRs. We need this information to efficiently process PRs.

**Comment by sanjay-wagento** [comment]
@jeff-matthews , Can you please tell me which template I need to complete?

**Comment by jeff-matthews** [comment]
We've configured this repo to use a custom template for PR descriptions. When you create a PR, you need to update the text in the description. 

For example, select the PR type from the list of options:
-  New topic
- Content update
- Content fix or rewrite
- Bug fix or improvement

Provide a brief description of what this Pr accomplishes in the **Summary** section:

> When this pull request is merged, it will... <add text here>

Provide links to affected URLs:

> - https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/data-patches.html

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
