### PR TITLE
AC-689: Update Dev Docs

### PR DESCRIPTION
**Pull request by xmav**
- update tinyMCE version
- update links

## Purpose of this pull request

TinyMCE was upgrade in core. This PR contains changes to documentation to accommodate changes introduced in upgrade

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/wysiwyg/configure-tinymce-editor.html
https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-wysiwyg.html
https://devdocs.magento.com/guides/v2.4/mrg/ce/Cms.html
https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/wysiwyg/extension-points/

## Related PR:
https://github.com/magento-commerce/magento2-page-builder-docs/pull/1

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Great update.

Please correct the linting errors and sign the Adobe CLA

**Review by jeff-matthews — APPROVED** [review]
After running a diffcheck on the changed files, it's clear that the majority of changes simply replace "tinyMCE4" with "tinyMCE".

The most substantial change is in code samples in the `src/guides/v2.4/ui_comp_guide/components/wysiwyg/extension-points/index.md` file.

**Comment by jeff-matthews** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by lenaorobei** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@lenaorobei the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-9114`.

**Review by BarnyShergold — APPROVED** [review]

**Pull request merged**
