### PR TITLE
Update bk-install-guide.md

### PR DESCRIPTION
**Pull request by shivbhadrasinhgohil**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Improves a sentence Structure.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/install-gde/bk-install-guide.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@shivbhadrasinhgohil thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3862) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3862) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Thanks for the contribution, Shiv. While I will approve this small change, we usually ask that when editing a file, please try to give the entire file a pass. For instance, removing contractions and converting HTML tables to markdown. I will take care of those with another PR shortly.
Thanks again.

**Comment by dobooth** [comment]
running tests

**Comment by shivbhadrasinhgohil** [comment]
Thank you so much for approving the PR. This is my first one :)
Regarding
"please try to give the entire file a pass. For instance, removing contractions and converting HTML tables to markdown."

Can you please explain to me what do you mean by this? I am new to this so if you can elaborate that would be helpful for my future contribution.

**Pull request merged**
