### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) merges several `small-changes` PRs to `master`.

- #6227
- #6240
- #6249
- #6275
- #6276
- #6278
- #6286
- #6287
- #6288
- #6289
- #6290
- #6292

### CODE REVIEW

**Comment by dshevtsov** [comment]
This PR adds new sections to topics, which doesn't seem to align with small changes.

**Comment by jeff-matthews** [comment]
It's not an uncommon occurrence if you look at previous workflows. The main purpose is to save time testing. None of the PRs contain "what's new" metadata.

**Comment by dshevtsov** [comment]
Maybe we should start a discussion about changing the label (and procedure) name to reflect its real purpose then.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Sure, that sounds like a good idea for when we get back in 2020.

**Pull request merged**
