### PR TITLE
Fixed Typo and Formatted Code

### PR DESCRIPTION
**Pull request by vishal-7037**
## Purpose of this PR

Properly formatted the code.

## Affected URLs

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html

## Links to source code

- https://prnt.sc/nde7nz

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4276) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4276) before we can accept your contribution.<br/>**3** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: mage2pratik<br/>:white_check_mark: keharper<br/>:white_check_mark: jeff-matthews<br/>:x: AlexMaxHorkun<br/>:x: Vishal Sutariya<hr/>**Vishal Sutariya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @vishal-7037. Please, sign CLA. It's a required procedure for processing the proposed changes. Thank you

**Comment by vishal-7037** [comment]
Hi @rogyar,

Thanks for reply. I've already signed it and now again tried to sign it. But still, it will display "licence/cla Pending — Contributor License Agreement is not signed yet." :(

Thank you.

**Pull request closed without merging**
