### PR TITLE
REST API Tutorial on how to create a bundle product

### PR DESCRIPTION
**Pull request by goivvy**
## Purpose of this pull request

This pull request (PR) add a tutorial on how to add a bundle product using REST API.

Fixes https://github.com/magento/devdocs/issues/8968

whatsnew

Added a tutorial on [creating a bundled product](https://devdocs.magento.com/guides/v2.4/rest/tutorials/bundle-product/bundle-product-intro.html) with the API.

### CODE REVIEW

**Comment by keharper** [comment]
@goivvy That's for another large (and great) contribution. It'll take a few days to set aside the time to work through this tutorial. In the meantime, I want to verify that I'm reading the tutorial correctly. Is there a base cost for the computer, or only for the monitor and RAM? Also, I'd like to see different prices for the peripherals, since larger monitors/more RAM should generally cost more.

**Comment by goivvy** [comment]
@keharper There is no base price for the computer. Only for RAM and Monitor, we are assuming computer only consists of RAM and monitor for the simplicity. Should there be one? 
I'll make RAM/monitor price adjustments.

**Comment by goivvy** [comment]
@keharper "Also, I'd like to see different prices for the peripherals, since larger monitors/more RAM should generally cost more." - done.

**Comment by jhadobe** [comment]
@goivvy, I've made a few edits and formatting changes. please review.

**Comment by goivvy** [comment]
@jhadobe Seems OK, thank you!

**Comment by goivvy** [comment]
@jhadobe Do I need to approve them or do anything?

**Comment by jhadobe** [comment]
> @jhadobe Do I need to approve them or do anything?

No, I'll take it from here. Thanks for the contribution!

**Review by jhadobe — APPROVED** [review]

**Comment by jhadobe** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@jhadobe the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-goivvy-devdocs-9407`.

**Comment by dshevtsov** [comment]
@jhadobe, please add whatsnew.

**Pull request merged**
