### PR TITLE
Added Reset Password API in anonymous list

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will add a Reset Password API in anonymous list.

Webapi.xml File of Customer : https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/etc/webapi.xml

```
<route url="/V1/customers/resetPassword" method="POST">
        <service class="Magento\Customer\Api\AccountManagementInterface" method="resetPassword"/>
        <resources>
            <resource ref="anonymous"/>
        </resources>
    </route>
```

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/rest/anonymous-api-security.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
@keharper I made these changes in 2.1.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @ronak2ram for your contribution!

**Pull request merged**
