### PR TITLE
Update indexing.md

### PR DESCRIPTION
**Pull request by slopukhov**
Add application lock mode for reindex process

## Purpose of this pull request

This pull request (PR) will introduce a new mode to enable using application lock mode for reindex process

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@slopukhov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
I cannot comment on the PR - please can you check access and amend?

**Comment by slopukhov** [comment]
@BarnyShergold I do not have permission to edit and provide access to this repository. Please write to @mmansoor-magento  to resolve access issues.

**Comment by jeff-matthews** [comment]
This actually isn't a repo access issue. It's related to breaking a symlink and adding a new file.

**Comment by slopukhov** [comment]
@jeff-matthews Yes, I removed the symlink from 2.3 and moved the content to 2.4 with additional information since this functionality is relevant for 2.4 only. If I did something wrong, please tell me how to fix it.

**Comment by jeff-matthews** [comment]
@slopukhov , no, you didn't do anything wrong. This is a well known issue in our project and is related to GitHub. I'm trying to find a reference to other PRs, but basically inline commenting doesn't work.

@BarnyShergold, unfortunately, you must provide review feedback in regular comments.

**Comment by jeff-matthews** [comment]
Here's an example of another PR where the same issue occurred: https://github.com/magento/devdocs/pull/7272#pullrequestreview-417312619

**Comment by slopukhov** [comment]
@jeff-matthews Ok, thanks a lot.
@BarnyShergold To make it easier to understand, I want to clarify that I copied the content from 2.3 and added a new section "Using application lock mode for reindex process"

**Comment by dobooth** [comment]
It is usually because your fork is not editable by maintainers. You can enable it if you wish. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by slopukhov** [comment]
@dobooth I don't see such options on my side. Perhaps this is because that this is a command's fork and I do not have permission to do this.
@BarnyShergold Could you make a review in this PR or do I need to recreate it somehow?

**Review by BarnyShergold — COMMENTED** [review]
@dobooth @slopukhov - I can't even make normal comments. I get "Line must be part of the diff" - I can't see how I can do a meaningful review on this PR. Unfortunately my time is limited the next week or so. 

How am I supposed to leave comments? Would it simply be quicker if @slopukhov closed this PR, sorted out his for and then resubmitted? Otherwise won;t we keep running into this problem on other PRs?

**Comment by dobooth** [comment]
Yup, best thing to do is to just add the change directly here: https://github.com/magento/devdocs/blob/master/src/guides/v2.3/extension-dev-guide/indexing.md
and we will be able to edit it with no problem.

**Review by jeff-matthews — COMMENTED** [review]
> Yup, best thing to do is to just add the change directly here: https://github.com/magento/devdocs/blob/master/src/guides/v2.3/extension-dev-guide/indexing.md
> and we will be able to edit it with no problem.

That's not a good suggestion if the proposed change applies to 2.4.x only @dobooth. @slopukhov, is this for 2.4.x only.

this has nothing to do with forked repo permissions/settings. It's related to the symlink issue.

**Comment by dobooth** [comment]
Opps...correct, Jeff. And that file is symlinked to 2.3, so if this is 2.4.3 specific, that would have to be broken.

**Comment by slopukhov** [comment]
@jeff-matthews Yes, this new functionality is only for version 2.4.x (started from 2.4.3)

**Comment by dobooth** [comment]
Even the Comment button is being ornery on this PR...

**Comment by slopukhov** [comment]
Perhaps it helps, I just want to add the following node to the 2.4 documentation:


### Using application lock mode for reindex process

Starting from 2.4.3 its possible to enable using application lock mode for reindex process through the environment variables or in `app/etc/env.php`.

Example of configuration in `app/etc/env.php`

```php
<?php
return [
    'indexer' => [
        'use_application_lock' => true
    ]
];
```

Using this mode will allow to get the correct status of the indexer in case of a failure in the completion of its process.

Since this mode expands the functionality of checking the status, the current status can be obtained only through viewing the indexer grid in Magento Admin or when running the index status from the CLI.
When this option is used, the values in the SQL table `indexer_state` may indicate an irrelevant status value.

**Comment by dobooth** [comment]
Here are the edits for you. Please paste them in.

### Using application lock mode for reindex processes
Starting with 2.4.3, you can enable `use_application_lock` mode for reindexing through the use of environment variables, or in `app/etc/env.php`:
```php
<?php
return [
    'indexer' => [
        'use_application_lock' => true
    ]
];
```
In case of a failure, this mode will return the correct status of the indexer.
The current status can be obtained from the indexer grid in Magento Admin or through the index status in the CLI.
When this option is used, the values in the SQL table `indexer_state` may not be up to date.

**Comment by dobooth** [comment]
and update the base branch please. Let me know when you do.

**Comment by slopukhov** [comment]
@dobooth Thanks.
Done, please check it.

**Comment by dobooth** [comment]
I need the "This branch is out-of-date with the base branch" message to go away below. Once this is up-to-date, then I can merge it.

**Comment by dobooth** [comment]
running tests

**Comment by slopukhov** [comment]
@dobooth Done

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Good teamwork. Thanks!

**Comment by slopukhov** [comment]
Thanks a lot, everyone!

**Comment by hostep** [comment]
Hi @slopukhov!

I'm trying to figure out what this new application lock mode for reindexing actually means in practice.
For me, it's currently not very clear based on the description that got added.

For example:
- What is the benefit of using this mode?
- What exactly does `In case of a failure, this mode will return the correct status of the indexer.` mean?
- Does Adobe recommend to use this setting or not? Or maybe only in certain cases? Then in which cases?

Would be great if these questions can be answered and then maybe they can be added to the devdocs as well if these are proven valuable?

**Comment by hostep** [comment]
Based on the [code change](https://github.com/magento/magento2/commit/3fef6d1933e6f0eb21446304f5781aa65b0a72c9) associated with this new mode, I think I understand the following:
- This new mode can show a more accurate status of indexers
- Because without this mode, if an indexing job would get killed or crashed somehow, it might still show up as "working" even though nothing was actually happening. And because it's in "working", no new process will ever start up to pick it up again. And one would have to manually reset the indexer.
- But with this new mode, in this particular case the status will say "invalid" & "idle", which is a more accurate representation. But will Magento be able to recover then and trigger a full reindex based on this invalid status, or will it still need a manual action to truly reset the indexer?

Am I understanding this correctly or am I mistaken?

**Comment by slopukhov** [comment]
Hi @hostep 

Yes you are right.
In your case, with this option enabled, the cron run will automatically restart the reindex and you won't need to manually reset its status.

Best regards,
Stanislav

**Comment by hostep** [comment]
Awesome!

Do you think that adding some additional information about this new mode would be beneficial for the devdocs? I certainly would appreciate that this is a bit better explained since it sounds like an option many users will want to take advantage of.

Are there any downsides to this new mode? Any reason for having to manually enable this mode in 2.4.3? Or is the idea to have people trying this out first and based on feedback decide to make this a default in Magento 2.5.0 maybe?

**Comment by slopukhov** [comment]
Thank you.
Yes, it's a good idea to add some additional information into devdocs.
I will share with our product owner the idea of making this option the default.

**Comment by hostep** [comment]
Follow up PR created with the description updated a little bit: https://github.com/magento/devdocs/pull/9048, feel free to leave some feedback if it can be improved some more 🙂

**Comment by hostep** [comment]
Hmm, after playing around a bit with this new mode on a Magento staging shop which has indexer problems, I'm not sure anymore if this should become a default setting.

This particular shop has a problem with the partial reindexing of the `catalog_category_product` indexer for some reason, it takes a ridiculous amounts of memory and time to execute, and then runs against the `memory_limit` of PHP at a certain point.
With this new mode enabled, that partial reindexing starts again after it ran against the limit, and then runs against it again, every single time (which makes sense since it does exactle the same thing over and over). So it keeps the CPU & database very busy on this shop.
When the mode is disabled, it will stop after one attempt, but then the indexer will have backlogged items and is incorrectly marked as `working`.

So it's a bit of a balancing act, if you haven't got that new mode enabled, you need to manually check the indexer statuses every so often to make sure they are finishing correctly. With the new mode enabled, it will try to self-recover, but could potentially cause higher system resources to be used if it can't recover by trying over and over and over again.
But the higher system resources usage should then hopefully be noticed earlier by monitoring tools or noticing that a shop is slower than usually.

(In our particular case, resetting that one indexer fixes the problem, because a full reindex is able to run without issues, it's only the partial indexer that for some strange reason takes ridiculous amounts of resources to run, which is strange)

**Comment by kandy** [comment]
@hostep So, you actually confirm that this works correctly and indexers status with this setting works as expected

**Comment by hostep** [comment]
Hi @kandy 

Yes, the status of indexers are more accurate.
When not using this mode, and when an indexer has failed/crashed during its run, the status in the database will keep saying `working` and this is also shown in the cli output, but since the process is not running anymore, this is not accurate:

Screenshot 2021-07-23 at 08 08 39

When we use this new mode, it will now say `idle` when the process crashes and the cronjob will see this and try to run it again:

Screenshot 2021-07-23 at 08 09 51

---

Another thing, and this is not really the proper place for this discussion, but another nice improvement to the partial reindexing system I've been thinking of the last couple of days would be to mark a batch of of processed work as finished by updating the `version_id` in the `mview_state` after every single batch.
Right now that doesn't seem to happen.
Quick example: we have 149 backlogged items, the partial indexer [processes these](https://github.com/magento/magento2/blob/2.4.2/lib/internal/Magento/Framework/Mview/View.php#L283-L308) in batches of 1000 items by default, which we can override with something like this (which is not documented btw):
```xml
<type name="Magento\Framework\Mview\View">
    <arguments>
        <argument name="changelogBatchSize" xsi:type="array">
            <item name="catalog_category_product" xsi:type="number">50</item>
        </argument>
    </arguments>
</type>
```

What I would expect, but this doesn't seem to happen, is that if the first 50 batched items are processed, that the current version is written back to the `mview_state` table.
Because suppose that the second batch fails with a memory_limit error, then the next time the partial indexer tries to do his job, it will try to process those 50 items it already processed in the previous run which it should no longer do in my opinion.

Does this make sense as an extra improvement?

**Pull request merged**
