### PR TITLE
Update BIC reference

### PR DESCRIPTION
**Pull request by devops-devdocs**
Updated reference documentation on backward incompatible changes for 2.3.0-2.4.0 versions delta.

whatsnew
Updated [reference documentation](https://devdocs.magento.com/guides/v2.4/release-notes/backward-incompatible-changes/reference.html) covering backward incompatible changes for 2.3.0-2.4.0 versions delta.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
running test

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
