### PR TITLE
Add documentation for the ColumnsEditorRecord UI component

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds the documentation for the ColumnsEditorRecord UI component.

The following sections were added for this component: 
- `Configuration options` this section describes the options of the ColumnsEditorRecord component and their properties.
- `Sources files` - this section provides information about files that is related to the ColumnsEditorRecord component.
- `Examples` - this section provides examples of how to use this component.

## Affected DevDocs pages

The new page will be created with the URL:
-  https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-columns-editor-record.html

## Links to Magento source code

-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/grid/editing/record.js
-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/templates/grid/editing/row.html
-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/templates/grid/editing/field.html
-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/grid/editing/editor.js#L34-L42 

whatsnew
Added topic for [ColumnsEditorRecord](https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-columns-editor-record.html) UI component.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by serhiyzhovnir** [comment]
Hi @rogyar 
I've updated the description of this PR.
Could, you, please, check this PR again.
Thank you!

**Comment by dobooth** [comment]
That's what all Descriptions should look like! Lovely.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
