### PR TITLE
Adding code sample example for the use of collapsible widget

### PR DESCRIPTION
**Pull request by ParthBrahmbhatt**
## Purpose of this PR

This PR is an improvement of Collapsible widget, which provide an example of how the collapsible can be used and how the widget's options can be passed during initialization.

## Affected URLs

- v2.3 https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_collapsible.html
- v2.2 https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.html
- v2.1 https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.html

whatsnew
Added a code example section to [Collapsible Widget](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_collapsible.html).

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @ParthBrahmbhatt Thanks for the contribution. Looks like the heading is wrong. It's important to follow header order. I think your code sample should be ####.

**Comment by ParthBrahmbhatt** [comment]
Hi @dobooth 
I have updated the header format as per your suggetion.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
