### PR TITLE
Fix env.php code sample for message queue configuration

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request 

This pull request (PR) fixes an invalid `env.php` code sample for message queue configuration. 

See internal ticket MC-32147 for details. 

## Affected DevDocs pages 

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/message-queues.html#override-topic-configuration 

whatsnew
Fixed invalid `env.php` code sample for [message queue configuration](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/message-queues.html#override-topic-configuration).

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Review by dhorytskyi — COMMENTED** [review]
The provided code snippet is an example of final queue configuration.
Here is a part that relates only to switching from mysql to amqp for "product_action_attribute.update" queue:
```
'topics' => [
    'product_action_attribute.update' => [
        'publisher' => 'amqp-magento'
    ]
],
'config' => [
    'publishers' => [
        'product_action_attribute.update' => [
            'connections' => [
                'amqp' => [
                    'name' => 'amqp',
                    'exchange' => 'magento',
                    'disabled' => false
                ],
                'db' => [
                    'name' => 'db',
                    'disabled' => true
                ]
            ]
        ]
    ]
],
'consumers' => [
    'product_action_attribute.update' => [
        'connection' => 'amqp',
    ],
],
```

**Review by dhorytskyi — COMMENTED** [review]
This section is named "Override topic configuration", but contains information only about switching from mysql to amqp. As for now we don't have more information about overriding other parameters, I suggest renaming this section.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@dhorytskyi

**Review by dhorytskyi — CHANGES_REQUESTED** [review]
Please remove the old config sample (lines 55-78)

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
