### PR TITLE
Update mtf_installation.md

### PR DESCRIPTION
**Pull request by PathToLife**
Windows is not supported, php_openssl.dll is windows isn't it?

## This PR is a:

-  Content fix or rewrite

## Summary

When this pull request is merged, it will...

Adds a note about Win compatibility.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3613) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3613) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@PathToLife thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
