### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by dobooth**
- #5451 
- #5477 
- #5427 
- #5442 
- #5447

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5510) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5510) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: mrodespin<br/>:white_check_mark: drpayyne<br/>:white_check_mark: atwixfirster<br/>:white_check_mark: dobooth<br/>:white_check_mark: meker12<br/>:white_check_mark: mageprince<br/>:x: bradleyfrye

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
