### PR TITLE
MAGECLOUD-2956: Exception during build phase: Undefined class constant 'PARSE_CONSTANT'

### PR DESCRIPTION
**Pull request by oshmyheliuk**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will add warning message about package version compatibility.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/cloud/project/magento-env-yaml.html
- https://devdocs.magento.com/guides/v2.2/cloud/project/magento-env-yaml.html
- https://devdocs.magento.com/guides/v2.3/cloud/project/magento-env-yaml.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3446) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3446) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@oshmyheliuk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
running tests

**Comment by hguthrie** [comment]
@oshmyheliuk Looks like you need to sign the CLA. 😬

**Comment by oshmyheliuk** [comment]
@hguthrie Done, sorry that I missed that CLI was unsigned

**Comment by hguthrie** [comment]
running tests

**Comment by hguthrie** [comment]
OMG @oshmyheliuk A miracle happened. 😜 Merged!

**Pull request merged**
