### PR TITLE
Remove abandoned Baler module

### PR DESCRIPTION
**Pull request by Leland**
## Purpose of this pull request

Magento's "early Alpha" bundling solution `baler` has not been under development since the release of Magento v2.3.4, 7 months ago – I propose it be removed from the "Advanced JavaScript bundling" page masthead.

* Because of the staleness of the repository, [unresolved issues are cropping up](https://github.com/magento/baler/issues)
* Modern dependency versions [pose issues with the module](https://github.com/magento/baler/issues/62), and need to be manually downgraded and pinned
* The underlying M2 module [does not support PHP 7.4](https://github.com/magento/m2-baler/blob/c491c97b6f98567c7015290c6163d6e3f4a94a09/composer.json#L8), and is thus incompatible with Magento v2.4
* `baler`, in general, does not appear to have been tested whatsoever on modern Magento versions

I desperately hope development on `baler` is resuscitated. It's a fabulous tool, and better bundling _is_ needed on Magento. But recommending a stale, broken, unsupported, and undeveloped approach – even in an "alpha testing" way – does not seem wise!

Magento's "Magento Tech Tips," a resource that provides performance advice for Commerce Cloud clients, links out to this page. Clients should _not_ be seeing broken alpha software recommendations in the masthead. I've even had Commerce Cloud 
support reps recommend I test out `baler` to improve performance on clients. Another no-no.

Also see my issue on the `baler` repo proper: https://github.com/magento/baler/issues/70

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-js-bundling.html
- https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-js-bundling.html

## Links to Magento source code

- https://github.com/magento/baler
- https://github.com/magento/m2-baler

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by BarnyShergold — APPROVED** [review]

**Review by bdenham — APPROVED** [review]
Check!

**Comment by meker12** [comment]
running tests

**Comment by Leland** [comment]
Fastest Magento merge ever. Thanks y'all 💌

**Comment by davidalger** [comment]
It might be good to remove the 'baler' references in the Lighthouse stack-pack that was added for Magento: https://github.com/GoogleChrome/lighthouse/pull/9797/files#diff-308b7b792d1ff34f5f1059de97567b43R1535-R1540

I'm thinking a link to the page on Advanced JS Bundling, [MagePack](https://www.npmjs.com/package/magepack), or perhaps just a link to the former (with an update to link to MagePack as a simpler means of going about achieving the bundling?)

What do you all think?

**Comment by meker12** [comment]
@davidalger  That makes sense to me, but maybe better to ask the question in that repo. Adding @DrewML for his technical expertise.

**Comment by davidwindell** [comment]
Magepack is a great alternative for those looking.

**Comment by Leland** [comment]
@davidalger added an issue to the Lighthouse repo regarding that, if you want to add any thoughts about a replacement 🍻 https://github.com/GoogleChrome/lighthouse/issues/11954 

Have not had a chance to use Magepack, personally.

**Pull request merged**
