### PR TITLE
Adding troubleshooting guide and fixing CLI usage

### PR DESCRIPTION
**Pull request by ChristopheDujarric**
## This PR is a:
- [ ] New topic
- [x] Content fix or rewrite
- [ ] Bug fix or improvement
 
## Summary
 
When this pull request is merged, it will enable Cloud users to easier troubleshoot when Blackfire can't profile ("Are You Authorized to Profile this Page? Probe Not Found or Invalid signature." issue), and to use the Blackfire CLI commands properly.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2015) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2015) before we can accept your contribution.<br/><hr/>**ChristopheDujarric** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by ChristopheDujarric** [comment]
Sure, I just did :)

**Comment by hguthrie** [comment]
Thanks for your contribution! @ChristopheDujarric This is great information! I just have to make a few, minor grammatical fixes and then I will merge.

**Comment by hguthrie** [comment]
@ChristopheDujarric Please check the edits that I made in the PR #2163 . I wanted your command line examples to be easy for users to copy, so I made some formatting changes, in addition to grammatical changes.

**Comment by ChristopheDujarric** [comment]
LGTM!

Thanks @hguthrie !

**Comment by dshevtsov** [comment]
@hguthrie please add whatsnew

**Pull request merged**
