### PR TITLE
Remove blank line from metadata

### PR DESCRIPTION
**Pull request by meker12**
## Purpose of this pull request

Removed blank line from metadata that caused page to render incorrectly.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/security/security-txt.html

### CODE REVIEW

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
It builds and works locally. In my browser, it still says that the page was updated 36 hours ago, even though I refreshed. Am looking again.

**Comment by jeff-matthews** [comment]
Ah, yes. I think you're right about the deployment option. You should select the `all` parameter on the devdocs-production pipeline.

**Pull request merged**
