### PR TITLE
Added "Virtual product data types" topic to graphql

### PR DESCRIPTION
**Pull request by andrewbess**
## Purpose of this pull request

This pull request (PR) adds the new topic that describes VirtualProduct in GraphQL Developer Guide, and fixes some topics that use it.

## Affected DevDocs pages

-  [ProductInterface attributes v.2.3](https://devdocs.magento.com/guides/v2.3/graphql/interfaces/product-interface.html)
-  [ProductInterface attributes v.2.4](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/product-interface.html)
-  [Product interface implementations v.2.3](https://devdocs.magento.com/guides/v2.3/graphql/interfaces/product-interface-implementations.html)
-  [Product interface implementations v.2.4](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/product-interface-implementations.html)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @andrewbess. Thank you for your collaboration. 
We have separate pages that describe all types of products except simple product and virtual product since they don't have product-specific attributes and basically identical from the API endpoint perspective. 
Introducing a separate page with an example only for the virtual product might not be consistent and transparent. Maybe it makes sense to create a single page for both simple/virtual products. 

This page will be similar to the following one with the example and additional information

https://github.com/magento/devdocs/pull/7806/files#diff-e8bee8fd89f1d25a276a0117a4c4438a

@keharper we need your assistance here for the decision. 

Thank you!

**Comment by keharper** [comment]
@andrewbess @rogyar I need a few days to sort out my overall plans for the `interfaces` directory.

**Comment by keharper** [comment]
@andrewbess @rogyar  When I wrote the X product data types documentation, I deliberately did not include topics for simple and virtual products, because their implementations didn't add  any attributes to the `ProductInterface`.  Thus, there's no point in using a `...on SimpleProduct` or `...on VirtualProduct` fragment. But since I'm now expanding the interface docs, I'll add these topics. I'll process them after #7832 is merged.

**Comment by keharper** [comment]
@andrewbess I made the exact same modifications to this PR and #7805. Make sure they're accurate.

**Comment by andrewbess** [comment]
Hello @keharper 
I agree with the changes you made.
Thank you

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Pull request merged**
