### PR TITLE
[WIP] 3361 new configuration type

### PR DESCRIPTION
**Pull request by diazwatson**
## Purpose of this pull request

#3361 This pull request (PR) adds a new topic / section to explain how to use the classes described in Overview of module configuration files.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/config/config-files.html
- https://devdocs.magento.com/guides/v2.3/config-guide/config/config-create.html#config-files-extend-create-create

## Links to Magento source code

-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Sales/etc/pdf.xml
- https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/Config/Data.php
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Sales/Model/Order/Pdf/Config.php

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by diazwatson** [comment]
Hi @rogyar this PR should contain all the changes you recommended me t apply in a previous PR. Could you please have a look and let me know if so see something missing? Thanks

**Comment by diazwatson** [comment]
Thanks, I'll have a look

**Comment by atwixfirster** [comment]
@diazwatson , a correct file location - `src/guides/v2.3/config-guide/config/config-files.md`

Please pull the latest changes from `master` branch!

Thank you!

**Comment by diazwatson** [comment]
Thanks @atwixfirster I got confused because one of the initial recommendation was to add this changes to 2.2 and 2.3 and it was valid for both versions. I'll update this PR with the correct location today. 👍

**Comment by atwixfirster** [comment]
>I got confused because one of the initial recommendation was to add this changes to 2.2 and 2.3 and it was valid for both versions.

@diazwatson  please note, what we do not accept PRs with updates for 2.2 version. So, please add your updates for **2.3** only.

Thanks

**Comment by diazwatson** [comment]
Closing in favour of https://github.com/magento/devdocs/pull/6514

**Pull request closed without merging**
