### PR TITLE
Fix issue with escaping of JSON in context of html/attribute

### PR DESCRIPTION
**Pull request by kandy**
## Purpose of this pull request

This pull request (PR) fix improper example with escaping of JSON in context of html/attribute.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-security.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5065) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5065) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-engcom-team** [comment]
@kandy thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by jeff-matthews** [comment]
@kandy, please complete the PR template.

**Comment by kandy** [comment]
@jeff-matthews  done

**Comment by jeff-matthews** [comment]
Thanks @kandy!

**Pull request merged**
