### PR TITLE
[WIP] MCLOUD-6557: Re-invent Cloud Docker documentation

### PR DESCRIPTION
**Pull request by shiftedreality**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
@shiftedreality  I love where you are going with this PR. I am walking through Docker processes right now with some folks that are new to it. I would be happy to help with the review.

**Comment by hguthrie** [comment]
These are significant changes and I noticed some things marked TBD. I recommend this PR be converted to a **Draft** PR, because it is a work in progress that needs to align with docs architecture.

**Comment by hguthrie** [comment]
@meker12 @shiftedreality  There was a recent update to Docker content in #8216
Does this change the scope of this PR? This PR is getting old and we need to update it or **close** it. It references an Epic MCLOUD-6557, so it is fine to continue working with an integration branch.

Adding @bdenham for visibility.

**Comment by dobooth** [comment]
Closing until ready later on.

**Pull request closed without merging**
