### PR TITLE
magento/devdocs#: Remove unused include file

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) removes unused include file `_includes/migration/find-version.md` from repository in in favor of

- https://devdocs.magento.com/guides/v2.1/extension-dev-guide/versioning/check-version.html
- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/check-version.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/check-version.html

## Affected DevDocs pages

none

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
Hi @jeff-matthews 
This file `_includes/migration/find-version.md` do not used in devdocs code.
Actually, `migration` folder in only one file `find-version.md` and we are going to remove that so as per my suggestion we have to remove `migration` folder as well. what your suggestion?

**Comment by jeff-matthews** [comment]
@ronak2ram, yes, I confirmed that this include isn't used anywhere in devdocs. We should remove the `_includes/migration/` directory.

**Comment by atwixfirster** [comment]
> nfirmed that this include isn't used anywhere in devdocs. We should remove the `_includes/migration/` directory.

It will be automatically removed because it does not have any files.

Thank you!

**Comment by jeff-matthews** [comment]
@atwixfirster, that's not necessarily true. I guess it probably depends on how you deleted the file. I just checked out your branch and confirmed that the `_includes/migration/` directory was deleted. Thanks!

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
