### PR TITLE
updating terminology

### PR DESCRIPTION
**Pull request by misha-kotov**
Environment IDs were renamed to Data Space IDs

## Purpose of this pull request

This pull request (PR) updates the terminology used

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Comment by keharper** [comment]
@misha-kotov For future reference, internal doc PRs should be opened against this repo.
https://github.com/magento-commerce/devdocs/pulls

**Comment by misha-kotov** [comment]
@keharper I just used the "edit on github" link on the public page and it look me to the magento/devdocs repo. 
Might be a good idea to change that link

**Pull request merged**
