### PR TITLE
Add ProductImage object as per the code base repository

### PR DESCRIPTION
**Pull request by ParthBrahmbhatt**
## Purpose of this PR

This PR will merge, it will add the ProductImage object with parameter as per the magento v2.3 codebase repository

## Affected URLs

- v2.3 https://devdocs.magento.com/guides/v2.3/graphql/reference/products.html

## Links to source code

- v2.3 https://github.com/magento/magento2/blob/2.3/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L352

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
This is another table that I skipped in favor of in-line descriptions of the object. Please make the following changes:

* Change the heading to H3 (###)
* Add links from the ProductInterface to the new section
* Add any other undocumented objects directly related to ProductInterface (besides Enums) to this PR

**Comment by ParthBrahmbhatt** [comment]
Hi @keharper and @ronak2ram 
I have updated the heading label and also add link of Prodcutimage object into ProductInterface table.
Also I have cheked that all undocumented objects are covered from the ProductInterface table. 
Kindly review it from your end and let me know if you still have any suggetion.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @ParthBrahmbhatt

**Comment by ParthBrahmbhatt** [comment]
You're welcome @keharper . I think you forgot to add technical label on this PR.

**Pull request merged**
