### PR TITLE
Update customer.md

### PR DESCRIPTION
**Pull request by jmas**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@jmas thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Good fix but please can you fill in the PR description as described on the WIKI (or look at an approved PR) and sign the Adobe CLA (this is a one time thing)

Thanks!

**Comment by BarnyShergold** [comment]
@jmas - You still need to sign the CLA and it's been 8 days. If not signed in next 2 days, the PR will have to be closed.

**Comment by BarnyShergold** [comment]
Closing to due author not signing Adobe CLA after 2 weeks

**Pull request closed without merging**
