### PR TITLE
Fix an incorrcet filename

### PR DESCRIPTION
**Pull request by mega667**
Need to update `zip_code.xml` to `zip_codes.xml` in the 'Add custom ZIP code input masks' section

## Purpose of this pull request

To fix an incorrect filename on the page.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_zip.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@mega667 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Example from the codebase https://github.com/magento/magento2/blob/2.3/app/code/Magento/Directory/etc/zip_codes.xml

**Comment by dobooth** [comment]
running tests

**Pull request merged**
