### PR TITLE
Prefer exception expectations in body

### PR DESCRIPTION
**Pull request by Vinai**
## Purpose of this pull request

This pull request (PR) gives guidance on how to declare expected exceptions in tests in a forward compatible manner.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@atwixfirster based on @Vinai's comment, should we remove the annotations section?

**Comment by atwixfirster** [comment]
> @atwixfirster based on @Vinai's comment, should we remove the annotations section?

The purpose of my update was - display all of possible ways how developers can set exceptions for tests. 

@keharper , if you want I can add a `bs-callout` message with best practices advice - set exception in the test body.

What do you think?

Thank you!

**Comment by keharper** [comment]
@atwixfirster Yes, this text should be highlighted. Use `tip` instead of `info` 

I would also prefer to change "when Magento upgrades PHPUnit" to "when Magento requires that version of PHPUnit"

**Comment by atwixfirster** [comment]
> @atwixfirster Yes, this text should be highlighted. Use `tip` instead of `info`
> 
> I would also prefer to change "when Magento upgrades PHPUnit" to "when Magento requires that version of PHPUnit"

@keharper , I was unable to make a commit into Vinai's PR. So, I've created this one - https://github.com/Vinai/devdocs/pull/1

Could you please merge?

Thank you!

**Comment by keharper** [comment]
@atwixfirster I can't merge over there either. I'll update the file in this PR.

**Comment by Vinai** [comment]
I'm a little confused - is there anything to do to the PR or are you taking care of all things?

> `bs-callout`
What does "bs" stand for? :D

@keharper 
> I would also prefer to change "when Magento upgrades PHPUnit" to "when Magento requires that version of PHPUnit"

To be correct it would need to be "that version of PHPUnit or newer" I think...
What is wrong with "upgrades PHPUnit" ? Just curious, happy to learn.

**Comment by keharper** [comment]
@Vinai 

The `bs-callout...` is the Kramdown tagging that renders text as a note/warning/tip.

As to "upgrades PHPUnit", I know it's highly improbable that we start requiring PHPUnit 7 but it's technically possible.

**Comment by keharper** [comment]
Thanks @Vinai

**Pull request merged**
