### PR TITLE
Add Code Sample example for calendar widget

### PR DESCRIPTION
**Pull request by ParthBrahmbhatt**
## Purpose of this pull request

This PR is an improvement of Calendar widget, which provide an example of how the calendar can be used during initialization.

## Affected DevDocs pages

- v2.3 https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_calendar.html
- v2.2 https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_calendar.html

whatsnew
Added a 'Code sample' section to [Calendar Widget](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_calendar.html).

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ParthBrahmbhatt** [comment]
Hello @dobooth ,
Let me know if anything is missing into above PR from my end.

**Comment by dobooth** [comment]
Thanks @ParthBrahmbhatt. Since we stopped supported v2.1 a few day ago, we need to remove the v2.1 file and fix the merge conflict with v2.2 and we can get this in.

**Comment by ParthBrahmbhatt** [comment]
Hello @dobooth 
Thanks for the support and help for resolve this conflict.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
