### PR TITLE
Added Release Notes Links To Release Information

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request

This pull request (PR) addresses issue #9355 

Using an enhancement to the JSON file, the links to the Release notes can be added which will then display on the page.

A special value indicates if there are any release notes in the section so the table can be created with a third column

Currently only v2.4 has had links added. If the solution is approved, then I will add 2.3 & 2.2 release note links to the PR for approval 

## Affected DevDocs pages
https://devdocs.magento.com/release/released-versions.html

## Screenshot
https://capture.dropbox.com/pj2P8gznSBrsQdmo?src=ss

whatsnew
Added release notes data to `src/_data/core-releases.json` and [Released versions](https://devdocs.magento.com/release/released-versions.html).

### CODE REVIEW

**Comment by meker12** [comment]
Looks great @BarnyShergold. I'll wait until you add the 2.3 stuff before completing the PR processing.  Also, adding @jfrontain and @jeff-matthews  as reviewers for awareness.

**Review by meker12 — APPROVED** [review]

**Comment by dshevtsov** [comment]
@BarnyShergold I converted it to draft until it is discussed within the Community guild.

**Review by dshevtsov — COMMENTED** [review]
We have to consider that the target purpose of the JSON file is API for automation. The purpose of maintaining the devdocs topic is secondary by priority. Considering this we should avoid introducing any data that can cause breaking changes.
- `"release-notes" : true` -- I don't think we need this field. I cannot recall any precedent when release notes did not exist for a released version, especially on a minor level. Anyway, even if this precedent will appear it still can be resolved programmatically.
- `"commerceReleaseNotes"`, `"opensourceReleaseNotes"`, `"combinedReleaseNotes"` -- considering a long history of migrations and rebranding I suggest we use an object `releaseNotes` that contain absolute links such as:
   ```
   "releaseNotes": {"commerce": "https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html", "openSource": ...,  "whatever": ... }
   ```

**Comment by BarnyShergold** [comment]
@dshevtsov - Leave this with me

**Comment by BarnyShergold** [comment]
@dshevtsov @dobooth 
I think this achieves what was suggested? Where next?

**Review by dshevtsov — APPROVED** [review]
Looks good. Thank you, @BarnyShergold!

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dshevtsov the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-BarnyShergold-devdocs-9358`.

**Pull request merged**
