### PR TITLE
Fix JS bundling documentation

### LINKED ISSUE #2084: Feedback on page: /guides/v2.2/frontend-dev-guide/themes/js-bundling.html
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other
 

## Description:
Documentation is incorrect. Documentation states the following:
"To optimize bundling, set the following settings to Yes:
Javascript Settings -> Merge JavaScript Files"
This is untrue and will not optimize bundling. In fact, merging javascript files seems to override bundling. When js files are merged, no bundles are generated.
 

### Steps to reproduce
 
1. Turn on JS Bundling
2. Turn on JS Merging, JS Minification, and Sign Static Files per documentation
3. Put site into production
4. Deploy static content
5. Observe merged JS file and no JS bundles
 

## Expected result:
 Remove the line "Javascript Settings -> Merge JavaScript Files" from the documentation

## Possible solutions:
"To optimize bundling, set the following settings to Yes:

Javascript Settings -> Minify Javascript Files
Static Files Settings -> Sign Static Files"

### PR DESCRIPTION
**Pull request by bhargavmehta**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix documentation for JS Bundling

PR is a fix for /guides/v2.2/frontend-dev-guide/themes/js-bundling.html

## Additional information
Fixes #2084

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3020) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3020) before we can accept your contribution.<br/>

**Comment by meker12** [comment]
LGTM +1 OK to merge.

Thank you for your contribution

**Comment by meker12** [comment]
@bhargavmehta thanks for helping us improve the Magento DevDocs 👍

**Comment by dshevtsov** [comment]
@meker12 the PR is labeled as __Major update__, please add the corresponding _whatsnew_

**Pull request merged**
