### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by dobooth**
## This PR is a:
 Merging small_changes branch.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4153) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4153) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: abrarpathan19<br/>:white_check_mark: markshust<br/>:white_check_mark: ParthBrahmbhatt<br/>:white_check_mark: dobooth<br/>:white_check_mark: yogeshsuhagiya<br/>:x: ankitsrivastavacedcoss

**Comment by dshevtsov** [comment]
@dobooth consider changing the PR description to a more descriptive.
That this PR is a merge of PRs with editorial and technical changes only. The list of included PRs is the following:
- `#1245`
- `#1236`
- `...`

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
