### PR TITLE
magento/devdocs#4410: Broken link

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) fixes **Broken link #4410** [issue](https://github.com/magento/devdocs/issues/4410).

## Affected DevDocs pages

- https://devdocs.magento.com/extensions/install/
- https://devdocs.magento.com/guides/v2.1/comp-mgr/install-extensions.html
- https://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions.html
- https://devdocs.magento.com/guides/v2.3/comp-mgr/install-extensions.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @atwixfirster

**Comment by atwixfirster** [comment]
> Thanks @atwixfirster

with my pleasure @keharper  ;)

**Pull request merged**
