### PR TITLE
Introduce image lazy loading mechanism

### PR DESCRIPTION
**Pull request by adifucan**
## Purpose of this pull request

This pull request (PR) introduces image lazy loading mechanism

## Affected DevDocs pages

- src/guides/v2.4/frontend-dev-guide/themes/theme-images.md

## Links to Magento source code
Here is a PR with this functionality to 2.4-develop: https://github.com/magento/magento2ce/pull/5674

whatsnew
Added the 'Image lazy loading' section to the [Configure theme properties](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-images.html).

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dmytro-ch** [comment]
Hello @adifucan. 
Unfortunately, I didn't find the related PR in [magento/magento2](https://github.com/magento/magento2/) repository.
Could you please check the related PR's link in the description? It seems to be broken. Does this link work for you?

**Comment by dobooth** [comment]
The PR link is correct but it points to a private repo.

**Comment by adifucan** [comment]
Currently PR with this functionality is located in private [magento/magento2ce](https://github.com/magento/magento2ce) repo. Once it will be merged there, it will be available in public [magento/magento2](https://github.com/magento/magento2) repo after sync.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
