### PR TITLE
adds missing disabled="*" attribute to code sample

### PR DESCRIPTION
**Pull request by riconeitzel**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will improve code sample for plugin to show disabling

### CODE REVIEW

**Comment by osrecio** [comment]
Thabks @riconeitzel for your contribution!

I will check this PR in MLEU Contribution Day (8th Oct.)

**Comment by lorikrell** [comment]
Thanks for the contribution @riconeitzel and review @osrecio !

**Comment by osrecio** [comment]
And thanks @mhauri to review too 😄

**Comment by lorikrell** [comment]
Yes! Sorry I need more coffee. :) Thanks @mhauri !!

**Pull request merged**
