### PR TITLE
Updated the command in sample-data-rc1-cli-24.md file

### LINKED ISSUE #8275: Feedback on page: /guides/v2.4/comp-mgr/cli/cli-rc1-samp.html
# General issue

## Description:

In latest Magento 2.4, there should not be var/generation folder

## Possible solutions:

Update Text from "rm -rf var/cache/* var/page_cache/* var/generation/*" to "rm -rf var/cache/* var/page_cache/* generated/*"

### PR DESCRIPTION
**Pull request by chiranjeevi-cj**
## Purpose of this pull request

In the latest Magento 2.4, there should not be a var/generation folder. This pull request (PR) updates the command.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-rc1-samp.html

## Links to Magento source code

-  Fixes #8275 
Screenshot from 2020-12-01 12-41-11

### CODE REVIEW

**Review by Techytt — COMMENTED** [review]
Please review your code

**Comment by Techytt** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
Hello, Techytt anything needs to be changed?

**Comment by chiranjeevi-cj** [comment]
@erikmarr Can you please verify this PR?

**Review by jeff-matthews — APPROVED** [review]
Confirmed in my local install.

There are a lot more references throughout 2.4 devdocs. Some references are `generation/*` and some are `var/generation/*`.

https://devdocs.magento.com/guides/v2.4/search.html?query=var/generation

I'll create a new issue to clean up references globally since that's a wider scope.

**Comment by jeff-matthews** [comment]
See #8338

**Pull request merged**
