### PR TITLE
Update create-integration.md

### PR DESCRIPTION
**Pull request by shivbhadrasinhgohil**
grammatical mistake

## Purpose of this pull request

Fixes Grammatical Error(s), Sentence Structure Error(s).

This pull request (PR) ...

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/get-started/create-integration.html
- https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-oauth.html
- https://devdocs.magento.com/guides/v2.3/get-started/gs-web-api-request.html
- https://devdocs.magento.com/guides/v2.3/pattern-library/containers/staticContentContainer/contentContainer.html
- https://devdocs.magento.com/guides/v2.3/pattern-library/bk-pattern.html
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/bk-javascript-dev-guide.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shivbhadrasinhgohil** [comment]
#dmcdindia1

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @shivbhadrasinhgohil !

**Pull request merged**
