### PR TITLE
Correct usage of "Recovery Time Objective" term

### PR DESCRIPTION
**Pull request by erikhansen**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will... Update the page to use the proper term. See [Wikipedia for verification](https://en.wikipedia.org/wiki/Disaster_recovery#Recovery_time_objective).

## Additional information

Affects https://devdocs.magento.com/guides/v2.2/cloud/architecture/pro-architecture.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3769) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3769) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @erikhansen , Can you add this change in the same PR  for 2.1 #3770 To have only one PR.

Thanks for your contribution.

**Comment by erikhansen** [comment]
@osrecio Good call. I created the PR using Github's web interface, thus why it's two PRs. I just added the change from this PR to #3770, so closing this PR.

**Pull request closed without merging**
