### PR TITLE
Result section added for adding new layout document

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - This document has a content about creating new page layout. The result is missing here. So added the Result step with screenshot.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-create.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by chandru-199** [comment]
Hi @dobooth I have missed the .png file in previous commit. added now. Thank you.

**Comment by dobooth** [comment]
running tests

**Comment by chandru-199** [comment]
Hi @dobooth why this PR not having any labels?

**Comment by keharper** [comment]
Apologies, @chandru-199. Sometimes we forget.

**Comment by chandru-199** [comment]
Thanks @keharper

**Pull request merged**
