### PR TITLE
Update custom js content

### PR DESCRIPTION
**Pull request by mrtuvn**
## Purpose of this pull request

This pull request (PR) update content for this topic
This content is make misunderstand for use. We should update it to avoid confusing for reader/devs

Recall this issue https://github.com/magento/magento2/issues/24830

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/custom_js.html

## Related docs
https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/requirejs.html#requirejs-config-deps

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
I'm not sure what is this section about but the `deps` part of `requirejs-config` is being merged across all modules/themes. So, technically, we cannot override something in that way. Removing it might be a good idea but maybe there's something behind the scenes that the original author wanted to say. Still not sure.

**Comment by mrtuvn** [comment]
@dshevtsov @rafaelstz Can you guys give me some comments

**Comment by mrtuvn** [comment]
@guz-anton What do you think about this update

**Pull request merged**
