### PR TITLE
Update config-create.md

### PR DESCRIPTION
**Pull request by snowcore**
Added missing word "add"

## Purpose of this PR

This PR fixes sentence with missing word

## Affected URLs
 - https://devdocs.magento.com/guides/v2.0/config-guide/config/config-create.html
 - https://devdocs.magento.com/guides/v2.1/config-guide/config/config-create.html
 - https://devdocs.magento.com/guides/v2.2/config-guide/config/config-create.html
 - https://devdocs.magento.com/guides/v2.3/config-guide/config/config-create.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4382) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4382) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@snowcore thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @snowcore can you update the [PR Template](https://github.com/magento/devdocs/blob/master/.github/PULL_REQUEST_TEMPLATE.md) with all information required?

**Comment by dobooth** [comment]
@snowcore Please see if the 2.1 and 2.3 versions need this update as well.

**Comment by shrielenee** [comment]
Hey @snowcore --- I noticed that you made two very small changes in two separate PRs. In order to make it efficient for us to facilitate contributions, we require you to batch small changes into one PR. If we hadn't already merged your other PR I would close this and require you to add this change there.

Keep this in mind for your future contributions. Thanks!

**Comment by dobooth** [comment]
Fixed the other two versions.

**Pull request merged**
