### PR TITLE
Document multiple arguments for trans directive

### PR DESCRIPTION
**Pull request by wojtekn**
## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will document an ability to use multiple arguments for {{trans directive in email templates.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.0/frontend-dev-guide/templates/template-email.html
- https://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-email.html
- https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/templates/template-email.html
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-email.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by bdenham** [comment]
Hi @wojtekn, thanks for the examples. We no longer make any changes to version 2.0. Please update your PR to remove that version and use code fencing on the existing example:

{% raw %}
```
 {{trans "Dear %first_name %last_name," first_name=$first_name last_name=$last_name}}
```
{% endraw %}

**Comment by wojtekn** [comment]
@bdenham thanks for the review, I've just removed change made to 2.0 branch.

I'm not sure about the other part of the request, could you explain it more?

**Comment by bdenham** [comment]
Hey @wojtekn, take a look at the changes. I just added markdown code fencing to a few of the examples.

**Comment by wojtekn** [comment]
Thanks @bdenham !

**Comment by hguthrie** [comment]
running tests

**Pull request merged**
