### PR TITLE
Markdown linting: Fix MD010 (hard tabs) errors and enable rule

### LINKED ISSUE #5245: Markdown linting: Hard tabs (MD010)
# Bug report

## Description

The Markdown linter reports about 11725 issues when the [rule 'MD010'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md010---hard-tabs) is enabled.

### Steps to reproduce

1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD010'` to `rule 'MD010'`.
2. In your terminal, run `rake test:md`.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) fixes all MD010 (hard tabs) errors and enables the rule on production.

All the changes in this PR come from PRs that were reviewed, approved, and merged with the `db_hardtabs_integration` branch.

Fixes #5245

### CODE REVIEW

**Comment by jeff-matthews** [comment]
running tests

**Comment by dshevtsov** [comment]
when I search for regex `\t` in `.md` files, I see 75 results in 9 files.

**Comment by jeff-matthews** [comment]
Yeah, I'm not sure how that happened. I'm fixing them now. I also need to enable the rule.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
