### PR TITLE
magento/devdocs#: Editorial. ColorPicker component.

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) formats table content of "**ColorPicker component**" page regarding to [DevDocs Contributor](https://devdocs.magento.com/guides/v2.3/contributor-guide/templates/basic_template.html#tables).

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-colorpicker.html

## Links to Magento source code

- ...

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by diazwatson** [comment]
Guys, page is now broken :(
Screenshot 2019-07-11 at 01 19 48

**Comment by atwixfirster** [comment]
> Guys, page is now broken :(
> Screenshot 2019-07-11 at 01 19 48

Probably I've missed up with empty line after header. Added it in https://github.com/magento/devdocs/pull/4935.

I am sorry about this minor issue, @diazwatson

**Comment by jeff-matthews** [comment]
No problem @atwixfirster. These things happen. We're working on adding some markdown linting rules to our tests which should help prevent this in the future.

**Comment by diazwatson** [comment]
@atwixfirster as @jeff-matthews says there is no problem.

Looking forward to see the fix deployed to live :)

**Comment by atwixfirster** [comment]
> @atwixfirster as @jeff-matthews says there is no problem.
> 
> Looking forward to see the fix deployed to live :)

I am happy that you are do not angry, @diazwatson  ;)

Thanks

**Comment by diazwatson** [comment]
Naah not at all. 
You owe me a beer 🤣

**Pull request merged**
