### PR TITLE
Fixed link to web-api-access link

### PR DESCRIPTION
**Pull request by bbakalov**
## Purpose of this pull request

This pull request (PR) fixed typo in link creation

## Affected DevDocs pages

-  [https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication.html](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication.html)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@bbakalov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]
Nice fix

**Comment by bbakalov** [comment]
@BarnyShergold what should be done next?

**Comment by BarnyShergold** [comment]
> @BarnyShergold what should be done next?

We have to wait one of the Adobe Technical Writers to approve and merge the PR - can take a couple of days, depends on how busy they are.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
