### PR TITLE
Typo fix (minor)

### PR DESCRIPTION
**Pull request by medmek**
"a proxy has only one (not once) dependency"

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix a small typo in the sentence (one not once)

> a proxy has only **once** dependency

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.X/extension-dev-guide/proxies.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3517) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3517) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@medmek thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
