### PR TITLE
Added an MDB variable for Page Builder

### PR DESCRIPTION
**Pull request by bdenham**
## Purpose of this pull request

This pull request (PR) adds Page Builder as a new MDE variable.

### CODE REVIEW

**Comment by bdenham** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@bdenham the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8744`.

**Review by BarnyShergold — APPROVED** [review]

**Review by dobooth — APPROVED** [review]

**Comment by bdenham** [comment]
running test

**Comment by dobooth** [comment]
running tests

**Pull request merged**
