### PR TITLE
Fixed wrong notation for view_preprocessed directory.

### PR DESCRIPTION
**Pull request by sanganinamrata**
## This PR is a:
- [ ] New topic
- [ ] Content fix or rewrite
- [X] Bug fix or improvement
 

## Summary
Original PR: #2418 (Added missed files by this PR)

When this pull request is merged, it will make the correct notation for Magento's **view_preprocessed** directory.
 

## Additional information
N/A

### CODE REVIEW

**Comment by shrielenee** [comment]
Hey @sanganinamrata - I preliminarily approve these changes, but notice that now there are merge conflicts. Please resolve those and push back up for review.

**Comment by sanganinamrata** [comment]
@shrielenee , both above links gives **404 page**

- https://github.com/magento/devdocs/blob/develop/guides/v2.0/howdoi/troubleshoot/reset_theme.md
- https://github.com/magento/devdocs/blob/develop/guides/v2.1/howdoi/troubleshoot/reset_theme.md

**Comment by shrielenee** [comment]
Thank you for this contribution @sanganinamrata! I also converted links and images to markdown, so please take note of that for further contributions.

**Comment by sanganinamrata** [comment]
@shrielenee Sure!

**Pull request merged**
