### PR TITLE
Page redirect to same version page

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will redirect to same version page.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-issue-refund.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @ronak2ram

**Pull request merged**
