### PR TITLE
Removed duplicate datatype in example of date component

### PR DESCRIPTION
**Pull request by srsathish92**
## Purpose of this pull request

This pull request (PR) to remove duplicate datatype in example of date component.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-datecolumn.html.
- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-datecolumn.html.

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-srsathish92-devdocs-9294`.

**Comment by dobooth** [comment]
Hi @srsathish92 It looks like the block also needs a `dateFormat` line?

**Comment by srsathish92** [comment]
@dobooth I guess "dateFormat" is not required and it takes from default.

**Comment by keharper** [comment]
@srsathish92 I'm looking at the page on devdocs. The default dateFormat seems to agree with the example at the bottom. However, using the default value for timeZone for column 1 and a custom value for column 2 looks absolutely weird. Maybe that's OK. If you can confirm that the example is showing what's intended, I think we can merge this PR.

**Comment by srsathish92** [comment]
@keharper I can confirm that given example was intended correctly.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
