### PR TITLE
Add new custom layout update guide

### PR DESCRIPTION
**Pull request by AlexMaxHorkun**
Custom layout updates flow has been changed for 2.3.4 and 2.2.11, here's a guide reflecting those changes

## Purpose of this pull request

This pull request (PR) will guide front-end devs and merchants on the new flow of providing custom layout updates for cms pages, categories and products

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html
-  https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/xml-manage.html

## Related changes to Magento 2 codebase
-  https://github.com/magento/magento2ce/pull/4969 (v2.2.11)
-  https://github.com/magento/magento2ce/pull/4967 (v2.3.4)

whatsnew
Added the 'Create cms-page/product/category-specific layouts' section to [Common layout customization tasks](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html).

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by ccondra** [comment]
I had opened a user guide issue for this, and will link to the guide when it's available. https://github.com/magento/merchdocs/issues/314

**Pull request merged**
