### PR TITLE
Update info about system.xml's fields validation

### PR DESCRIPTION
**Pull request by Dren7755**
## Purpose of this pull request

This pull request adds correct information about how to separate validations entry for the <validate> node

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-systemxml.html
- https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-systemxml.html

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
This fix is also required on the 2.3 version of the document. Please add this to this PR

**Comment by Dren7755** [comment]
@BarnyShergold added for 2.3

**Review by BarnyShergold — APPROVED** [review]
Apologies for the delay

**Comment by m2-github-services** [comment]
@hguthrie the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-Dren7755-devdocs-9431`.

**Pull request merged**
