### PR TITLE
Updated Download Link of Upgrade Tool

### PR DESCRIPTION
**Pull request by rajmohanr12**
## Purpose of this pull request

This pull request (PR) is to Update the Download Link of Upgrade Compatibility Tool to the correct section in link

## Affected DevDocs pages

https://devdocs.magento.com/upgrade-compatibility-tool/install.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@rajmohanr12 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please fill in the PR description in full. Please refer to REPO WIKI & Other PRs

**Review by BarnyShergold — APPROVED** [review]
Thanks

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8896`.

**Pull request merged**
