### PR TITLE
Add the documentation for the ColumnsResize UI component

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds the documentation for the ColumnsResize UI component.

The following sections were added for this component:

-  `Configuration options` - this section describes the options of the ColumnsResize UI component and their properties.
-  `Sources files` - this section provides information about files that is related to the ColumnsResize UI component.
-  `Examples` - this section provides examples of how to use this component.

## Affected DevDocs pages

The new page will be created with the URL:

-  https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-columns-resize.html

## Links to Magento source code

-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/grid/resize.js
-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/grid/listing.js#L52-L57

whatsnew
Added topic for [ColumnsResize UI](https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-columns-resize.html)

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by serhiyzhovnir** [comment]
Thank you for the question.
I've added the additional information to the `tableSelector` and `mainTableSelector` options.
Additional code reference: https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/grid/resize.js#L92-L96
May I kindly ask you to check this PR again and let me know if something is unclear.

**Comment by rogyar** [comment]
Awesome, thank you!

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
