### PR TITLE
magento/magento2#: Remove duplicated page

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) removes [Module dependency types](https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend_types.html) as a page with duplicated content.

**Issue:** there are 2 pages [Module dependency types](https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend_types.html) and [Module dependencies](https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.html) which contain the identical content. 

I've compared them (left - Module dependency types, right - Module dependencies):

compare

Also, we do not have any references to [Module dependency types](https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend_types.html) page from the another pages and this page does not include to left menu unlike [Module dependencies](https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.html).

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend_types.html

## Links to Magento source code

- ...

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @atwixfirster. Thank you for this catch. Have you double-checked that the removed page does not have additional dependencies (links) from other pages?

**Comment by atwixfirster** [comment]
> Have you double-checked that the removed page does not have additional dependencies (links) from other pages?

yes, sir. I did that twice

**Comment by dobooth** [comment]
Thanks @atwixfirster. I think I merged those files and forgot to delete the old.

**Comment by dobooth** [comment]
running tests

**Comment by atwixfirster** [comment]
> Thanks @atwixfirster. I think I merged those files and forgot to delete the old.

Someone should fix your bugs, @dobooth ;)))

With my pleasure

**Pull request merged**
