### PR TITLE
Fix invalid command to install, improve formatting

### PR DESCRIPTION
**Pull request by diazwatson**
## Purpose of this pull request

This pull request (PR) fFix issue #6388

## Affected DevDocs pages

-  https://devdocs.magento.com/extensions/b2b/#configure-b2b

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
Praise be.

**Pull request merged**
