### PR TITLE
fixed redis page cache parameter names

### PR DESCRIPTION
**Pull request by sprankhub**
## Purpose of this pull request

This pull request (PR) fixes the parameter names when defining Redis as a backend for the page cache.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/redis/redis-pg-cache.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @sprankhub , can you link the code base changes in the params to take a look on it please

**Comment by sprankhub** [comment]
@osrecio please check the page under https://devdocs.magento.com/guides/v2.3/config-guide/redis/redis-pg-cache.html#configure-redis-page-caching. You see that the parameter is correctly mentioned in the introduction, but shown wrong in the table. My impression is that the table was copied from the above section about the default cache.

Anyway, the relevant code is [here](https://github.com/magento/magento2/blob/db9eaf13e2bf1c40339d7557e9ce0f578ca70feb/setup/src/Magento/Setup/Model/ConfigOptionsList/PageCache.php#L26-L32).

**Comment by lorikrell** [comment]
running tests

**Pull request merged**
