### PR TITLE
PB-480: Update content type styling concepts

### PR DESCRIPTION
**Pull request by bdenham**
Updated TOC entry for existing PB topic

## Purpose of this pull request

This pull request (PR) changes the TOC link to the updated Page Builder topic `How to configure styling options`. The previous link no longer described the topic adequately after the topic was updated and expanded in scope. 

## Affected DevDocs pages

https://devdocs.magento.com/page-builder/docs/how-to/how-to-use-attributes-for-styling.html

whatsnew
New Page Builder topic on how to configure three different options for styling elements in your content types: [How to configure styling options](https://devdocs.magento.com/page-builder/docs/how-to/how-to-configure-styling-options.html).

### CODE REVIEW

**Comment by bdenham** [comment]
running tests

**Comment by bdenham** [comment]
running tests

**Comment by dshevtsov** [comment]
@bdenham, a PR can have only one type of changes highlighted by a label. Here, it should be _Major update_ OR _Technical_, not both.

**Comment by dshevtsov** [comment]
@keharper when you approve a review, please take a look on labels and what's new as well, to make sure they correspond to our standards.

**Pull request merged**
