### PR TITLE
Providing a way of how data can be validated before importing it.

### PR DESCRIPTION
**Pull request by eduard13**
## Purpose of this pull request

This pull request (PR) provides a way of how a custom entity data can be validated before importing it.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/ext-best-practices/tutorials/custom-import-entity.html
- https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/custom-import-entity.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/AdvancedPricingImportExport/Model/Import/AdvancedPricing.php#L261-L287
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/AdvancedPricingImportExport/Model/Import/AdvancedPricing.php#L227-L229

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @eduard13. Thanks for the submissions. I was wondering, if you have not already, if you could optimize the image for this PR. We are trying to get images optimized before they are committed to help keep repo size down.
Thanks!

**Comment by eduard13** [comment]
Hi @dobooth actually the image is already optimized. Please let me know if we need to have a resized image here.
Thanks.

**Comment by dobooth** [comment]
Great! Seemed on the big side but thanks for the update.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
