### PR TITLE
Update ui-listing-grid.md

### PR DESCRIPTION
**Pull request by sanjay-wagento**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

In Magento 2.2.* ui-listing-grid defination change. So I modified example code of CMS page module.

## Additional information

List all affected URLs 
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-listing-grid.html

https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-listing-grid.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
@sanjay-wagento - Fill out the PR form each time, so that we may have all the info we need to review and merge issues. 🙇‍♀️

**Comment by sanjay-wagento** [comment]
@shrielenee , I updated PR form please review and let me know if you need more information

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
