### PR TITLE
Added MediaUploader widget documentation

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds the documentation for the MediaUploader widget.

## Affected DevDocs pages

This documentation will have the following links:

- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget-media-uploader.html
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget-media-uploader.html

_Page look:_
Media Uploader widget look

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Backend/view/adminhtml/web/js/media-uploader.js
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Backend/view/adminhtml/web/js/media-uploader.js
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Backend/view/adminhtml/templates/media/uploader.phtml#L14
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Backend/view/adminhtml/templates/media/uploader.phtml#L14

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by meker12** [comment]
@dobooth   Missing whatsnew text.

**Pull request merged**
