### PR TITLE
Add documentation for RedirectUrl widget

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds the RedirectUrl widget documentation.
The PR is an adjusted copy of https://github.com/magento/devdocs/pull/4715 PR.
I've created it on purpose to not to increase repo size too much.

## Affected DevDocs pages

These pages do not exist yet, but they will be created for the RedirectUrl widget documentation and the URLs should be like the following:

- https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_redirectUrl.html
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_redirectUrl.html
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_redirectUrl.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.1/lib/web/mage/redirect-url.js - redirectUrl widget source
- https://github.com/magento/magento2/blob/2.2/lib/web/mage/redirect-url.js - redirectUrl widget source
- https://github.com/magento/magento2/blob/2.3/lib/web/mage/redirect-url.js - redirectUrl widget source
- https://github.com/magento/magento2/blob/2.1/app/code/Magento/Catalog/view/frontend/templates/product/list/items.phtml#L221 - Example of usage
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/view/frontend/templates/product/list/items.phtml#L221 - Example of usage
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Catalog/view/frontend/templates/product/list/items.phtml#L220 - Example of usage

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
@serhiyzhovnir Thanks for redoing the PR!

**Comment by dobooth** [comment]
running tests

**Comment by jeff-matthews** [comment]
@dobooth, please add `whatsnew`.

**Pull request merged**
