### PR TITLE
all varnish 5 versions should be supported

### PR DESCRIPTION
**Pull request by jonashrem**
The varnish installation guide here https://devdocs.magento.com/guides/v2.2/config-guide/varnish/config-varnish-advanced.html explains how to install varnish 5.1 and there are no breaking changes with 5.1 https://varnish-cache.org/docs/5.2/whats-new/upgrading-5.1.html and 5.2 https://varnish-cache.org/docs/5.2/whats-new/upgrading-5.2.html#other-changes so I assume all Varnish 5.x Versions are fine (probably also 6.0)

## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

### CODE REVIEW

**Comment by magento-cicd2** [comment]
Can one of the admins verify this patch?

**Comment by jeff-matthews** [comment]
@buskamuza, will you please review this PR?

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
@jeff-matthews How we should proceed with this PR?

**Comment by jeff-matthews** [comment]
@buskamuza, please have an architect review this PR or we'll have no choice but to close it.

**Comment by hguthrie** [comment]
Looks like this was already addressed in another update #3319  . Closing this PR.

**Pull request closed without merging**
