### PR TITLE
Tango_MAGETWO-52625

### PR DESCRIPTION
**Pull request by adifucan**
MAGETWO-52625: Fail fast for layout XML errors

### CODE REVIEW

**Comment by tanberry** [comment]
Thank so much, @adifucan , for adding those debugging steps! We really appreciate your help in improving the tech docs. @almarchenko can you take a look and merge when ready? Thanks again!

**Comment by almarchenko** [comment]
Thanks! I will take a look and contact you if any questions!

**Comment by almarchenko** [comment]
According to @adifucan  the info should go to v.2.2, so closing this, and moving to 2.2 in the scope of https://jira.corp.magento.com/browse/MAGETWO-56424

**Comment by almarchenko** [comment]
Merged https://github.com/magento/devdocs_internal/pull/185

**Pull request closed without merging**
