### PR TITLE
Update cli-upgrade.md

### PR DESCRIPTION
**Pull request by ygyryn**
## Purpose of this pull request
This pull request (PR) will fix outdated version of Magento from (2.2.4 to 2.2.10)

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.2/comp-mgr/cli/cli-upgrade.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
Hey @ygyryn  --- The minor versions used in this CLI Upgrade page are meant as examples, and they communicate that with the sentence intros "For example,". I'm not sure we need to keep those updated, as they are used as examples.

**Comment by shrielenee** [comment]
Also, it appears you must sign our CLA @ygyryn.

**Comment by shrielenee** [comment]
Hey @ygyryn --- We will accept this PR. Can you please sign our new CLA again? Things recently changed, and perhaps you haven't signed it for this repo?

We can't merge your PR without it. Thanks! 🙇‍♀

**Comment by ygyryn** [comment]
Created ticket about Adobe CLA Signed problem
https://github.com/adobe/cla-bot/issues/104

**Pull request merged**
