### PR TITLE
Generated backward incompatible changes docs for 2.4-develop

### PR DESCRIPTION
**Pull request by devops-devdocs**
Generated doc updates for backward incompatible changes between 2.3.0 - 2.4.0-develop codebases

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
@dshevtsov should I expect the multiple "magento_login_as_customer_log" entries?

**Comment by dshevtsov** [comment]
@dobooth, I don't think so. Something is definitely wrong with the tool that produces this.

@pdohogne-magento there is a number of duplicates at the _Database changes_ tables generated by our automation plan _Publish BICs (devdocs 2.4)_. Will you have time to look into this? It would be great to fix this before GA.

**Comment by jeff-matthews** [comment]
@dshevtsov, can we just clean up this PR and merge it? We'll need to start publishing these docs next Monday (June 1).

**Comment by dshevtsov** [comment]
I am not sure if it make sense, because each next update would overwrite all the work. We can merge it as-is for beta publication, and clean it up prior GA.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
