### PR TITLE
Update "Manage company users" to describe current features

### PR DESCRIPTION
**Pull request by enderandpeter**
## Purpose of this pull request

This pull request (PR) removes language describing a feature that is currently not available. Due to a security issue being addressed, currently it is not possible to assign a user to a company upon creation with the REST API. Please see [MC-29084](https://jira.corp.magento.com/browse/MC-29084) for more details. The company can still be set with the "Modify a user" request. I am also including B2B developers @AlexMaxHorkun and @arnobsh in this conversation.

## Affected DevDocs pages

 * https://devdocs.magento.com/guides/v2.3/b2b/company-users.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by AlexMaxHorkun** [comment]
Looks good to me

**Comment by keharper** [comment]
@enderandpeter As of last Wednesday, there's a new top-level directory (`src/`) above `guides/`. Please pull in those changes and fix the merge conflict.

We also need a statement saying that you cannot use REST to assign a company when you create a customer. Also mention the workarounds of later modifying customer or creating the customer from the Admin.

**Comment by enderandpeter** [comment]
@keharper Alright, yes let me make that happen...

**Comment by enderandpeter** [comment]
Oh my... I apologize in that I thought that I had updated this branch with the latest master but clearly not, but I think I'm in true alignment now.

@keharper I made your requested changes which are all indeed very good ideas. You should check out my commit notes for more details but I tried to phrase things in a way that only talks about Magento's capabilities as opposed to what it lacks. I read in an anthropology book that it is best to take this approach when describing different cultures and I cannot help but to see this advice as equally useful here. But if you insist on any particular phrasing, I will of course comply.

@AlexMaxHorkun and/or @arnobsh I hope you would not mind taking another brief look. The code examples should be exactly the same unless I did something weird.

**Pull request merged**
