### PR TITLE
Update system-requirements-tech.md

### PR DESCRIPTION
**Pull request by PathToLife**
Warning for windows that was popular in the past.
It's a shame since evidence of windows support exists throughout the code, and in documentation.

## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

## Additional information

List all affected URLs 

- ...
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3614) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3614) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
@osrecio Do you know if this is accurate?

**Comment by jeff-matthews** [comment]
Since we don't support installing Magento on Windows, I don't think this appropriate in the docs.

**Comment by PathToLife** [comment]
This commit is made to help solve issues from my experience (as a new magento developer).

It's purpose is to help prevent new developers from installing using WAMP (which is still pretty common)

> There's quite a few guides online which teach you (wrongly) how to install magento 2 using WAMP.

I've wished I heard "we don't support installing Magento on Windows" on the first day.
There's plenty of information that might wrongly suggest windows support.
> search for '\\'
.dll is for windows

This commit ultimately is made to help new developers.
Short of putting in a check in setup for windows (which i think would be great)

@jeff-matthews We could change my it to be more accurate/appropriate.

**Comment by shrielenee** [comment]
Hey @PathToLife - I'm going to close this issue, as it addresses an edge case/unsupported procedure. If you feel a similar change is absolutely needed please open a new GitHub issue or PR so we may address it. Thank you for taking the time to submit a contribution PR to our docs!

**Pull request closed without merging**
