### PR TITLE
Update magento-bindings.md

### PR DESCRIPTION
**Pull request by gosteev**
Adjusting indentations and binding name

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will improve readability of devdocs

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/magento-bindings.html
- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiclass_concept.html
- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_uilayout_concept.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3647) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3647) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@gosteev thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
@gosteev - Please fill out the PR form so that we may have information to begin looking at your contribution. Thanks!

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
@gosteev Please sign the CLA so we can process this PR. Thanks!

**Comment by shrielenee** [comment]
running tests

**Pull request merged**
