### PR TITLE
Update docs for magento/graphql-ce#757

### PR DESCRIPTION
**Pull request by pmclain**
## Purpose of this pull request
This PR corresponds with changes proposed in magento/graphql-ce#757

This PR removes the `PaymentMethodAdditionalDataInput` and moves its children up
one level into the `PaymentMethodInput`.

## Affected DevDocs pages
- https://github.com/magento/devdocs/blob/develop/guides/v2.3/graphql/payment-methods/payflow-pro.md
- https://github.com/magento/devdocs/blob/develop/guides/v2.3/graphql/payment-methods/payflow-link.md
- https://github.com/magento/devdocs/blob/develop/guides/v2.3/graphql/reference/quote-payment-method.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
This PR is ready for merging, but I have to wait until magento/graphql-ce#757 has been merged into 2.3.3. 

We'll have to update this later, because the Magento core development team is continuing to support for more payment methods. I also need to create topics devoted to the PayPal Express methods. (I've created a topic for Authorize.Net since you submitted this PR, which will also require updating.)

**Comment by pmclain** [comment]
@keharper https://github.com/magento/graphql-ce/pull/757 merged. I'll address the conflicts this evening.

**Comment by osrecio** [comment]
I tested in my local environment and from technical point of view is valid this PR , thanks @pmclain you're working hard in GraphQL 👍

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @pmclain!

**Pull request merged**
