### PR TITLE
added multiple store constraint on exporting mysqldump for manually c…

### PR DESCRIPTION
**Pull request by kishorekumarkesavan**
## Purpose of this pull request 

This pull request (PR) added multiple store constraint on exporting tables through mysqldump for manually configuring multiple databases in the  magento instance

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/multi-master/multi-master_manual.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@kishorekumarkesavan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @kishorekumarkesavan Thanks for the PR. As of the new year, we are no longer taking submissions for v2.2. If you wish to, please port this fix (including my changes) to the v2.3 branch and we can merge it. This PR will be closed as out of date.

**Pull request closed without merging**
