### PR TITLE
theme /i18n location inaccurate

### PR DESCRIPTION
**Pull request by PromInc**
Per example in this page https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/translations/translate_practice.html the location of the theme /i18n directory and files was not accurate.

## Purpose of this pull request

This pull request (PR) improves the accuracy of the information provided.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/translations/xlate.html

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@PromInc thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dmytro-ch** [comment]
Hello @PromInc,
thank you for your contribution!

Please [sign the Adobe CLA](http://opensource.adobe.com/cla.html), otherwise, Magento Community Engineering team won't be able to process your pull request.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
