### PR TITLE
Update assign-source-to-stock.md template

### PR DESCRIPTION
**Pull request by ygyryn**
## Purpose of this pull request
This pull request (PR) adding corresponding links to previous steps in template

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/rest/tutorials/inventory/assign-source-to-stock.html

## Links to Magento source code
guides/v2.3/rest/tutorials/inventory/assign-source-to-stock.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
runnng tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @ygyryn

**Comment by ygyryn** [comment]
Thank you, @keharper

**Pull request merged**
