### PR TITLE
magento/devdocs#6774: Input UI Component Example incorrect

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) provides a fix for https://github.com/magento/devdocs/issues/6774.

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
You're a hero @atwixfirster! Thank you for demonstrating the power of the Magento Community.

**Comment by atwixfirster** [comment]
> You're a hero @atwixfirster! Thank you for demonstrating the power of the Magento Community.

With my pleasure , @jeff-matthews :)

Thank you 👍

**Comment by dobooth** [comment]
running tests

**Pull request merged**
