### PR TITLE
Added configuration update command in command summary

### PR DESCRIPTION
**Pull request by shikhamis11**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will add the available configuration commands in Command summary which was missing

## Additional information
reference page of configuration command - /config-guide/cli/config-cli-subcommands-config-mgmt-set.html
is only available from magento 2.2 version onwards  

List all affected URLs 

https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands.html
https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
Hi @shikhamis11 thank you for your contribution!

It looks like this topic was deleted then created resulting in the entire topic being new. In diffing the files locally, however, I see the following addition to the Command Summary table:

|[`magento config:{set/sensitive:set/show/}`]({{ page.baseurl }}/config-guide/cli/config-cli-subcommands-config-mgmt-set.html)|Manages backend configurations|

Can you confirm this is the only intended change for this PR?

**Comment by shikhamis11** [comment]
@erikmarr . yes I have just added this command in command summary table.
 |[magento config:{set/sensitive:set/show/}]({{ page.baseurl }}/config-guide/cli/config-cli-subcommands-config-mgmt-set.html)|Manages backend configurations| 

I had to create new file because earlier it was being used as symlink of previous version . But I can not add these in earlier versions because the referenced topic link is not available in previous versions . so It is only for version 2.2 and 2.3

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @shikhamis11 for your contribution!

**Pull request merged**
