### PR TITLE
Add information about Composer 2 compatibility

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) adds information about Composer 2 compatibility.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html
- https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

whatsnew
Added information about Composer 2 compatibility in [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and [upgrade scenarios](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html).

### CODE REVIEW

**Comment by dshevtsov** [comment]
Reported about the unexpectedly failing check in https://github.com/github/super-linter/issues/1123

**Review by dobooth — APPROVED** [review]

**Comment by jeff-matthews** [comment]
FYI - I think that the JS errors were resolved in #8371, so the next time we sync the `2.4.2-develop` branch with `master`, the checks should pass. While that will probably unblock this PR, it may make investigating the issue tricky.

**Comment by jeff-matthews** [comment]
running tests

**Comment by dshevtsov** [comment]
> While that will probably unblock this PR, it may make investigating the issue tricky
Both the commit and the failed check report are available, so it shouldn't be a big issue.

**Pull request merged**
