### PR TITLE
Correct commands for splitting databases

### PR DESCRIPTION
**Pull request by navarr**
## Purpose of this pull request

This pull request (PR) corrects what I believe is incorrect information on how to split the Magento database.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-setup.html
-  https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-setup.html

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
I concur - however the same changes need to be made to the 2.3 version of the page. Please can you do this on this PR and then it can be approved

**Review by BarnyShergold — APPROVED** [review]
You need to add the 2.3 page to the "Affected DevDocs pages" section but I'll approve on the premise that you'll add

**Review by meker12 — APPROVED** [review]

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Pull request merged**
