### PR TITLE
Fix theme inheritance layout files load order - Issue #2796

### PR DESCRIPTION
**Pull request by rodrigowebjump**
## Purpose of this pull request
Fix the topic Extend layouts load XML files order

https://github.com/magento/devdocs/issues/2796

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-inherit.html

whatsnew
Updated information for XML file order for [Theme inheritance](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-inherit.html).

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4499) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4499) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by lorikrell** [comment]
@rodrigowebjump thanks for your contribution! I will review the content, and continue with running tests, to merge. If I have requests for changes, I'll let you know. 👍

**Comment by lorikrell** [comment]
running tests

**Pull request merged**
