### PR TITLE
Error on installation in system with no files session storage

### PR DESCRIPTION
**Pull request by biotech**
All details on files, also issue created for discuss that https://github.com/magento/magento2/issues/1735 , but this is huge change which will take some time to resolve and issue could be common problem for users who configure session storage at redis or memcached

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
@biotech I'll wait until the Magento 2 GitHub issue is resolved before doing this.

**Comment by biotech** [comment]
@xcomSteveJohnson ok, but there is could be long discussion and way to patch, in same time this is common issue which can be blocking for lot of users - really hard to debug and understand the issue, not reported yet on SE or any other place. let's wait for some feedback from core team first - agree :)

**Comment by biotech** [comment]
@xcomSteveJohnson issue confirmed and ticket internal created, but until resolved solution can be helpful for users faced with that.

**Comment by xcomSteveJohnson** [comment]
Thanks, I will investigate. It will take some time, please be patient.

**Comment by xcomSteveJohnson** [comment]
MAGEDOC-2450 replaced by MAGETWO-42059

**Comment by biotech** [comment]
Great , nice to this is accepted. Thanks @xcomSteveJohnson

**Comment by xcomSteveJohnson** [comment]
Sure, thanks!

**Pull request merged**
