### PR TITLE
Update - Simple product add to cart mutation

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Updating add simple product to cart mutation request.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/mutations/add-simple-products.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @chandru-199  I accepted a PR with a minor change to that example, but I didn't test it. Thanks for your diligence.

**Comment by chandru-199** [comment]
Thanks @keharper. It seems no labels added for this PR.

**Pull request merged**
