### PR TITLE
Replaced two links

### PR DESCRIPTION
**Pull request by dbeezt**
Signed-off-by: dbeezt <dbrereton1995@gmail.com>

## This PR is a:

- [ ] New topic
- [ ] Content update
- [X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary
Replaced sample composer and sample language github links with links to internal documentation. Partial #3207. I'd like to do some more stuff for this issue but was unable to find additional information on constructing a glossary tooltip aside from the file located [here](https://github.com/magento/devdocs/blob/master/_plugins/glossary-tooltip.rb).

When this pull request is merged, it will...
- replace two inline links that linked to Github with links to relevant documentation located elsewhere on the magento website as part of an internalisation process.

## Additional information

List all affected URLs 
- https://github.com/magento/devdocs/blob/master/guides/v2.1/frontend-dev-guide/translations/xlate.md

The Url that this PR will modify 
- https://github.com/magento/devdocs/blob/master/guides/v2.1/frontend-dev-guide/translations/xlate.md

What other information can you provide about this PR?
- simply replaced two Github links with internal references located on the Magento website (.io)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3208) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3208) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@dbeezt thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by jeff-matthews** [comment]
Thanks @dbeezt. To add a glossary tooltip, you need to first locate a term in the [glossary](https://magento.github.io/glossary/). Click the **Show content author links** link at the top of the glossary website, locate the glossary term, click **Show Metadata**, and copy the UUID.

In the markdown file, wrap the glossary term in the `glossarytooltip` liquid tag + UUID. For example:

> {% glossarytooltip c1e4242b-1f1a-44c3-9d72-1d5b1435e142 %}module{% endglossarytooltip %}

If the term doesn't exist in the glossary, you  can click the **Send us feedback** link at the top of the glossary website to request that it be added.

**Comment by dbeezt** [comment]
Thanks for getting back so fast, I've submitted an issue for a new glossary tooltip [here](https://github.com/magento/glossary/issues/6).

**Comment by jeff-matthews** [comment]
@jcalcaben, please assist with adding the new glossary term (`phrase`) to https://github.com/magento/glossary.

**Comment by magento-cicd2** [comment]
Can one of the admins verify this patch?

**Comment by jeff-matthews** [comment]
@jcalcaben, please finish processing this PR and merge it.

**Comment by jcalcaben** [comment]
running tests

**Pull request merged**
