### PR TITLE
Make Cloud region reference generic in Cloud stack diagram

### PR DESCRIPTION
**Pull request by meker12**
## Purpose of this pull request

Replaced AWS specific reference in the [Cloud Production technology stack diagram](https://devdocs.magento.com/cloud/architecture/pro-architecture.html#production-technology-stack) with generic reference to "Cloud Region" since Magento now supports both AWS and Azure.

image

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/architecture/pro-architecture.html#production-technology-stack

### CODE REVIEW

**Comment by meker12** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by bdenham** [comment]
@meker12, need a whatsnew entry for the `Technical` label. Thanks.

**Comment by meker12** [comment]
So on the PRs with the Technical label, the whatsnew text is optional. In this case, the change in this PR doesn't need to be noted in the What's New topic.

**Comment by bdenham** [comment]
Got it.

**Pull request merged**
