### PR TITLE
Update shared-cat-product-assign.md

### PR DESCRIPTION
**Pull request by MikeSheward**
## Purpose of this pull request

- To update the documentation and keep it correct.
- Changing the title to the correct wording, for listing shared catalog products.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.2/b2b/shared-cat-product-assign.html
https://devdocs.magento.com/guides/v2.3/b2b/shared-cat-product-assign.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@MikeSheward, did you close this PR because you do not want to sign the Adobe CLA?

**Comment by MikeSheward** [comment]
I signed it, after the test failed. Upon signing however it instructed me to close the PR and open a new one. The new PR is merged

**Comment by jeff-matthews** [comment]
Oh interesting. I didn't know that the check advised contributors to close their PR. That doesn't seem like a good workflow.

**Comment by MikeSheward** [comment]
Nope it’s not a great workflow, luckily it was a smaller change so I didn’t mind. I can see how some would be put off by doing that as first contributors

**Pull request closed without merging**
