### PR TITLE
Update data type of latitude,longitude for the Inventory manage sources api

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will show correct data type of the latitude,longitude field of Inventory manage sources API.
Class File : https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryApi/Api/Data/SourceInterface.php#L131

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/rest/modules/inventory/manage-sources.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@keharper, since numbers in general can be either an "integer" or "float", should we specify that—within this context of latitude/longitude—a number must be of type float? Curious what you think based on your experience with our REST documentation as a whole.

**Comment by keharper** [comment]
Here's a screenshot of Swagger:

screen shot 2019-02-21 at 9 06 06 am

We need to investigate whether Swagger displays all float values as "number"

**Comment by keharper** [comment]
Per discussion with @ronak2ram, the true issue is that the OpenAPI schema Magento produces doesn't go far enough in labeling Float attributes as such. It merely labels them as Number attributes.

Until we can get this fixed in the code, I'd like for all instances of the "Number" data type in the REST be replaced with "Float".  I know there are instances in B2B negotiable quotes and company credit topics.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Pull request merged**
