### PR TITLE
Fix wrong entity in headline

### PR DESCRIPTION
**Pull request by cmuench**
## Purpose of this pull request

This pull request (PR) fixes a wrong entity in a headline.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/b2b/shared-cat-product-assign.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Good spot!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-9039`.

**Pull request merged**
