### PR TITLE
Remove unnecessary dots

### PR DESCRIPTION
**Pull request by ahmedch1**
The dots removed are copied with the code and they are unnecessary

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@ahmedch1 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ahmedch1** [comment]
> Hello @ahmedch1,
> thank you for your contribution!
> 
> Please [sign the Adobe CLA](http://opensource.adobe.com/cla.html), otherwise, Magento Community Engineering team won't be able to process your pull request.

Thanks for information ! Done

**Comment by dobooth** [comment]
running tests

**Pull request merged**
