### PR TITLE
Add missing parameter into technical document

### PR DESCRIPTION
**Pull request by ParthBrahmbhatt**
## Purpose of this PR

This PR will merge, it will add the missing parameter into technical document as per the magento version v2.2 and v2.3 codebase repository.

## Affected URLs

- v2.3 https://devdocs.magento.com/guides/v2.3/payments-integrations/payment-gateway/request-builder.html
- v2.2 https://devdocs.magento.com/guides/v2.2/payments-integrations/payment-gateway/request-builder.html

## Links to source code

- v2.3 https://github.com/magento/magento2/blob/2.2/app/code/Magento/Braintree/etc/di.xml#L236
- v2.2 https://github.com/magento/magento2/blob/2.2/app/code/Magento/Braintree/etc/di.xml#L236

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Please see #4250

**Comment by ParthBrahmbhatt** [comment]
Hi @dobooth , I have checked both the PR and check below explanation for individual PR.

[#4250](https://github.com/magento/devdocs/pull/4250/files) : This PR has also updated the braintree parameter but the devdocs technical page link is different. Please compare the Affected URLs and do the needful.

[#4263](https://github.com/magento/devdocs/pull/4263/files) : This is PR is also mine but when I checked the magento v2.2 and v2.3 codebase repository,I found that one more parameter has added for v2.2 and v2.3. So I have to create separate page for devdocs technical version for 2.2 and 2.3.

**Comment by rogyar** [comment]
According to the code base the provided change is correct

**Comment by dobooth** [comment]
Thanks for confirming.

**Comment by dobooth** [comment]
running tests

**Comment by ParthBrahmbhatt** [comment]
You're welcome @rogyar  and @dobooth.

**Pull request merged**
