### PR TITLE
Adding parameters to request

### PR DESCRIPTION
**Pull request by magesanjay**
## This PR is a:

- Adding payment gateway request parameters in BraintreeAuthorizeRequest.

## Summary

When this pull request is merged, it will add the missing payment gateway request builder parameters.

Codebase Urls: 
- https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Braintree/etc/di.xml
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Braintree/etc/di.xml

## Additional information

List all affected URLs 

1. https://devdocs.magento.com/guides/v2.2/payments-integrations/payment-gateway/request-builder.html
2. https://devdocs.magento.com/guides/v2.3/payments-integrations/payment-gateway/request-builder.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
Hi @magesanjay ,
Can you please update PR description.
It would be good if you provide a codebase link.
Thanks

**Comment by magesanjay** [comment]
Hi Ronak,

I have updated PR description and codebase link.
Thanks

**Comment by dobooth** [comment]
Need to verify the new content.

**Comment by magesanjay** [comment]
Hello @eriksmarr 
I suggest removing that paragraph.

**Comment by erikmarr** [comment]
> Hello @eriksmarr
> I suggest removing that paragraph.

Ok, can you update your PR so this paragraph is removed? Thanks!

**Comment by magesanjay** [comment]
Hello @erikmarr 
**Ok, can you update your PR so this paragraph is removed? Thanks!**
- Yes

I have removed that paragraph and PR is updated.
Thanks!

**Comment by magesanjay** [comment]
> > Hello @eriksmarr
> > I suggest removing that paragraph.
> 
> Ok, can you update your PR so this paragraph is removed? Thanks!

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @magesanjay!

**Pull request merged**
