### PR TITLE
update to new blackfire:setup workflow

### PR DESCRIPTION
**Pull request by simensen**
## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will update the Blackfire integration documentation for the Cloud Guide to reference the new `blackfire:setup` command.

## Additional information

List all affected URLs 

- /guides/v2.1/cloud/project/project-integrate-blackfire.html
- /guides/v2.2/cloud/project/project-integrate-blackfire.html
- /guides/v2.3/cloud/project/project-integrate-blackfire.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@simensen thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3484) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3484) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
running tests

**Pull request merged**
