### PR TITLE
Added remaining Inventory Sales Api 

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

Added remaining Inventory Sales API's.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/rest/list.html#inventorysalesapi

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @ronak2ram can you add affected list of url's? , please.

Check it out our [PR Template](https://github.com/magento/devdocs/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by ronak2ram** [comment]
@osrecio I updated PR description.

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
