### PR TITLE
Fix wrong XPath to `media_gallery_image_folders`

### PR DESCRIPTION
**Pull request by flancer64**
My Magento version is 2.4.3-p1.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Good spot, but please fill out the PR descriptions as detailed in the repo WIKI.

**Comment by dobooth** [comment]
@BarnyShergold is this technically a good fix?

**Comment by BarnyShergold** [comment]
> @BarnyShergold is this technically a good fix?

@dobooth yes it is. The config.xml has this fragment -
```
       <system>
            <media_storage_configuration>
                <allowed_resources>
                    <media_gallery_image_folders>
                        <wysiwyg_image_folder>wysiwyg</wysiwyg_image_folder>
                    </media_gallery_image_folders>
                    <preview_folder>.thumbs</preview_folder>
                </allowed_resources>
            </media_storage_configuration>
        </system>
```

**Comment by BarnyShergold** [comment]
@flancer64 - We are waiting for you to update this PR. It's been 3 weeks and no news - please can you update

**Comment by flancer64** [comment]
Sorry guys, I just read the docs and found an error. I've pointed for the error. That's all. If it so complicated to fix this error just close this PR and forget about it.

**Pull request closed without merging**
