### PR TITLE
Adding parameters to Brainetree Vault request builder

### PR DESCRIPTION
**Pull request by magesanjay**
## Scope of this PR

- __Technical__: Adding parameters to Braintree Vault request builder

## Purpose of this PR

When this pull request is merged, it will add the missing parameters (3dsecure, device_data, store, merchant_account) to Braintree Vault request builder which is already available into codebase.

## Affected URLs

- https://devdocs.magento.com/guides/v2.1/payments-integrations/vault/admin-integration.html#specific-vault-configuration-for-admin
- https://devdocs.magento.com/guides/v2.2/payments-integrations/vault/admin-integration.html#specific-vault-configuration-for-admin
- https://devdocs.magento.com/guides/v2.3/payments-integrations/vault/admin-integration.html#specific-vault-configuration-for-admin

## Links to source code

Codebase Urls:

- https://github.com/magento/magento2/blob/2.1/app/code/Magento/Braintree/etc/di.xml#L257
- https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Braintree/etc/di.xml#L284
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Braintree/etc/di.xml#L284

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
Hi @magesanjay 
I think we need to update the same change in doc v2.1.
Please refer doc file v2.1 file:

https://github.com/magento/devdocs/blob/master/guides/v2.1/payments-integrations/vault/admin-integration.md 

v2.1 code base file: https://github.com/magento/magento2/blob/2.1/app/code/Magento/Braintree/etc/di.xml#L257

And I compare this PR v2.2 and v2.3 file and both are same so can you please revert v2.3 file.

**Comment by ronak2ram** [comment]
@magesanjay Thanks for the update,
Now, PR looks good.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
