### PR TITLE
Deprecated fields removed from graphql query

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

This pull request (PR) - Lot of deprecated fields are used in graphql query. all deprecated fields are removed from query in this PR.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/product/downloadable-product.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Related schema items from the codebase:

- https://github.com/magento/magento2/blob/388f2e95d36ddae1ecb2a6c2730672e55c859720/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L108
- https://github.com/magento/magento2/blob/388f2e95d36ddae1ecb2a6c2730672e55c859720/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L103
- https://github.com/magento/magento2/blob/8ad0f2ec2d477dd5b5bc267502b17998aac533a4/app/code/Magento/DownloadableGraphQl/etc/schema.graphqls#L55

**Comment by keharper** [comment]
I applied my previous comment to the wrong PR.

**Comment by keharper** [comment]
running tests

**Pull request merged**
