### PR TITLE
Klarna payment method overview and GraphQL mutation

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) adds a new preview page for Klarna's payment method and a new reference page for Klarna's `createKlarnaPaymentsSession` GraphQL mutation for 2.4.1.

Content was submitted by Klarna. I requested more information from Klarna about the input and output attributes. I'm still waiting for a response. There are placeholder sections in the mutation reference topic for now.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/graphql/payment-methods/klarna.html
- https://devdocs.magento.com/guides/v2.4/graphql/mutations/create-klarna-payments-session.html

whatsnew
Added a new overview page for [Klarna's payment method](https://devdocs.magento.com/guides/v2.4/graphql/payment-methods/klarna.html) and a new reference page for Klarna's [`createKlarnaPaymentsSession`](https://devdocs.magento.com/guides/v2.4/graphql/mutations/create-klarna-payments-session.html) GraphQL mutation.

### CODE REVIEW

**Review by keharper — CHANGES_REQUESTED** [review]
Another round will be necessary. This'll get you started.

**Review by keharper — COMMENTED** [review]
The text in the graphics could use a little attention. 

The first one:

5. Get all available payment methods
6. Ask Klarna for updates
7. Klarna returns the latest status
8. Magento returns the updated info
9. PWA renders the Klarna Payments widget
10. PWA sends authorize() directly to Klarna

I'll wait on the second one, because I have questions about the sequence.

**Comment by keharper** [comment]
I have questions about the diagram under "How to handle cart updates".

Step 2 states that Magento returns an updated cart object in response to running `createKlarnaPaymentsSession".  The mutation might update the cart object, but that information is not available in the mutation's response. Is there really a step 2? Or are other things going on that aren't described?

**Comment by samoko85** [comment]
> I have questions about the diagram under "How to handle cart updates".
> 
> Step 2 states that Magento returns an updated cart object in response to running `createKlarnaPaymentsSession". The mutation might update the cart object, but that information is not available in the mutation's response. Is there really a step 2? Or are other things going on that aren't described?

Hello, I reviewed that section and it was actually wrong. In particular the diagram was stating to use createKlarnaPaymentsSession mutation while that first call could be any kind of cart update.

I will provided an updated description.

Thanks for spotting!

**Comment by keharper** [comment]
@jeff-matthews I've updated the "update cart" sequence in the `klarna.md` document. I think all that's left to do is update the diagram.

**Comment by jeff-matthews** [comment]
Thanks @keharper! I'll update the diagram.

**Review by keharper — APPROVED** [review]

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
