### PR TITLE
Update config-cli-subcommands-index.md with Catalog Permissions Indexer changes

### PR DESCRIPTION
**Pull request by aakashk994**
## Purpose of this pull request

This pull request (PR) updates config-cli-subcommands-index.md with Catalog Permissions Indexer changes for 2.4.5.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-index.html

## Links to Magento source code

-  https://github.com/magento-commerce/magento2ee/pull/3261

### CODE REVIEW

**Comment by dobooth** [comment]
Hi @aakashk994 Thanks for the contribution, one of the first for 2.4.5. A couple of small things: Please sign the Adobe CLA below, and if you could add a link in the description of where in the codebase this is from, that would be helpful.

**Review by BarnyShergold — APPROVED** [review]

**Comment by dobooth** [comment]
Ah, it's your code PR. Good work updating the docs! Really appreciate that, @aakashk994.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Comment by dobooth** [comment]
Merged

**Comment by aakashk994** [comment]
@dobooth thank you!

**Pull request closed without merging**
