### PR TITLE
Update _extend.less should be under source folder

### PR DESCRIPTION
**Pull request by mehmetuygun**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@mehmetuygun thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Also, you need to sign Adobe CLA for further PR processing. 

Thank you

**Comment by dobooth** [comment]
Closing as lack of CLA.

**Pull request closed without merging**
