### PR TITLE
If merge js is enabled bundling don't work

### PR DESCRIPTION
**Pull request by mrodespin**
I want to add a specification for tell to developers that if merge configuration is enable at the same time than bundling, bundling does not work.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/js-bundling.html
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/js-bundling.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/View/Asset/MergeService.php#L86-L112
- https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/View/Asset/MergeService.php#L86-L109

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4888) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4888) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@mrodespin thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
I approved technical part of the PR. Maybe the syntax should be checked

**Pull request merged**
