### PR TITLE
Add release notes for MQP 1.0.11 release

### PR DESCRIPTION
**Pull request by viktym**
## Purpose of this pull request
- Add release notes for MQP 1.0.11 release

## Affected DevDocs pages
- Page https://devdocs.magento.com/quality-patches/release-notes.html

whatsnew
Published [release notes](https://devdocs.magento.com/quality-patches/release-notes.html) for the 1.0.10 Magento Quality Patch (MQP) package release.

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
@viktym, unless specified otherwise in the PR description, all MQP release notes PRs will be merged right away. So if you ever need to time release notes publication with the actual MQP package release, please mention it in the PR description.

**Comment by jeff-matthews** [comment]
@viktym, please sign the Adobe CLA so I can merge this PR.

**Comment by viktym** [comment]
@jeff-matthews  I did it, can you restart the build?

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Thanks @viktym. The release notes will be published on devdocs in ~8 minutes.

**Pull request merged**
