### PR TITLE
Update adding-attributes.md

### PR DESCRIPTION
**Pull request by Vinai**
## Purpose of this pull request

Fix name of method to plug into and clarify return type notation.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.html
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@Vinai  Try adding a blank line before the beginning of the code block.

**Comment by Vinai** [comment]
Is there a way to restart the Jenkins build? It's been 4 days now... guess it's stalled?

**Comment by jeff-matthews** [comment]
@Vinai, to rerun tests, you can just push new commits. We have a GitHub Action that runs the linting tests. It doesn't look like Jenkins has been run yet. That's a manual process that requires an admin to use a trigger phrase in the comments. Jenkins will test for broken links.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
