### PR TITLE
Default break-point file path added on RWD topic

### PR DESCRIPTION
**Pull request by rajesh-mage**
## Purpose of this pull request

This pull request (PR) Default break-point file path added on RWD topic

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/responsive-web-design/rwd_css.html

## Links to Magento source code

https://github.com/magento/magento2/blob/2.4-develop/lib/web/css/source/lib/variables/_responsive.less

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Review by ajithkumar-maragathavel — APPROVED** [review]
Good one!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8917`.

**Comment by atwixfirster** [comment]
Sorry for being late on this party, but in `line 31` we have a sentence with `:` at the end and without any logical conclusion :



Per my understanding a content should be:

```
 The default breakpoint variables are located in the Magento UI library: `lib/web/css/source/lib/variables/_responsive.less`.

The Blank and Luma themes use Less variables to implement the following [breakpoints][breakpoints-link]:

-  `@screen__xxs`: 320px
-  `@screen__xs`: 480px
-  `@screen__s`: 640px
```

Thanks

CC: @BarnyShergold @dobooth

**Comment by rajesh-mage** [comment]
Hi @atwixfirster,
Thanks for your review and suggestion. The mentioned changes are done. 

Thanks.

CC: @BarnyShergold @dobooth

**Review by ajith107 — APPROVED** [review]
@atwixfirster Thanks for the suggestions. Hope now it's fine for you.

**Review by ajithkumar-maragathavel — APPROVED** [review]
Thanks for the update.

**Comment by atwixfirster** [comment]
> @atwixfirster Thanks for the suggestions. Hope now it's fine for you.

@ajith107 , looks ok to me.

Thank you!

**Comment by dobooth** [comment]
@rajesh-mage Looks like changes were made after I imported the code. Once I @magento import the code, I assume the PR is complete and approved and I will likely not check for updates here. So now this PR is in a strange state and I will have to close it. Please check the current state of the doc and if it needs further refining, please open a new PR. They can be a small change so you get points for this effort.

**Review by BarnyShergold — APPROVED** [review]

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs

**Pull request closed without merging**
