### PR TITLE
Add Website attributes parameter as per the codebase repository

### PR DESCRIPTION
**Pull request by ParthBrahmbhatt**
## Purpose of this PR

This PR will merge, it will be add new Website attributes parameter section into technical document as per the v2.3 codebase repository.

## Affected URLs

- v2.3 https://devdocs.magento.com/guides/v2.3/graphql/reference/store-config.html

## Links to source code

- v2.3 https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/StoreGraphQl/etc/schema.graphqls#L7

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ParthBrahmbhatt** [comment]
Hello @keharper and @ronak2ram
I have added link on ProductInterface page as per your suggetion.
Kindly review it and let me know if any other suggetion is there.
Thanks

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @ParthBrahmbhatt

**Pull request merged**
