### PR TITLE
Fixing typo in apc codeblock

### PR DESCRIPTION
**Pull request by MellenIO**
## Purpose of this pull request

This pull request (PR) fixes a typo in the APC codeblock for software recommendations

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/performance-best-practices/software.html#php-settings

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @MellenIO Thanks for the contribution. Can you please include the fix in the version 2.2 file as well?

**Comment by MellenIO** [comment]
@dobooth I've done this now, sorry for the delay.

**Comment by keharper** [comment]
Thanks @MellenIO. We'll merge this PR in our next batch.

**Pull request merged**
