### PR TITLE
Update config sample for 2.3 and add additional context

### PR DESCRIPTION
**Pull request by pmclain**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

* AMQP settings are included in the dist config since 2.3
* Expand configuration section beyond DB config. This file allows configuring
  any arguments available to `setup:install`.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/test/integration/integration_test_execution.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
Can one of the admins verify this patch?

**Comment by jeff-matthews** [comment]
@dshevtsov, please finish processing this PR and merge it.

**Comment by dshevtsov** [comment]
@jeff-matthews it is in my current backlog

**Comment by jeff-matthews** [comment]
@dshevtsov, if you can't get to it this week, please let me know so I can reassign it to another writer.

**Comment by dshevtsov** [comment]
@jeff-matthews please reassign it to another writer
the PR has passed a technical review and requires editorial review only

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
