### PR TITLE
Update bulk-endpoints.md

### PR DESCRIPTION
**Pull request by hiren-wagento**
Update Bulk route, add "async/bulk"

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3539) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3539) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@hiren-wagento thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks for finding this error, @hiren-wagento .

**Pull request merged**
