### PR TITLE
Update prod_perf-optimize.md

### PR DESCRIPTION
**Pull request by kandy**
Other command does not need for enable production mode especially on deployment on production

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@kandy: Do these changes apply to versions 2.0 and 2.1 as well? If so, please update the following files:

-  guides/v2.0/config-guide/prod/prod_perf-optimize.md
-  guides/v2.1/config-guide/prod/prod_perf-optimize.md

**Comment by hostep** [comment]
@kandy: when the `-s` flag is used, you need to regenerate the static assets and run the compiler, unless they are already up to date, right?
The docs say:
```
➜ php bin/magento deploy:mode:set --help
Usage:
  deploy:mode:set [options] [--] <mode>

Arguments:
  mode                    The application mode to set. Available options are "developer" or "production"

Options:
  -s, --skip-compilation  Skips the clearing and regeneration of static content (generated code, preprocessed CSS, and assets in pub/static/)
  ...
```

(Unless this will be changed in 2.2? I haven't tested this out yet.)

Also, slightly relevant, maybe while you're at it, I think the command: `bin/magento deploy:mode:set -s production` is missing on this page: http://devdocs.magento.com/guides/v2.1/config-guide/prod/single-machine-deployment.html
I noticed this some days ago but failed to create an issue or PR for this, sorry!

**Comment by jeff-matthews** [comment]
@kandy: Please confirm whether this affects all versions or just v2.2.

**Comment by jeff-matthews** [comment]
I confirmed with an internal product manager that this behavior is consistent across all version.

**Pull request merged**
