### PR TITLE
Update public-content.md

### PR DESCRIPTION
**Pull request by artttj**
Add missing method visibility for beforeGetVaryString in the Context plugin.

## Purpose of this pull request

Fix missing method visibility in the code snippet.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/cache/page-caching/public-content.html
- https://devdocs.magento.com/guides/v2.4/extension-dev-guide/cache/page-caching/public-content.html

### CODE REVIEW

**Comment by ajithkumar-maragathavel** [comment]
@artttj It is a good finding. Thanks.

**Review by ajithkumar-maragathavel — APPROVED** [review]

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8820`.

**Comment by artttj** [comment]
@dobooth looks like something is wrong with the github token while the linter checking

**Comment by dobooth** [comment]
@artttj Yup..a bug in their new version. It was affecting many PRs. We have now worked around it.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8820`.

**Comment by dobooth** [comment]
Well....I thought we did.

**Comment by dobooth** [comment]
Merged. Not sure why it didn't auto-close.

**Comment by dshevtsov** [comment]
> Merged. Not sure why it didn't auto-close.

Possible reason could be that the head branch was gone.

**Pull request closed without merging**
