### PR TITLE
Added information about missed options of the UI button and added the Source files section

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds the information about missed options of the UI button and adds the `Source files` section.
Also, the tables markdown was adjusted.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-button.html
- https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-button.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Ui/view/base/web/js/form/components/button.js#L19
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/form/components/button.js#L18

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Hi @serhiyzhovnir! Thanks for the contribution!

This PR and #5051 & #5052 are all closely related. Please cherry pick the commits from your other two PRs into this branch and we'll merge all the changes together.

**Comment by serhiyzhovnir** [comment]
Hi @jeff-matthews 
We have added the required changes.
Thank you!

**Comment by jeff-matthews** [comment]
running tests

**Pull request merged**
