### PR TITLE
Add list of Magento features to DevDocs

### PR DESCRIPTION
**Pull request by rtull**
This is most of the work to add a comprehensive list of Magento features along with version differences to the DevDocs.

TODOS:

- Finish updating all column checkmarks to be accurate
- Finish linking all feature lines to the corresponding page in the User Guide

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
@rtull Would you like to push your TODOs to devdocs before I start to merge?

**Comment by davidalger** [comment]
I'm pretty positive that the compiled CSS files are _not_ supposed to be committed to the repository, but they were in this PR. Hoping that is reversed before it's merged in.

**Comment by xcomSteveJohnson** [comment]
@davidalger I don't see the harm in it. I haven't been able to run gulp on Windows but as long as all the compiled CSS is correct, it seems OK to me.

**Comment by tanberry** [comment]
@davidalger thanks for asking about the CSS; I'd like to have a chance to study it a bit with you @xcomSteveJohnson, before we merge. And we still have some work to do on the content in the table, with adding X's to appropriate columns at end of table. @mcspronko  might help us out iwh that.

Let's target end of week, please don't merge til we meet. But we need to get this out here; this awesome contribution to DevDocs was actually mentioned by Alan Kent at a session about migration at Imagine yesterday, so the community knows it is coming soon!

**Comment by rtull** [comment]
Hey folks, sorry for the delay in response. For some reason I'm not seeing the email notifications from this. In regards to compiled CSS, I committed them because the files were in the repo already. I can change the PR submission to exclude the CSS if you would prefer.

**Comment by tanberry** [comment]
Hey there @rtull ; I am missing all my new friends from Imagine. ;-(

We can take a bit of time and review the CSS; I haven't yet had a chance to sit with Steve and look through it. Sorry for our delay in publishing this much-needed doc. If it's ok by you it might be end of next week before we publish it (and tweet about it!).

Thanks again for this, and for all of the awesome work Classy Llama is doing!

**Comment by rtull** [comment]
@tanberry You're welcome! Please don't feel any timeline pressure for my part. I completely understand that it's important for things detailing application features like this that all of the information be absolutely correct.

**Comment by xcomSteveJohnson** [comment]
@rtull Don't redo anything, we'll get it merged soon.

**Comment by xcomSteveJohnson** [comment]
Sorry this has taken so long. We're done formatting and need Marketing approval to publish. Hopefully that will happen soon.

**Comment by xcomSteveJohnson** [comment]
@rtull Merging but not publishing. We still don't have Marketing approval to publish but I want you to get credit for this. We're expecting big changes to the devdocs repo this week, including renaming the `2.0

**Pull request merged**
