### PR TITLE
Add supported service versions of RabbitMQ

### PR DESCRIPTION
**Pull request by pmclain**
## Purpose of this pull request

Document the available versions of RabbitMQ from platform.sh docs.
From the platform.sh docs https://docs.platform.sh/configuration/services/rabbitmq.html

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/cloud/project/project-conf-files_services-rabbit.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
@pmclain  We moved away from listing service versions in multiple places throughout the Cloud documentation. Instead, supported services versions are listed in the following topic:
https://devdocs.magento.com/guides/v2.2/cloud/project/project-conf-files_services.html#service-versions

**Comment by pmclain** [comment]
@hguthrie I've updated so the page links to the service list.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
