### PR TITLE
Added startSetup/endSetup calls for install method

### PR DESCRIPTION
**Pull request by agorbivskyi**
## Purpose of this pull request

This pull request (PR) adds startSetup/endSetup calls for install method

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.2/ui_comp_guide/howto/add_category_attribute.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@agorbivskyi thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by igrybkov** [comment]
@agorbivskyi I didn't check the code myself, so just asking: do we actually need these methods in this example or they're just added because they were missing?
There's an article by @buskamuza about why and when these methods should be used and in most of cases they're redundant. Just make sure this it's not the case here.
https://community.magento.com/t5/Magento-DevBlog/Mysterious-startSetup-and-endSetup-Methods/ba-p/68483

**Comment by agorbivskyi** [comment]
@igrybkov you are right, looks like these changes are not necessary here

**Pull request closed without merging**
