### PR TITLE
Sync 2.3.5-develop and master

### PR DESCRIPTION
**Pull request by keharper**
## Purpose of this pull request

This pull request (PR) syncs 2.3.5-develop and master to resolve a merge conflict.

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by dshevtsov** [comment]
The [2.3.5-develop](https://github.com/magento/devdocs/tree/2.3.5-develop) branch is 72 commits behind master, so we should expect 73 commits because we want to make the branch to be up-to-date with master, not vice versa.

**Comment by dshevtsov** [comment]
running tests

**Comment by jeff-matthews** [comment]
> The [2.3.5-develop](https://github.com/magento/devdocs/tree/2.3.5-develop) branch is 72 commits behind master, so we should expect 73 commits because we want to make the branch to be up-to-date with master, not vice versa.

Yeah, but knowing how many commits ahead of master the branch is gives us confidence that it contains all the expected content in addition to master. So perhaps it's best to compare both.

**Comment by dshevtsov** [comment]
Yes, good point.

**Pull request merged**
