### PR TITLE
[fix] broken github links

### PR DESCRIPTION
**Pull request by mhauri**
## This PR is a:
- [ ] New topic
- [x] Content fix or rewrite
- [x] Bug fix or improvement
 

## Summary
 
When this pull request is merged, it will fix the broken links to github in V2.1, V2.2 and V2.3 documents as the `{{page.guide_version}}` in the links isn't enough and requires the `-develop` addition.

### CODE REVIEW

**Comment by mhauri** [comment]
Hi @jcalcaben and @dshevtsov is there anything I can do to help processing this PR?

**Comment by dshevtsov** [comment]
@mhauri thank you for your contribution.
2.1 and 2.2 documentation cannot contain links to `-develop` branches.
It covers the released code only.

**Comment by jcalcaben** [comment]
This works @dshevtsov since 2.3 does not have a main branch so this fixes the broken links in that version.

**Comment by dshevtsov** [comment]
@jcalcaben this works for the current 2.3 docs only
BUT it also changes the links in 2.1 and 2.2 to `2.1-develop` and `2.2-develop`.
Moreover, after the 2.3 release these links will still lead to `2.3-develop` instead of `2.3`.

**Pull request merged**
