### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by tshabatyn**
Updating XPath to meet the XML structure.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@tshabatyn thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
The change is good but please fill in the PR description fully, as detailed in the WIKI

**Comment by tshabatyn** [comment]
@BarnyShergold Done. Thank you 🙏

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
