### PR TITLE
Update code contributions documentation according to closing 2.2-develop branch

### PR DESCRIPTION
**Pull request by VladimirZaets**
## Purpose of this pull request

Update code contributions documentation according to closing 2.2-develop branch

## Affected DevDocs pages

Code Contributions page

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4941) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4941) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@VladimirZaets thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
