### PR TITLE
MAGEDOC-3297 Add line numbers to some languages

### PR DESCRIPTION
**Pull request by belbiy**
## This PR is a:

- Bug fix or improvement

## Summary

When this pull request is merged, it will add line numbers to the following languages:
- json
- php
- html
- xml
- js
- yaml

It will actually add line numbers to ALL code blocks, but by default, they will be hidden with CSS.

## Additional information

List all affected URLs: all.

### CODE REVIEW

**Comment by keharper** [comment]
Please provide a build to view this feature before merging it.

**Comment by belbiy** [comment]
@keharper , please see the feature here: https://devdocs.magedevteam.com/yb_linenos/

**Comment by bdenham** [comment]
I would like to tweak the formatting a bit. I'll post an image later this evening.

**Comment by keharper** [comment]
Most of my code samples are still enclosed in Liquid variables, such as `{% highlight json %}`. I'm sure that's beyond the scope of this PR, but maybe we should make a concerted effort to transform the Liquid variables before pushing this PR.

**Comment by dshevtsov** [comment]
@keharper  You are welcome to create an internal ticket for that, but it shouldn't block this PR.
I tried to do the conversion in the past, but there are so many different cases when we cannot do the conversion that I decided to wait for a next time when I'll have more time to do this.

**Comment by bdenham** [comment]
I tweaked the line-number formatting by centering and removing some padding. I also added a format that includes a border to separate the numbers from the code. The border gives it a cleaner look, but may separate too much? I'm undecided, but the non-border tweaks feel better and more balanced in general. Screenshots of the options so far:

**Original:**
image

**Less Padding**
image

**With Border:**
image

**Comment by belbiy** [comment]
@bdenham , i like everything in your suggestions except the border color. I suggest using something barely visible so it does not distract from the content.`#F4F4F4` would be good. This is a "decorative" element, so it's ok if it's barely visible.

**Comment by belbiy** [comment]
> Most of my code samples are still enclosed in Liquid variables, such as `{% highlight json %}`
@keharper , you can enable line numbers on a per-block basis with `{% highlight json linenos %}`
Basically, add a `linenos` parameter to the code block and you'll have line numbers (if code block is in the list).

**Comment by belbiy** [comment]
@bdenham , once we're all agree on styling, i'll remove the style-specific code from the devdocs and move it to the theme. Devdocs CSS should really contain only the styles that ENABLE line numbers, not how they look like.

**Comment by bdenham** [comment]
Yeah, sounds good. How about #e7e7e7. The problem I have with #f4f4f4 is that with such a thin line, it causes me eye strain because I'm wondering if I see a line there or not. I have old eyes, but they may be relevant. I'm good with whatever you think. Thanks for doing this!

**Comment by bdenham** [comment]
I just put on the right glasses and #ececec looks ok as well. Still old eyes, though. :)

**Comment by belbiy** [comment]
running tests

**Comment by jeff-matthews** [comment]
@belbiy, is this PR still valid?

**Comment by belbiy** [comment]
@jeff-matthews , i think i need some more time to work on this, since i see some bugs with the code blocks when i switch on the line numbers. 

Ideally, i want to merge this after we get rid of all `{% highlight %}` tags and move to backticks `````  syntax.

**Comment by dobooth** [comment]
@belbiy I just pushed a PR that removes all the {% highlight %} syntax and replaces with backticks globally.

**Comment by hguthrie** [comment]
This PR has been open for some time. Since you need more time to work on this, I am closing the PR. You can create a new PR when you are ready.

**Comment by dshevtsov** [comment]
Reopening this PR would make more sense because it contains a conversation related to the implementation.
Another way to consider (instead of closing) for this kind of PRs is adding 'WiP' (abbreviation for Work in progress) to the title.

**Comment by hguthrie** [comment]
Closing a PR does not erase the conversation. You are welcome to reopen whenever it is ready OR you can open the PR as a DRAFT.

**Pull request closed without merging**
