### PR TITLE
module-load-order.md #3649

### LINKED ISSUE #3649: The example in module load order is not correct
# Bug report

The first example given to explain module load order is not correct. I think component A and component B should be switched in the example.

The current documentation is as follows:

> Component A introduces gadgetlayout.xml, which updates block gadgetBlock from component B. In this case, layout files from component A should be loaded before component B, so you should specify that in component B’s <sequence> entry in module .xml. In other words, component B is dependent on component A. That is to say:

### Steps to reproduce

Please visit the following link to see the erroneous example, https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-load-order.html

## Expected result

I think that the correct paragraph should be as follows:
Component A introduces gadgetlayout.xml, which updates block gadgetBlock from component B. In this case, layout files from component B should be loaded before component A, so you should specify that in component A’s <sequence> entry in module .xml. In other words, component A is dependent on component B. That is to say:

## Possible solutions

I have just put the solution above.

## Additional information

I might misunderstood the example. What I understand is the following:
There are two components called **Component A** and **Component B**. **Component B** has a block defined in it. That block is called **gadgetBlock**. **Component B** has no idea about **Component A**. But, **Component A** would like to update the block **gadgetBlock**, which is defined in **Component B** in the first place. So, **Component A** should depend on **Component B**. Because, if there were not any **Component B**, then there would not be any block for **Component A** to update.

### PR DESCRIPTION
**Pull request by irajneeshgupta**
Fixes #3649 

## This PR is a:

- Content fix or rewrite

## Summary

The first example given to explain module load order was not correct. Rectified this example as per #3649 author suggested.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-load-order.html

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-load-order.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3685) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3685) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Thanks for the contribution @irajneeshgupta, but you must complete the template when opening a PR so that we can efficiently process it.

**Comment by irajneeshgupta** [comment]
> Thanks for the contribution @irajneeshgupta, but you must complete the template when opening a PR so that we can efficiently process it.

@jeff-matthews 
I have added the required field summary in PR template.
Thank you sir.

**Comment by dobooth** [comment]
Thanks for the fix!

**Pull request merged**
