### PR TITLE
Add information about PopupWindow widget

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds information about the PopupWindow widget.

## Affected DevDocs pages

The following pages will be added:

- https://devdocs.magento.com//guides/v2.3/javascript-dev-guide/widgets/widget_popupWindow.html
- https://devdocs.magento.com//guides/v2.2/javascript-dev-guide/widgets/widget_popupWindow.html

*The view of the new page:*
image

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.2/lib/web/mage/popup-window.js#L13
- https://github.com/magento/magento2/blob/2.3/lib/web/mage/popup-window.js#L13
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Shipping/view/frontend/templates/tracking/link.phtml#L13
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Shipping/view/frontend/templates/tracking/link.phtml#L13
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Shipping/view/frontend/templates/items.phtml#L31
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Shipping/view/frontend/templates/items.phtml#L31
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Shipping/view/frontend/templates/items.phtml#L50
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Shipping/view/frontend/templates/items.phtml#L50

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by serhiyzhovnir** [comment]
Hi @dobooth!
The name of the file has changed.
Thank you!

**Comment by dobooth** [comment]
Thanks @serhiyzhovnir . Don't forget to update the name and destination of the symlink for v2.3.  Some with the other PR?

**Comment by serhiyzhovnir** [comment]
Hi @dobooth 
The symlink for v2.3 is fixed for this PR.
The v2.3 symlink for the TrimInput widget (other PR) is correct.
Thank you!

**Comment by dobooth** [comment]
I apologize for not noticing earlier, @serhiyzhovnir . The image is quite large. Could you please optimize/resize it as needed? This is the case with any image coming into the repo; they can increase the size quite a bit.

**Comment by serhiyzhovnir** [comment]
Hi @dobooth 
We have created a new PR without a large image.
New PR: https://github.com/magento/devdocs/pull/5171
Thank you!

**Pull request closed without merging**
