### PR TITLE
Missing slash with bin/magento path

### PR DESCRIPTION
**Pull request by lbajsarowicz**
## This PR is a:

- [x] Content fix or rewrite

## Summary

When this pull request is merged, it will describe properly the path to `bin/magento` used for reindex

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/configure-magento.html#es-reindex
- https://devdocs.magento.com/guides/v2.2/config-guide/elasticsearch/configure-magento.html#es-reindex
- https://devdocs.magento.com/guides/v2.1/config-guide/elasticsearch/configure-magento.html#es-reindex

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3398) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3398) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@lbajsarowicz thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Thanks for the contribution @lbajsarowicz!

**Pull request merged**
