### PR TITLE
corrected the grunt file path for Magento2.3.x

### PR DESCRIPTION
**Pull request by Renu05**
`dev/tools/grunt/configs/local-themes.js' is not existing in Magento 2.3.x The correct one is `dev/tools/grunt/configs/themes.js'

## Purpose of this pull request

This pull request (PR)  contains the updated file path

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css_debug.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @Renu05 Thanks for the contribution. If you could please sign the new Adobe CLA, we can get this merged. Thanks!

**Comment by Renu05** [comment]
Hi @dobooth 

I have signed the new Adobe CLA.

Thank You

**Pull request merged**
