### PR TITLE
Update queries.md

### PR DESCRIPTION
**Pull request by sanjay-wagento**
## Purpose of this pull request

Previous logic was only for AND condition. If we remove or then also get same result but using my modified query we can get AND OR result with 8 items.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/graphql/queries.html

## Links to Magento source code

- N/A

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia19

**Comment by rogyar** [comment]
From the technical standpoint, the provided change is correct.
We need to have logical AND between price and (name OR sku) as it's mentioned in the description.
Currently we have logical AND between price AND name OR sku

**Comment by keharper** [comment]
I updated the example further because this phrase was invalid.

pair of women’s shorts in size 10 (WSH%10%)

There are no women's shorts in Luma in that size. To ensure the search returns meaningful results, I changed the query to search for pants (WP%).

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @sanjay-wagento

**Pull request merged**
