### PR TITLE
Update log-locations.md

### PR DESCRIPTION
**Pull request by Renu05**
## Purpose of this pull request

This pull request (PR) fixes the path to reports.

## Affected DevDocs pages

https://devdocs.magento.com/cloud/project/log-locations.html

### CODE REVIEW

**Comment by Renu05** [comment]
In Cloud the path to report folder is var/report not var/reports

**Review by BarnyShergold — APPROVED** [review]
Good spot!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
