### PR TITLE
magento/devdocs#7029: for text column in db_schema the attribute 'length' is not allowed.

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/devdocs/issues/7029.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html

## Links to Magento source code

-  [TEXT](https://www.mysqltutorial.org/mysql-text/) MySQL string data type

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
An example from the codebase 

https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/app/code/Magento/Newsletter/etc/db_schema.xml#L44

**Comment by dobooth** [comment]
running tests

**Comment by milindsingh** [comment]
@atwixfirster I think this can also be updated.

Configure declarative schema   Magento 2 Developer Documentation

**Comment by atwixfirster** [comment]
> @atwixfirster I think this can also be updated.

@milindsingh , **done** in https://github.com/magento/devdocs/pull/7057

Thanks for notice!

**Comment by lano-vargas** [comment]
Also in the docs you may want to update it has an example with type text which contains length  ref: https://developer.adobe.com/commerce/php/development/components/declarative-schema/configuration/#add-an-index

**Pull request merged**
