### PR TITLE
fix #3857 Fix collapsible savestate default value

### LINKED ISSUE #3857: Feedback on page: /guides/v2.3/javascript-dev-guide/widgets/widget_collapsible.html
# General issue
Collapsible attribute "saveState" default value is in correct.
https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_collapsible.html#fedg_collaps_saveState

## Description:
In doc it's true, but in code it's false
https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/collapsible.js#L34

### PR DESCRIPTION
**Pull request by Karlasa**
## This PR is a:
fix issue #3857

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...
corrects saveState default value

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.html#fedg_collaps_saveState
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.html#fedg_collaps_saveState
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_collapsible.html#fedg_collaps_saveState

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
Hi @Karlasa can you add to PR Template the list affected url's please?

Thanks!

**Comment by Karlasa** [comment]
Sure 👍

**Comment by erikmarr** [comment]
Approved, but will wait to merge until @osrecio has a chance to review.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @Karlasa for your contribution!

**Pull request merged**
