### PR TITLE
Fix Router DI folder

### PR DESCRIPTION
**Pull request by VincentMarmiesse**
## Purpose of this pull request

This pull request (PR) fixes the `di.xml` folder for the routers, it has to be in `frontend` folder.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/routing.html

### CODE REVIEW

**Comment by dobooth** [comment]
Thanks for the contribution, @VincentMarmiesse. Could you please sign the Adobe CLA above?

**Comment by VincentMarmiesse** [comment]
Hi @dobooth,
I did but the status didn't update.
Should I do something else?

**Comment by BarnyShergold** [comment]
> Hi @dobooth, I did but the status didn't update. Should I do something else?

@VincentMarmiesse - Try making a small change and then committing & pushing - you can then reverse the change. This often works.

**Comment by dobooth** [comment]
Funny how turning it off and turning it on again works.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by m2-github-services** [comment]
@keharper the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-VincentMarmiesse-devdocs-9276`.

**Pull request merged**
