### PR TITLE
magento/devdocs#: Cloud. Elastic search plugins.

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) provides information about Elasticsearch versions which support `analysis-icu`, `analysis-phonetic` plugins.

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/project/project-conf-files_services-elastic.html

## Links to Magento source code

-  [Internal support ticket](https://support.magento.com/hc/en-us/requests/328443)

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @atwixfirster. Thank you for your edit. Let's try to groom this assumption a little bit. The screenshot your provided says `v7.5`, you say `> v7.2`, the official documentation says that all the mentioned versions up to 7.8 (current) support both modules. 

https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-phonetic.html
https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html

Does that mean that Magento Cloud does not support these plugins for some particular ES version? 

Thank you!

**Comment by atwixfirster** [comment]
> Does that mean that Magento Cloud does not support these plugins for some particular ES version?

@rogyar , honestly, I can not say for sure. This is a response from Cloud support. Regarding to it  ES versions more than 7.2 does not support mentioned plugins in Cloud infrastructure. 

@meker12 , could you please clarify this point with DEVOPS CLOUD team?

Thank you!

**Comment by meker12** [comment]
> > Does that mean that Magento Cloud does not support these plugins for some particular ES version?
> 
> @rogyar , honestly, I can not say for sure. This is a response from Cloud support. Regarding to it ES versions more than 7.2 does not support mentioned plugins in Cloud infrastructure.
> 
> @meker12 , could you please clarify this point with DEVOPS CLOUD team?
> 
> Thank you!

As @rogyar indicated, the Elasticsearch documentation indicates that the analysis-icu and analysis-phonetics plugins are supported on 7.x versions.

Is it possible that the problem was caused because the plugins installed on the integration environment needed to be updated to the newer version to work with the updated ES version as described here: https://www.elastic.co/guide/en/elasticsearch/plugins/current/listing-removing-updating.html#_updating_plugins?

**Comment by BaDos** [comment]
Need some investigation with infrastructure team.
It is in progress now.

**Comment by BaDos** [comment]
We have checked ES 7.2, 7.5 and 7.7
All of them work fine with these plugins.

**Comment by BaDos** [comment]
@atwixfirster if you have some problem with ES and these plugins, please let me know project id.
You can find me in Slack or send me an email korablov@adobe.com

**Comment by meker12** [comment]
@atwixfirster  I am closing this PR, and the corresponding issue. If you think there is still an issue, let us know.

**Comment by shrielenee** [comment]
There is an automation issue. Leave this issue where it is for now!

**Comment by atwixfirster** [comment]
Hi, @BaDos !

> @atwixfirster if you have some problem with ES and these plugins, please let me know project id.

**My problem was:** we tried to install `analysis-icu`, `analysis-phonetic` plugins on ES5 to make `Smile_Elasticsuite` module workable. 

However, a Cloud support team informed us that ES 5 **did not support** mentioned plugins and we should downgrade the Elasticsearch version.



More details you may find in [support ticket](https://support.magento.com/hc/en-us/requests/328443)

In the same time, you wrote that you've checked and ES 5 supports `analysis-icu`, `analysis-phonetic`.

So, my concern is: which of opinions is a correct here? :)

Thank you, @BaDos !

**Comment by BaDos** [comment]
Hi @atwixfirster,

I rechecked ES 7.2, 7.5, 7.7 on my starter and integration environments - it works fine.
I had a problem only with 7.6, but this version will be removed.

Regarding downgrade.
You cannot downgrade a version of any service. You can remove it and add the new version with the different name in `.magento/services.yaml` and `.magento.app.yaml`

**Comment by atwixfirster** [comment]
Hi, @BaDos !

> I rechecked ES 7.2, 7.5, 7.7 on my starter and integration environments - it works fine.
awesome 

>  I had a problem only with 7.6, but this version will be removed.

should we update a documentation about that?

Thank you!

**Comment by meker12** [comment]
@atwixfirster  We have updated the Cloud docs to remove 7.6, but I noticed another instance. Submitted the PR , which also includes a note about different service versions on Cloud vs. core: https://github.com/magento/devdocs/pull/7857

**Pull request closed without merging**
