### PR TITLE
Update ui_comp_data_source.md

### PR DESCRIPTION
**Pull request by mohammadttc**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@mohammadttc thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @mohammadttc. Please, sign CLA to proceed with the PR processing. Thank you!

**Comment by dobooth** [comment]
Thanks for the contribution, @mohammadttc. Please sign the Adobe CLA below so we can process the PR. Also, please add information to the description, so we know what this PR is for. Thanks!

**Comment by mohammadttc** [comment]
I just signed CLA. Thanks!

**Comment by dobooth** [comment]
Thanks Mohammad. For some reason, it seems it didn't take. Still seeing the red X below...not sure why.

**Comment by dobooth** [comment]
Closing as abandoned. Will fix typo in another PR.

**Pull request closed without merging**
