### PR TITLE
remove leading backslash when importing namespaces

### PR DESCRIPTION
**Pull request by idsergiu**
## Purpose of this pull request

This pull request (PR) fixes unnecessary use of backlash when importing namespaces

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/component-registration.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=register%20component

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@idsergiu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Comment by hguthrie** [comment]
@dobooth  The hand of fate has been dealt. You must add a section for `whatsnew` or change your labeling strategy.

**Pull request merged**
