### PR TITLE
Update security-txt.md

### PR DESCRIPTION
**Pull request by kalpmehta**
## Purpose of this pull request

Added contributor acknowledgement for contributing content to the  new `security.txt` file documentation.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/security/security-txt.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by meker12** [comment]
@kalpmehta Please complete the PR description to add description, files affected, and a link to source code associated with this change.  Thx.

**Comment by ccondra** [comment]
This topic was based primarily on the readme from Corra's code contribution, so their contribution to the documentation should be acknowledged!  However, it goes in the meta data, rather than in a callout. See the format in this topic, and then update the meta data and remove the callout.  Thanks!

**Comment by meker12** [comment]
@kalpmehta  Thanks for reminding us to acknowledge your contribution. I went ahead and added the metadata for the acknowledgement. Changes ought to be published in next day or two.

**Comment by kalpmehta** [comment]
@ccondra @meker12 I added the callout after checking other similar pages. Example can be found here: https://devdocs.magento.com/guides/v2.4/security/two-factor-authentication.html

Please note, this is not only about the DevDocs article contribution, but also the Security.txt module contribution to the core codebase as well :)
Original PR of the security.txt module: https://github.com/magento/security-package/pull/1

Thank you.

**Comment by kalpmehta** [comment]
FYI the page broke after the merge: https://devdocs.magento.com/guides/v2.4/security/security-txt.html

**Comment by jeff-matthews** [comment]
@meker12, I think it's because there's an extra line in the metadata block.

**Comment by meker12** [comment]
Thanks for the heads up -- submitted #7628 to fix.  Building on staging to test.  Will publish when fix is available @kalpmehta.

**Pull request merged**
