### PR TITLE
Added Magento 2 Awesome List

### PR DESCRIPTION
**Pull request by DavidLambauer**
Based on the Idea of [Awesome](https://github.com/sindresorhus/awesome), I added a List for the whole Magento 2 environment.

### CODE REVIEW

**Comment by tanberry** [comment]
@DavidLambauer  I'm stunned, you're awesome. Or, as we know, our community is awesome.

This looks like an totally awesome contribution and addition to our Community Resources page. The DevDocs team will need a little time to absorb the content... and slowly close our collective mouths that fell open with awe at the comprehensive content (who knew there was a list of the language packages?? Danke, @avoelkl !).

This list of awesome is indeed awesome; let me look at how best to include it into the Community Resources page, but yeah, ummm... thanks!

**Comment by DavidLambauer** [comment]
Thank you :) I also like the Idea of an Awesome List. It is a single point of community related content and is like a table of contents for the whole environment. 

While you'll find the right place for the list, I'll add more and more resources.

**Comment by tanberry** [comment]
not forgotten!! Just got to find a moment to work it in.

**Comment by DavidLambauer** [comment]
No worries! 👍

**Comment by tanberry** [comment]
Thanks again, @DavidLambauer !

**Comment by DavidLambauer** [comment]
Cooooooool :D Thank you :)

**Pull request merged**
