### PR TITLE
Deployment command added for the frontend and backend separately.

### PR DESCRIPTION
**Pull request by rajesh-mage**
## Purpose of this pull request

This pull request (PR) Deployment command added for the frontend and backend separately.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/css-preprocess.html

### CODE REVIEW

**Comment by dobooth** [comment]
Got the CLA! Nice.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8916`.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8916`.

**Pull request merged**
