### PR TITLE
Form component container

### PR DESCRIPTION
**Pull request by Jehangir-Wahid**
## Adding documentation for the Container ui-component

This pull request (PR) is intended to add the Container ui-component's documentation to the [ui-components](https://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html) list.

## Affected DevDocs pages

This PR will add a new page to the [ui-components](https://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html). None of the pages will be affected by this PR.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@Jehangir-Wahid thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by Jehangir-Wahid** [comment]
Removed trailing spaces, as recommended by Markdown Linting.

**Comment by Jehangir-Wahid** [comment]
Reopening pull request.

**Pull request closed without merging**
