### PR TITLE
Updated deprecated WEBAPI integration creation documentation.

### PR DESCRIPTION
**Pull request by joni-jones**
Removed usage of deprecated configuration.
Updated documentation

### CODE REVIEW

**Comment by keharper** [comment]
@joni-jones Is this for 2.2.3?

**Comment by joni-jones** [comment]
This relevant to any 2.2.x release.

**Comment by keharper** [comment]
If you'd make one small change, I'll merge this right away.

**Comment by joni-jones** [comment]
@keharper what kind of change?

**Comment by keharper** [comment]
I mentioned it above. Please  add "your" between "define" and "own".

**Comment by joni-jones** [comment]
Done

**Comment by keharper** [comment]
Thanks for the corrections, @joni-jones

**Pull request merged**
