### PR TITLE
magento/devdocs#5245: Hard tabs. Folder: guides/performance-best-practices

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request converts HARD TABs to SPACES in the folder: `guides/performance-best-practices` (v.2.2 and v.2.3)

## Affected DevDocs pages

- ...

## Links to Magento source code

- ...

CC: @jeff-matthews 

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by atwixfirster** [comment]
> #5538 fixes MD010 errors in the Performance Best Practices.

Hi, @jeff-matthews ! 

This is really a good notice but why did you mention #5538 in #5245. So, I did a double work 

:(

**Comment by jeff-matthews** [comment]
My apologies @atwixfirster. It's not my intention for you to do double work. 

Please monitor the PRs in this repo for hardtabs to ensure you're not doing extra work.

**Comment by atwixfirster** [comment]
> My apologies @atwixfirster. It's not my intention for you to do double work.
> 
> Please monitor the PRs in this repo for hardtabs to ensure you're not doing extra work.

Yes, thank you for notice. But I want to say that was my issue and I thought what only I worked on it. It was to big to make all changes in the same day. Sorry..

**Comment by jeff-matthews** [comment]
These linting issues are large enough that multiple contributors can work on them. It's also important that we get this work done in a reasonable amount of time as we have other projects that require our attention.

We appreciate all of your help and patience while we learn the best way to coordinate work on issues like this.

**Comment by atwixfirster** [comment]
Just to clarify all things here and for the understanding how to work on such issue in the future.

> These linting issues are large enough that multiple contributors can work on them. It's also important that we get this work done in a reasonable amount of time as we have other projects that require our attention.
Issue #5245 has been created about 45 days ago (Aug 22). Also, we do not have any info about deadline there like in the another open issues.

A big part of work has been done on Friday (Contribution day). Today's Wednesday... 4 days have passed (include weekend)... 

I want to hope that HARD TABs issue became a very urgent problem because I do not see any reason to speed up a progress here (again - this is my personal opinion).

> We appreciate all of your help and patience while we learn the best way to coordinate work on issues like this.

I think you do but @jeff-matthews would be REALLY nice to have a flow how multiply contributors can work together on the same issue and how they can productively collaborate (include DevDocs team too).

Thank you!

**Comment by jeff-matthews** [comment]
The reason we need to speed this up is because it's blocking progress on all other linting issues and resolving these linting issues by the end of the year is a personal goal for the team. 

We recently discovered that rules must be implemented in a specific order, which we have not communicated until now. So if other contributors volunteer for other rules, we'll be sure to let them know if they're ready for development or not.

You're right, we **do** need to provide more information about how to work on issues like this. We've learned several helpful lessons so far that we'll document in the issues themselves and possibly on the devdocs repo wiki, including:

- Use the designated integration branch for all PRs related to an issue
- Limit PRs to ~15 files
- Leave a comment in the issue stating which directories you are working on
- Resolve all errors in the directories you've claimed, even if it takes multiple PRs to do so
- Check out the designated integration branch frequently and run tests locally (`rake test:md`) to see what errors still need to be resolved
- Guidance on what other syntax fixes are appropriate to make in addition to the main syntax errors for that specific linting rule

**Comment by atwixfirster** [comment]
Thank you for the explanations , @jeff-matthews 👍

**Pull request closed without merging**
