### PR TITLE
Period(".") added and Extra colon removed

### PR DESCRIPTION
**Pull request by david-ziffity**
## Purpose of this pull request
Period(".") added and Extra colon(":") removed

This pull request (PR) 
1. In Mixins section under naming example extra colon(":") removed.
2. In Theme variables period (".") added at the end of file

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-less.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@david-ziffity thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by david-ziffity** [comment]
@magento-engcom-team Please add label as Partner: Ziffity

**Comment by david-ziffity** [comment]
@osrecio Can you please add a label Partner: Ziffity

**Pull request merged**
