### PR TITLE
Replace identical files with symlinks

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request replaces files in 2.3 that are identical to their 2.2 versions with symlinks. 
This recreates 2.3 symlinks that were erroneously removed in #4803.

## Affected DevDocs pages

- guides/v2.3 files that have exact copies in guides/v2.2

## Additional information

Internal ticket: MAGEDOC-3929

### Automation that generated the changes

`symlink-ident-files.rb`:

```
require 'pathname'
require 'fileutils'

def given_path
  ARGV[0]
end

def pattern(path)
    File.absolute_path(
      File.join(path, '**', 'v2.3', '**', '*.*')
    )
end

def file_exists(path)
  File.exist?(path)
end

def file_is_not_a_symlink(path)
  not File.symlink?(path)
end

def files_are_identical(path1, path2)
  FileUtils.compare_file(path1, path2)
end

def path_to_relative(current_path, base_path)
  current_path = Pathname.new(current_path)
  current_dir = current_path.dirname
  base_path = Pathname.new(base_path)

  File.join(
    base_path.relative_path_from(current_dir),
    current_path.relative_path_from(base_path)
  )
end

counter = 0

Dir.glob(pattern(given_path)) do |version_2_3|
  version_2_2 = version_2_3.sub '/v2.3/', '/v2.2/'
  if file_is_not_a_symlink(version_2_3) and file_exists(version_2_2) and files_are_identical(version_2_3, version_2_2)
    relative_2_2 = path_to_relative(version_2_2, given_path)

    `unlink #{version_2_3}`
    
    puts "Linking #{version_2_3} to\n#{relative_2_2}"
    `ln -s #{relative_2_2} #{version_2_3}`

    counter +=1
  end
end

puts "Replaced #{counter} identical files with symlinks"
```

To run the script locally:

```
$ ruby symlink-ident-files.rb <path to devdocs directory>
```

Example:

```
$ ruby symlink-ident-files.rb ~/Projects/repos/magento/devdocs

<truncated output>
Linking /Users/user/Projects/repos/magento/devdocs/guides/v2.3/ext-best-practices/tutorials/dynamic-row-system-config.md to
../../../../guides/v2.2/ext-best-practices/tutorials/dynamic-row-system-config.md
Linking /Users/user/Projects/repos/magento/devdocs/guides/v2.3/ext-best-practices/tutorials/copy-fieldsets.md to
../../../../guides/v2.2/ext-best-practices/tutorials/copy-fieldsets.md
Replaced 589 identical files with symlinks
```

### CODE REVIEW

**Comment by dshevtsov** [comment]
running tests

**Comment by hguthrie** [comment]
@dshevtsov You need more than one approval to merge something of this level that affects a lot of guides. I was still reviewing.

**Comment by dshevtsov** [comment]
Please add you as a reviewer in pull requests where you want to be a mandatory approver with the corresponding request in a comment.

**Comment by hguthrie** [comment]
I can do that. Thanks @dshevtsov

**Comment by erravimishracse** [comment]
Thanks to you !!!!


-------
Thanks & Regards,

Ravi Mishra
IT Software Developer | Analyst | Digital Transformation
AquadSoft Pvt Ltd, New Delhi | Gurgaon
Contact No :  +91-8076229291
Email Id:   ravimishra05sep@gmail.com
LinkedIn Url : https://www.linkedin.com/in/erravimishracse/
Skype ID:  496f212a5930610e

**Pull request merged**
