### PR TITLE
add purchase order changes

### PR DESCRIPTION
**Pull request by RakeshJesadiya**
## Purpose of this pull request

**Magento Version 2.4**
This pull request (PR) improves the purchase order API and Service details. As well add grouped product requisition list details for the Magento version 2.4 only.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/b2b/integrations.html
https://devdocs.magento.com/guides/v2.4/b2b/bk-b2b.html

### CODE REVIEW

**Comment by keharper** [comment]
@RakeshJesadiya Both of the files you edited are symlinks to 2.3 files. Since these changes are for 2.4, you'll have to break the symlinks by running the follow command on both files:

rake symlink:replace_at path=src/guides/v2.4/b2b/<filename.md>

Copy your changes to the v2.4 directory then revert the v2.3 files.

Also, are you interested in writing the documentation for the new REST endpoint?

**Comment by RakeshJesadiya** [comment]
@keharper I am interested to write REST API endpoint.

**Comment by RakeshJesadiya** [comment]
@keharper @BarnyShergold I have error on breaking the symlinks by given command,

`rakesh@rakesh-ThinkPad-E490:/var/www/html/devdocs$ rake symlink:replace_at path=/var/www/html/devdocs/src/guides/v2.4/b2b/integrations.md
rake aborted!
LoadError: cannot load such file -- html-proofer
/var/www/html/devdocs/Rakefile:12:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)`

How Can I resolved above error?

**Comment by keharper** [comment]
@RakeshJesadiya  You need to be in the devdocs root directory when you run the command. Also, the path to the file must be relative to the root directory, so it must begin with `src/guides/`

**Comment by RakeshJesadiya** [comment]
@keharper Please check the changes as per Version specific only.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Pull request merged**
