### PR TITLE
Added . to path

### PR DESCRIPTION
**Pull request by andriyShevtsov**
## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- ...
- ...

## Links to Magento source code

- ...
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4750) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4750) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@andriyShevtsov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
@andriyShevtsov these changes are included in the Cloud-2002.0.20 release branch. Do they need to be merged sooner?

**Comment by hguthrie** [comment]
I am closing this PR. These changes were made in the PR #4565 to the Cloud release branch.

**Pull request closed without merging**
