### PR TITLE
Fix broken js highlighter rendering

### PR DESCRIPTION
**Pull request by wojtekn**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix broken JS code rendering on uiClass docs page.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_uiclass_concept.html
- https://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_uiclass_concept.html
- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiclass_concept.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @wojtekn!

**Pull request merged**
