### PR TITLE
magento/devdocs#: Layout instructions. Editorial. Remove a redundant …

### PR DESCRIPTION
**Pull request by DenisSaltanahmedov**
## Purpose of this pull request

This pull request (PR) removes a redundant colon char:

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.3/install-gde/basics/basics_os-version.html

## Links to Magento source code
-  https://github.com/magento/devdocs/blob/master/src/guides/v2.3/install-gde/basics/basics_os-version.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @DenisSaltanahmedov Thanks for the contributions. To make things more efficient, we ask that multiple tiny fixes be wrapped up into a single PR. It saves processing/testing time. I already merged one of yours from yesterday. If you could merge this PR with #6478, we can process them together. Thanks for the help.

**Comment by DenisSaltanahmedov** [comment]
Hi @dobooth, I have merged the changes from #6478, and it will be able to test together.
Thanks.

**Comment by dobooth** [comment]
That's excellent! Thanks for doing so.

**Pull request merged**
