### PR TITLE
Callout what's new

### PR DESCRIPTION
**Pull request by bdenham**
## Purpose of this pull request

This pull request (PR) helps bring more attention to the what's new information on devdocs by adding a flag icon and reordering the What's New list item to the top of its block.
## Staged build

https://devdocs.magedevteam.com/2052/

image

I decided it was best to leave the blocks in their current order for "positional memory" so it won't throw people off.

## Affected DevDocs pages

Index/home page: https://devdocs.magento.com/

### CODE REVIEW

**Comment by bdenham** [comment]
@hguthrie, good questions. I'll ponder and research the :.flag: addition idea.

**Comment by jeff-matthews** [comment]
@bdenham, I mean to the Release Information box. All other boxes on the home page have 4 links except the Release Information block. Not only will adding a 4th link add some symmetry, but it will also provide navigation to that Upcoming releases page. There currently is no navigation to that page.

**Comment by bdenham** [comment]
@jeff-matthews, ah yes, of course. I'm obviously not completely awake this morning. I interpreted "add a link to the Upcoming Releases page" as _I should a link to the What's New info to the Upcoming Releases page,_ not I should add a link **_for_** the Upcoming Releases page. 😄

**Comment by jeff-matthews** [comment]
@bdenham, I could have been more clear ;)

**Comment by keharper** [comment]
Remove the "New!" next to the GraphQL. It's old now.

**Comment by bdenham** [comment]
@keharper done.
@hguthrie I worked this flag into the devdocs-theme so it can be used in lists like the existing `.new`, `.bug`, and `.fix` icons. See https://github.com/magento-devdocs/devdocs-theme/pull/60

**Comment by bdenham** [comment]
running tests

**Pull request merged**
