### PR TITLE
Add a contributor to What's New entries

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) adds a contributor to entries at [What's new on DevDocs](https://devdocs.magento.com/whats-new.html).

## Affected DevDocs pages

-  https://devdocs.magento.com/whats-new.html

Example:

Screen Shot 2020-08-07 at 18 54 07

### CODE REVIEW

**Comment by keharper** [comment]
Does this exclude writers? Most of the entries in the whatsnew are from us, and it seems kind of hokey to have a long list of writer contributions, with a few Adobe developers and outside contributors sprinkled in there.

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
> Does this exclude writers?
No.

**Comment by jeff-matthews** [comment]
That's a good call out @keharper. We should have a team discussion about how we want to approach internal contributions.

**Comment by dshevtsov** [comment]
From the other hand, a signed work would add more motivation to a writer for higher quality. The list would show areas of expertise of writers. And for a contributor might be a nice additional motivation to get into that list.

**Pull request merged**
