### PR TITLE
Documentation updated for installing RabbitMQ on CentOS 7.x

### PR DESCRIPTION
**Pull request by konarshankar07**
## Purpose of this pull request

This pull request (PR) provides information for installing RabbitMQ in CentOS 7.x

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/install-gde/prereq/install-rabbitmq.html#install-rabbitmq
Fixed https://github.com/magento/devdocs/issues/2370

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by konarshankar07** [comment]
Hello @rogyar ,
Thanks for the feedback, I have tested this in CentOS 7 and `erlang` version is compatible but I'll try to install CentoOS 6 and update the documentation according to the latest version.
Thanks

**Comment by konarshankar07** [comment]
Hello @rogyar ,
Any Updates?

**Comment by dobooth** [comment]
I do not think we can take this PR. This is saying that 2.2 (and 2.3) support RabbitMQ 3.7, which is not true. While it is excellent news that you got Magento working with the latest version of Rabbit, this PR would say that Magento the company supports these versions, which is not true.
We have not officially tested v2.2 with RabbitMQ 3.7 so we cannot update the docs to say we do.

**Pull request closed without merging**
