### PR TITLE
Updated docker-magento repo to new url

### PR DESCRIPTION
**Pull request by markshust**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

## Additional information

List all affected URLs 

- ...
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3658) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3658) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
@markshust It is required that you fill out the PR form everytime you submit a PR. Please do so, so that we may have the relevant information to start working your submitted PR. Thanks!

**Comment by shrielenee** [comment]
running tests

**Pull request merged**
