### PR TITLE
Add information about Magento consumers

### PR DESCRIPTION
**Pull request by nuzil**
## Purpose of this pull request

This pull request (PR) add information about Message queue configuration in terms of handlers and consumers processing.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/config-mq.html
https://devdocs.magento.com/guides/v2.2/extension-dev-guide/message-queues/config-mq.html

whatsnew
Added a section about consumer handlers in [Configure message queues](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/config-mq.html
) of the  _PHP Developer Guide_.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @nuzil Thanks for the contribution. We have recently been enabling markdown linting tests with submitted PRs. Can you please check the Details link below and fix up the markdown errors? Thanks.

**Comment by jeff-matthews** [comment]
Tests are broken at the moment: https://github.com/magento/devdocs/pull/5962#issuecomment-552456560

**Comment by keharper** [comment]
The error messages about extra spaces are valid, though.

**Comment by jeff-matthews** [comment]
Yes, you're right @keharper. I re-ran checks and now the list of errors is accurate (does not include false positives).

```
guides/v2.2/extension-dev-guide/message-queues/config-mq.md:109: MD009 Trailing spaces
guides/v2.2/extension-dev-guide/message-queues/config-mq.md:114: MD009 Trailing spaces
guides/v2.2/extension-dev-guide/message-queues/config-mq.md:116: MD009 Trailing spaces
guides/v2.2/extension-dev-guide/message-queues/config-mq.md:117: MD009 Trailing spaces
guides/v2.2/extension-dev-guide/message-queues/config-mq.md:123: MD009 Trailing spaces
guides/v2.3/extension-dev-guide/message-queues/config-mq.md:147: MD009 Trailing spaces
guides/v2.3/extension-dev-guide/message-queues/config-mq.md:152: MD009 Trailing spaces
guides/v2.3/extension-dev-guide/message-queues/config-mq.md:154: MD009 Trailing spaces
guides/v2.3/extension-dev-guide/message-queues/config-mq.md:155: MD009 Trailing spaces
guides/v2.3/extension-dev-guide/message-queues/config-mq.md:161: MD009 Trailing spaces
guides/v2.3/extension-dev-guide/message-queues/config-mq.md:144: MD012 Multiple consecutive blank lines
guides/v2.3/extension-dev-guide/message-queues/config-mq.md:166: MD012 Multiple consecutive blank lines
```

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @nuzil !

**Pull request merged**
