### PR TITLE
magento/devdocs#: Cloud. Upgrade to 2.3.3 via composer

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) corrects a command to upgrade Magento to 2.3.3 via composer. Because now, if you use `composer require "magento/magento-cloud-metapackage":">=2.3.2 <2.3.3" --no-update` you will get something like that in the response:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/magento-cloud-metapackage 2.3.2-p1 requires magento/product-enterprise-edition >=2.3.2 <2.3.3 -> satisfiable by magento/product-enterprise-edition[2.3.2-p2, 2.3.2] but these conflict with your requirements or minimum-stability.
    - magento/magento-cloud-metapackage 2.3.2 requires magento/product-enterprise-edition 2.3.2 -> satisfiable by magento/product-enterprise-edition[2.3.2] but these conflict with your requirements or minimum-stability.
    - magento/magento-cloud-metapackage 2.3.2-p1 requires magento/product-enterprise-edition >=2.3.2 <2.3.3 -> satisfiable by magento/product-enterprise-edition[2.3.2-p2, 2.3.2] but these conflict with your requirements or minimum-stability.
    - Installation request for magento/magento-cloud-metapackage >=2.3.2 <2.3.3 -> satisfiable by magento/magento-cloud-metapackage[2.3.2-p1, 2.3.2].
```

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/cloud/project/project-upgrade.html

## Links to Magento source code

- ...

Thank you!

CC: @meker12

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Technically Composer should recognize `>=2.3.2 <2.3.3` as 2.3.2-p2. So `>=2.3.2 <=2.3.3` is the correct condition.

**Comment by shiftedreality** [comment]
Hello @atwixfirster,

To upgrade to 2.3.3 please use:

```
composer require "magento/magento-cloud-metapackage":">=2.3.3 <=2.3.4" --no-update
``

**Comment by atwixfirster** [comment]
Hi, @shiftedreality !

> composer require "magento/magento-cloud-metapackage":">=2.3.3 <=2.3.4" --no-update

**fixed**

Thank you!

**Comment by meker12** [comment]
running tests

**Pull request merged**
