### PR TITLE
Add missing type

### PR DESCRIPTION
**Pull request by mageprince**
## This PR is a:

- [ ] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will add missing type in the parameter of check the available quantity of a salable product

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/rest/modules/inventory/check-salable-quantity.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3918) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3918) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @mageprince!

**Comment by mageprince** [comment]
@magento-engcom-team 
Thanks for merging this PR. Actual I have a concern about the label. Is there any specific reason to remove Technical label?

**Comment by jeff-matthews** [comment]
@mageprince, I put the label back and will investigate why it was removed. Thanks.

**Pull request merged**
