### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by luanalves**
## Purpose of this pull request

In this document existis informantion error "bin/magento magento setup:static-content:deploy", but the command correct is "bin/magento setup:static-content:deploy"

## Affected DevDocs pages

- ...

## Links to Magento source code

- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5311) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5311) before we can accept your contribution.<br/>**3** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: keharper<br/>:white_check_mark: jeff-matthews<br/>:white_check_mark: sdzhepa<br/>:x: Lori Krell<br/>:x: viktym<hr/>**Lori Krell** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
@luanalves thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ronak2ram** [comment]
@luanalves  I need you to resubmit your PR. You've used an outdated version of master, and as a result, this PR affects 170 topics and has many merge conflicts. Please pull in the latest changes to master and resubmit.

**Comment by luanalves** [comment]
Open new PR https://github.com/magento/devdocs/pull/5315

**Pull request closed without merging**
