### PR TITLE
Updated command for queue consumers list

### LINKED ISSUE #4233: There are missing feature on queue:consumes:list command
# New topic request
There are some missing feature for **queue:consumes:list** command https://devdocs.magento.com/guides/v2.3/comp-mgr/install-extensions/b2b-installation.html

## Content checklist

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains code samples that shows ____.
- [ ] Other (please specify)

### PR DESCRIPTION
**Pull request by gelanivishal**
## Scope of this PR

- __Technical__: Changes to technical content/code/processes/naming conventions (any change to technical content)

## Purpose of this PR
I have added remaining command for queue:consumers:list command as per screenshot, It will fixed #4233 issue.

## Affected URLs

- https://devdocs.magento.com/guides/v2.3/comp-mgr/install-extensions/b2b-installation.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@gelanivishal, you must choose one option from the list of scopes in the PR description and delete the others.

**Comment by gelanivishal** [comment]
@jeff-matthews Yeah, I updated it.

**Comment by keharper** [comment]
It would be better to delete step 1 and rewrite step 2 to state to start the two queues. We don't want to maintain an ever-increasing list of consumers.

**Comment by keharper** [comment]
Oops, I didn't notice there are only two steps, so remove the procedure and rewrite as a paragraph.

**Comment by keharper** [comment]
@gelanivishal I'm closing this PR because the `b2b-installation.md` file was moved to https://devdocs.magento.com/extensions/b2b/ as part of #4214.

I don't want to list every consumer that is added to the system, so if you choose to open a new PR to address the issue, either rewrite the procedure to avoid giving the impression that only 2 consumers exist, or state that the two consumers are among those listed in the output. Thanks!

**Pull request closed without merging**
