### PR TITLE
Added Purchase Order to comany resource table

### PR DESCRIPTION
**Pull request by dobooth**
## Purpose of this pull request

This pull request (PR) adds Purchase Order items to the Company Resource table.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/b2b/roles.html

whatsnew
Added Purchase Order resources to the [Manage Company Roles](https://devdocs.magento.com/guides/v2.4/b2b/roles.html) topic.

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
RE 2.4 file -
These 2 sections are not arranged as tables (as on 2.3 version of page) and are really hard to read. Also this page has the first list but this is not on the 2.3 page.

If the first list has is supposed to mimic the Roles and Permissions screen then please indicate this. 

The second list is better arrange as the table on 2.3 - it is difficult to read properly.

Had to add this as a general comment as GitHub kept saying "line must be part of the diff" when trying to add a comment

**Comment by BarnyShergold** [comment]
Table  should be -
--- | ---

(Can't add suggestions or comments)

The table is being badly messed up due to the extra column and not used

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Still can't add comments!

**Comment by keharper** [comment]
@BarnyShergold I asked for these changes because we need to better show the permissions hierarchy. In 2.4.2, GraphQL adds several mutations/queries that assign and return B2B roles. I didn't ask for 2.3 to be updated because B2B purchase orders are not available in 2.3. 

I'm not at a point at the moment where I can do a preview build of the latest changes. But from scanning that table, it looks like it will show the roles in a nested format, similar to what the B2B user will see.

The "line must be part of the diff"  error sometimes occurs when a symlink is broken. We reported the problem to GH well over a year ago, and it remains a problem.

**Review by BarnyShergold — APPROVED** [review]
Looks awesome now! 😄

**Review by keharper — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
