### PR TITLE
Update label based on modules names

### PR DESCRIPTION
**Pull request by ronak2ram**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged,  it will show the correct header name based on the module.
Referance page : https://devdocs.magento.com/guides/v2.3/rest/list.html

Original PR #3671 

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/rest/rest_endpoints.html
- https://devdocs.magento.com/guides/v2.2/rest/rest_endpoints.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
Thanks @ronak2ram

**Pull request merged**
