### PR TITLE
 MQP Release 1.0.12

### PR DESCRIPTION
**Pull request by ilima-ebay**
## Purpose of this pull request
 
Added RN for MQP v1.0.12
 
## Affected DevDocs pages
 
https://devdocs.magento.com/quality-patches/release-notes.html
 
whatsnew
Published [release notes](https://devdocs.magento.com/quality-patches/release-notes.html) for the 1.0.12 Magento Quality Patch (MQP) package release.

### CODE REVIEW

**Comment by ilima-ebay** [comment]
@jeff-matthews please review, you can publish right away. Thanks!

**Review by jeff-matthews — APPROVED** [review]
Thanks @ilima-ebay!

Unfortunately, our build server is down right now and we're unable to deploy to production. We're trying to fix it. I'll let you know when these get published.

**Comment by jeff-matthews** [comment]
@ilima-ebay, I forgot to mention that you'll need to "re-sign" the Adobe CLA before I can merge because it's a required check.

The Adobe Open Contribution Office recently made some changes to the CLA tool that require Adobe employees to do this. It's a one-time thing though.

**Comment by jeff-matthews** [comment]
Our build server is down due to AWS issues in North America: https://techcrunch.com/2020/11/25/amazon-web-services-outage-takes-a-portion-of-the-internet-down-with-it/.

We will have to wait until AWS has been restored.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
@ilima-ebay, [1.0.12 release notes](https://devdocs.magento.com/quality-patches/release-notes.html#v1012) have been published.

**Pull request merged**
