### PR TITLE
Add (basic) print stylesheet.

### PR DESCRIPTION
**Pull request by davidalger**
This hides stuff that is completely useless when the documentation is printed. Also saves a lot of paper! ;) Example: printing http://devdocs.magento.com/guides/v2.0/config-guide/multi-master/multi-master.html without these print styles applied results in 8 pages, vs with them printing only 3 pages which is far more readable.

### CODE REVIEW

**Comment by tanberry** [comment]
Thanks, @davidalger ! We definitely get the value of not printing all of the unneeded content (navigation, etc.). Is your thought that we could add a Print this page button/link somewhere on each page? That sounds good, though we'll have to decide if we also want PDF option, just this Print option, or..

**Comment by xcomSteveJohnson** [comment]
@tanberry This is a print-a-topic solution. I think more would be involved to print an entire guide.

@davidalger Thanks! This is a great idea!!

Granted this is for print but all guide cross-references are printed and the URLs are not complete. I'm running Jekyll locally but if you go to this URL for example:

`guides/v2.0/config-guide/bk-config-guide.html`

And look at the print preview, you'll see things like this:

```
Set up Varnish (/guides/v2.0/config-guide/varnish/config-varnish.html)
Set up caching (/guides/v2.0/config-guide/config/caching.html)
Set up database caching (/guides/v2.0/config-guide/database/database.html)
Set up Redis (/guides/v2.0/config-guide/redis/config-redis.html)
Session storage (/guides/v2.0/config-guide/memcache/memcache.html)
```

Interestingly, the links work in a browser but it might be nice to hide them. Is there a way to do that?

**Comment by xcomSteveJohnson** [comment]
* We've recently changed how CSS is organized as a result of the devdocs site being responsive; we're no longer adding individual common/css/.css files. Everything should be managed in the `scss` directory. Our RWD developer needs to look at this and figure out how best to make the change. 

*  We're going to close or merge all PRs in the near future because we're replacing the develop branch with a 2.0 branch. At that time, even if this PR is closed, its contents will be in a local branch for future use.

Thanks for your contribution!

**Comment by davidalger** [comment]
I'll have to update my PR. He did do some of it, but not all of what I did. Mine also removed a lot of highly excessive padding which is unnecessary on print.

**Comment by davidalger** [comment]
Oh, somehow missed your notes about the links… I dug into that and found there are print styles built into the app and overrides css files. Is it ok for a PR to touch both of those, or is the app one from a framework of some sort? In one of these are print styles specifically intended to make links print out like that vs just underlined text.

**Comment by xcomSteveJohnson** [comment]
Yeh, we'd appreciate it if you didn't create an override.css. app.css is generated from SCSS partials under here: https://github.com/magento/devdocs/tree/develop/scss

We did the development using gulp but as long as you don't directly modify CSS files. Let us know if you have questions.

**Comment by davidalger** [comment]
Ok. So css/app.css is generated, and common/css/override.css is by hand? I was actually saying that an overrides.css already exists! :)

**Comment by xcomSteveJohnson** [comment]
Hm, I thought overrides.css was gone. It should be. We'll take care of that later. Can you figure out how to make the same changes in SCSS?

**Comment by davidalger** [comment]
Yep. I'll ping back here once I do. Probably next day or two

**Comment by xcomSteveJohnson** [comment]
Thanks! We'll provide some guidance on this at some point but right now scrambling with the 2.0.1 patch. Let us know if you have problems.

**Comment by xcomSteveJohnson** [comment]
@davidalger Heads up: We're going to close this pull request without merging on 1/27 because we're reanming the develop branch to 2.0. All PRs have to either be merged or closed before then.

I assume you have your work in a local branch and can create another PR if you're not done by 1/27. 

All that's changing is the branch name so I don't think it will be an issue. Let us know if you have concerns.

**Comment by davidalger** [comment]
@xcomSteveJohnson Got everything on a local branch, so no worries there. :) Anyhow, I just pushed updated code to this PR.

I moved the entire `@media print` from app.css into a print.css file which is loaded only for print media, and then made my changes there. Let me know what you think!

**Comment by xcomSteveJohnson** [comment]
Thanks! Looks really good!!

**Comment by xcomSteveJohnson** [comment]
Hi, @davidalger we have a request: "The only thing it lacks are breadcrumbs or at least the topic title. Cause now it is printed without the title". Is this hard to do? Can you take it on?

**Comment by davidalger** [comment]
I can do that… won't be too difficult. Thought I had it showing, but missed removing the display:none that was added when I pulled in the updated code :) I'll submit a new PR in a just a bit

**Comment by xcomSteveJohnson** [comment]
Thanks! We're planning on creating the 2.0 branch tonight so please check to see if there is a 2.0 branch before doing your PR. (We start at about 5:30 CT). I'll probably send out a notification on Twitter.

**Comment by tanberry** [comment]
I don't normally use emoticons, but I wish I had a big heart or happy llama or clapping hands or something here... a big Thanks and a smiley face will have to do. ;-)

**Comment by davidalger** [comment]
@xcomSteveJohnson I submitted it earlier as #498…if it doesn't get merged before the branch is created tonight, well, I can resubmit it

@tanberry You're welcome!

**Pull request merged**
