### PR TITLE
[maintenance] Add plugins for debugging

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) adds two plugins to facilitate debugging. The plugins will allow to start a REPL session in the running application in two different states of the serving mode:
- Just before rendering the whole site. Enabled by adding `debug: site_pre_render` to the `_config.local.yml`.
- After rendering the whole site, but before writing any files. Enabled by adding `debug: site_pre_render` to the `_config.local.yml`.

See documentation in comments within plugins for details.

### CODE REVIEW

**Comment by dshevtsov** [comment]
@jeff-matthews, please review

**Review by jeff-matthews — APPROVED** [review]
The plugins work as described. Ii'm not sure how this info will be useful for debugging, but I trust you @dshevtsov.

**Comment by dshevtsov** [comment]
> The plugins work as described. Ii'm not sure how this info will be useful for debugging, but I trust you @dshevtsov.

It is helps to work with plugins and investigate any issues occurring on an object level at different layers.

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
