### PR TITLE
Add screenshot of clear cache and set logo from admin

### PR DESCRIPTION
**Pull request by Santoshziffity**
## Purpose of this pull request

This pull request (PR) For add screen-shot of clear the cache and set store logo from magento admin 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-apply.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Great addition!

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
I've just noticed - image file names should be in lowercase.
Please correct.

**Review by BarnyShergold — APPROVED** [review]

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8774`.

**Pull request merged**
