### PR TITLE
MS-6352 Improve Marketplace Public API Documentation

### PR DESCRIPTION
**Pull request by rdaily-magento**
## Purpose of this pull request

Updating the Marketplace Public API documentation in preparation for the end of our Early Adopters Program. The next step will be making these APIs available to more users.

- Added API callbacks documentation
- Updated /status endpoints with new structures
- Moved /status endpoints to a separate page
- Replaced inconsistent file_upload_ids with better values
- Changed action verb for profile submission from publish to submit
- Fixed other inconsistencies and errors

## Affected DevDocs pages

/marketplace/eqp/v1/users.html
/marketplace/eqp/v1/files.html
/marketplace/eqp/v1/packages.html
/marketplace/eqp/v1/filtering.html
**new** /marketplace/eqp/v1/test-results.html
**new** /marketplace/eqp/v1/callbacks.html

whatsnew
Updated the [Marketplace EQP API reference](https://devdocs.magento.com/marketplace/eqp/v1/api.html) and added new topics about [test results](https://devdocs.magento.com/marketplace/eqp/v1/test-results.html) and [callbacks](https://devdocs.magento.com/marketplace/eqp/v1/callbacks.html).

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@rdaily-magento thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
Thanks for the PR @rdaily-magento! When would you like this published on devdocs?

**Comment by rdaily-magento** [comment]
Hey @jeff-matthews, These changes can go out as soon as they are approved. The related updates are already available on our sandbox and production APIs.

**Comment by jeff-matthews** [comment]
Sounds good. We'll proceed with processing and let you know if you need any changes.

**Comment by jeff-matthews** [comment]
@rdaily-magento, we're sorting out some technical issues with our repo. Thank you for your patience while we troubleshoot. Please don't push any changes to your branch while we investigate.

**Pull request merged**
