### PR TITLE
env.php configuration values

### PR DESCRIPTION
**Pull request by Dren7755**
## Purpose of this pull request

This pull request (PR) adds info about how to set configuration values that cannot be edited in the Magento Admin directly in env.php

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-envphp.html

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Good addition but system should be added to the table at the top of the page.

**Review by BarnyShergold — APPROVED** [review]
Thank you!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8854`.

**Pull request merged**
