### PR TITLE
Replacing the layout existing plugin with a proper one

### PR DESCRIPTION
**Pull request by eduard13**
## Purpose of this pull request

This pull request (PR) replaces the not related layout plugin with a proper one. The existing plugin explains how to use plugins, but doesn't not have anything related to layout customization.

Even more, we have a separate topic that describes the plugins:
https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/xml-manage.html
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Cms/Block/Page.php#L106

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @eduard13, that's a very good catch, thank you. I believe this part should describe using plugins from the layout customization perspective rather than using plugins in general. Especially considering the fact that we have separate documentation about the general usage of plugins.

**Comment by eduard13** [comment]
Hi @dobooth, could you please let me know what are we waiting here? 🤔
Thank you.

**Comment by eduard13** [comment]
Hey @dobooth, any updates on this one?

**Comment by dobooth** [comment]
I think I was waiting for you to reply to Rogyar's concerns but he approved it. Sorry for delay.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
