### PR TITLE
Adding a code sample of how the menu widget can be initialized and used.

### PR DESCRIPTION
**Pull request by eduard13**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will provide an example of how the menu widget can be used and how the widget's options can be passed during initialization.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_menu.html
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_menu.html
- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_menu.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by eduard13** [comment]
Looks like the 2.0 isn't supported anymore. Please let me know if I have to remove the changes related to this Magento version.
Thank you.

**Comment by eduard13** [comment]
@bdenham is there any update on this one? Maybe there is needed some additional info from my side?
Thank you.

**Comment by bdenham** [comment]
running tests

**Comment by bdenham** [comment]
Hey @eduard13, looks like your missing images for versions 2.2 and 2.3. Can you push them up and I'll run the tests again. Thanks.

Here are the links that failed: 
- internal image /guides/v2.2/javascript-dev-guide/widgets/images/menu-widget-result.png does not exist
  *  _site/guides/v2.2/javascript-dev-guide/widgets/widget_menu.html (line 2276)
- internal image /guides/v2.3/javascript-dev-guide/widgets/images/menu-widget-result.png does not exist
  *  _site/guides/v2.3/javascript-dev-guide/widgets/widget_menu.html (line 2332)

**Comment by eduard13** [comment]
Hey @bdenham, thank you for letting me know, as I couldn't see what was wrong, so I've just pushed them as well.

**Comment by bdenham** [comment]
Awesome, running tests now. Will merge when complete. Thanks!

**Comment by dobooth** [comment]
running tests

**Comment by dshevtsov** [comment]
@bdenham please add whatsnew when you work with a PR with the Major update label.

**Comment by dshevtsov** [comment]
@bdenham add labels to indicate the affected versions.

**Pull request merged**
