### PR TITLE
magento/devdocs#: Exception handling

### PR DESCRIPTION
**Pull request by atwixfirster**
1. Update "Exception handling" exceptions table

## This PR is a:

- [ ] New topic
- [X] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will update "Exception handling" information about GraphQl exception. Basically, this pull request adds `GraphQlAlreadyExistsException` and `GraphQlAuthenticationException` into exceptions list.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/develop/exceptions.html

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @atwixfirster!

**Pull request merged**
