### PR TITLE
Array vs [] fix

### PR DESCRIPTION
**Pull request by biotech**
After fresh install of CE& EE 2.0.2 env.php have all config with arrays, this why [] not works there and should be array() - then works correct

### CODE REVIEW

**Comment by davidalger** [comment]
@biotech I'm curious what problems you ran into with the config as currently documented, because mixing and matching the `array(…)` and `[…]` syntaxes doesn't affect the end result and is valid PHP code. IMO the documentation here is still correct. Maybe you'd missed a comma on the initial copy/paste?

**Comment by AlexPernot** [comment]
I haven't tried the current documentation code, but isn't there 4 ']' missing anyway? I know it was confusing for me.

**Comment by davidalger** [comment]
@AlexPernot Well, that's a good point! Now I what felt wrong when I was looking at that diff ;) So maybe it'd be good to update the PR to add the closing brackets… @biotech do you want to do that? :)

**Comment by xcomSteveJohnson** [comment]
@davidalger @AlexPernot @biotech Would you mind checking [the topic](http://devdocs.magento.com/guides/v2.0/config-guide/redis/config-redis.html#config-redis-config) again? I've made some recent updates.

**Comment by davidalger** [comment]
With the updates, I think this is all irrelevant now. Looks good to me :)

--
David Alger
Director of Technology, Classy Llama

**Comment by xcomSteveJohnson** [comment]
Closing, thanks!

**Pull request closed without merging**
