### PR TITLE
HTML markdown in frontend guide

### PR DESCRIPTION
**Pull request by hitesh-wagento**
## This PR is a:
- [ ] New topic
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement
 

## Summary
HTML markdown in frontend guide
 
When this pull request is merged, it will...

### CODE REVIEW

**Comment by hitesh-wagento** [comment]
Hi @jeff-matthews 

Any updated in this PR ? 

Thanks

**Comment by jeff-matthews** [comment]
@jcalcaben, please review.

**Comment by jcalcaben** [comment]
Hi @hitesh-wagento,
There seems to be merge conflict with one of your changed files. Please resolve it and then I can merge.

**Comment by hitesh-wagento** [comment]
Hi @jcalcaben

I have resolved conflicts.

Thanks

**Comment by hitesh-wagento** [comment]
Hi @jcalcaben

I have resolved conflicts. 
This conflicts because I have created this PR before 6 Days and after someone do change in same files.

Thanks

**Comment by jcalcaben** [comment]
Merged. Thanks @hitesh-wagento !

**Pull request merged**
