### PR TITLE
Add ioncube to list of available extensions 

### PR DESCRIPTION
**Pull request by mattskr**
…47690

## Purpose of this pull request

This pull request (PR) is to add the _ioncube_ extension to the list of available PHP extensions that can be installed in cloud. I had to open a support ticket (#247690) just to get this information.

Tested on a Pro and Starter environment.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/cloud/project/project-conf-files_magento-app.html
https://devdocs.magento.com/guides/v2.2/cloud/project/project-conf-files_magento-app.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5513) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5513) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@mattskr thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @mattskr We just converted our CLA to the Adobe version. We need you to sign the new version before we can merge this PR. Thanks for the contribution!

**Comment by mattskr** [comment]
can you please tag this PR with partner Zilker Technology

**Pull request merged**
