### PR TITLE
Update message-queue-consumers.md

### PR DESCRIPTION
**Pull request by marcneubauer**
The default value and message are incorrect.  

Please see \Magento\Framework\MessageQueue\CallbackInvoker::isWaitingNextMessage for evidence.

## Purpose of this pull request
The default value in the documentation is incorrect, this fixes that.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html#start-message-queue-consumers
-  ...

## Links to Magento source code

evidence for default value: \Magento\Framework\MessageQueue\CallbackInvoker::isWaitingNextMessage

-  ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Please note that we already have a [PR](https://github.com/magento/devdocs/pull/7483) that changes the default value. But the current PR contains really useful adjustment to the explanation of "Wait for messages" concept.

**Comment by marcneubauer** [comment]
> Please note that we already have a [PR](https://github.com/magento/devdocs/pull/7483) that changes the default value. But the current PR contains really useful adjustments to the explanation of the "Wait for messages" concept.

Understood, and agreed this makes more sense, let me know if you'd like me to update this PR.

**Comment by keharper** [comment]
I accepted both #7484 and this PR, but I kept the text added here because it was more detailed.

**Pull request merged**
