### PR TITLE
Correct vendor name

### PR DESCRIPTION
**Pull request by billygilbert**
## Purpose of this pull request

The proper vendor name for the elasticsearch module is elasticsearch, not elastic.
## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/configure-magento.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@billygilbert thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
From a technical standpoint, this PR is correct. Here is a link with an example from the codebase

https://github.com/magento/magento2/blob/211dd25c73bb2539c3c064374d9d5649f253fd14/composer.json#L38

**Comment by keharper** [comment]
Thanks @billygilbert

**Pull request merged**
