### PR TITLE
Update Customer attributes

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will update Customer attributes.

## Additional information

Codebase link:
1. https://github.com/magento/magento2/blob/e45703786fecdf557e3c6b01b50b363e33a79ea1/app/code/Magento/CustomerGraphQl/etc/schema.graphqls#L79

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@mage2pratik 2.3.1 PR https://github.com/magento/graphql-ce/pull/104 causes the Graphiql browser to display attributes/fields in alphabetical order. So for 2.3.1, devdocs now lists all the attributes in alphabetic order as well. The original table also contains two attributes that are displayed in the Graphiql browser with the Customer attributes but are defined in the Rewards module. When we are able to automate the devdocs GraphQL content, we'll probably lose those Rewards attributes, but for now, they should be kept. 

I'm going to close this PR, but thanks for creating it against the 2.3.1-integration branch.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Reopening because `gender` wasn't previously documented.

**Comment by erikmarr** [comment]
@mage2pratik can you add a space between 'gender' and the opening parentheses?
gender(Male
and I'll get this merged in.

**Comment by keharper** [comment]
As always, thanks for your diligence, @mage2pratik

**Pull request merged**
