### PR TITLE
Add storageConfig entry to data provider of admin grid doc

### PR DESCRIPTION
**Pull request by naitsirch**
## Purpose of this pull request

Without storage config the filter clearing leads to a bug. The solution is found at https://magento.stackexchange.com/a/132130/31734.

Credits to [Tony Bartiloro](https://magento.stackexchange.com/users/43467/tony-bartiloro)

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/admin-grid.html
- https://devdocs.magento.com/guides/v2.4/extension-dev-guide/admin-grid.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Nice fix!

**Comment by BarnyShergold** [comment]
@naitsirch - Could you add a link reference to the 2.3 page to your description for completeness please?

**Comment by naitsirch** [comment]
@BarnyShergold I have updated the description.

**Comment by dobooth** [comment]
running tests

**Review by dobooth — APPROVED** [review]

**Pull request merged**
