### PR TITLE
Added proper space on function. Updated syntax for build.js file.

### PR DESCRIPTION
**Pull request by sanganinamrata**
## Purpose of this pull request

This pull request (PR) is the correction to `To get RequireJS to use your bundles, add a onModuleBundleCompletecallback after the modules node in the build.js file` sentence. Also added a required comma to build.js

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-js-bundling.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5519) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5519) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: sanganinamrata<br/>:x: Namrata Vora<hr/>**Namrata Vora** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @sanganinamrata. Thank you for your contribution. Your PR consists of 2 commits from different accounts. One of the accounts does not have the CLA signed. You must have the CLA signed for all authors of the PR. Thank you.

**Comment by dobooth** [comment]
Hi @sanganinamrata Adobe just changed the CLA and we need you to go through that guick acceptance step. Then we can merge your PR. Good eye!

**Comment by sanganinamrata** [comment]
@dobooth Hi, Sorry for the late reply! I'm done with the acceptance step of Adobe. You can proceed now.

**Pull request merged**
