### PR TITLE
Fixed ACL name in IP Whitelist Fastly VCL snippet example

### PR DESCRIPTION
**Pull request by sergio-ryzhokhin**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

Fixed ACL name in IP Whitelist Fastly VCL snippet example

## Additional information

List all affected URL's 

cloud/configure/fastly-vcl-whitelist.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2887) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2887) before we can accept your contribution.<br/><hr/>**Sergio Ryzhokhin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
@sergio-ryzhokhin thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by meker12** [comment]
Hello @sergio-ryzhokhin --  Thank you for your contribution.  

Please add your email to GitHub and sign the contributor agreement?

**Comment by meker12** [comment]
This change was merged in PR #2985.

**Pull request closed without merging**
