### PR TITLE
Update xss-protection.md

### PR DESCRIPTION
**Pull request by imvvashistha**
Updated spell mistake.

## Purpose of this pull request

This pull request (PR) will fix the spell mistake in DecDocs page regarding XSS proetction.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/xss-protection.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@imvvashistha thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi @imvvashistha Please sign the Adobe CLA so we can then process this PR.

**Comment by dobooth** [comment]
Closing as abandoned.

**Pull request closed without merging**
