### PR TITLE
minor clarification

### PR DESCRIPTION
**Pull request by melaxon**
## This PR is a:
- [ ] New topic
- [x] Content fix or rewrite
- [ ] Bug fix or improvement
 

## Summary
 
When this pull request is merged, it will...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=2393) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=2393) before we can accept your contribution.<br/>

**Comment by jeff-matthews** [comment]
@melaxon, please fill out the required Summary section of the PR template so that we can process your PR faster.

**Comment by bdenham** [comment]
Hey @melaxon, can you provide more info about these changes? Also, please sign our Contributor License Agreement (CLA) for your submission. Thanks.

**Comment by melaxon** [comment]
This change aims to correctly outline system behavior:  "Compilation mode" can be assigned to Default Config only, but now the document suggests to verify this setting for all store views

**Comment by bdenham** [comment]
@melaxon, I removed step 5 for you and merged your changes to production. Thanks for the fix to the docs. Much appreciated!

**Pull request merged**
