### PR TITLE
Update db-schema.md

### PR DESCRIPTION
**Pull request by sanjay-wagento**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

Drop table description was incorrect. disabled attribute does not support in table node. Please check at https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/schema.xsd

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@sanjay-wagento The `disabled` attribute is defined in the `operations.xsd` file. The other sections on dropping DB elements have pretty much the same sentence, so I'd like to get some clarification on whether 1) the sentence should be deleted in multiple places or 2) we should add examples showing the `disabled` attribute set to `true`.

**Comment by sanjay-wagento** [comment]
@keharper , As per https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/schema.xsd file it does not allow disabled attribute in table node. I tried and received error.
So **To drop a table declared in another module, redeclare it with the disabled attribute set to true** sentence is not correct

**Comment by keharper** [comment]
Checking with an internal developer to verify this is a doc bug, and not a code bug.

**Comment by fascinosum** [comment]
@sanjay-wagento what error did you get?
https://github.com/magento/magento2/blob/c427332aefb3ea0851fffa6967de7fe7106abfb3/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/schema.xsd#L87 declares `disabled` attribute

**Comment by sanjay-wagento** [comment]
@fascinosum This is error
Element 'table', attribute 'disabled': The attribute 'disabled' is not allowed.
Verify the XML and try again.

**Comment by fascinosum** [comment]
@sanjay-wagento this attribute will be available with the next patch release

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
@sanjay-wagento , based on the fact that @fascinosum states the attribute will be available in 2.3.1, please open a new PR against the *2.3.1-integration* branch that adds the statement deleted in this PR.

**Pull request merged**
