### PR TITLE
Replace deprecated attribute name

### PR DESCRIPTION
**Pull request by mageprince**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will replace deprecated attribute

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.3/graphql/reference/url-resolver.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Closing because this PR is not correct. See #4064  and #3925

**Comment by mageprince** [comment]
@keharper I have added an attribute in develop branch which is 2.3.2 and I checked https://github.com/magento/devdocs/pull/3925 @mage2pratik  has missed adding an attribute so I have created this PR based on his PR. So please reopen this and proceed further.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
Thanks @mageprince

**Pull request merged**
