### PR TITLE
Add information about the TrimInput widget

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds information about the TrimInput widget.

## Affected DevDocs pages

The following pages will be added:

- https://devdocs.magento.com//guides/v2.3/javascript-dev-guide/widgets/widget_trimInput.html
- https://devdocs.magento.com//guides/v2.2/javascript-dev-guide/widgets/widget_trimInput.html

*The view of the new page:*
TrimInputWidget_page_view

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.2/lib/web/mage/trim-input.js
- https://github.com/magento/magento2/blob/2.3/lib/web/mage/trim-input.js
- https://github.com/magento/magento2/blob/2.3/app/code/Magento/Newsletter/view/frontend/templates/subscribe.phtml#L29
- https://github.com/magento/magento2/blob/2.2/app/code/Magento/Customer/view/frontend/templates/form/confirmation.phtml#L17

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by serhiyzhovnir** [comment]
Hi @dobooth 
The file name is changed.
Thank you!

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
