### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by dshevtsov**
Optimized images with [ImgBot](https://imgbot.net)

*Total -- 128,930.51kb -> 102,158.24kb (20.76%)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4138) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4138) before we can accept your contribution.<br/>

**Comment by jeff-matthews** [comment]
Thanks @dshevtsov. A 20% reduction is significant.
 
@belbiy, shouldn't we be doing image optimization during the build process?

**Comment by belbiy** [comment]
@jeff-matthews , due to the large number of images it's not efficient to optimize them on each build. 

It's better not to store unoptimized images in the repo in the first place. Image optimization needs to happen before commit ideally. 

But i see the bot as a quick and reliable way to at least not to serve the unoptimized images to the frontend users.

We need to think about the solution for storing images separately, since this bot will not take care that for us.

**Comment by jeff-matthews** [comment]
Right, because without an optimization process, new or revised images may not be optimized in new PRs. Ok, thanks @belbiy. This looks good to me.

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
