### PR TITLE
Update flow-diagram.md

### PR DESCRIPTION
**Pull request by ygyryn**
## This PR is a:

- [ ] New topic
- [x] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...
Add new point with link for 2.3.x system requirements page.
This template is included in other templates, see: List all affected URLs   

## Additional information

List all affected URLs: 
https://devdocs.magento.com/guides/v2.0/install-gde/install-resource-diagram.html
https://devdocs.magento.com/guides/v2.1/install-gde/install-resource-diagram.html
https://devdocs.magento.com/guides/v2.2/install-gde/install-resource-diagram.html
https://devdocs.magento.com/guides/v2.3/install-gde/install-resource-diagram.html
https://devdocs.magento.com/guides/v2.0/install-gde/install-flow-diagram.html
https://devdocs.magento.com/guides/v2.1/install-gde/install-flow-diagram.html
https://devdocs.magento.com/guides/v2.2/install-gde/install-flow-diagram.html
https://devdocs.magento.com/guides/v2.3/install-gde/install-flow-diagram.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
Thanks @ygyryn 🎉

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
running tests

**Comment by ygyryn** [comment]
@shrielenee  Thank you, too!

**Pull request merged**
