### PR TITLE
Updated routes.md

### PR DESCRIPTION
**Pull request by salmanazeez786**
## Purpose of this pull request
This pull request (PR) provides fixes of the output example for magento-cloud environment:routes CLI command

## Affected DevDocs pages
https://devdocs.magento.com/cloud/project/routes.html

-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@salmanazeez786 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by andrewbess — APPROVED** [review]
Hello @salmanazeez786 
Thank you for your contribution.
Changes look correct from technical side.

**Comment by andrewbess** [comment]
Hello @salmanazeez786 
Please process CLA issue.
We cannot merge this PR without it.
Thank you in advance.

**Comment by salmanazeez786** [comment]
@andrewbess  Please check now

**Comment by danidelcar** [comment]
Hi @salmanazeez786 would you mind filling the **purpose of this PR** field with information about this PR?, thanks!

**Comment by andrewbess** [comment]
### Purpose of this pull request
This pull request (PR) provides fixes of the output example for `magento-cloud environment:routes` CLI command

### Affected DevDocs pages
- https://devdocs.magento.com/cloud/project/routes.html

@salmanazeez786 Could you please change description of this PR with the my text?
Thank you in advance.

**Comment by salmanazeez786** [comment]
@andrewbess Done !!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
