### PR TITLE
Fixed spelling typo mistake in cloud files.

### PR DESCRIPTION
**Pull request by NamrataChangani**
## This PR is a:
- [x] Content fix or rewrite
 

## Summary
Fixed spelling typo mistake in cloud files.
 

## Additional information
N/A

### CODE REVIEW

**Comment by mhauri** [comment]
Hi @NamrataChangani looks like there are a lot of changes which got already fixed and merged in PR  #1990

**Comment by NamrataChangani** [comment]
@mhauri : I've added some of the missing files for the PR request #1990. Please verify once.

**Comment by mhauri** [comment]
Hi @NamrataChangani indeed, there where some files missing in the original PR, but the most of them where already fixed in #1990. Maybe update your PR to only cover the missing files.

**Comment by meker12** [comment]
@NamrataChangani  Thanks for the spelling updates. The DevDocs v2.0x is EOL as of April 2018. We no longer make or accept changes to the 2.0x version of docs. No need to submit any further changes for those docs. A few of the changes apply to v2.1, so I'll review those, apply them, and close the PR on completion

**Pull request merged**
