### PR TITLE
Updating theme to use the latest Adobe analytics script

### PR DESCRIPTION
**Pull request by dobooth**
## Purpose of this pull request

This pull request (PR) updates the theme to use the latest Adobe Analytics script and removes the workaround.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
My apologies! I thought this was a PR in the theme repo 🤦

**Comment by jeff-matthews** [comment]
@belbiy, don't we have to remove the `src/_includes/layout/header-scripts.html` file completely in order for devdocs to use the them file instead?

**Comment by belbiy** [comment]
@jeff-matthews , yeah, you actually right. I was not paying attention to what was deleted. @dobooth , let's discuss the strategy of where do we put this script so every website is easily shared the OMEGA and we still keep header scripts in all the repos.

**Comment by belbiy** [comment]
This PR is good to merge after moving the script from the `_includes/layout/header-scripts.html` to `_includes/layout/header.html`

**Comment by dobooth** [comment]
I have moved the script to header.html as requested.

**Comment by jeff-matthews** [comment]
@dobooth, I think you are committing directly to the `master` branch in the theme repo. Please create PRs instead. I'll set up some branch protections to help enforce that.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
