### PR TITLE
Fixed #5015 Incorrect Example: /guides/v2.3/howdoi/customize-modifier-class.html

### LINKED ISSUE #5015: Incorrect Example: /guides/v2.3/howdoi/customize-modifier-class.html
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/howdoi/customize-modifier-class.html

## Description

`Example::modifyMeta` in the first code sample under the **Add your modifier** section is not adding the required `componentType` argument to the `test_fieldset_name`'s configuration. This throws a `LocalizedException`.

## Possible solutions

```diff
public function modifyMeta(array $meta)
    {
        $meta['test_fieldset_name'] = [
            'arguments' => [
                'data' => [
                    'config' => [
                        'label' => __('Label For Fieldset'),
                        'sortOrder' => 50,
                        'collapsible' => true,
+                        'componentType' => 'fieldset',
                    ]
                ]
            ],
```

### PR DESCRIPTION
**Pull request by kirtinariya1**
## Purpose of this pull request

This pull request (PR) will be merge the show correct Example in the Customize using a modifier class
## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.2/howdoi/customize-modifier-class.html
- https://devdocs.magento.com/guides/v2.3/howdoi/customize-modifier-class.html

## Links to Magento source code
N/A

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=5016) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=5016) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kirtinariya1<br/>:x: Kirti Nariya<hr/>**Kirti Nariya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by osrecio** [comment]
@kirtinariya1 can you sign the CLA for two users that you use to make commits. Or maybe is better squash the commit with only contributor and commit. 

Thanks!

**Comment by dobooth** [comment]
I have had that double name/CLA issue before. I believe something in .git/config gets changed or updated and then this happens. Can't recall for sure.

**Pull request merged**
