### PR TITLE
Front end folder in module

### PR DESCRIPTION
**Pull request by kandarp26**
As per current theme structure frontend folder inside the view folder. So i have changed 
1. `<module_dir>/view/layout/` to 3. `<module_dir>/view/frontend/layout/`

### CODE REVIEW

**Comment by kandarp26** [comment]
@xcomSteveJohnson Any update ?

**Comment by xcomSteveJohnson** [comment]
@almarchenko Please provide an update for this PR. Thanks!

**Comment by kandarp26** [comment]
Hi Any update on it? Can I close this pull request ?

**Comment by almarchenko** [comment]
@kandarp26  Thank you very much for your input! 
And sorry for the delay!

**Pull request merged**
