### PR TITLE
Add performance best practices

### PR DESCRIPTION
**Pull request by choukalos**
Added reference architecture diagram and common Varnish architecture diagram to Performance Best Practice Guide.  Expanded Hardware page to provide more detail and guidance on memory usage (as of 2.2.0).  

Would be great if someone could also provide insight on a general recommend memory configuration for sites doing a pipeline deployment.

### CODE REVIEW

**Comment by keharper** [comment]
Thank you @choukalos for this fantastic contribution! I'll have to get approval from architects and/or PMs before I can merge this. 

Meanwhile, are you able to edit the graphics you submitted? In version 2.3, Open Source will support message queues and Elasticsearch, so the `m2-deployment-architecture.png` graphic will be out of date.

**Comment by choukalos** [comment]
Hi @keharper - Yes I have the graphics in power point and can upload those files as well if there's an appropriate place to put them to make it easier to maintain go-forward.  I'll do an update of the graphic for 2.3 based on that insight and add to the branch.  Are both RabbitMQ (for message queues) and Elasticsearch both optional tech stack items?

**Comment by keharper** [comment]
RabbitMQ and Elasticsearch remain optional.

**Comment by choukalos** [comment]
@keharper - I updated the diagram for 2.3 and am now showing Elasticsearch & RabbitMQ as optional Community Edition items.  I also cleaned up the wording to not say Elasticsearch is Enterprise.

**Comment by lorikrell** [comment]
@choukalos  Thanks for the edits! I'll route the diagrams through UX and working through feedback.

**Comment by keharper** [comment]
@choukalos I've merged this PR. Again, thanks for this information.

I've created an internal ticket (MAGEDOC-2950) to track the request for information for memory recommendations for pipeline deployments and other issues.

**Comment by dshevtsov** [comment]
@keharper please add `whatsnew` to the PR description

**Pull request merged**
