### PR TITLE
Update gulp-sass.md

### PR DESCRIPTION
**Pull request by Demiot**
## This PR is a:

- [x] Content update

## Summary

"package.json" is useless and is a source of error

When this pull request is merged, it will...

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/gulp-sass.html
- https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/gulp-sass.html
- https://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/gulp-sass.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3749) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3749) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@Demiot thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@Demiot, filling out the PR form is mandatory for each contribution. This helps us efficiently process your PRs.

**Comment by Demiot** [comment]
For only one file name in excess. This is not a little abused? a contributor can look it's yes or it's no ....

**Comment by jeff-matthews** [comment]
We must apply the same rules to all contributors and all pull requests @Demiot. Thank you for updating the description.

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
Thanks for the contribution @Demiot.

**Pull request merged**
