### PR TITLE
magento/devdocs#: Migrate install/upgrade scripts to declarative schema. Add available types to "setup:db-declaration:generate-patch" command.

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) adds information about available type options of the `bin/magento setup:db-declaration:generate-patch` command.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.html
- https://devdocs.magento.com/guides/v2.3/reference/cli/magento.html

## Links to Magento source code

- [data](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Developer/Console/Command/GeneratePatchCommand.php#L83)
- [schema](https://github.com/magento/magento2/tree/2.3.2/app/code/Magento/Catalog/Setup/Patch)

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
From the technical standpoint, this PR is correct

**Comment by dshevtsov** [comment]
@atwixfirster the files in `_data/codebase` are autogenerated from the Magento codebase. After the next cycle of release updates, any changes to these files will be overwritten by actual data from the codebase. Please consider porting the corresponding changes to the codebase.

**Comment by atwixfirster** [comment]
> @atwixfirster the files in `_data/codebase` are autogenerated from the Magento codebase. After the next cycle of release updates, any changes to these files will be overwritten by actual data from the codebase. Please consider porting the corresponding changes to the codebase.

Thank you for the clarification, @dshevtsov !

**done** in https://github.com/magento/magento2/pull/23868

**Pull request merged**
