### PR TITLE
Config files updates 2.2

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) extends `Configuration types and objects` section for **Magento 2.2** and adds information about the next files:
- `address_formats.xml`
- `acl.xml`
- `analytics.xml`
- `cache.xml`
- `catalog_attributes.xml`
- `crontab.xml`
- `cron_groups.xml`
- `eav_attributes.xml`
- `email_templates.xml`
- `export.xml`
- `extension_attributes.xml`
- `fieldset.xml`
- `indexer.xml`
- `import.xml`
- `module.xml`
- `mview.xml`
- `payment.xml`
- `persistent.xml`
- `pdf.xml`
- `product_options.xml`
- `product_types.xml`
- `reports.xml`
- `resources.xml`
- `sales.xml`
- `search_engine.xml`
- `search_request.xml`
- `system.xml`
- `validation.xml`
- `view.xml`
- `webapi.xml`
- `widget.xml`
- `zip_codes.xml`

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.2/config-guide/config/config-files.html

## Links to Magento source code

- [acl.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cms/etc/acl.xml)
- [address_formats.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Customer/etc/address_formats.xml)
- [analytics.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Analytics/etc/analytics.xml)
- [cache.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Store/etc/cache.xml)
- [catalog_attributes.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Sales/etc/catalog_attributes.xml)
- [cron_groups.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cron/etc/cron_groups.xml)
- [crontab.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Tax/etc/crontab.xml)
- [eav_attributes.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/etc/eav_attributes.xml)
- [email_templates.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/User/etc/email_templates.xml)
- [export.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/BundleImportExport/etc/export.xml)
- [extension_attributes.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Eav/etc/extension_attributes.xml)
- [fieldset.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Tax/etc/fieldset.xml)
- [indexer.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/etc/indexer.xml)
- [import.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/CatalogImportExport/etc/import.xml)
- [module.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cms/etc/module.xml)
- [mview.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/CatalogSearch/etc/mview.xml)
- [payment.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Paypal/etc/payment.xml)
- [persistent.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Persistent/etc/persistent.xml)
- [pdf.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Tax/etc/pdf.xml)
- [product_options.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/etc/product_options.xml)
- [product_types.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Bundle/etc/product_types.xml)
- [reports.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Analytics/etc/reports.xml)
- [resources.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Sales/etc/resources.xml)
- [sales.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Tax/etc/sales.xml)
- [search_engine.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Search/etc/search_engine.xml)
- [search_request.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/CatalogSearch/etc/search_request.xml)
- [system.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cms/etc/adminhtml/system.xml)
- [validation.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Eav/etc/validation.xml)
- [view.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/etc/view.xml)
- [webapi.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cms/etc/webapi.xml)
- [widget.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cms/etc/widget.xml)
- [zip_codes.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Directory/etc/zip_codes.xml)

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
> This HTML topic doesn't exist in 2.1 or 2.2. Looks like it was introduced in 2.3. Can you remove this entry?

Nevermind...the docs are missing for 2.1 and 2.2. We'll handle creating those in a separate PR. As soon as those are checked in, we can merge this.

**Comment by atwixfirster** [comment]
> Nevermind...the docs are missing for 2.1 and 2.2.

sir, yes sir :)

Thank you, @erikmarr !

**Comment by atwixfirster** [comment]
> We'll handle creating those in a separate PR. As soon as those are checked in, we can merge this.

**done**

Could you please review - https://github.com/magento/devdocs/pull/4707

Thank you!

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @atwixfirster!

**Pull request merged**
