### PR TITLE
MAGEDOC-5240: enabled MD001 header increment rule

### PR DESCRIPTION
**Pull request by VitaliyBoyko**
## Purpose of this pull request
This pull request (PR) enables MD001 header increment rule

## Fixed issue
#5240 Markdown linting: Header levels should only increment by one level at a time (MD001)

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hguthrie** [comment]
Update: Letting you know that I have not forgotten about this PR. We are working on a solution for Cloud guide procedure headings. Thanks for your patience.

**Comment by hguthrie** [comment]
Okay, the Cloud guide procedures have been updated. You can continue to make the necessary changes to this PR. Thanks for waiting!

**Comment by jeff-matthews** [comment]
@VitaliyBoyko, please fix the conflict and I'll merge this.

**Comment by jeff-matthews** [comment]
Thanks @VitaliyBoyko!

**Pull request merged**
