### PR TITLE
Fixed #4846 /guides/v2.3/config-guide/cli/config-cli-subcommands-cache.html and v2.2

### LINKED ISSUE #4846: Statement that cache can be enabled|disabled only from command line starting Magento 2.2 is false
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.html

## Description

Statement that cache can be enabled|disabled only from command line starting Magento 2.2 is false
## Possible solutions

Remove the false statement

### PR DESCRIPTION
**Pull request by kirtinariya1**
## Purpose of this pull request

This pull request (PR) will be merge the show correct 

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-cache.html
- https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.html

## Links to Magento source code
N/A

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
@kirtinariya1 it looks like this PR is a dup of the following:
https://github.com/magento/devdocs/pull/4878
Can we close this one?

**Comment by kirtinariya1** [comment]
> @kirtinariya1 it looks like this PR is a dup of the following:
> #4878
> Can we close this one?

Yes. It was something miss mess about to wrong commit.

**Comment by erikmarr** [comment]
This is a duplicate of #4878. Closing.

**Pull request closed without merging**
