### PR TITLE
Updated attribute type for customAttributMetadata query

### PR DESCRIPTION
**Pull request by VinothKumar361**
## Purpose of this pull request

This pull request (PR) Updating attribute type for customAttributMetadata query

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/graphql/queries/custom-attribute-metadata.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @VinothKumar361. Thank you for your contribution. Could I kindly ask you in your next PRs to provide more info about not only **what** has been changed but also **why** it has been changed? It will help a lot with PRs processing. Thank you!

**Comment by VinothKumar361** [comment]
sure @rogyar.

> Hi @VinothKumar361. Thank you for your contribution. Could I kindly ask you in your next PRs to provide more info about not only **what** has been changed but also **why** it has been changed? It will help a lot with PRs processing. Thank you!

sure @rogyar

**Comment by keharper** [comment]
I ran the query exactly as listed on devdocs on a 2.3.4 build. These are the results, truncated

{
  "data": {
    "customAttributeMetadata": {
      "items": [
        {
          "attribute_code": "size",
          "attribute_type": "Int",
          "attribute_options": [
            {
              "value": "16579",
              "label": "55 cm"
            },
            {
              "value": "16804",
              "label": "XS"
            }
          ]
        },
        {
          "attribute_code": "color",
          "attribute_type": "String",
          "attribute_options": [
            {
              "value": "16453",
              "label": "Black"
            },
            {
              "value": "16456",
              "label": "Blue"
            }
          ]
        }
      ]
    }
  }
}

For the `size` attribute, the `attribute_type` is `Int`.  For  `color`, it's `String`.

Closing this because the output is correct.

**Comment by VinothKumar361** [comment]
Hi @keharper ,
i'm sure that the atrtibute type as Int for color is correct by below points
1.From this page(https://devdocs.magento.com/guides/v2.3/graphql/queries/products.html) in layered navigation filter the color attribute is given as integer 
2.As you can see the value for size and color were both int (which is the attribute_type) from your query response itself
3.i ran the same command in magento2.3.4 instance and i got the below response
{
  "data": {
    "customAttributeMetadata": {
      "items": [
        {
          "attribute_code": "size",
          "attribute_type": "Int",
          "attribute_options": [
            {
              "value": "91",
              "label": "55 cm"
            },
            {
              "value": "166",
              "label": "XS"
            },
            {
              "value": "92",
              "label": "65 cm"
            },
            {
              "value": "167",
              "label": "S"
            },
            {
              "value": "93",
              "label": "75 cm"
            },
            {
              "value": "168",
              "label": "M"
            },
            {
              "value": "94",
              "label": "6 foot"
            },
            {
              "value": "169",
              "label": "L"
            },
            {
              "value": "95",
              "label": "8 foot"
            },
            {
              "value": "170",
              "label": "XL"
            },
            {
              "value": "96",
              "label": "10 foot"
            },
            {
              "value": "171",
              "label": "28"
            },
            {
              "value": "172",
              "label": "29"
            },
            {
              "value": "173",
              "label": "30"
            },
            {
              "value": "174",
              "label": "31"
            },
            {
              "value": "175",
              "label": "32"
            },
            {
              "value": "176",
              "label": "33"
            },
            {
              "value": "177",
              "label": "34"
            },
            {
              "value": "178",
              "label": "36"
            },
            {
              "value": "179",
              "label": "38"
            }
          ]
        },
        {
          "attribute_code": "color",
          "attribute_type": "Int",
          "attribute_options": [
            {
              "value": "49",
              "label": "Black"
            },
            {
              "value": "50",
              "label": "Blue"
            },
            {
              "value": "51",
              "label": "Brown"
            },
            {
              "value": "52",
              "label": "Gray"
            },
            {
              "value": "53",
              "label": "Green"
            },
            {
              "value": "54",
              "label": "Lavender"
            },
            {
              "value": "55",
              "label": "Multi"
            },
            {
              "value": "56",
              "label": "Orange"
            },
            {
              "value": "57",
              "label": "Purple"
            },
            {
              "value": "58",
              "label": "Red"
            },
            {
              "value": "59",
              "label": "White"
            },
            {
              "value": "60",
              "label": "Yellow"
            }
          ]
        }
      ]
    }
  }
}
4.Also yo can check database eav_attribute table for color attribute backend_type value

**Comment by rogyar** [comment]
Hi @keharper. That's a very interesting case. Since the "color" attribute is a part of layered navigation and it's backend type is `int`

image

technically it cannot be `string`. So, there's a chance that we have a bug or misunderstanding here. I will double-check on my end if you don't mind.

**Comment by RamSamMindz** [comment]
Hi vinoth ,

I have one small doubt , order status doesn't show my order view page plz ref attach
img_20200228
ment

**Comment by VinothKumar361** [comment]
> Hi vinoth ,
> 
> I have one small doubt , order status doesn't show my order view page plz ref attach
> img_20200228
> ment
Hi RamSamMindz, could you please provide information about
magento version?
how did you placed order?
did you override sales_order_grid.xml file ?

**Comment by VinothKumar361** [comment]
Hi @keharper, do you have any information about this PR?

**Comment by rogyar** [comment]
That's why I got on a clean 2.3.4 installation with NO sample data (the color attribute values added manually)

image

**Comment by dobooth** [comment]
@keharper

**Comment by keharper** [comment]
Accepting this PR despite the fact I can't verify this. I see in my database that the attribute in question is an integer, but on 3 different instances, the query returns a value of `String`

**Pull request merged**
