### PR TITLE
Config files updates (m.2.3)

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) extends `Configuration types and objects` section for **Magento 2.3** and adds information about the next files:
- `address_formats.xml`
- `acl.xml`
- `analytics.xml`
- `cache.xml`
- `catalog_attributes.xml`
- `communication.xml`
- `crontab.xml`
- `cron_groups.xml`
- `db_schema.xml`
- `eav_attributes.xml`
- `email_templates.xml`
- `esconfig.xml`
- `export.xml`
- `extension_attributes.xml`
- `fieldset.xml`
- `indexer.xml`
- `import.xml`
- `module.xml`
- `mview.xml`
- `payment.xml`
- `persistent.xml`
- `pdf.xml`
- `product_options.xml`
- `product_types.xml`
- `queue.xml`
- `queue_consumer.xml`
- `queue_publisher.xml`
- `queue_topology.xml`
- `reports.xml`
- `resources.xml`
- `sales.xml`
- `search_engine.xml`
- `search_request.xml`
- `system.xml`
- `validation.xml`
- `view.xml`
- `webapi.xml`
- `webapi_async.xml`
- `widget.xml`
- `zip_codes.xml`

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/config/config-files.html

## Links to Magento source code

- [address_formats.xml](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Customer/etc/address_formats.xml)
- [acl.xml](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Cms/etc/acl.xml)
- [analytics.xml](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Analytics/etc/analytics.xml)
- [cache.xml](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Store/etc/cache.xml)
- [catalog_attributes.xml](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Sales/etc/catalog_attributes.xml)
- communication.xml
- [crontab.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Tax/etc/crontab.xml)
- [cron_groups.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Cron/etc/cron_groups.xml)
- [db_schema.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Cms/etc/db_schema.xml)
- [eav_attributes.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Catalog/etc/eav_attributes.xml)
- [email_templates.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/User/etc/email_templates.xml)
- [esconfig.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Elasticsearch/etc/esconfig.xml)
- [export.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/BundleImportExport/etc/export.xml)
- [extension_attributes.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Eav/etc/extension_attributes.xml)
- [fieldset.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Tax/etc/fieldset.xml)
- [indexer.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Catalog/etc/indexer.xml)
- [import.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/CatalogImportExport/etc/import.xml)
- [module.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Cms/etc/module.xml)
- [mview.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/CatalogSearch/etc/mview.xml)
- [payment.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Paypal/etc/payment.xml)
- [persistent.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Persistent/etc/persistent.xml)
- [pdf.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Tax/etc/pdf.xml)
- [product_options.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Catalog/etc/product_options.xml)
- [product_types.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Bundle/etc/product_types.xml)
- queue.xml (deprecated in Magento 2.3)
- [queue_consumer.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/WebapiAsync/etc/queue_consumer.xml)
- [queue_publisher.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/WebapiAsync/Code/Generator/Config/RemoteServiceReader/Publisher.php)
- [queue_topology.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/WebapiAsync/etc/queue_topology.xml)
- [reports.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Analytics/etc/reports.xml)
- [resources.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Sales/etc/resources.xml)
- [sales.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Tax/etc/sales.xml)
- [search_engine.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Search/etc/search_engine.xml)
- [search_request.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/CatalogSearch/etc/search_request.xml)
- [system.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Cms/etc/adminhtml/system.xml)
- [validation.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Eav/etc/validation.xml)
- [view.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Catalog/etc/view.xml)
- [webapi.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Cms/etc/webapi.xml)
- [webapi_async.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Catalog/etc/webapi_async.xml)
- [widget.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Cms/etc/widget.xml)
- [zip_codes.xml](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Directory/etc/zip_codes.xml)

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hey @rogyar We pushed a huge change on Friday that completely changed the format of all glossary links. The UUIDs went away and now it is just a straight link. I suspect we will have some merge conflicts for a few days until everyone updates. https://github.com/magento/devdocs/pull/4650

**Comment by atwixfirster** [comment]
> About config.php and env.php I would say that these files are readable/writeable by the internal config processor.

**Added new description**

**Comment by atwixfirster** [comment]
> The module link has been changed
> 
> ```
>  {% glossarytooltip c1e4242b-1f1a-44c3-9d72-1d5b1435e142 %}module{% endglossarytooltip %}
> ```
> 
> Do we need this change or it happened accidentally?
> 
> The same issue is for https://github.com/magento/devdocs/pull/4643/files#diff-21dd23c487515a8ca8be55218d0e91d6R117 (line 117). Sorry, GitHub is throwing errors on an attempt to post a code review today

**fixed**

@rogyar , could you please review now?

Thank you!

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @atwixfirster for your contribution!

**Comment by dshevtsov** [comment]
@erikmarr add whatsnew to the PR description.

**Pull request merged**
