### PR TITLE
Changes made in declarative schema doc

### PR DESCRIPTION
**Pull request by samuvelbalan**
## Purpose of this pull request

This pull request (PR) is to change the data type "tiny text" to "text" Since the tiny text is not declared in the XSD file so this will throw an error while doing setup upgrade as "Types tinytext is not declared".

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html

-  ...

## Links to Magento source code
https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/schema.xsd

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@samuvelbalan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
Hi @samuvelbalan. Thank you for the fix, that's a very good catch. I can confirm that the [XSD schema](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Setup/Declaration/Schema/etc/schema.xsd) does not have the `tinytext` definition but `text`, `longtext`, etc.

**Comment by samuvelbalan** [comment]
Thank you @rogyar.

**Pull request merged**
