### PR TITLE
Index Status Updated

### LINKED ISSUE #7820: 2.4 index status labels are not correct in documentation
# General issue

## Description:

The indexer status labels are different in 2.4 compared to what documentation says
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing.html

## Possible solutions:

Update the status labels from "Valid, Invalid, Working" to "Ready, Reindex Required, Processing"

## Additional information:

N/A

### PR DESCRIPTION
**Pull request by chandru-199**
## Purpose of this pull request

Updates the index status labels.

Fixes #7820 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexing.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@chandru-199 I ran `bin/magento indexer:reindex` and checked the INDEXER_STATE table while the command was running. I was able to see the `valid` and `working` statuses using this simple test.

I don't think the docs are wrong--I think we're seeing two different perspectives: the database and the Admin. I suggest converting the bulleted list to a table and listing both the database and the UI values. I would list the db value first, since we're in the developer guide.

**Comment by BarnyShergold** [comment]
@chandru-199 - Please may we nudge you to complete this PR as recommended? Thanks

**Comment by dobooth** [comment]
@chandru-199

**Comment by chandru-199** [comment]
Sorry for the delay @dobooth @BarnyShergold. I will update this docs soon. Thanks!

**Comment by dobooth** [comment]
Hi @chandru-199 Please reopen this PR when you are ready to update it. Thanks!

**Pull request closed without merging**
