### PR TITLE
Issue 7976 widget

### LINKED ISSUE #7976: Unclear on how to activate the Magnifier widget
# General issue

## Description:

https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_gallery_mg.html
It says:

> Magnifier is a widget that allows displaying images in 100% scaled size in separate dedicated layer. In Magento it is used by the gallery widget for zooming the product images on product pages.

But if I hover over a product image in the product view in the frontend, then there is no zoom.
Do I have to enable this first or add a script to make it work?

### PR DESCRIPTION
**Pull request by jenlindner**
## Purpose of this pull request

This pull request (PR) fixes #7976 by adding the information that the Magnifier requires an edit in a local theme file, `view.xml`, in order to be enabled. 

## Affected DevDocs pages

/devdocs/guides/v2.3/javascript-dev-guide/widgetswidget_gallery_mg.md

I didn't see this .md file in the v2.4 directory, so I made the changes in the v2.3 directory. I'll be happy to port that file to the other directory if that doesn't break anything.
-  ...

## Links to Magento source code

-  ...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@jenlindner thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by jeff-matthews** [comment]
Thanks @jenlindner! 

The 2.3 file that you modified is actually symlinked to 2.4, so that change will apply to the 2.4 version of the docs.

**Comment by jenlindner** [comment]
Thank you - sorry! I forgot to join and sign earlier though I meant to. It's done now.

**Comment by jeff-matthews** [comment]
No problem! Thanks for contributing!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Thanks for the contribution, @jenlindner. Nice to have a new contributor.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
