### PR TITLE
Marketplace Migration - Sellers

### PR DESCRIPTION
**Pull request by ccondra**
## Purpose of this pull request

The purpose of this PR is to migrate all Marketplace Seller content from the Marketplace user guide to devdocs.  "Extensions Marketplace" was added to the Functional Areas navigation, with a Marketplace Sellers TOC in the left nav. Many of the Marketplace files were renamed for consistency and brevity. Also incorporated the FAQ content from [DOC-84](https://jira.corp.magento.com/browse/DOC-84). 

## Affected DevDocs pages

**TOC UPDATES**
main-nav.yml (added Extensions Marketplace)
marketplace-sellers.yml (left nav for Marketplace topics)

**NEW TOPICS**
1. [Getting Started](http://devdocs.magento.com/extensions/marketplace/getting-started.html)
2. [Before You Begin](http://devdocs.magento.com/extensions/marketplace/before-you-begin.html)
3. [Extension Quality Program](http://devdocs.magento.com/extensions/marketplace/extension-quality-program.html)
4. [Seller Overview](http://devdocs.magento.com/extensions/marketplace/seller-overview.html)
5. [Your Seller Account](http://devdocs.magento.com/extensions/marketplace/account-overview.html)
6. [Account Setup Process](http://devdocs.magento.com/extensions/marketplace/account-setup.html)
7. [Register as a Developer](http://devdocs.magento.com/extensions/marketplace/developer-register.html)
8. [Marketplace Developer Portal](http://devdocs.magento.com/extensions/marketplace/developer-portal.html)
9. [Profile Information](http://devdocs.magento.com/extensions/marketplace/profile-account.html)
10. [Company Profile](http://devdocs.magento.com/extensions/marketplace/profile-company.html)
11. [Personal Profile](http://devdocs.magento.com/extensions/marketplace/profile-personal.html)
12. [Extensions](http://devdocs.magento.com/extensions/marketplace/extensions.html)
13. [Create an Extension](http://devdocs.magento.com/extensions/marketplace/extension-complete.html)
14. [Specify the Version](http://devdocs.magento.com/extensions/marketplace/extension-version.html)
15. [Complete the Extension Information](http://devdocs.magento.com/extensions/marketplace/extension-information.html)
16. [Add Extension Content](http://devdocs.magento.com/extensions/marketplace/content.html)
17. [Establish Your Brand](http://devdocs.magento.com/extensions/marketplace/branding.html)
18. [Define the Business Value](http://devdocs.magento.com/extensions/marketplace/branding.html)
19. [Update Extension Information](http://devdocs.magento.com/extensions/marketplace/extension-update-information.html)
20. [Themes](http://devdocs.magento.com/extensions/marketplace/themes.html)
21. [Shared Packages](http://devdocs.magento.com/extensions/marketplace/shared-packages.html)
22. [Review Process](http://devdocs.magento.com/extensions/marketplace/submit-for-review.html)
23. [Submit for Technical Review](http://devdocs.magento.com/extensions/marketplace/submit-for-technical-review.html)
24. [Technical Review Guidelines](http://devdocs.magento.com/extensions/marketplace/technical-review-guidelines.html)
25. [Code Validation](http://devdocs.magento.com/extensions/marketplace/code-validation.html)
26. [Submit for Marketing Review](http://devdocs.magento.com/extensions/marketplace/submit-for-marketing-review.html)
27. [Marketing Review Guidelines](http://devdocs.magento.com/extensions/marketplace/marketing-review-guidelines.html)
28. [Product Descriptions](http://devdocs.magento.com/extensions/marketplace/product-descriptions.html)
29. [Video Tips](http://devdocs.magento.com/extensions/marketplace/video-tips.html)
30. [Image Tips](http://devdocs.magento.com/extensions/marketplace/image-tips.html)
31. [Preview Your Submission](http://devdocs.magento.com/extensions/marketplace/marketing-submission-preview.html)
32. [View the Results](http://devdocs.magento.com/extensions/marketplace/review-report.html)
33. [ Resubmit an Extension](http://devdocs.magento.com/extensions/marketplace/extension-resubmit.html)
34. [Manage Sales](http://devdocs.magento.com/extensions/marketplace/sales.html)
35. [Revenue Share](http://devdocs.magento.com/extensions/marketplace/revenue-share.html)
36. [Analytics](http://devdocs.magento.com/extensions/marketplace/analytics.html)
37. [Technical Reference](http://devdocs.magento.com/extensions/marketplace/technical-reference.html)
38. [Packaging v1.x Extensions](http://devdocs.magento.com/extensions/marketplace/packaging-v1x-extensions.html)

**RENAMED/REDIRECTED TOPICS**

1. Seller Overview
     from: /marketplace/user_guide/sellers/overview.html
     to: /marketplace/sellers/seller-overview.html

2. Account Setup Process
     from: /marketplace/user_guide/sellers/set-up-your-account.html
     to:  /marketplace/sellers/account-setup-process
	
3. Account Setup
     form: /marketplace/user_guide/sellers/account-setup-overview.html
     to:   /marketplace/sellers/account-setup.html
	
4. Register as a Developer
     from:   /marketplace/user_guide/sellers/register-as-a-developer.html
     to:	/marketplace/sellers/developer-register.html
	
5. Developer Portal
     from: /marketplace/user_guide/sellers/marketplace-developer-dashboard.html	
     to: /marketplace/sellers/developer-portal.htm
	
6. Company Profile
     from: /marketplace/user_guide/sellers/company-profile.html
     to: /marketplace/sellers/profile-company.html

7. Personal Profile
     from: /marketplace/user_guide/sellers/personal-profile.html
     to: /marketplace/sellers/profile-personal.html
	
8. Create an Extension
     from: /marketplace/user_guide/sellers/completing-your-extension.html
     to:  /marketplace/sellers/extension-create.html
	
9. Specify the Version
     from: /marketplace/user_guide/sellers/creating-a-new-version.html
     to: /marketplace/sellers/extension-version.html
	
10. Complete the Extension Information
     from: /marketplace/user_guide/sellers/creating-a-new-extension.html
     to: /marketplace/sellers/extension-information.html
	
11. View the Results
     from: /marketplace/user_guide/sellers/test-reports.html
     to: /marketplace/sellers/review-report.html
	
12. Resubmit an Extension
     from: /marketplace/user_guide/sellers/resubmitting-an-extension.html
     to: /marketplace/sellers/extension-resubmit.html
	
13. Update Extension Information
     from: /marketplace/user_guide/sellers/updating-extension-information.html
     to: /marketplace/sellers/extension-update-information.html

**TOPICS NOT MIGRATED**

1. [Build Your Extension](https://docs.magento.com/marketplace/user_guide/sellers/build-your-extension.html) (Only had 1 sentence)
2. [Resources](https://docs.magento.com/marketplace/user_guide/resources/resources.html) (landing page not needed)
3. [Frequently Asked Questions for Developers](https://docs.magento.com/marketplace/user_guide/sellers/faq-sellers.html)
4. [Frequently Asked Questions for Buyers](https://docs.magento.com/marketplace/user_guide/buyers/faq-buyers.html)
5. [Marketplace Tools](url) (No longer available)	
	
## Additional Info

Staging: # 1523

whatsnew
Migrated Sellers content from the Marketplace User Guide to Functional Areas > Extensions Marketplace.
[Extensions Marketplace](https://devdocs.magento.com/marketplace/sellers/getting-started.html)

### CODE REVIEW

**Comment by ccondra** [comment]
I added a list of renamed/redirected topics and also those that were not migrated to the PR description,

**Comment by jeff-matthews** [comment]
Everything looks good on staging. I'd like to test the redirects before approving and merging though. Doing that now.

**Comment by ccondra** [comment]
All the redirects check out, so this is good to go.

**Comment by ccondra** [comment]
running tests

**Comment by jeff-matthews** [comment]
Thanks @ccondra, please run tests and then do a **Squash and merge**.

**Comment by ccondra** [comment]
running tests

**Pull request merged**
