### PR TITLE
Add documentation for columns editing bulk ui component

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
## Purpose of this pull request

This pull request (PR) adds documentation for the ColumnsEditingBulk UI component.

## Affected DevDocs pages

The new page will be created with the following URL: 
-  https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-columns-editing-bulk.html

## Links to Magento source code

-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/grid/editing/bulk.js
-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/grid/editing/editor.js#L45-L50
-  https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/templates/grid/editing/bulk.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Please make the same TOC change here that you did on the other.

**Comment by serhiyzhovnir** [comment]
Hi @dobooth
I've added requested changes.
Thanks.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
