### PR TITLE
Fix customer auth example with cURL

### PR DESCRIPTION
**Pull request by ihor-sviziev**
## Purpose of this pull request

This pull request (PR) fixes authentication example with cURL

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-token.html#token-example

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ihor-sviziev** [comment]
Also would be great to add curl examples with admin tokens

**Comment by rogyar** [comment]
Hi @ihor-sviziev. Great idea, we will be waiting for another PR 😉

**Comment by dobooth** [comment]
running tests

**Pull request merged**
