### PR TITLE
Update placement-and-design.md minor typo issue

### PR DESCRIPTION
**Pull request by denish-c-vachhani**
Replace "**Store** > **Settings > **Configuration** section." with "**Store** > **Settings** > **Configuration** section."

image

## Purpose of this pull request

This pull request (PR) solve minor typo issue.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/ext-best-practices/admin/placement-and-design.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@denish-c-vachhani thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Good eye, @denish-c-vachhani and thanks for the contribution. The general rule for breadcrumbs is that we bold things you actually click on and do not bold section headers. So in this case, can you please unbold "Settings"?

**Comment by denish-c-vachhani** [comment]
@dobooth Changed as per your comment.

**Pull request merged**
