### PR TITLE
[cicd] Add a GitHub action to lint Markdown at PRs

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request adds a GitHub action that runs markdown linting test for pull requests to master or develop.

## Validation

Open [Actions](https://github.com/magento/devdocs/actions) to observe the workflow runs.

### CODE REVIEW

**Comment by dobooth** [comment]
I noticed that Jenkins will fail on linting and report only the first error. Will this report back all errors at once?

**Comment by dshevtsov** [comment]
This PR is not related to Jenkins.

**Comment by dshevtsov** [comment]
> Does this mean we should remove the Md test stage in the Jenkins pipeline?

I hope so, this was original goal. But I don't know how this will work. We should monitor this for a while (week or two).

> Will failed tests from GitHub Actions block PR merging?

I don't know for sure. I think to make it a required check, it has to be configured additionally. Will need to play around to find out.

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
