### PR TITLE
Performance best practices > Improve the syntax

### PR DESCRIPTION
**Pull request by rafaelstz**
## Purpose of this pull request

The purpose is to fix the syntax and keep all bash commands following the same pattern.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-setup.html
-  https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-setup.html

## Reference

Capture d’écran, le 2020-10-02 à 13 54 06

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
You will also need to do the same changes to the 2.4 version of this file as the 2.3 & 2.4 versions are no longer symlinked. Please also update the description to show the 2.4 page link,

**Comment by rafaelstz** [comment]
All set @BarnyShergold

**Review by BarnyShergold — APPROVED** [review]
Thanks!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
