### PR TITLE
Resolve code quotation error.

### PR DESCRIPTION
**Pull request by niravkrish**
## Purpose of this pull request

This pull request (PR) ... The code provided in the documentation has some issues regarding the quotation. I have resolved the issue regarding the code provided to reference in the documentation.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/knockout-bindings.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Comment by meker12** [comment]
running tests

**Pull request merged**
