### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by dangminh**
## Purpose of this pull request

This pull request (PR) fixes an incorrect file extension.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/wysiwyg/add-custom-editor/
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@dangminh thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by swnsma** [comment]
Hi @dangminh!
May I ask you to sign Adobe CLA, so we will be able to proceed with your pull request?

**Comment by dangminh** [comment]
> Hi @dangminh!
> May I ask you to sign Adobe CLA, so we will be able to proceed with your pull request?

i'm signed to Adobe CLA.

**Review by swnsma — APPROVED** [review]

**Comment by swnsma** [comment]
Affected pages:
https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/wysiwyg/add-custom-editor/
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/

**Pull request merged**
