### PR TITLE
magento/devdocs#:5916 Adding more information to searching with repositories topic

### PR DESCRIPTION
**Pull request by DenisSaltanahmedov**
## Purpose of this pull request
This pull request (PR) Adding more information to searching with repositories topic

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/searching-with-repositories.html

## Links to Magento source code
-  https://github.com/magento/devdocs/blob/master/src/guides/v2.3/extension-dev-guide/searching-with-repositories.md

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by DenisSaltanahmedov** [comment]
Hi, @dshevtsov could you please let me know if the PR is ok? Thanks.

**Comment by dshevtsov** [comment]
@DenisSaltanahmedov please run `rake test:md` locally to identify and fix the Markdown style issues.

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
