### PR TITLE
Update a couple of inconsistent URL's pointing to 2.0/2.1 code repositories.

### PR DESCRIPTION
**Pull request by realadityayadav**
## Purpose of this pull request

This pull request (PR) is surely a cleanup but I think this is essential. 

Via Search, I found out more than 100 inconsistent URL's of incorrect anchors pointing to the older version of the code but I have only corrected 2 in this pull request. I understand this can be made understood to developers for now but indeed a more robust solution is needed before we target release of 2.4, 2.5 & so on because the codeset in Magento Devdocs still would be referring/pointing to 2.0/2.1 files which would make it highly inconsistent in the long run. 
Maybe we can set some special redirects for these URL's when they originate from Devdocs so they land on the correct repository.

Original Issue -  #4422
## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/config-guide/bootstrap/magento-how-to-set.html
- https://devdocs.magento.com/guides/v2.3/config-guide/log/log-magento.html

## Links to Magento source code

- ...
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4496) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4496) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by lorikrell** [comment]
@realadityayadav , thank you so much for adding new files and removing the symlinks to provide version specific code repo links! We'll review and test the PR soon as possible. 👍

**Comment by realadityayadav** [comment]
Sure. I'll refer & make the changes in a bit.

**Comment by erikmarr** [comment]
Thanks @realadityayadav for your feedback. This has been resolved by the following PR: https://github.com/magento/devdocs/pull/4518
I'm closing this one.

**Pull request closed without merging**
