### PR TITLE
Added Event Framework Architecture diagrams

### PR DESCRIPTION
**Pull request by roma-glushko**
## This PR is a:

- Content update

## Summary

This PR adds a visual representation of key components of Magento 2 Event Framework in the following cases:

- General Event Framework (Both Open Source/Commerce)
- Adjustments that Magento_Staging module brings to Magento 2 Event Framework (Commerce only feature)

Two diagrams were committed to show these points. 

## Additional information

No pages were updated yet. Working on this 🙌

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3590) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3590) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by lorikrell** [comment]
@roma-glushko Thanks! Don and I will check these over with you. And help find the right place to add them in the docs. We may also get Alex Palinrush to provide an architecture review. 

Per Legal, keep the copyrighting out (like you did). We can add a caption/page note of contribution note for yourself and Atwix. Thanks! 👍

**Comment by lorikrell** [comment]
Getting a discussion going with architects. Working to have updates and further info.

**Comment by dobooth** [comment]
Hi @roma-glushko 
Sorry for the delay!
We would like to make some grammatical updates to some of the descriptions.
I have made the following suggestions:
--Architecture-event-framework
Config (on left)
Observers are defined in the `events.xml` files. These are loaded by the Magento2 Configuration File Framework and are validated by the `events.xsd` schema.

Magento\Framework\Event
Represents the dispatched event and extends Magento\Framework\DataObject. 
Also contains event data.

Vendor\Module\Observer\CustomObserver
Custom endpoints should implement the ObserverInterface and are registrable in `events.xml`.

ManagerInterface
Dispatches events by executing all registered observers by passing $data to all of them.

InvokeInterface
Creates and executes a single observer via $configuration.

Observer
DTO class which extends Magento\Framework\DataObject. Enable magic getEvent, setEvent and other methods.

--Architecture-event-framework-staging

Magento\Staging\Mode\Event\Manager
Staging Event Manager provides the ability to ignore specific events and observers from executing when the staging update is previewing.

Thanks for your patience.

**Comment by dobooth** [comment]
Hi @roma-glushko Any movement on this? I would like to get this out of the queue. Post an update please, or I will have to close the PR.

**Comment by roma-glushko** [comment]
Hi @dobooth , 
I have adjusted labels on diagrams, can you please take a look when you have time? 
Thank you,
Roman

**Comment by dobooth** [comment]
Thanks for the changes, @roma-glushko. Where are these file going to be used within the site?

**Comment by dobooth** [comment]
Hi @roma-glushko  I'm going to close this PR due to inactivity. 
Please feel free to resubmit the PR at any time, but please note how/where these images will be used.

**Pull request closed without merging**
