### PR TITLE
magento/devdocs#7092: Correction for Accessing js resources in JavaScript resources in Magento

### PR DESCRIPTION
**Pull request by atwixfirster**
## Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/devdocs/issues/7092.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/js-resources.html

## Links to Magento source code

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by rogyar** [comment]
I can confirm that the [js/theme](https://github.com/magento/magento2/blob/dfc712f9628144335884f6f22bc107b74d2cced5/app/code/Magento/Theme/view/adminhtml/requirejs-config.js#L20) bundle defined only for `adminhtml`

**Comment by dobooth** [comment]
running tests

**Comment by dobooth** [comment]
running tests

**Pull request merged**
