### PR TITLE
Update unit_test_execution_cli.md

### PR DESCRIPTION
**Pull request by michaeldyl520**
Magento 2.2.x need PHPUnit 6.x

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- ...

## Links to Magento source code

- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4971) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4971) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@michaeldyl520 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
