### PR TITLE
Release notes (2.3.4)

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) adds DRAFT 2.3.4 release notes for pre-release. These notes are subject to change before GA.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
running tests

**Comment by dshevtsov** [comment]
A file name should not contain a name of parent directory per our file naming convention.

**Comment by jeff-matthews** [comment]
@dshevtsov, please be more specific

**Comment by dshevtsov** [comment]
The files `src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md` and `src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md` do not meet the file naming convention. `release-notes` appears in the directory names and in file names.

**Comment by jeff-matthews** [comment]
Neither do the 2.3.3 release notes. We can remedy this for 2.3.4 before GA.

**Comment by dshevtsov** [comment]
I mention this almost each release, hope it'll happen one day :)

**Comment by jeff-matthews** [comment]
hahaha! i'll see to it

**Pull request merged**
