### PR TITLE
Add missing argument parameter as per the codebase repository

### PR DESCRIPTION
**Pull request by ParthBrahmbhatt**
## Purpose of this PR

This PR will merge, it will add the missing parameter into technical document as per the magento version v2.1, v2.2 and v2.3 codebase repository.

## Affected URLs

- v2.3 https://devdocs.magento.com/guides/v2.3/payments-integrations/base-integration/payment-action.html
- v2.2 https://devdocs.magento.com/guides/v2.2/payments-integrations/base-integration/payment-action.html
- v2.1 https://devdocs.magento.com/guides/v2.1/payments-integrations/base-integration/payment-action.html

## Links to source code

- v2.3 https://github.com/magento/magento2/blob/2.3/app/code/Magento/Braintree/etc/di.xml#L224
- v2.2 https://github.com/magento/magento2/blob/2.2/app/code/Magento/Braintree/etc/di.xml#L224
- v2.1 https://github.com/magento/magento2/blob/2.1/app/code/Magento/Braintree/etc/di.xml#L200

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
hi @ParthBrahmbhatt, thanks for the submission.
This is the 4th PR in the last two days around these exact XML nodes.
Please look at the other PRs around this issue to see if it has been handled already.
Read comments here:
https://github.com/magento/devdocs/pull/4275

**Comment by ParthBrahmbhatt** [comment]
Hi @dobooth, I have checked that there are different pages over technical document where braintree xml nodes used for explain the payment gateway. As this page has different from my previous PR which I just got before sometime.

**Comment by ronak2ram** [comment]
Hi @ParthBrahmbhatt 
Thanks for your contribution.
According to the code base file, the provided change is correct.

You are doing a good job in the Devdocs. but I have one suggestion, before generating PR, Just confirm the same change is not remaining to any other pages.

**Comment by ParthBrahmbhatt** [comment]
Hi @dobooth  @ronak2ram
Actually, I am new into devdocs contribution and forgot to verify same changes in other file. I will take care next time before create PR.
Thanks for guiding me

**Comment by dobooth** [comment]
That's great. I wanted to be sure we were duplicating effort. Thanks for making sure.

**Comment by dobooth** [comment]
running tests

**Pull request merged**
