### PR TITLE
Removed wrong instruction; corrected link

### PR DESCRIPTION
**Pull request by JonyD**
The deleted instruction was wrong because there is no such checkbox in the **Default View**; corrected link same as in commit d5d08f4.

### CODE REVIEW

**Comment by xcomSteveJohnson** [comment]
Unable to automatically merge this one, closing.

**Comment by JonyD** [comment]
@xcomSteveJohnson "Unable to automatically merge this one, closing."? Can you please at least look at the changes and edit the "unmergable" commit? You are throwing away a correction to something that is published/wrong.

**Comment by xcomSteveJohnson** [comment]
I took a look, I don't see anything. What am I missing?

**Comment by JonyD** [comment]
look here: https://github.com/magento/devdocs/pull/913/files.
the instruction 4. was removed because, like my first comment says, "The deleted instruction was wrong because there is no such checkbox in the Default View". Other change is in the link: has 3 dashes instead of 2..

**Comment by xcomSteveJohnson** [comment]
Look [here](http://devdocs.magento.com/guides/v2.1/config-guide/multi-site/ms_websites.html#multi-storecode-baseurl) and [here](http://devdocs.magento.com/guides/v2.1/config-guide/multi-site/ms_websites.html#step-7-change-the-default-store-views-base-url)

**Comment by JonyD** [comment]
I looked and I stand my point: I did everything right. Please read carefully:
- in point 7.  the link is wrong. It needs 3 dashes instead of 2 (according to the text: "you must replace the first period with three dashes" ) so, instead of "http://french--branch-sbg" it should be "http://french---branch-sbgW"
- point 7.4 needs to be removed because that procedure to "change the default store view's base URL", does not exist. If you follow instructions steps you will see that there is no default checkbox (you can even see that in the image after 5.). So, the instruction that says "In the Base URL section, clear the Use Default check box." needs to be removed from this step-by-step guide.
I cannot explain any better.

**Comment by JonyD** [comment]
I made a new commit so you can see it better. commit: https://github.com/magento/devdocs/commit/6becad16f761ba0427c5700f6988ef4659389141

**Comment by xcomSteveJohnson** [comment]
@JonyD Was a busy week, finally got a chance to look. You're correct. Fixed now.

**Pull request closed without merging**
