### PR TITLE
Correct max page size for elasticsearch engine

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will correct max page size for elasticsearch engine.

## Additional information

Codebase [link](https://github.com/magento/magento2/blob/3a4ba669c7a834007d15c4005e716da2ca72fdbb/app/code/Magento/Elasticsearch/etc/di.xml#L420)

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/searching-with-repositories.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by keharper** [comment]
@mage2pratik Is the value defined in `di.xml`? I don't see it there.

**Comment by keharper** [comment]
Never mind, it's in the 2.3.1 branch. This PR needs to be merged in to the 2.3.1-integration branch.

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
@mage2pratik I can't merge this into master because the code update is in 2.3.1.  I tried switching it in GitHub, but that produced its own set of problems. Please rebase your branch to 2.3.1-integration, or close this PR and open a new one with 2.3.1-integration as the target. 

I think this command would work for the first option:

git rebase --onto 2.3.1-integration master <your branch>

**Comment by keharper** [comment]
Thanks for finding this @mage2pratik

**Pull request merged**
