### PR TITLE
MAGECLOUD-2891: [Cloud Docker] Verify Xdebug functionality

### PR DESCRIPTION
**Pull request by oshmyheliuk**
## This PR is a:

- [x] New topic
- [x] Content update
- [ ] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will add documentation on how to configure Xdebug on cloud docker environment.

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.1/cloud/docker/docker-config.html
https://devdocs.magento.com/guides/v2.1/cloud/docker/docker-development-debug.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3708) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3708) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: oshmyheliuk<br/>:x: BaDos

**Comment by hguthrie** [comment]
Hey there. Thanks for this. Unfortunately, it breaks our navigation, so I will be working on incorporating this in detail. Expect a technical review soon.

**Comment by hguthrie** [comment]
Ha! My merge should have closed this PR automatically. I apologize for the confusion, but rest assured that your changes were applied! Thanks @oshmyheliuk !

**Pull request closed without merging**
