### PR TITLE
magento/devdocs#: Replace ``` php with ``` json for the JSON data

### PR DESCRIPTION
**Pull request by atwixfirster**
**json code format for the JSON data**

## This PR is a:

- [ ] New topic
- [X] Content update
- [X] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will fix a code format for the JSON data.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/graphql/develop/create-graphqls-file.html
- https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/

Thank you!

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by shrielenee** [comment]
running tests

**Comment by shrielenee** [comment]
thanks @atwixfirster! 🌟

**Comment by keharper** [comment]
@atwixfirster Unfortunately, this PR was not correct. In GraphQL, query and mutation inputs should use the `text` code gates, not `json` or `php`. Inputs are specified in GraphQL schema definition language, and there's no special  Responses should use the `json` code gates.  I'm correcting the GraphQL changes in #4051

**Comment by keharper** [comment]
Also see https://github.com/magento/devdocs/pull/3670/

**Comment by atwixfirster** [comment]
> @atwixfirster Unfortunately, this PR was not correct. In GraphQL, query and mutation inputs should use the `text` code gates, not `json` or `php`. Inputs are specified in GraphQL schema definition language, and there's no special highlighting available for that. Responses should use the `json` code gates. I'm correcting the GraphQL changes in #4051

Thank you for this comment, @keharper ! It's useful for my future PRs.

Thanks again!

**Comment by atwixfirster** [comment]
> Also see #3670

@keharper , could you please clarify here?

In https://github.com/magento/devdocs/pull/3670 `text` code style is defined as
```
``` text
```
However, per @dobooth comment in https://github.com/magento/devdocs/pull/4022 we should use a SPACE. So a correct `text` code style should be:
```
```text
```
Could you please confirm that?

Thank you!

**Pull request merged**
