### PR TITLE
Rewrite "bad code" example to "good"

### PR DESCRIPTION
**Pull request by likemusic**
Rewrite "bad code" example to "good" for Around methods example.

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will have right version for exmple for "Around methods" for methods with default null value.

At the moment there is no any visual differense batween right and bad (with mistakes) code (like cross out text or color hilight). Therefore imho it would be better to have in docs only good code exmples, with noting about possible mistakes (to not confuse developers with bad code exmpled that could be copy-pasted from by mistake).

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
running tests

**Comment by erikmarr** [comment]
Thanks @likemusic!

**Pull request merged**
