### PR TITLE
Fixing issue - https://github.com/magento/devdocs/issues/3213

### PR DESCRIPTION
**Pull request by caseybecking**
## This PR is a:

- [ ] New topic
- [ ] Content update
- [ ] Content fix or rewrite
- [x] Bug fix or improvement

## Summary

When this pull request is merged, it will fix the issue 3213 which is a link issue with the devdocs

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.1/config-guide/varnish/config-varnish.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3214) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3214) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
@caseybecking thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by caseybecking** [comment]
Contributors Agreement has been signed.

**Comment by jeff-matthews** [comment]
Fixes #3213

**Pull request merged**
