### PR TITLE
Fix typo in db-schema.md

### PR DESCRIPTION
**Pull request by artttj**
db_schema.xml file should have snake-case writing.

## Purpose of this pull request

Fix typo in devdocs.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html
- https://devdocs.magento.com/guides/v2.4/extension-dev-guide/declarative-schema/db-schema.html

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@artttj thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by BarnyShergold — APPROVED** [review]
NIce spot - please sign the Adobe CLA so the PR can progress, you only need to do this once.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
running tests

**Comment by keharper** [comment]
running tests

**Pull request merged**
