### PR TITLE
Update config-cli-subcommands-cache.md

### PR DESCRIPTION
**Pull request by mage2pratik**
## This PR is a:

- Content fix or rewrite

## Summary

When this pull request is merged, it will add missing cache related information.

## Additional information

List all affected URLs 

- https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Hi Pratik. Thanks for this PR.
The file needs a bit more work before I can approve it. 
3 main ideas:
Convert the HTML table to markdown. 
Use code blocks for proper code sample rendering.
Replace tab with spaces, such as lines 178 and 185.
Give it another pass and then I will review it.

**Comment by dobooth** [comment]
running tests

**Comment by keharper** [comment]
@dobooth @mage2pratik The command line examples should be preceded with "```bash" instead of "```terminal". In the cases where there's two commands on consecutive lines, separate them into separate examples, each provided by "```bash"

**Pull request merged**
