### PR TITLE
Correct missing part in content

### PR DESCRIPTION
**Pull request by mrtuvn**
## Purpose of this pull request

This pull request (PR) Update content and correct missing parts

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/install-gde/prereq/apache.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/apache.html

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
Good fix!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Good eye!

**Comment by mrtuvn** [comment]
I have updated for src 2.4 too

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8816`.

**Pull request merged**
