### PR TITLE
Fixed path to Restricting access to anonymous web APIs v.2.2

### PR DESCRIPTION
**Pull request by ygyryn**
Added missed *Settings* in path

## This PR is a:

- [ ] New topic
- [ ] Content update
- [x] Content fix or rewrite
- [ ] Bug fix or improvement

## Summary

When this pull request is merged, it will...

Add missed option _Settings_ in updated path in template
guides/v2.2/rest/anonymous-api-security.md

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.2/rest/anonymous-api-security.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=3750) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=3750) before we can accept your contribution.<br/>

**Comment by magento-cicd2** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
@ygyryn, please combine this PR with #3752.

Also, filling out the PR form is mandatory so that we can efficiently process your contribution.

**Comment by jeff-matthews** [comment]
See #3752

**Pull request closed without merging**
