### PR TITLE
Magento 2.4.1 Release Notes update

### PR DESCRIPTION
**Pull request by rafaelstz**
## Purpose of this pull request

Fix my name broke because of the special character.

Capture d’écran, le 2020-10-15 à 15 30 02

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/release-notes/commerce-2-4-1.html#partner-contributions

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
running tests

**Comment by jeff-matthews** [comment]
@rafaelstz, before I can merge this, I need you to sign the Adobe CLA.

It's strange though because you've contributed to the devdocs repo before, so we should already have a signed CLA for you....

**Comment by rafaelstz** [comment]
Hi @jeff-matthews, I did it, thanks for letting me know it!

**Comment by jeff-matthews** [comment]
Thanks @rafaelstz!

**Pull request merged**
