### PR TITLE
Fix list of allowed attributes in escaper

### PR DESCRIPTION
**Pull request by dannynimmo**
## Purpose of this pull request

Removed `target` as this attribute is not allowed by the escaper. List of allowed attributes can be found here: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Escaper.php#L45

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/extension-dev-guide/xss-protection.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Escaper.php

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by nuzil — CHANGES_REQUESTED** [review]
Hi @dannynimmo can you please update also version for 2.3 I see there are same change

**Comment by dannynimmo** [comment]
@nuzil sure, done

**Review by nuzil — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
