### PR TITLE
Convert html to markdown on message queues page

### PR DESCRIPTION
**Pull request by leviv**
## This PR is a:
- [ ] New topic
- [x] Content fix or rewrite
- [ ] Bug fix or improvement
 

## Summary
Converts HTML to markdown on message queues page 

When this pull request is merged, it will...
Improve the readability of the source code

### CODE REVIEW

**Comment by keharper** [comment]
Hi @leviv. Would you make these changes in the 2.1 and 2.3 versions as well?

**Comment by leviv** [comment]
Updated for 2.1 and 2.3

**Comment by jeff-matthews** [comment]
@keharper, please merge.

**Comment by keharper** [comment]
Hi, @leviv. I really like the more detailed table, but I have to ask you to back out some of the other changes you made in the `message-queues.md` files:

- In the header section, re-add the line `ee_only: True`.  This header adds the "Magento Commerce only" box at the top of https://devdocs.magento.com/guides/v2.1/extension-dev-guide/message-queues/message-queues.html . In 2.3, all the message queue functionality has been moved to Open Source, so that line no longer appears in the 2.3 version of the file. 

- Change the `redirect_from` line to `redirect_from: /guides/v2.x/extension-dev-guide/message-queues.html` where x = 1 in the v2.1  branch and x = 2 in the v2.2 branch. At some point in the past, I changed the location of the `message-queues.html` file, and having this line prevents a 404 error, in case someone happened to bookmark the page.

**Comment by leviv** [comment]
Hey @keharper thanks for the feedback. I added the tags in the 2.1 and 2.2 files, let me know if I missed anything else

**Comment by keharper** [comment]
Thanks, @leviv

**Pull request merged**
