### PR TITLE
added missing php tags

### PR DESCRIPTION
**Pull request by gauravagarwal1001**
## This PR is a:

- [x] Content fix or rewrite

## Summary

When this pull request is merged, it will...
it will add php tag in examples

## Additional information

List all affected URLs 

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html
https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/devdocs?pullRequest=4497) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/devdocs?pullRequest=4497) before we can accept your contribution.<br/>

**Comment by gauravagarwal1001** [comment]
#ContributionDay

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by dobooth** [comment]
Thanks @gauravagarwal1001 !

**Pull request merged**
